### ISSUE TITLE
Cell slop

### ISSUE THREAD

**Issue by sviola** [andmarti1424/sc-im#101]
Does sc-im support slop (having a cell overflow into empty ones next to it) like sc does? [One of the screenshots][1] appears to show that this functionality is available (see "Future and Present Values Factors"), but when I try to reproduce it, the text that doesn't fit in the cell is displayed as asterisks. In sc, the text automatically overflows into the one to the right of it, if you add left-aligned text to a cell that has empty neighbors.

Here is an example of a file that should show the difference in functionality between sc and sc-im:

```
leftstring A0 = "This text should overflow into B0."
goto A0
```

I am running [sc-im from the AUR][2].

[1]:https://raw.githubusercontent.com/andmarti1424/sc-im/depgraph/scim4.png
[2]:https://aur.archlinux.org/packages/sc-im/

**Comment by andmarti1424** [comment]
You have to set the overlap variable.

**Comment by sviola** [comment]
Thanks for the info! I see that the option was added after v0.3.0, which is why I didn't see it.
