### ISSUE TITLE
redo and scroll down map to same keys (<Ctrl-f>)

### ISSUE THREAD

**Issue by jimgregory** [andmarti1424/sc-im#103]
According to the help documentation, Ctrl-f should redo a command that 's been undone when in normal mode.

But Ctrl-f is also scroll down.

This means that when you attempt to undo an undo command using redo, the page scrolls down instead.

**Comment by andmarti1424** [comment]
Should be C-r for redo

**Comment by jimgregory** [comment]
Thanks, that works.
You might want to correct the online help screen, because it says 'c-f'.
