### ISSUE TITLE
Sorting segmentation fault error

### ISSUE THREAD

**Issue by gotbletu** [andmarti1424/sc-im#110]
getting this error **segmentation fault (core dumped)** everytime i try to sort. Tryed both from command mode and with visual mode. In the past version it work sometimes but in **version 0.4.0-1** does not seem to work at all.

    :sort A1:F150 "+$A;+$B;+$C;+$D;+$E;+$F;"
    :sort A1:F150 "+$A;+$B;+$C;+$D;+$E;+$F"

    #visual mode
    :sort "+$A;+$B;+$C;+$D;+$E;+$F;"
    :sort "+$A;+$B;+$C;+$D;+$E;+$F"

**Comment by andmarti1424** [comment]
Thanks for reporting this. Will check this out as soon as I can.

**Comment by andmarti1424** [comment]
Hello. I did some tests and did not have this issue. Could you please send me your file and another test, could you please try the sort.sc example file and the sort example shown in the doc?? Thanks again.

**Comment by gotbletu** [comment]
heres my file:
http://ix.io/1PCw

another issue is that it **does not sort the year** correctly either

**Comment by andmarti1424** [comment]
About the years order, I see they are strings, and not date type. Please see the DATE INPUT section in help to see how to convert it to dates..
Then you could try sorting them but ordering those values as numbers.

Could not make to seg fault (arm architecture).
Will try in another computer (i386) to see if I can find the seg fault problem.
Thanks again.

**Comment by andmarti1424** [comment]
Confirmed. It SEGFAULT in another machine with that file. Will check it out. Thanks!

**Comment by andmarti1424** [comment]
This is caused because of the empty cells..

**Comment by gotbletu** [comment]
Is that suppose to happen? =)

**Comment by andmarti1424** [comment]
It should not happen. I added a control to check this behaviour. Please update to latest depgraph branch commit and try again. Thanks!

**Comment by andmarti1424** [comment]
Could you please update to latest commit and try again?? Thanks!!

**Comment by gotbletu** [comment]
Thanks, it works fine now, good job sir
