### ISSUE TITLE
Implement a function that outputs current row/column index

### ISSUE THREAD

**Issue by BlitzKraft** [andmarti1424/sc-im#112]
If it was already there, I couldn't find it. 

I am currently trying to make a spreadsheet that has a  quantity, price and output amount on an itemized list. Besides manually entering the formula (multiply two cells in the same row) in each row, I couldn't find an alternative. 

Are there any column operations available ?  Is there an easier way to do this?

**Comment by andmarti1424** [comment]
I do t think k if this is what you are looking for, but did you check coltoa function in doc? You all have @myrow and @mycol variables..

**Comment by andmarti1424** [comment]
Could you try those functions?

**Comment by andmarti1424** [comment]
Please update to latest depgraph branch commit and try the frow and fcol functions. I still have to add them to the documentation.

**Comment by BlitzKraft** [comment]
Ah. I just pulled the latest commit.  The frow and fcol do what I wanted.  

Also, I have trouble using 'backspace' when typing the commands. Could you check it's working for you?


When I am typing the ":" commands, I can't backspace.

**Comment by andmarti1424** [comment]
About the backspace issue, what is your OS? Please check the key code set in macros.h file..

**Comment by BlitzKraft** [comment]
Yes, I use tmux. My OS is Linux Sabayon, on gnome-terminal.

**Comment by andmarti1424** [comment]
Please try it without tmux and see if it still happens.. You could also edit OKEY_BS keycode in macros.h file..

**Comment by BlitzKraft** [comment]
Yes, it happens without tmux also.

**Comment by andmarti1424** [comment]
Try this in macros.h file... #define OKEY_BS 0x7f

**Comment by BlitzKraft** [comment]
That works.  But I am not sure why. Mine's neither NETBSD nor MACOSX. 

There were a few warnings about redefining ithe OKEY_BS, during make.

**Comment by andmarti1424** [comment]
@BlitzKraft, Do you have large csv files to send me, so I can do some improvements in SC-IM ??
Thanks.

**Comment by andmarti1424** [comment]
@BlitzKraft, dont worry. I do not need them anymore. Improved csv import times!! Please try it out.

**Comment by BlitzKraft** [comment]
Hey, thank you for letting me know. I will try it out!!
