### ISSUE TITLE
Prevent csv import changing text to numbers

### ISSUE THREAD

**Issue by ctSkennerton** [andmarti1424/sc-im#113]
I have a csv file that looks like the following:
```
grp,id
1-3,12
1-3,15
5,22
```

Upon import this data gets modified so that the values look like:

```
grp,id
-2,12
-2,15
5,22
```

The values in the first column are treated like a formula and the result is -2, which is not what I want. Is there a way to prevent this auto-calculation on import?

**Comment by andmarti1424** [comment]
Interesting behavior. Will add a configuration variable to force the import as text..

**Comment by andmarti1424** [comment]
Could you please update to latest depgraph commit and try again the import?

**Comment by ctSkennerton** [comment]
It works!

**Comment by andmarti1424** [comment]
Improved csv import times, for big files!! Please try it out.
