### ISSUE TITLE
string.c's split() has several issues

### ISSUE THREAD

**Issue by yokattana** [andmarti1424/sc-im#116]
Came across this because the compiler warned about assigning a \0 character to a pointer.

Function at time of writing:

https://github.com/andmarti1424/sc-im/blob/41f54cd3cc8c8d4504f2a049ccd8b609244b9318/src/utils/string.c#L178

**1. It allocates too many array entries**

First, the function counts the number of substrings, storing the value in `count`, but then goes on to allocatie based on `length` instead: `malloc(sizeof(char *) * (length + 1 + lastnull)`.

**2. It will seek into out of bounds memory**

`while(string[j] != delimiter) j++;` will go off past the end of the string for the last entry.

**3. It seeds to many nulls**

If `lastnull` the function sets the last substrings array element to `NULL`, but then on the next line it will do so again immediately.
__

The function also doesn't normalise the value of `lastnull` to 1/0 and should probably take a `const char**` instead of `char**`, but those are less problematic.

I've attached a sample reproducing these issues.

[splittest.txt](https://github.com/andmarti1424/sc-im/files/760215/splittest.txt)
[splittest.c.zip](https://github.com/andmarti1424/sc-im/files/760218/splittest.c.zip)

**Comment by andmarti1424** [comment]
Thanks for the pull request. I took it and removed variable declaration in "for" statements..

**Comment by yokattana** [comment]
Sure. Are you trying to stay ANSI C compliant? I think there are some other places in the code where inline declarations are used.

**Comment by andmarti1424** [comment]
Yes.
Really? I do not recall those lines.. where are them?

About the split function... I think we should fix it. we no longer use it, but its pretty useful..may be in future work I would need them.

**Comment by yokattana** [comment]
I think `strsep` and friends should be plenty. As seen, most uses of it can be trivially replaced.

I might be mistaken about the inline declarations. Doesn't really matter to me, ANSI C is fine.
