### ISSUE TITLE
$HOME/.scimrc is not processed if a file to be open is given on the command line

### ISSUE THREAD

**Issue by melak** [andmarti1424/sc-im#134]
- Add something to your `.scimrc` that makes it apparent whether or not it has been processed
- Run `./scim existing.sc` (or `./scim existing.xls`, the type quite probably doesn't matter)
- Observe settings in `.scimrc` _not_ having been applied to the session

**Comment by andmarti1424** [comment]
Interesting. Will check this.

**Comment by melak** [comment]
Fixed in 92fa68d2.
