### ISSUE TITLE
Questions & comments 2

### ISSUE THREAD

**Issue by brucehohl** [andmarti1424/sc-im#141]
A few more questions please:
(1) Thanks for adding "gg" for help file navigation.  As many will be unfamiliar with vi style navigation, for the help file, I suggest also support for these keys: Home, End, Page-up & Page-down.
(2) Is there a command to determine the name of the file currently loaded (other than to :w)?
(3) Can you provide an example of how to use: @sum({range},{expr}) with the {expr} parameter.  I assume this is meant to work like sumif().
(4) How does Command Mode C-f work?  I have selected a cell with a "cellcolor" entry in the file but no matter what I try I always get message "cell has no format".  The help file states this will "Paste the current cell format (if any) to the command line."

**Comment by andmarti1424** [comment]
1. Added those commands as well.
2. No command. Will work on it. How do you achieve this in vim?
3. You can sum pair numbers of a range with this example:
@sum(A0:A10, A0%2=0)

**Comment by andmarti1424** [comment]
4. C-f pastes the format added with the :format special command or with C-d of normal mode.
For instance try entering the following text in a Cell:
10/02/2017
then press C-d in normal mode.
That adds a date format to the cell.
if you then enter command mode and try C-f it pastes the format in the command line.

**Comment by andmarti1424** [comment]
Regarding #2, @melak just added the file special command..

**Comment by brucehohl** [comment]
Many thanks for you responses.  My questions have been answered and the additions to code worked perfectly for me.
