### ISSUE TITLE
Possible autocalc bug

### ISSUE THREAD

**Issue by brucehohl** [andmarti1424/sc-im#144]
The attached file (test2.sc) shows steps in cell F7 (1st) then F1:F2 (2nd) where autocalc did not appear to work correctly.  Please check.

[test2.sc.zip](https://github.com/andmarti1424/sc-im/files/769984/test2.sc.zip)

**Comment by andmarti1424** [comment]
Yep. Confirmed. Will check the "paste" function.

**Comment by andmarti1424** [comment]
To note, this also happens with the 'c' command.

**Comment by andmarti1424** [comment]
Uploaded some changes to fix this. Could you please update to latest depgraph commit and try again? Thanks!

**Comment by andmarti1424** [comment]
Can I add a screenshot of your file in SCIM to post in home page of https://github.com/andmarti1424/sc-im ??

**Comment by brucehohl** [comment]
Andrés, Many thanks for this fix (and the others).  The problem is resolved on my test worksheets.  You are welcome to use a screen-shot of my test2.sc file for the home page.  Next weekend I will create some additional sc-im test files and see what comes up.  Regards, Bruce

**Comment by andmarti1424** [comment]
That would be great! Thank you.
