### ISSUE TITLE
Sort command not working?

### ISSUE THREAD

**Issue by spcmd** [andmarti1424/sc-im#146]
Hi! Thanks for sci-im! I started using it and I'm wondering whether I am doing something wrong or the sort command doesn't work now? I tried with a new, clean file, tried sorting string values, numeric values, neither of them got sorted.

I even tried with the [sort.sc](https://github.com/andmarti1424/sc-im/blob/master/files/sc/sort.sc), I selected a range in the E column and tried the command `:sort "+$E"` ([screenshot](http://i.imgur.com/1ha1vxC.png)) but nothing happens. I tried single column, multiple columns, ascending, descending, but nothing happens. No error message either.

I'm using Arch Linux, installed from the AUR, version: 0.5.0-1

**Comment by andmarti1424** [comment]
I believe its not working correctly if you sort it without specifying a range. Will check it out.
You can sort it like this:
:sort C10:F13 "+#E"
or like this, if you want to order by the string content..
:sort C10:F13 "+$E"

**Comment by andmarti1424** [comment]
Confirmed. It failed if a range was selected.
Just fixed this, but in the new "freeze" branch.

**Comment by andmarti1424** [comment]
Also fixed in master branch.

**Comment by andmarti1424** [comment]
Could you please check it out?

**Comment by spcmd** [comment]
Checked out, works fine, thank you!
