### ISSUE TITLE
sc-im Macros ?

### ISSUE THREAD

**Issue by roman65536** [andmarti1424/sc-im#147]
Hi,
I wonder whether you will also implement the macro features from the original SC or may be even extend it a bit  ?
This is cool feature of the sc, the way a macro can interact with sc, such as query etc.

regards
Roman

**Comment by andmarti1424** [comment]
You mean this :
"Use SC-IM as a non-interactive calculator, reading its input from a external script."??

**Comment by roman65536** [comment]
No,
see the SC.MACRO in the 7.13 tarball.
https://github.com/n-t-roff/sc/blob/master/SC.MACROS 
here is an test script i wrote of sc macro, it asks you to "Input a value" it writes the value to a0 and  gets some data from mysql : 
#!/bin/bash
echo "query \"Input a value\"" 
read a
echo "let a0=$a"
echo "down"
b=1
IFS=$'\n'
for a in `mysql -u root -ppwd -D test -e "select sensor,count(*) from sensors group by 1" -B -N`
do
	c=`echo $a | cut -d'	' -f 1`
	d=`echo $a | cut -d'	' -f 2`
echo "leftstring b$b=\"$c\""
echo "let c$b=$d"
b=$(( $b + 1))
done

**Comment by andmarti1424** [comment]
I believe you can do a bash script like this, that outputs commands such as "leftstring.." or "let"  and redirects it to scim throw pipe..

**Comment by roman65536** [comment]
Yes, you are right that is possible, but as described, in a non interactive way as i understand it. Since the stdin will be redirected. 
Macros work a bit different. Macros are called from sc. Sc will open pipes (stdin,stdout) to communicate with the macro.  So you can send a "query" to sc and sc will ask user for input and still do stuff interactive via terminal.  Or send "getnum" and sc send the numeric content of the cell back to the macro. Macro work both way, in and out, which is pretty cool thing. It would be great thing to have it in more updated version of sc ;)

**Comment by roman65536** [comment]
see here: 
![screenshot from 2017-02-21 23 23 01](https://cloud.githubusercontent.com/assets/4540854/23187897/ed0db320-f88c-11e6-9dc2-0cae166a59c0.png)

rgds
roman

**Comment by andmarti1424** [comment]
Yes. May be we can work on this a little.

**Comment by roman65536** [comment]
May be more up to day version of it, embed lua for example. So lua script can interact with scim, similar as  lualatex does. So extending scim with new functions such input/output from/to a db is no big deal. just a thought. Excel has basic, why not having lua in scim ;)

**Comment by roman65536** [comment]
I Just played a bit... and added the lua macro support in my branch. 
https://github.com/roman65536/sc-im/tree/master/src

Actually just for fun also added triggers (two kinds), one general - when ever something was changed and cell trigger- when ever a cell was changed. 
see the macro.lua and trigger.lua to get the idea.

**Comment by andmarti1424** [comment]
That seems interesting. How the @lua function is interpretted?

**Comment by roman65536** [comment]
It calls doLUA() in lua.c and the first parameter is the filename of the lua script (see test.sc).
The rest is doing the lua library -llua5.1. 
On triggers it calls always trigger in trigger.lua or trigger_cell also in trigger.lua (those are hardcoded)
trigger_cell has 3 parameter (col,row,flags). The trigger_cell can be turned on and off via "set luatrg".


at the beginning in sc.c, lua is initialized and calls init.lua. There you can also setup global variable. Those can be used in all scripts. 

so far, there are 4 sc specific lua functions (lgetnum - get number from a cell, lsetnum - set number to a cell, lsetstr - set string to a cell, query - which suppose to be a user query but not implemented yet on sc-im). Depending on your lua on system config, you can use lua's modules such sockets or sql etc.

hope you get the idea

**Comment by andmarti1424** [comment]
Thank you very much!! This would be a good start point. Please do not remove that branch of yours.

**Comment by roman65536** [comment]
Don't worry, wont remove it :) 
What I would love to do, the triggers are very rudimentary, is just basic concept of it. For example on formula (such as @sum(a1:a3)) it triggers twice for the same cell, once with value 0 and second time with the effective value calculated from the formula. Nice would be extending the Cell structure, so individual trigger can be define for specific cells, not for all and maybe extending the concept of the trigger to "read","write", something like :set cell_trigger  a5,read trigger.lua trigger123 (where a5 is the cell, read means on read aka when ever the a5 cell will be read out, trigger.lua is file name, trigger123 is the lua function).


One thing I would like to do, may be you can give me a hint, passing formulas for a particular cell from lua to sc. Not sure whether there is a such way. 
Other thing, how best implement user "query" for input ? in the old sc, there was routine called query(). Also extending the lua functions, so the color can be set etc.

rgds
roman

**Comment by andmarti1424** [comment]
To pass a formula.. send_to_interpreter("let A0=@sum(B0:B20)");   that is what you meant?

**Comment by roman65536** [comment]
I guess that's it ;) and how about query input ?

**Comment by andmarti1424** [comment]
To query: 1st:    wtimeout(input_win, -1);

**Comment by roman65536** [comment]
You mean calling curses directly ?

**Comment by andmarti1424** [comment]
You just have to. You need to get out of the handle_input of input. c.  setting that timeout is the only way..

**Comment by andmarti1424** [comment]
Do you prefer leaving that query function to me?

**Comment by roman65536** [comment]
would you mind explain more in detail, what is the story behind the timeout ? Not sure how this effects other things.

**Comment by roman65536** [comment]
Sorry... didn't see your last comment ;) go a head, if you like to.

**Comment by andmarti1424** [comment]
here is the query function:
[query.txt](https://github.com/andmarti1424/sc-im/files/830982/query.txt)

setting the timeout over a window
like this:
wtimeout(input_win, TIMEOUT_CURSES);
makes the wgetch() function to wait an amount of time.
if that time passes, it returns -1 (if I recall well).
setting the timeout to -1 just makes wgetch() function to wait forever.

**Comment by roman65536** [comment]
Thank you very much. Check out the branch, it works ;) also lsetform(col,row,str) added, to pass formulas from lua to sc. I guess it works only numeric since "let" is place in front, before sending to parser.

**Comment by andmarti1424** [comment]
you should use slet for string formulas.

**Comment by andmarti1424** [comment]
question: Did you change something in the str_search function of your branch??

just to tell you, in one week or so, I would replace the master branch with the other "freeze" branch.
After that I will be able to test and merge your work..

**Comment by andmarti1424** [comment]
May be we should include functions for these ones as well:
* get currow
* get curcol
* get maxcols
* get maxrows
* get screen size ROWS and COLS
(for that I should add those six to gram.y first)

I believe all the work you're doing would be a good starting point for plugins support.
talking about plugins..
may be we should do common functions that could be called from lua scripts for
creating, closing ncurses windows in screen, and for putting content in them.
With that achieved, we should have all the basic for other people to start creating some plugins..

**Comment by roman65536** [comment]
No didn't change anything, but it's has been a while since I fork it. So I may be a bit off. 
I have anyway bit trouble with github.. need to get use to it and git :) and how it works with updates.

to answer you question. I may replace the lsetform because I'm not happy with it. Probably it would be better pass over the whole string (including let). This way lua script can do everything, including slet or cellcolor etc. That gives more flexibility on the lua site.

"get currow
get curcol
get maxcols
get maxrows
get screen size ROWS and COLS"

I guess you meant as general purpose C interface ? Yes, absolutely. Not sure about curses, since for lua it self, there are modules for it around. 
 

Speaking of gram.y, the original sc was developed back in the 80s when even I was young ;), with few functions. 
However in the meantime the gram.y got bigger and bigger. Not that yacc is a bad thing not at all. 
I dream of something like dynamic functions, where you just add the name of a function and pointer to function without always playing around with gram.y, lexer and the interpreter etc. Similar as you do with dictionary.  This way extending sc with new functions would be just matter of seconds, could be even done as a real plugin without recompiling (as firefox plugins do). 
May be I should explain it different. Let's I like to build a interface to "R". I have to extend sc at very heard of the sc, need to have knowledge of yacc syntax etc. With the method above, just register_the_function() and that's it. But as I sad before, dreaming ;)

**Comment by andmarti1424** [comment]
about the lsetform problem, what about using the more general send_to_interpret function..? that function actually can do almost everything in sc-im. and the small part that is not covered there, will be.

I could do the curses part without a problem, and besides there are many things that are more specific to the sc-im ui.

**Comment by roman65536** [comment]
Both ok.. Could you expain more about the send_to_interpret ? Not clear to me, doesn't send_to_interpp() do already the job ?
 I'll try to do some helper routines for LUA such as asciitorc and back, which are needed anyway.

**Comment by andmarti1424** [comment]
I meant that function you say! The are both because, one converts from wide char.. and the other improves time during large csv import (files over 65k rows). Will leave just one for next version though.

**Comment by roman65536** [comment]
what are your thoughts about my dream on the dynamic functions ?

**Comment by andmarti1424** [comment]
Might be a good idea, but may be for a more polished status of the app.
By now gram.y is not that big as well.

**Comment by roman65536** [comment]
When I do something like from a file

let A0 = @ston(@lua("macro.lua",0))

and macro.lua : 

tmp=lquery("Info from Lua, type in your input: ")
lsetstr(0,0,tmp)

I got attached output, the sc main screen is not drawn yet.  
![screenshot from 2017-03-09 21 15 46](https://cloud.githubusercontent.com/assets/4540854/23768982/1722e1de-050e-11e7-9559-c7173294f28c.png)

**Comment by andmarti1424** [comment]
let me think.. that is because of the loading routine.
first the file is loaded, then the grid is shown.
perhaps a forced screen update show be thrown from the file.. calling refresh();

if i recall well, there is not a call from gram.y to refresh()..
perhaps we can reuse the old and commented redraw..
there also might be necessary to mark the loading flag to false inside redraw.
otherwise update function will return as soon as called..

**Comment by roman65536** [comment]
now it works... called update() when loading, but cheating with loading flag ;)

**Comment by roman65536** [comment]
added  sc.currow() sc.curcol() sc.maxrows() sc.maxcols() as lua functions.
also changed the lua lib a bit, so every sc specific function starts with sc. so lgetnum is now sc.lgetnum

**Comment by andmarti1424** [comment]
Good job Roman

**Comment by andmarti1424** [comment]
Cant -llua5.1 eval to pkg-config in Makefile, so we can add
something like the following, but for lua:
-  NCURSES_CFLAGS ?= $(shell pkg-config --cflags ncursesw)
-  NCURSES_LIBS   ?= $(shell pkg-config --libs ncursesw)
??

**Comment by roman65536** [comment]
On my debian, yes it can : 
$ pkg-config --libs lua51
-llua5.1 
$ pkg-config --cflags lua51
-I/usr/include/lua5.1

**Comment by roman65536** [comment]
Well ... I just did the wildest thing, will need more code writing on this.
Added trigger on cell based. Not just for lua, but also for c dynamic linked modules. 
will push the code shortly. for this add a new command trigger:
:trigger cell_cellrange "type=[C|LUA] mode=[R|W|RW] file=[file to module, for c module ./ add if module in the same directory] function=[C or LUA Function to call]

C example:
#include <stdio.h>

#include "sc.h"
#include "macros.h"
#include "utils/dictionary.h"
#include "utils/string.h"
#include "range.h"
#include "color.h"
#include "screen.h"
#include "undo.h"
#include "conf.h"
#include "cmds.h"
#include "trigger.h"


extern char * query(char * );



int do_c_call(struct ent *p , int rw)
{

char * str = query("Call from C");


FILE *fd = fopen("/tmp/modul.txt","a+");
fprintf(fd,"%d %d %g %d\n",p->col,p->row,p->v,rw);
fclose(fd);

 return(0);
}

to compile:
# gcc -shared -fPIC -o module.so -g -Wall module.c

in SC type 
:trigger a4 "mode=RW type=C file=./module.so function=do_c_call"
and when ever a4 got a new result (after evaluation) do_c_call will be called.

will change the old lua triggers and also include a read trigger. 
roman

**Comment by andmarti1424** [comment]
It seems interesting. It would be great to start updating the doc file, adding how all these new features work and some examples!

**Comment by roman65536** [comment]
Not finished yet... the big deal is trigger on READ, when ever a cell value is needed, such also from sum,prod etc. Doing so, trigger can for example read the value from a DB and pass it it over, before evaluation.  eval() reads different then dosum(). Just hope, everything is only in interp.c ;) 
But yes then I will do more docu on this, with some cool examples.

**Comment by andmarti1424** [comment]
That would be great!!!
Just let me know when you fininish that, may be you can give a hand with something that I am stucked with..

**Comment by roman65536** [comment]
Andrés,
my changes are in my repo, so if you like to take a look, be my guest. 
Also the example of the "C" plugin should be there.

**Comment by andmarti1424** [comment]
I downloaded the code. I like it but couldn't test it. The example test. Sc is giving me segfault. Both if i press esc or enter. It also shows same strange chars i  header..

**Comment by roman65536** [comment]
Do you already have the lua stuff included ? test.sc calls the macro.lua right a way.
otherwise...
gdb and post the "bt".

**Comment by andmarti1424** [comment]
i just left the sc.lquery line in macro.lua and changed bail function in lua.c so it use sc_error..
i got this strange header with weird chars in top and obviously the lquery function was called, since its waiting for input. no matter if ENTER or ESC key is pressed.. i attach my valgrind log.

I believe the query gets the correct initial text message but then ??its called again?? with initial message NULL?

**Comment by roman65536** [comment]
Hmm.. that is interesting.. are you sure, you are using same files as me ? and not a mix from your version? You should get something like this 
![screenshot from 2017-03-11 23 00 30](https://cloud.githubusercontent.com/assets/4540854/23827219/c16f3fe2-06ae-11e7-9edd-37eb74b7ec8b.png)
![screenshot from 2017-03-11 23 00 58](https://cloud.githubusercontent.com/assets/4540854/23827221/c73eb7cc-06ae-11e7-97b2-0809c74e5f8b.png)

**Comment by andmarti1424** [comment]
now i did call the macro.lua manually after scim was loaded. now query function is sort of working..
i left the sc.lquery and the first sc.lsetstr of macro.lua..
now query asks me for input (but 2 times) and then the reply to the second query is written in cell A0..

**Comment by roman65536** [comment]
When did you download it ?

**Comment by andmarti1424** [comment]
Today.

**Comment by andmarti1424** [comment]
Could you please send me an email to scim.spreadsheet@gmail.com ?
