### ISSUE TITLE
Crash after dc followed by c{a-zA-Z}

### ISSUE THREAD

**Issue by brucehohl** [andmarti1424/sc-im#148]
With versions dated 2017-02-13_18:51 (0.5) and 2017-02-12_21:18 (0.4) a crash occurs if a column is deleted "dc" followed by "c{a-zA-Z}".

**Comment by andmarti1424** [comment]
You mean for instance   'dc' and then 'ca'  ?

**Comment by brucehohl** [comment]
Yes, 'dc' and then 'ca'.  Or, 'dc' and then 'cb', etc.  
I am using Linux Mint 18.0 with xfce4-terminal.

**Comment by andmarti1424** [comment]
I could reproduce it. It happens when you delete the first column..

**Comment by andmarti1424** [comment]
Could you please update to latest master branch commit and try again ?

**Comment by brucehohl** [comment]
Thanks.  Tested OK.  With commit 5d9e5d8 the problem has been resolved.
