### ISSUE TITLE
:! {cmd} does not appear to work

### ISSUE THREAD

**Issue by brucehohl** [andmarti1424/sc-im#149]
For example, entering ":! pwd" switches to the terminal but the command is not executed.  Only the message "Press ENTER to return." is displayed.  Pressing ENTER returns to scim.

**Comment by andmarti1424** [comment]
I dont have thia problem. What is your OS ?

**Comment by spcmd** [comment]
I can confirm  this.
Arch Linux
terminal: rxvt-unicode (urxvt) v9.22

**Comment by brucehohl** [comment]
I am using Linux Mint 18.0 with xfce4-terminal.

**Comment by andmarti1424** [comment]
What is you OS, @spcmd?
I have no problem in Debian and in Arch..

**Comment by spcmd** [comment]
@andmarti1424: I wrote it in my previous comment, I'm using Arch also.

BTW,  I think I found the problem: you can't put a space after the exclamation mark.

`:! pwd` won't work, only got a "Press ENTER to return" message
`:!pwd` works fine

In the help, there is a space after the _bang_

>  :! {cmd}    Executes shell command {cmd}.

**Comment by andmarti1424** [comment]
Sorry. I missed your comment before. Please update to latest commit. It should be fixed.

**Comment by spcmd** [comment]
It's working.
