### ISSUE TITLE
cellcolor is not always saved

### ISSUE THREAD

**Issue by spcmd** [andmarti1424/sc-im#150]
It looks like the cellcolor is not always saved. Simple test:

create a new file
write some string in **A0** and **B0**
select them and apply the command: `:cellcolor "bg=RED fg=WHITE"`
save and exit `:x`
open the file again: the A0 has red red background, but the B0 does not.

Tested with the latest commit: 0f3d240

**Comment by brucehohl** [comment]
I have noticed this as well and it appears that cell color setting are lost only for cells in right most column of the spreadsheet.  It seems to happen for most "save, close, reopen cycles" but not all.

**Comment by andmarti1424** [comment]
Is this command stored in the sc file:
cellcolor A0:B0 "fg=WHITE bg=RED"
???
This does not happen to me or we are doing different steps..

**Comment by spcmd** [comment]
No, the **B** isn't there. 

- I set  the cell colors, see: [screenshot A0:B0](http://i.imgur.com/3AaPayD.png)
- Then save and exit `:x`
- Then opened the saved file and the B0 cell isn't colored, see: [screenshot A0:B0 bug](http://i.imgur.com/LXcBSny.png)

In the sc file, I got this:

```
# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

cellcolor A0 "fg=WHITE bg=RED"
goto B3
```

So the B part is missing. As @brucehohl said, it must be something with the right most columns, because if I colororize from A0:C0, then the C part will be missing.

[screenshot A0:C0](http://i.imgur.com/cGOTLfL.png)
[screenshot A0:C0 bug](http://i.imgur.com/rBb9qWQ.png)

```
# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

cellcolor A0:B0 "fg=WHITE bg=RED"
goto C3
```

**Comment by andmarti1424** [comment]
Could you please update to latest master branch commit and try again?
Thanks!

**Comment by spcmd** [comment]
It seems fine, thank you!
