### ISSUE TITLE
sc-im freezes when moving to the next search match

### ISSUE THREAD

**Issue by spcmd** [andmarti1424/sc-im#151]
When I hit the **n** key to  go to the next search match, sc-im freezes. Test:

- create a new file
- put some string in the column **A**, e.g.:
foo
bar
baz
foo
bar
baz
foo
- then search: `:int goto "foo"`
- it will find the the first match, but then press **n** key to got to the next match and then sc-im freezes. 
No error message, can't do anything, except closing the terminal.

Tested with the latest commit: 0f3d240
The terminal is: rxvt-unicode (urxvt) v9.22
Arch Linux

**Comment by andmarti1424** [comment]
Please update to latest master branch commit and try again. thanks.

**Comment by spcmd** [comment]
Moving to the next is okay now, but it still freezes if it can't find a match: 

- if there is no match
- if there were a case insensitive match, for example:

Put a string in a cell: **Foobar** (with capital F)
Then search for foobar (with a lowercase f): `:int goto "foobar"`

**Comment by andmarti1424** [comment]
Could you please try again. Now search does not cycle..

**Comment by spcmd** [comment]
Seems okay, but yeah, search does not cycle. 

By the way, is there a way to enable case **in**sensitive search (by default)?

**Comment by andmarti1424** [comment]
It does not cycle. May be we can add it when I rewrite this for the new freeze (v0.6) version.
Regarding the case insensitive search.. you can may be use reg expressions..

**Comment by spcmd** [comment]
Ok, the cycle is not that important for me, personally. But a case insensitive option/setting would be good. If it could be set in the .scimrc to be case insensitive by default, it would be great. Just a suggestion. :)

**Comment by andmarti1424** [comment]
Yes. Please open a new issue, and we label it as user request..
