### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by spcmd** [andmarti1424/sc-im#152]
String search is now case sensitive. So for example, if you have "Foobar" in a cell and you search for "foobar" (`:int goto "foobar"`), it won't find it.

I think search should be case _insensitive_ by default or at least it should be configurable in `.scimrc`.

Or maybe it could be _smartcase_, like the option in Vim, see: [http://vim.wikia.com/wiki/Searching#Case_sensitivity](http://vim.wikia.com/wiki/Searching#Case_sensitivity)

**Comment by andmarti1424** [comment]
We leave this as a feature request for next version. You could probably use reg exp for these cases..

**Comment by andmarti1424** [comment]
I added this to the new branch (freeze). it will be there in next release. You will be able to set this in runtime or in your .scimrc file

**Comment by andmarti1424** [comment]
Could you give it a try?

**Comment by spcmd** [comment]
Sorry, I misunderstood you, I thought I should wait until it gets merged into the master branch.
Anyway, I switched to the freeze branch and tried it, It seems to work fine. Thanks!

**Comment by andmarti1424** [comment]
Closing this now. These fixes are now in the default branch, which is freeze.
