### ISSUE TITLE
Fails to compile on FreeBSD aarch64

### ISSUE THREAD

**Issue by yokattana** [andmarti1424/sc-im#153]
Noticed this while checking out the FreeBSD port:

https://svnweb.freebsd.org/ports/head/math/sc-im/Makefile?r1=434438&r2=434754&pathrev=434754

I don't know any details but will try to reproduce.

**Comment by andmarti1424** [comment]
Do you know since when it is happening?

**Comment by yokattana** [comment]
Unfortunately no. This change was on 20 Feb but that doesn't say much as official aarch64 support was, I think, only added with the fairly recent release of FreeBSD 11.

I'll try to set up a cross build + emulation system to see if I can reproduce the issue.

**Comment by andmarti1424** [comment]
What I want to understand is.. 
is this problem caused by an update in FreeBSD?

**Comment by yokattana** [comment]
FreeBSD 11 added aarch64 (arm64) support. It appears the maintainer found that the sc-im port doesn’t build on that architecture.

I’ve set up an emulated chroot from the FreeBSD 11 aarch64 base package and succesfully compiled and installed sc-im without encountering the issue mentioned by the maintainer. Log attached.

I’ll send him an email to ask if he can help reproduce to that it can be fixed.
[log.txt](https://github.com/andmarti1424/sc-im/files/835216/log.txt)

**Comment by yokattana** [comment]
> 0.4.0 was busted on aarch64 and armv6[1] but 0.5.0 builds fine[2].
> 
> [1] http://thunderx1.nyi.freebsd.org/data/110arm64-default/432608/logs/errors/sc-im-0.4.0.log
>     http://beefy8.nyi.freebsd.org/data/head-armv6-default/p434391_s313928/logs/errors/sc-im-0.4.0.log
> [2] http://thunderx1.nyi.freebsd.org/data/110arm64-default/434495/logs/sc-im-0.5.0.log
>     http://beefy8.nyi.freebsd.org/data/head-armv6-default/p434757_s314234/logs/sc-im-0.5.0.log

https://lists.freebsd.org/pipermail/freebsd-ports/2017-March/107724.html

Once the port file is updated everything should be good and I'll close this issue.

**Comment by andmarti1424** [comment]
Great! Thanks for your work!

**Comment by yokattana** [comment]
Fix is in:

> I've committed the fix.  Thanks for reporting and testing.

https://lists.freebsd.org/pipermail/freebsd-ports/2017-March/107729.html
