### ISSUE TITLE
All expressions evaluating to zero

### ISSUE THREAD

**Issue by liamscarlett** [andmarti1424/sc-im#156]
Running on macOS. Makefile unchanged. All expressions are being evaluated to zero for me. Even a simple =1+1 will return a value of 0 in that cell.

**Comment by luis-agapito** [comment]
Same issue here

**Comment by liamscarlett** [comment]
I have checked v0.4.0 on the same OS and the issue is not present.

**Comment by roman65536** [comment]
Not sure, if this is related, andres did some changes due to other problem, where we obsorved

**Comment by andmarti1424** [comment]
Yep. Probably. If you're there.. 
Could you please Roman, comment that change in eval, until we look at the other issue more carefully?

**Comment by roman65536** [comment]
Not any more.. I'm bit off the source, would introduce other problems.
