### ISSUE TITLE
:wq save and exit feature

### ISSUE THREAD

**Issue by liamscarlett** [andmarti1424/sc-im#157]
Is it possible to add the :wq save and exit command to be in fitting with the vim syntax? I understand that the :x vim command is available in sc-im but for those who are accustomed to the :wq command it is just habit.

**Comment by andmarti1424** [comment]
@roman65536 , what do you think about this issue. shall we add this?

**Comment by roman65536** [comment]
it's habit of every vi user :) 
on the otherhand... not sure whether simple keyboard mapping can do it ;)
but go ahead.

**Comment by andmarti1424** [comment]
I just added this.
Key mappings works only for normal mode and insert mode..

**Comment by liamscarlett** [comment]
the latest revision causes a segmentation fault on launch of scim in macOS.

**Comment by andmarti1424** [comment]
Can you send us stack trace?

**Comment by liamscarlett** [comment]
Actually I've checked some of the previous commits and it's actually the commit "Add stderr buffer and changed bail function in lua.c" where the issue appears. This is the backtrace I get from gdb, not sure if this helps.

**Comment by andmarti1424** [comment]
Probably the setvbuf is not portable to OSX..

**Comment by andmarti1424** [comment]
segfault details is not much help.
could you please comment one by one,
each of the following lines, to see which one generates the SEGFAULT?

101: freopen("/dev/stderr", "w", stderr);
102: setvbuf(stderr, stderr_buffer, _IOFBF, 1024);

thanks.

**Comment by liamscarlett** [comment]
The segfault is still generated with either one of those lines commented.

**Comment by andmarti1424** [comment]
Same with latest commit?

**Comment by andmarti1424** [comment]
Close this and open a new issue for the issue @liamscarlett reported.
