### ISSUE TITLE
Undo issues

### ISSUE THREAD

**Issue by btiffin** [andmarti1424/sc-im#158]
= all by itself clears a cell, but does not allow Undo

But =1, setting a cell to a value, does.  For instance, on a new sheet.

    =12
    =1
    u (back to 12)

    =12
    =
    u (cell stays empty, but a change message is display on the top status line)

Plus a minor typo when the Undo buffer is empty.  Message is 'Not UNDO's left', should be 'No' instead of 'Not'.

And a kudos:  Nice work on 0.5 Andrés, this is getting awesomer and awesomer.

**Comment by andmarti1424** [comment]
Well, that should not be easy to fix. Thanks x reporting. Btw, did you finish the doc?

**Comment by andmarti1424** [comment]
Could you please update to latest commit in freeze branch and try again?

**Comment by btiffin** [comment]
Fixed.  Well done.

No on doc completion, but yes on working on it again.  The Lua links seem very much worth exploring.  And I'll be giving the piping features a walk thru today.

**Comment by andmarti1424** [comment]
You'll have to thank @roman65536 for his work with lua/triggers/c dynamic linked modules..
Can't wait to see that man page.
