### ISSUE TITLE
SEGFAULT during launch of SCIM in macOS.

### ISSUE THREAD

**Issue by andmarti1424** [andmarti1424/sc-im#159]
@liamscarlett reported SEGFAULT during launch of SCIM in macOS.
Issue appears after commit "Add stderr buffer and changed bail function in lua.c" 

Things to check:
101: freopen("/dev/stderr", "w", stderr);
102: setvbuf(stderr, stderr_buffer, _IOFBF, 1024);
ncurses in macos not supporting newterm correctly.

**Comment by liamscarlett** [comment]
In the latest commit the program terminates immediately after starting, without a generating a SEGFAULT.

**Comment by andmarti1424** [comment]
Well, then its one of those lines that is generating this problem.

**Comment by andmarti1424** [comment]
I dont have here the darwin VM:

if you comment in main.c, leaving it like this:
`100     /* setup stderr buffer
101     if (freopen("/dev/stderr", "w", stderr) == NULL) {
102         fprintf(stderr, "Error opening stderr\n");
103         return -1;
104     }*/
105     if (setvbuf(stderr, stderr_buffer, _IOFBF, STDERRBUF) != 0) {
106         fprintf(stderr, "Error setting stderr buffer\n");
107         return -1;
108     }`


you still get segfault or does not start?

**Comment by andmarti1424** [comment]
just to tell.
workaround would be commenting this in main.c:
    // setup stderr buffer
    if (freopen("/dev/stderr", "w", stderr) == NULL) {
        fprintf(stderr, "Error opening stderr\n");
        return -1;
    }
    if (setvbuf(stderr, stderr_buffer, _IOFBF, STDERRBUF) != 0) {
        fprintf(stderr, "Error setting stderr buffer\n");
        return -1;
    }

and this in screen.c:
46:    sstderr = newterm(NULL, stderr, NULL);
47:    noecho();

93:    set_term(sstderr);
94:    endwin();


really dont know why the first freopen fails in macos.
any macos user can give us a clue??

**Comment by andmarti1424** [comment]
please update to latest commit and rebuild it.
it should rebuild using -lncursesw rather than -lncurses..
I still do not know why freopen fails for stderr...

**Comment by andmarti1424** [comment]
Could you give it a try?

**Comment by yokattana** [comment]
I'm not sure if using ncursesw is the right way. If I recall correctly that would need to be installed through Homebrew or such, while the system ncurses already has wide character support built in.

**Comment by liamscarlett** [comment]
Sorry for taking so long to get back to you. I have been unable to make the latest commit - issues finding ncursesw library. Will continue to try and get that working...

**Comment by andmarti1424** [comment]
The thing is that the ncurses build of macos seems not having the initscr funxtion built in. That seems to be the cause of the segfault. Installing the ncursesw throw homebrew works flawlessly.

**Comment by andmarti1424** [comment]
Well, this should be fixed using ncursesw. Still to determinate:
1. why the stock ncurses caused the SEGFAULT and why that does not happen with ncursesw..
2. why the freopen failed for stderr in macOS.

**Comment by liamscarlett** [comment]
Yes, this has fixed the problem. Just required adding the following to the Makefile.

LDFLAGS =  -L/usr/local/opt/ncurses/lib
CPPFLAGS = -I/usr/local/opt/ncurses/include

**Comment by yokattana** [comment]
Are you sure it's because of that missing function? Because then if you include the correct headers it shouldn't even be in there and compile.

I'd avoid adding a dependency to Homebrew if possible.

**Comment by andmarti1424** [comment]
Pretty much. If you want to build it with ncurses rather than ncursesw you can try changing initterm for initscr in screen.c

**Comment by andmarti1424** [comment]
@yokattana, did you check the "Build instructions for OSX" in the "Building SC IM" wiki? There its explained how to install homebrew..

**Comment by yokattana** [comment]
@andmarti1424 I’m familiar with Homebrew but would appreciate if it weren’t a dependency.

It appears that system ncurses has trouble with a null `ifp` parameter. The segfault happens on a call to `filestat(ifp)`. A cursory web search indicated that certain versions of ncurses do indeed not accept null for that value.

This changes prevents the segfault:

```diff
--- a/src/tui.c                              
+++ b/src/tui.c
@@ -81,7 +81,7 @@ SCREEN * sstdout;
 srange * ranges;

 void ui_start_screen() {
-    sstderr = newterm(NULL, stderr, NULL);
+    sstderr = newterm(NULL, stderr, stdin);
     noecho();
     sstdout = newterm(NULL, stdout, stdin);
     set_term(sstdout)
```

I really don’t know anything about ncurses itself so this might not be the right approach. However, with this change, sc-im builds and runs fine against just system libraries (with `-lncurses`).
