### ISSUE TITLE
how dot command works..

### ISSUE THREAD

**Issue by svenn71** [andmarti1424/sc-im#161]
When pressing '.', I would expect the previous thing done to be redone, like inserting a number, or adjusting a column to its contents. Instead, an undo is done if undo has been done or redo if redo has been done. I find this behaviour disturbing.

**Comment by andmarti1424** [comment]
Well, right now only edition commands can be used with the "." command.
but of course we can rethink how this command works..

**Comment by svenn71** [comment]
The most annoying thing was doing :autojus and then move to another column and press . just to experience that the previous justification was undone. Being a vim user, it is extremely hard to 'unlearn' the use of .

**Comment by andmarti1424** [comment]
Well. This is not happening to me. For me, the use of "." in that case, causes the second column to autofit.
You are using v0.5 or the freeze branch?

**Comment by svenn71** [comment]
freeze

**Comment by andmarti1424** [comment]
Just noticed that if you autofit with C-j and then press "." then it works. It does not if you use the :autojus in command mode.

**Comment by andmarti1424** [comment]
Another thing, in vim, "." command does not interact with command mode. does it?
For instance, if you type :tabnew and then press ".", it does not open a new tab..

**Comment by andmarti1424** [comment]
Well, then may be we can ignore undo/redo for the dot command..

**Comment by andmarti1424** [comment]
undo/redo are now ignored by the dot command..
