### ISSUE TITLE
autobackup files

### ISSUE THREAD

**Issue by svenn71** [andmarti1424/sc-im#162]
sc-im is segfaulting a lot on me, and I feel that I need to save all the time to not lose work. Could a temporary autosave file be implemented?

**Comment by andmarti1424** [comment]
yep. that is a TODO item for v0.7.
could you give us more details of those segfaults?
what is your OS?

**Comment by svenn71** [comment]
I am running Debian sid and a whole lot of custom compiled libraries and tools in /usr/local. I will try to have some cores dumped and do inspection with gdb to see if I can find any pointers to where things go wrong.

**Comment by andmarti1424** [comment]
That would be great.

**Comment by andmarti1424** [comment]
I believe i might have found what are you causing that segfaults. please edit your Makefile and disable the "insert mode history"..

**Comment by andmarti1424** [comment]
Could you update to latest commit? Did those segfaults get fixed?

**Comment by andmarti1424** [comment]
@svenn71, could you update to latest commit? Did those segfaults get fixed?

**Comment by svenn71** [comment]
I have not been able to make reproducable segfaults in a while.

**Comment by andmarti1424** [comment]
@svenn71, could you test this feature?

**Comment by andmarti1424** [comment]
@svenn71, could you test this feature?
