### ISSUE TITLE
Small error in manpage

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#163]
Hi,
great tool btw. There's a bad reference to an old keymapping on the manpage:

```
E      Edit  the  string ...  This is identical to ``<'', ``"'', or ``>'' except ...
```
should probably be
```
E      Edit  the  string ...  This is identical to ``<'', ``\'', or ``>'' except ...
```
Guess there was a remapping at some point and this didn't get updated. Unfortunately I didn't easily find the source corresponding to the manpage, otherwise I would have created a pull request for this.

**Comment by andmarti1424** [comment]
Done. Thanks!
