### ISSUE TITLE
[Question] Transparent Background

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#164]
Is it possible to use the default terminal background when defining colors?

**Comment by andmarti1424** [comment]
I dont believe ncurses allows this. If it does, we may be can add it.

**Comment by ber532k** [comment]
I have seen quite some ncurses-based programs which use my default background color. Ncmpc for instance. I also created a small python and ncurses script that uses it a while ago. I believe it has something to do with [``use_default_colors()``](https://linux.die.net/man/3/use_default_colors), but I'll check if I can find out more about it.

In my python script I used ``use_default_colors()`` and afterwards attributes like ``A_STANDOUT`` in ``.addstr()``. But then that's the python wrapper library, no idea about the original C.

**Comment by ber532k** [comment]
From the [manpage](https://linux.die.net/man/3/use_default_colors) it looks like ``init_pair(x,COLOR_RED,-1)`` specifies red text on default background - whatever the latter may be.

**Comment by andmarti1424** [comment]
Mat be you can try redefining 
#define BLACK  to -1 in macros. H and then setting a color to black to see if that preserve default background color..

**Comment by ber532k** [comment]
How do I define BLACK to -1? Is that via redefine_color?

**Comment by andmarti1424** [comment]
Lime 47 of macros.h . Just change COLOR_BLACK to -1

**Comment by ber532k** [comment]
That makes the background white. I guess it uses the default foreground instead of the default background color.

**Comment by ber532k** [comment]
Changing COLOR_RED in macros.h to -1 makes a small part of the background transparent. No Idea why. I guess using default colors is something bigger.

**Comment by andmarti1424** [comment]
I did some tests. I got the default background if I use use_default_colors() instead of start_color() in screen.c,  but then any foreground cannot be changed. init_pair(..,COLOR_RED,-1) does not work for me.

**Comment by ber532k** [comment]
That works for me as well. I guess this would be the way to go, but
the whole way colors are specified would probably need to be adapted
to ``use_default_colors()``. If I find time tomorrow, I might try to
look into that.

**Comment by andmarti1424** [comment]
As I said, foreground colors does not work for me.. dont know if it because of my ncurses rebuild or not..
i simple tried:use_default_colors() and the int_pair(.., COLOR_RED, -1).. no luck.

**Comment by ber532k** [comment]
By removing ``start_color()`` you simply deactivate all colors. As a side effect this gives you the default background. Something you can do is simply edit ``color.c`` and change
```
    ucolors[ DEFAULT         ].bg = BLACK;
```
to
```
    ucolors[ DEFAULT         ].bg = -1;
```
This gives you the default color as background. Unfortunately it uses the default foreground color instead of the background color and I could not yet understand how the pairs are initialized from these ucolor settings. Instead of converting ``ucolors[ DEFAULT         ].bg = -1`` to ``WHITE``, ``-1`` would need to be passed on to ``init_pair``.

**Comment by andmarti1424** [comment]
Just do this test. change line 102 of color.c and set all the init_pairs to (x, COLOR_RED, -1)
just to see if the default background is preserved.
and you'll notice it wont.
this its not related to ucolors..
just not working the way the doc says..

**Comment by ber532k** [comment]
In the end it was an issue with ucolor. I was able to reimplement ucolor as nucolor (with slightltly different syntax) and now default terminal colors can be used as expected. I'll create a pull request so you can see what I did. Anyway, there are still some changes necessary to make nucolor handle user configuration and the like. Please tell me what you think and if you're interested in merging.

**Comment by andmarti1424** [comment]
Great. Generate a pull request, and I'll check the code..

**Comment by andmarti1424** [comment]
Please check latest commit. There is no need to change all that code. Just a few lines.

**Comment by ber532k** [comment]
Basically this works, but try editing color.c and using:
```
    ucolors[ HEADINGS        ].fg = DEFAULT;
    ucolors[ HEADINGS        ].bg = DEFBG;
```
This leads to some strange bug and I'm not sure where that comes from. It might still be fixed and everything might work well.

**Comment by ber532k** [comment]
I created a pull request fixing this bug. Basically, I can live with the way you implemented this as well.

Just one more little thing: If one wants to refer to default-terminal-foreground in some configuration file or via ``:color`` command the syntax is currently ``fg=DEFBG``. This is counterintuitive. Maybe we could add ``#define DEFFG=-1`` or even free ``DEFAULT`` for ``-1`` for  this and change what currently is ``DEFAULT`` (namely index 0 and references to that) to something like ``DEF`` or ``DEF_FORMAT``. The latter definition ``#define DEFAULT=0`` (as far as I understand) is only used inside the code and not exposed to the user, thus reducing the need for intuitive naming.

If you're interested I would be happy to implement either.

**Comment by ber532k** [comment]
Sorry, my bad, no bug after all. I used ``fg=DEFAULT`` which produced the error.

**Comment by ber532k** [comment]
Other than the above I'm happy with the changes you made. Feel free to reject the pull request and close this issue in case you want to stick to DEFBG.

**Comment by andmarti1424** [comment]
DEFAULT_COLOR it is.
Updated doc as well.
Thanks.
