### ISSUE TITLE
Bug: recalculation stops when copying an expression

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#167]
Basically what the title says. I create a cell range with numbers (say column A) and an expression ``@sum(a0:a100)`` at B1. B1 gets recalculated when A changes as expected. Now I copy B1 to C1 (``x l p``) and C1 does not get updated until I reenter the expression in C1 (``e a <ENTER>``).

**Comment by andmarti1424** [comment]
Will check it out. Thanks

**Comment by andmarti1424** [comment]
Could you please update to latest commit and try again?

**Comment by ber532k** [comment]
Wow you're quick. Works for me, thanks!
