### ISSUE TITLE
Handling <esc> in insert mode.

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#168]
When in insert-mode, ``<ESC>`` will throw you back to normal-mode, discarding all previous changes. I suggest ``<ESC>`` should rather throw you back to edit-mode and only a second ``<ESC>`` leads to normal-mode.

**Comment by andmarti1424** [comment]
You mean if you go to edit mode, then jump from edit mode to insert mode and press ESC...right?
Cause otherwise.. if you are in insert mode, you dont neccesary stayed in edit mode before..
in that case you should not go to edit mode.

**Comment by ber532k** [comment]
Yes, definitely the first one. Nor sure about the second. I  guess I would like it if there was also an intermediary edit mode there, but I guess that's a matter of taste.

**Comment by andmarti1424** [comment]
Well, if other people thinks it would be a good change.. we'll sure can change this.
I leave this open until then.

**Comment by svenn71** [comment]
I support the possibility to go edit-insert-edit-insert by one <esc> and edit-insert-normal with two <esc>.

**Comment by andmarti1424** [comment]
please could you update to latest freeze branch commit and test this new feature? Thanks!

**Comment by ber532k** [comment]
Works for me, thanks!
