### ISSUE TITLE
.csv file can be rewritten with .sc formatted content.

### ISSUE THREAD

**Issue by chris-easton** [andmarti1424/sc-im#171]
Start sc-im from the command line with a file argument (not .sc format):
./scim ../files/csv/l1.csv
Do ":w"
This will overwrite the .csv file with .sc formatted content. When the .csv file is reopened the altered content can be seen.

**Comment by andmarti1424** [comment]
could you please update to latest freeze branch commit and try again?

**Comment by chris-easton** [comment]
It is fixed now. Thank you.
