### ISSUE TITLE
A few file-loading-related formatting issues

### ISSUE THREAD

**Issue by irskep** [andmarti1424/sc-im#172]
I'm trying to use this tool (which is very good in most ways!) to edit CSV files for a video game. I'm having a few problems storing some kinds of data. Entering it is fine, but when I read the file back, it's mangled in some way.

This happens for so many things it feels like expected behavior. I would love to know if I can have it just treat everything as opaque strings, maybe with a command line flag.

None of these are total showstoppers, but it means I have to change the way my game code reads the file, and it looks ugly.

## Example 1: commas

If I write a value like `a,b`, it is correctly stored as a quoted string `"a,b"`, but when I read it back, the  inner comma is removed (`ab`).

## Example 2: hash signs

If I write a value like `#ff0000` (an HTML color) and read it back, the `#` is removed.

## Example 3: integers

Integer values are parsed back as floats, so `1` ends up as `1.00` if I read and write the file again.

Thanks for your work on this tool! I can provide example CSVs if you need them. I'm working from current `master`.

**Comment by andmarti1424** [comment]
Hello. Could you please send some files to scim.spreadsheet@gmail.com ??

**Comment by andmarti1424** [comment]
n°2 is not happening to me. if I write #ff0000 to a csv file, it just gets loaded correctly.. and # is not removed
n°3 is not really a bug, its just how i wrote it. if its a number then, scim tries to load it as a number, and that is why it gets converted to number 1.00 with two decimals.. its the same as if you write =1.
n°1 is a bug. the comman should not be removed.

**Comment by andmarti1424** [comment]
Regarding, n°1, please update to latest commit of freeze branch and try again these cases..

**Comment by irskep** [comment]
I misspoke about number 2. The example was '#006688', which has only numerals.

I will respond to the rest later.

I just really wish that values I enter would stay as they are rather than being changed. Integers are integers, not floats!

**Comment by andmarti1424** [comment]
I still do not understand the problem you have with #006688. In the test I did it gets saved and loaded correctly as well.

**Comment by irskep** [comment]
I am also having trouble reproducing it, I will provide an example when it happens again.

**Comment by andmarti1424** [comment]
Regarding n°3, take note that the value itself in that case is still 1.
"1.00" is just the way it is shown because of the default precision..

**Comment by irskep** [comment]
Latest commit seems to fix my comma problem.

I still wish I could just configure it to treat everything as strings, but it sounds like that is not going to happen. I will live.

**Comment by andmarti1424** [comment]
May be we can add an option so that everything would be interpreted as text.

**Comment by irskep** [comment]
That would work nicely, then I could just alias `scim` to `scim --strings-only` or whatever.

**Comment by andmarti1424** [comment]
done. you can use --import_delimited_as_text flag or better yet, add it to your ~/.scimrc
