### ISSUE TITLE
problem building sc-im with colors

### ISSUE THREAD

**Issue by lancosch** [andmarti1424/sc-im#174]
I just compiled from the freeze branch, under linux linked with the latest ncursesw and it seems no colors are working. Using commands like :cellcolor "bg=CYAN fg=WHITE gives no error, just there is no visible effect.

My TERM variable is xterm-256color and all other ncurses related progs have working colors in my terminal.

Any idea? Thx.

ps: compiled from branch 0.6.0, it has the same issue

**Comment by andmarti1424** [comment]
Hello. This seems to be a problem with your ncurses build.
Which is your OS? You built ncurses yourself? If you did, take note that you have to configure it for building it with color support..

**Comment by lancosch** [comment]
Red Hat EL6, I built ncurses 6.0 with  --enable-ext-colors
All the demos come with the ncurses source tree are working with colors.

The odd thing I just noticed, looking at the scim binary with ldd I don't see any link to libncurses...

**Comment by pjpony** [comment]
Hi,
When I compiled 0.6.0 on Debian Jessie i had to first install cursesw dev files before the build would complete.

**Comment by andmarti1424** [comment]
Indeed @lancosch. It seems it is not linking properly to the ncursesw library you built.
Please check the LDLIBS and CFLAGS values you are using for building sc-im. You could also try building ncurses color examples using those values and see if colors appear ok.

**Comment by andmarti1424** [comment]
Yes, that is OK. You need libncursesw5-dev.

**Comment by andmarti1424** [comment]
I believe @lancosch, you might be having two different ncurses installations. One with colors, and one without colors.

**Comment by pjpony** [comment]
just another thought, figured i should check if it actually works for me ...

>>> Using commands like :cellcolor "bg=CYAN fg=WHITE gives no error, just there is no visible effect.

did you include the trailing double quote, or is it just missing in the example ?

syntax in sc-im :help example is :cellcolor "bg=CYAN fg=WHITE"

...without the closing quote, I also get "gives no error, just there is no visible effect."

**Comment by andmarti1424** [comment]
You should always close it, like this:
cellcolor "bg=CYAN fg=WHITE"

Red color of headings is not shown, right?

**Comment by pjpony** [comment]
I'm getting colour properly i think; cell, column index labels/borders are red.  cellcolor works with closing quote.

**Comment by andmarti1424** [comment]
yes thanks.
that question was to @lancosch..

**Comment by andmarti1424** [comment]
could you check it, @lancosch ?

**Comment by lancosch** [comment]
@andmarti1424  sorry for the late reply.
There was some missing switches in the ncurses configuration script, eg. create shared libs from the widechar version as well. After I got it, recompiled scim and ldd showed to correct link. It changed the behaviour, but it is pretty weird. The text on the welcome screen very dim, so as the text what shows the cell currently selected, everything else dark grey. If I enter something into a cell the text has the same dark grey colour as the background.

The heading show no red colour, and a cellcolor command does nothing either and yeah it has a trailing quote as well. :)

I didn't had much time to investigate, it is a company server, and every stuff installed is ancient, so every time I need something, I have to compile it from source with all dependencies...

**Comment by andmarti1424** [comment]
That is weird. Did you try building the ncurses examples then?

**Comment by lancosch** [comment]
Yes, all the ncurses examples working fine...

**Comment by andmarti1424** [comment]
I meant if they are working, after you build ncurses again with shared libs and widechar support..
If that is the case, please check the lines when building the examples and compare them to the lines when building sc-im.
those links to ncurses should be the same. if they are not, adapt your Makefile accordingly.

**Comment by andmarti1424** [comment]
could you check it, @lancosch ?

**Comment by lancosch** [comment]
Well IT started to make changes in toolchain availability so I am not be able to compile anything on that machine anymore.
Unless I will have the ability to retest in that environment again we should close this issue without conclusion....
