### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by laktak** [andmarti1424/sc-im#175]
When I enter an incorrect expression I get an `syntax error` and my input is gone.

After that I'd like to fix the syntax error but I found no way to get the input back or even see my mistake.

**Comment by andmarti1424** [comment]
Hello. What kind of content are you entering?
For instance, if you type =5g, it gives you "syntax error", and if you have INSERT_MODE history enable, you can press =, and move to latest command typed with C-p or UP key to correct the command.

**Comment by laktak** [comment]
Thanks, makes sense now. I think you could improve this by staying in insert mode.
