### ISSUE TITLE
cpaste broken

### ISSUE THREAD

**Issue by radostyle** [andmarti1424/sc-im#176]
When :cpaste is used the spreadsheet has a hard exit.

Using version df169951465a49936030736163f2029b20501e62
on OSX.  I tried with the standard tmux setting and the pbcopy/pbpaste settings in the Makefile.

    :cpastescim(22307,0x7fff782fd300) malloc: *** error for object 0x7fff5dff7200: pointer being freed was not allocated                                           -- COMMAND --
                                                                                                                        *** set a breakpoint in malloc_error_break to debug
        A         B         C         D         E         F         G         H         I         J         K         L         M         N         O         P         Q
Error !!! Quitting SC-IM.Abort trap: 6

**Comment by andmarti1424** [comment]
What is the exact content you are trying to paste?

**Comment by radostyle** [comment]
Hi Andres,

"12" is the content I was pasting.  I tried other content also and it also
broke.  If I comment out the free() on line 60 of clipboard.c  then it
works fine for me.

**Comment by andmarti1424** [comment]
Thanks for reporting this. Could you please update to latest commit in freeze branch and try again?

**Comment by andmarti1424** [comment]
Could you test this, @radostyle?

**Comment by jonalvarado** [comment]
9.us-west-2.compute.internal, 34101)
    :cpastescim(89090,0x7fff782fd300) malloc: *** error for object 0x7fff561e2c60: pointer being freed was not allocated                                           -- COMMAND --
                                                                                                                        *** set a breakpoint in malloc_error_break to debug
        A         B         C         D         E         F         G         H         I         J         K         L         M         N         O         P         Q
Error !!! Quitting SC-IM.Abort trap: 6
JAs-MacBook-Pro:src ja$

still broken for me

**Comment by jonalvarado** [comment]
If I comment out the line 

            //if (st != NULL) free(st);


then it works for me.

**Comment by andmarti1424** [comment]
Yep. That free should not be there. Thanks. Please update to be4852f commit.

**Comment by radostyle** [comment]
That (be4852f
<https://github.com/andmarti1424/sc-im/commit/be4852f78ce3daffe18190dbeda18aa102372f89>
 ) works.  Thanks.
