### ISSUE TITLE
When doing a 2-letter nmap.  The second letter is passed through.

### ISSUE THREAD

**Issue by jonalvarado** [andmarti1424/sc-im#178]
When doing a 2-letter mapping.  The second letter is passed through.
Ex: nmap "ab" ":w"
![image](https://cloud.githubusercontent.com/assets/4324111/26746834/a712afd6-47b7-11e7-9418-98f08d70a394.png)
When hitting "ab" on the keyboard the result is ":bw"  instead of the expected ":w"
![image](https://cloud.githubusercontent.com/assets/4324111/26746846/bc27bc2c-47b7-11e7-9954-b0e001ace116.png)

**Comment by andmarti1424** [comment]
@jonalvarado, please update to latest commit in freeze branch and try again.

**Comment by jonalvarado** [comment]
It works for me.  Thanks.
