### ISSUE TITLE
auto-suggestion/completion (super ticket)

### ISSUE THREAD

**Issue by 257** [andmarti1424/sc-im#18]
this shall be a super ticket for auto-suggestion/completion.
ideas so far:
1. implement pop-up menu like in vim for showing suggestions (youcompleteme et al use this)
2. a completer to fuzzy search possbile functions/named variables and so on
3. find or write a lib to talk to google's API for suggestions, pretty much the same google does it on it's own google-doc's spreadsheets.

**Comment by andmarti1424** [comment]
I thought about this before. There is a lot planned to get fixed / cleaned before plugin support though.

**Comment by foo-bar-baz** [comment]
https://cloud.google.com/prediction/docs/smart_autofill_add_on

**Comment by andmarti1424** [comment]
I believe this wont happen on version 1 of sc-im. Please feel free to open a discussion on adding this to v2 of SC-IM thoughts.
That one would have its core replaced and will support multisheet and multiple files open at the same..  Thanks.
