### ISSUE TITLE
Problem with sorting

### ISSUE THREAD

**Issue by njdan5691** [andmarti1424/sc-im#180]
I compiled scim on ubuntu
Linux divot 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

When I sort with a selection it seems to work, but when i specify a range it does not.
`:sort A0:A19 "+$A"`

```
# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

leftstring A0 = "Jacquelyne"
leftstring A1 = "Racheal"
leftstring A2 = "Ignacio"
leftstring A3 = "Deb"
leftstring A4 = "Ivonne"
leftstring A5 = "Hui"
leftstring A6 = "Thea"
leftstring A7 = "Oralee"
leftstring A8 = "Marco"
leftstring A9 = "Althea"
leftstring A10 = "Julene"
leftstring A11 = "Giuseppina"
leftstring A12 = "Pei"
leftstring A13 = "Luci"
leftstring A14 = "Bunny"
leftstring A15 = "Willena"
leftstring A16 = "Vernell"
leftstring A17 = "Nicolette"
leftstring A18 = "Malia"
leftstring A19 = "Phylicia"
```

**Comment by andmarti1424** [comment]
Yes. It seems a little problem exists when no range is selected. Until I fix this, you can try sorting it like this:
:int sort A0:A19 "+$A"

**Comment by andmarti1424** [comment]
Please update to latest commit in freeze branch and try again.

**Comment by njdan5691** [comment]
Great,
Thanks for the quick response and the work around. I like the changes you have made to sc.

**Comment by njdan5691** [comment]
i'm not very git literate. If fact 'git clone' is the sum total of my git knowledge. What git command would i use to get those changes

**Comment by andmarti1424** [comment]
git pull

**Comment by njdan5691** [comment]
Looks Good
