### ISSUE TITLE
handle " in maps

### ISSUE THREAD

**Issue by njdan5691** [andmarti1424/sc-im#184]
Is this just not documented?, does it work different?  Was it just left out in favor of using key maps? When I define a keymap with the `nmap` is there a way to escape the `"` so i can do something like the sort command?

**Comment by andmarti1424** [comment]
I left out fkey commands..
I really did not try escaping double quotes. may be its possible, may be its not.
may be a patch is needed for that.

**Comment by njdan5691** [comment]
This is an example of what I tried. 
```
# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

nmap "d" "sort A0:Z300 \"+$a\""
nmap "f" "sort A0:Z300 \"+$a\""

leftstring A0 = "David"
let B0 = 59
leftstring A1 = "Penny"
let B1 = 45
leftstring A2 = "John"
let B2 = 70
leftstring A3 = "Allen"
let B3 = 22
leftstring A4 = "Barbra"
let B4 = 28
```

**Comment by andmarti1424** [comment]
I think this should be handled correctly.

**Comment by andmarti1424** [comment]
Could you please update to latest commit in freeze branch and try your example again?

**Comment by andmarti1424** [comment]
Take note that you can map the enter key like this:

**Comment by njdan5691** [comment]
That looks good. There does seem to be a pause before the sort happens. I left the <CR> off so that I could review the command before it was sent. There is a small snafu in the doc, the example uses `<cr>`, not `<CR>`, which does not work.

**Comment by andmarti1424** [comment]
The last got fixed by a commit jist after the one you pulled.
That pause is just the sorting time. because you sort a lot of cells.. Try
the range i proposem

**Comment by andmarti1424** [comment]
Could you try that again with latest commit?

**Comment by njdan5691** [comment]
Looks good, <cr> works just as <CR>.
