### ISSUE TITLE
Support more file formats - ODS

### ISSUE THREAD

**Issue by ghost** [andmarti1424/sc-im#185]
It would be nice if .ods was supported, it's the open spreadsheet format used by LibreOffice, Open Office, etc.

Also, it would be nice if scim could open compressed (i.e. a .sc.gz file) or  GPG encrypted (.sc.gpg) files. Vim can edit a password protected GPG file via a plugin or some settings in .vimrc with pinentry-curses installed, which is useful if your file contains sensitive information.

**Comment by andmarti1424** [comment]
ODS format can be added for future versions, but it would require a lot of work/time.

**Comment by leorosa** [comment]
> Also, it would be nice if scim could open compressed (i.e. a .sc.gz file)

How about a bash script? For gzip files,

```
# zscim.sh
filename="${1%.*}"
gunzip "$1"
scim $filename
gzip $filename
```

**Comment by dannycolin** [comment]
> @andmarti1424 ODS format can be added for future versions, but it would require a lot of work/time.

It's many a lot of work but a software that have no interoperability with other programs that support ODS is IMHO worthless. In other words, there's no point to use a software with which you can't share your documents (and have almost no userbase). Don't get me wrong, I really like your project and I'm thankful for all the hours you spent on it but we need to be realistic. So, supporting ODS and other moderns functionalities like comments would be a game changer.

**Comment by andmarti1424** [comment]
Your opinion is respected. You can decide whether to use it or not.
About sharing your doc files, you can do so in other formats. As csv, for instance.

About the ODS support (and other formats), you can also make the mods neccesary and generate a pull request. I will be happy to analize your code and merge it to mainline.

**Comment by hymie0** [comment]
> @dannycolin  a software that has no interoperability with other programs that support ODS is IMHO worthless.

`sc` is not software I often expect to share data with/from.

I have a LibreOffice spreadsheet that I use to do my taxes.  With all due respect to @andmarti1424 , I wouldn't dream of doing my taxes in `sc`.

But when I have a quickie need, like "comparing the commuting costs of driving vs train" or "tracking my daily meal expenses", `sc` is perfect, and I wouldn't want the overhead of firing up Libre Office.

IMHO, two different programs, two different needs.

**Comment by andmarti1424** [comment]
Anyone know an ods library for C?

**Comment by andmarti1424** [comment]
Hello. I gave sc-im some basic ods files import. Please feel free to test it.
The guy who requested this has its account deleted..

**Comment by andmarti1424** [comment]
Anyone could test it?
