### ISSUE TITLE
executable name interferes with other application

### ISSUE THREAD

**Issue by charlespax** [andmarti1424/sc-im#186]
Ubuntu has a package named `scim`.

On Ubuntu `apt-cache show` gives a description of
```
Description-en: smart common input method platform
 Smart Common Input Method (SCIM) is an input method (IM) platform.  Input
 methods are needed to enter complex characters in many non-latin languages.
 SCIM provides a common platform for various plugin modules and independent IM
 programs, as well as a set of modules and programs on its own.  It is highly
 modularized and exposes abstract interfaces, so that plugin modules with
 different functions can easily communicate with each other.  The currently
 supported module types are configuration, IM engine, front end, filter, and
 setup GUI.
```

I think the executable of sc-im should be changed from `scim` to `sim` for sc improved. On second thought, it might be better to have a name that is likely to return results relevant to the program. 'scim' and 'sim' returns many irrelevant results.

**Comment by andmarti1424** [comment]
You can change binary name in Makefile.

**Comment by charlespax** [comment]
I'm thinking more in terms of possible future inclusion in Debian and other Linux distros. Neither `scv` nor `svm` appear to be taken and might be good choices.

Assuming scim is not an option, if someone were to package sc-im and submit it to Debian, what would you like the executable to be named?

**Comment by andmarti1424** [comment]
I leave this for package maintainers to choose the best one.. Some use scim-spreadsheet..
