### ISSUE TITLE
Segfault when searching for = in help

### ISSUE THREAD

**Issue by charlespax** [andmarti1424/sc-im#188]
Open sc-im. Open help by typing `:help`. Search for the equals sign by typing `/=` and pressing `ENTER`. Press `n` to go to the next result. The 41st time I press `n` I get a segmentation fault.

**Comment by andmarti1424** [comment]
Thabks for reporting thus. Will check it out

**Comment by andmarti1424** [comment]
I am afraid I am not able to reproduce this. I search every '=' in the file, until the end that displays "Pattern not found".

**Comment by andmarti1424** [comment]
Could you reproduce this? I am afraid I can't.

**Comment by charlespax** [comment]
I can reproduce it very reliably. The same result happens if I run scim from the src/ directory or typeing `scim` after it's installed.

I poked around a bit more and there's more to the mystery. I edited the doc file to have a bunch of lines, each with `=` on it. Then the problem stopped happening. After doing an `git checkout src/doc` the problem is back. This tells me it's not strictly an issue with the number of results and it's not a problem formatting in the doc file. Weird. I'll keep digging.

**Comment by andmarti1424** [comment]
Does this also happen if you move to the end and search the '=' backwards?

**Comment by andmarti1424** [comment]
Another important thing I am thinking right now!!!
What is the size of the terminal you are running scim?
80x25? 80x30?

**Comment by charlespax** [comment]
I think you're on to something!!!

ERROR:
```
$ tput cols
88
$ tput lines
53
```
ERROR:
```
$ tput cols
88
$ tput lines
25
```
WORKS:
```
$ tput cols
119
$ tput lines
41
```
WORKS:
```
$ tput cols
83
$ tput lines
41
```

**Comment by charlespax** [comment]
I do not get the error when searching backwards. I tried searching backwards in a 88x53 terminal that fails when searching forward.

**Comment by andmarti1424** [comment]
I could reproduce the segfault with 88 cols by 53 lines.
I now have something to work with. Will report back.

**Comment by andmarti1424** [comment]
Could you please update to latest commit in freeze branch and try again?

**Comment by charlespax** [comment]
Tested with commit d76edd90b8635245478ab85cbf2fc14a3eec6e7c. No error.

Tested on:
```
tput cols; tput lines
89
54
```

I think you can close this.

**Comment by andmarti1424** [comment]
Thanks!
