### ISSUE TITLE
:cellcolor formatting modifies only the specified parameters

### ISSUE THREAD

**Issue by charlespax** [andmarti1424/sc-im#190]
:cellcolor <range> "bold=1" will reset any cell coloring back to the default values. I haven't tested this after manually setting color values, but it's at least true for whatever formatting is displayed when first entering text or numbers. It would be nice if the cell colors would remain as they are and only become bold.

What are you thoughts on this feature? If it's something you think would be good, I'd like to take a crack at it. I'm working to learn the codebase and this seems like a good project for me.

**Comment by andmarti1424** [comment]
I will try to modify this. I believe you are right.

**Comment by andmarti1424** [comment]
Actually, I did this
`:cellcolor "bg=CYAN fg=RED bold=0"`
over a cell with a number
and then
`:cellcolor "bold=1"`

The result was that bold was set correctly AND the cyan background and red foreground remain set as well. So.. this seems to be working OK.
 I inspected the code and It will only change background and foreground color to default one, only if there is no color (ucolor is the structure name) set over the cell..

**Comment by andmarti1424** [comment]
Hello @charlespax, could you take a look at this?

**Comment by charlespax** [comment]
I tested what you did and that works as I would expect. First I add some text then...

```
:cellcolor "bg=CYAN fg=RED bold=0"
:cellcolor "bold=1"
```

The unexpected behavior come from typing `:cellcolor "bold=1"` on text that has no formatting.
![screenshot from 2017-12-14 16-48-41](https://user-images.githubusercontent.com/281642/34016113-b4cbf120-e0ee-11e7-962b-4176f5c2185e.png)

I would expect sc-im to not set the bg or fg to anything.

**Comment by andmarti1424** [comment]
Now I see what you are saying. Please update to latest commit and try again!

**Comment by andmarti1424** [comment]
Hello @charlespax, could you take a look at this? I commit a change regarding this, a couple of days ago. Thanks.

**Comment by charlespax** [comment]
I did the same procedure as described in my last comment. Everything appears to be working as expected.

![screenshot from 2017-12-28 00-42-10](https://user-images.githubusercontent.com/281642/34401300-034a924c-eb68-11e7-879f-cbb3cd77dbef.png)

Happy debugging with you! I think you can close this issue :-)
