### ISSUE TITLE
conf.c code organization [question]

### ISSUE THREAD

**Issue by charlespax** [andmarti1424/sc-im#191]
In main .c we have:
```
    // start configuration dictionaries
    user_conf_d = (struct dictionary *) create_dictionary();
    predefined_conf_d = (struct dictionary *) create_dictionary();
    store_default_config_values(); // Stores in user_conf_d   
```
in conf.c we have:
```
void store_default_config_values() {
    put(user_conf_d, "half_page_scroll", "0");
    put(user_conf_d, "autocalc", "1");
    put(user_conf_d, "numeric", "1");
```
How do you feel about me modifying the three functions in conf.c to accept a dictionary (or pointer to the dictionary) as an argument?

In main .c we would have:
```
    // start configuration dictionaries
    user_conf_d = (struct dictionary *) create_dictionary();
    predefined_conf_d = (struct dictionary *) create_dictionary();
    store_default_config_values(user_conf_d); // Stores in user_conf_d   
```
in conf.c we would have:
```
void store_default_config_values(<dictionary pointer>) {
    put(<dictionary pointer>, "half_page_scroll", "0");
    put(<dictionary pointer>, "autocalc", "1");
    put(<dictionary pointer>, "numeric", "1");
```
I think for people (like myself) going through the code first time would find it easier to understand how the code works if the code avoids using variables declared outside a given file. The code would be more modular and reusable. It would also be a bit nicer when grepping through the code looking for instances of `user_conf_d`.

I'm just going through the code for the first time, so maybe there's some non-obvious reason things are set up the first way and not the way I described. What are your thoughts?

**Comment by andmarti1424** [comment]
That change can be made, but user_conf_d and predefined_conf_d should be still declared in main.c.
