### ISSUE TITLE
Doxygen support

### ISSUE THREAD

**Issue by charlespax** [andmarti1424/sc-im#192]
It would be great if sc-im had doxygen comments, so documentation can be automatically generated.

I've been playing with with doxygen in a little helloworld project and I really like the output. I've even been able to have the files hosted directly from inside the repository via github pages. Check it out: https://charlespax.github.io/hello_c

As I'm learning the code base I can go through and convert comments into doxygen style comments. I've already been doing this in my sc-im fork, but I went a little overboard and wrote a template for everything. After learning a bit more I think I would start from scratch and only do things as I am able to document them. Otherwise things get a bit cluttered.

What do you think?

Here is an example of a caller graph that was generated for main()
![capture2](https://user-images.githubusercontent.com/281642/28636606-3f1132f6-7271-11e7-9f96-b50d5db3f890.PNG)

And here is one for exit_app()
![capture](https://user-images.githubusercontent.com/281642/28636497-e6de8502-7270-11e7-95cc-41cca0652194.PNG)

**Comment by charlespax** [comment]
I've added doxygen support for most of the files. See pull request #194.

**Comment by andmarti1424** [comment]
How this will work when I merge your work?? How can I see the documentation?

**Comment by charlespax** [comment]
I've merged the most recent freeze code into doxygen, so it should be a clean merge.

I just pushed a small change to the Makefile for generating the documentation files and cleaning them up. To generate the documentation enter the `sc-im/src` directory and type `make docs`. You will find the documentation in `sc-im/docs` (html, latex, and man. To view the html go to `sc-im/docs/html/index.html`.

I've converted most of the existing comments into doxygen comments. There's still a few files I need to finish. Most of the functions are documented with template comments and need a knowledgeable human to fill in the information.

Hold off on merging for right now. I made a mistake in one of the files and I'm having compile issues.

**Comment by charlespax** [comment]
Okay, I fixed a merge Issue I made with the dolmax and dolmin functions. You should not be able to safely merge my doxygen into your freeze branch. The only changes should be in the comments.

**Comment by andmarti1424** [comment]
Just let me know when you finish your work regarding this

**Comment by charlespax** [comment]
Okay, pull request #194 is ready for merging. I'm done with the initial setup. I've given all functions template doxygen comments. Where functions were documented, I've converted those comments into doxygen format. 

I compiled scim and it seems to run correctly. I believe I have not modified any compiled code; only comments. `make docs` also appears to be working correctly.

To make the docs you need `doxygen` and `graphviz` installed. Then just run `make docs`. You'll find the html docs at `sc-im/docs/html/index.html`.

There's a lot of work to be done to get the documentation filled out and looking good, but this is a good start.

**Comment by andmarti1424** [comment]
It will take me some time to check all your work. Probably manual file should be updated as well adding the "make docs" details..

**Comment by andmarti1424** [comment]
I am getting this error when making the docs..
doxygen Doxyfile
Warning: ignoring unsupported tag `GROUP_NESTED_COMPOUNDS =' at line 351, file Doxyfile
Warning: ignoring unsupported tag `HIDE_COMPOUND_REFERENCE=' at line 522, file Doxyfile
Warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 746, file Doxyfile
Warning: ignoring unsupported tag `LATEX_EXTRA_STYLESHEET =' at line 1700, file Doxyfile
Warning: ignoring unsupported tag `LATEX_TIMESTAMP        =' at line 1767, file Doxyfile
Warning: ignoring unsupported tag `RTF_SOURCE_CODE        =' at line 1833, file Doxyfile
Warning: ignoring unsupported tag `PLANTUML_INCLUDE_PATH  =' at line 2367, file Doxyfile
error: tag OUTPUT_DIRECTORY: Output directory `../docs' does not exist and cannot be created
Exiting...
Makefile:172: recipe for target 'docs' failed


I dont know which docs directory is refering to..

**Comment by charlespax** [comment]
The docs directory would be sc-im/docs/. The Makefile is set to create it when executing `make docs`.

The unsupported tags errors sounds like you might be running an older version of doxygen. What version do you have?

I'll look into it when I get back to my computer. What is you platform?

**Comment by andmarti1424** [comment]
That was Debian in 3.16.0-4-kirkwood. doxygen 1.8.8.
I also use Arch in an Intel's Kaby Lake i5.. but I am not in that one now.
Shouldnt Makefile create the directory if it does not exists?

**Comment by charlespax** [comment]
I'm on Linux Mint 18.2, dozygen 1.8.11. Executing `head Doxyfile` form the `src` directory gives:
```
# Doxyfile 1.8.11

# This file describes the settings to be used by the documentation system
# doxygen (www.doxygen.org) for a project.
#
# All text after a double hash (##) is considered a comment and is placed in
# front of the TAG it is preceding.
#
# All text after a single hash (#) is considered a comment and will be ignored.
# The format is:
```
At the top you can see this config file is probably meant for 1.8.11. I guess it has tags that aren't supported by your version. That's probably okay; the failure looks like it's due to the missing directory.

The Makefile does not make the directory. My doxygen install has been making that directory for me.
```
docs:
	doxygen Doxyfile

man_install:
	@cp -r ../docs/man/man3/ /usr/local/share/man/
	mandb

# "scim" MUST match what is in Doxyfile `MAN_EXTENSION = .scim.3`
man_uninstall:
	@rm -rf /usr/local/share/man/man3/*scim.3
	@mandb

clean:
	rm -f $(OBJS)
	rm -f *res.h $(YTAB).h
	rm -f core gram.c y.output pxmalloc.c pvmtbl.c tags $(name)qref
	rm -f qhelp.c $(name)
	rm -rf ../docs/ 
```
You should add.
```
docs:
	mkdir ../docs
	doxygen Doxyfile
```

**Comment by andmarti1424** [comment]
This "make docs" fails in this debian computer, but works ok in another arch installation.
That ../docs directory indeed exists!

**Comment by andmarti1424** [comment]
![1](https://user-images.githubusercontent.com/9466161/33501741-74357e38-d6bc-11e7-9d3c-099aabb557f4.png)
I am still having trouble in my debian computer..

**Comment by andmarti1424** [comment]
@charlespax, any idea what could be the issue with the above?

**Comment by akorchemniy** [comment]
Properly configured, Doxygen can generate graphs for all functions even without comments.
