### ISSUE TITLE
Simple sheet not recalculating - min & max functions

### ISSUE THREAD

**Issue by jb55** [andmarti1424/sc-im#193]
Hey there,

Just found this project and it's awesome! As a test I did a simple cumulative taxes calculator but for some reason it's not recalculating. I noticed it was happening when I used the min or max function. They worked for ranges but not in `@min({expr}, {expr}, ...)` form. I had to manually `:int rebuild_graph`, sometimes multiple times. Anyways, here's the sheet I was testing on:

```
# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

mark a E3
let A0 = 38898
let B0 = @min(A0,C0)
let C0 = 90000
let D0 = 5.06
let E0 = B0*(D0/100)
let A1 = 38899
let B1 = @min(A1,C1)
let C1 = @max(C0-A0,0)
let D1 = 7.7
let E1 = B1*(D1/100)
let A2 = 11523
let B2 = @min(A2,C2)
let C2 = @max(C1-A1,0)
let D2 = 10.5
let E2 = B2*(D2/100)
let A3 = 19140
let B3 = @min(A3,C3)
let C3 = @max(C2-A2,0)
let D3 = 12.29
let E3 = B3*(D3/100)
let C4 = @max(C3-A3,0)
let D4 = 14.7
let E4 = B4*(D4/100)
let E6 = @sum(E0:E4)
leftstring F6 = "taxes"
let E7 = C0-E6
leftstring F7 = "total"
let E8 = E7/261/8
leftstring F8 = "eff rate"
let E9 = E7/12
leftstring F9 = "monthly"
let E10 = E9/2
leftstring F10 = "bimonthly"
goto C5
```

thanks!

* tried on: fd70c8659e150174f4a24cfda3abf2c5d0fba979 and 0.6

**Comment by hymie0** [comment]
I see the same problem -- either I don't understand how `@max` and `@min` are supposed to work, or they aren't working.

```
let A0 = 5
let B0 = 10
let C0 = @max(A0,B0)
let D0 = @min(A0,B0)
```
works in sc 7.16 (c0=10, d0=5); fails in scim (c0=0, d0=0)

**Comment by andmarti1424** [comment]
Yep. It seems graph is not beeing generated correctly with those functions.

**Comment by andmarti1424** [comment]
Could you please update to latest commit in freeze branch and try this again?

**Comment by jb55** [comment]
just tried on fd70c8659e150174f4a24cfda3abf2c5d0fba979, when I load my tax calc spreadsheet the columns using the min functions are all 0.

**Comment by hymie0** [comment]
No improvement here.

I don't know enough git to tell you which version of the code I'm using.  It's as up-to-date as I can get.

**Comment by jb55** [comment]
my bad, I meant I tested on adcb4123f478d63c7a1cdefe08a39efce9d02f65 and still no luck

**Comment by charlespax** [comment]
@hymie0  `git log -1` will show you the latest log entry. It will look something like this:
```
commit 833fe766788ae41afef4285c591b48901db1e98b
Author: Charles Edward Pax <charles.pax@gmail.com>
Date:   Fri Jul 28 12:45:45 2017 -0400

    Doxygen comments.
```

Copy the commit number (e.g.`833fe766788ae41afef4285c591b48901db1e98b`) and paste it into you github comment. Github will automatically shorten it to something like 833fe766788ae41afef4285c591b48901db1e98b.

**Comment by charlespax** [comment]
In commit adcb4123f478d63c7a1cdefe08a39efce9d02f65 `@max()` appears to work.

Here is what I get when open the file in commit adcb4123f478d63c7a1cdefe08a39efce9d02f65 
![new](https://user-images.githubusercontent.com/281642/28743468-b57299a0-7418-11e7-8af7-f32641145a54.PNG)

Here is what I get when I open the file in the older fd70c8659e150174f4a24cfda3abf2c5d0fba979 commit.
![old](https://user-images.githubusercontent.com/281642/28743478-ef85de22-7418-11e7-8672-a6e3e17e92a8.PNG)

In both cases `:int rebuild_graph` populates the missing data.

**Comment by hymie0** [comment]
I just updated to d8e73b14178f6fbe8b575df71140088dca0760b9

My tiny little test file works perfectly.

@jb55's test file still shows the same problem when you open it, but the `@` command forces a recalc and everything works.  So I think @jb55's problem now is "don't use column B to compare two numbers in column A and column C."

In fact, if I take that file, insert a new column D, and copy all of column B into column D, then it all works the first time.  So I definitely think that is @jb55's remaining issue.

**Comment by jb55** [comment]
closing this since the issue is mostly fixed wrt. min/max functions. thanks!

**Comment by andmarti1424** [comment]
I reopen it, since I still have to fix the graph building..

**Comment by andmarti1424** [comment]
Actually the graph is building OK. The problem is in evaluation of the graph..

**Comment by andmarti1424** [comment]
I believe this min/max issue is fixed long time ago. Anyone still have problems with this?

However, I will change the way the graph is doing the calculation in a future version of sc-im.
Since there is a chance that one of two linked cells get calculated before the linked cell have its value calculated. It should be neccesary to do a bottom up evalution of the graph. If anyone is interested in helping with this, please send a message.

**Comment by jb55** [comment]
Thanks for looking into this!

**Comment by andmarti1424** [comment]
Please if you still had issues with this, update to latest commit and try again.
Thanks!
