### ISSUE TITLE
@slen() returns wrong values with wide char strings

### ISSUE THREAD

**Issue by programandala-net** [andmarti1424/sc-im#196]
I've been trying sc-im (0.6.4 on Raspbian) for a while and I find it great, the perfect companion to Vim and [Vifm](https://github.com/vifm/vifm).

After some testing, it seems the maximum length of a string constant is 75 8-bit characters, but longer strings are accepted as result of a string expression, e.g. concatenation of other cells' contents, right?

Besides, `@slen()` does not return the size in multi-byte characters, say UTF-8, but the size in bytes. Is it intended?

Is there any way to increase the maximum length of string constants, and show them in full length by increasing the height of the row? I don't mean the config variable `overlap`, which is a different thing.

I have searched the help, but I have found nothing about these issues.

Thank you

**Comment by andmarti1424** [comment]
Hello!

Max string length 75? I believe you can input larger strings..
I just did a test and was able to enter a longer string (more than 100 chars). If I recall well, this limitation comes from terminal width.. If you have a wider terminal, you could probable enter larger values.

"@slen() does not return the size in multi-byte characters, say UTF-8, but the size in bytes. Is it intended?"  -> this is a bus. Should be fixed.

About increasing row height. This is not possible in SC-IM at the moment.

**Comment by andmarti1424** [comment]
Regarding the @slen issue, please update to latest commit in freeze branch and try again.

**Comment by programandala-net** [comment]
En/Je/On 2017-08-14 11:18, Andrés M. escribió / skribis / wrote :

> Regarding the @slen issue, please update to latest commit in freeze
> branch and try again.

Now it works fine. Thank you.

-- 
Marcos Cruz
http://programandala.net

**Comment by programandala-net** [comment]
En/Je/On 2017-08-14 17:32, Andrés M. escribió / skribis / wrote :

> Max string length 75? I believe you can input larger strings..

> If I recall well, this limitation comes from terminal width.. If you
> have a wider terminal, you could probable enter larger values.

I see. Would it be feasible to remove this limitation in a future
version?

-- 
Marcos Cruz
http://programandala.net
