### ISSUE TITLE
Edited string expressions don't include their initial quote

### ISSUE THREAD

**Issue by programandala-net** [andmarti1424/sc-im#197]
I have a doubt:

1. I put a string at A2: `<left`
2. I put a string at B2: `>right`
3. I calculate their concatenation at C2: `\"a2#" and "#b2`

So far so good. But when I press the uppercase E key at C2 to edit the string expression, and then the I key to enter the insert mode, the initial quote, required by string expressions, is missing, so I have to add it again. Is this a bug or am I missing something?

Thank you.

**Comment by andmarti1424** [comment]
Well. It should probably be a good improvement to include it.

**Comment by andmarti1424** [comment]
Actually, more than an improvement I would say this is a bug. Should be fixed.

**Comment by andmarti1424** [comment]
Please update to latest commit and try again. Thanks!!
