### ISSUE TITLE
pin top row (or just any row or column)

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#198]
Many csv files use the first row as a header containing column names. In such files it would be extremely useful if one could pin the top row so that it is always visible to the user. Some csv files also use the first column for description, though this is by far not as common as using the first row.

The command could be something like `:pin 0` and `:unpin 0`. This would also allow for commands like `:pin 4` or `:pin A`, in case pinning anything other than the top row would be supported at some point.

**Comment by andmarti1424** [comment]
Try the freeze command

**Comment by ber532k** [comment]
Didn't see that, thanks.
