### ISSUE TITLE
Enlarging terminal causes invisible lines

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#199]
If I launch scim inside a terminal emulator and afterwards increase the vertical size of that terminal emulator (e. g. by resizing or maximizing the window) the bottom lines stay invisible. If i decrease the vertical size of that terminal however after launching scim (e. g. by drawing the lower border of the window up a few lines) and afterwards increase the size, everything seems to be working perfectly.

**Comment by andmarti1424** [comment]
Please update to latest commit in freeze branch and try again!

**Comment by ber532k** [comment]
Works, thanks.
