### ISSUE TITLE
won't make - not finding ncurses headers

### ISSUE THREAD

**Issue by pbhart** [andmarti1424/sc-im#2]
I get the following error:

gcc -DSYSV3 -O2 -pipe -g   -c -o buffer.o buffer.c
In file included from buffer.c:3:0:
macros.h:47:21: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
                     ^
compilation terminated.
make: *** [buffer.o] Error 1

It cannot seem to find <ncurses.h> which is installed.

Thanks for updating sc.

Phil hart

**Comment by tukusejssirs** [comment]
Sorry to write in an old issue, but I didn’t wanted to create new issue with the same problem.
OS: Arch Linux x86_64

Note: Actual question is at the end of this post.

#### What I’ve done
I just cloned `scim` to my computer:
```bash
git clone git@github.com:andmarti1424/sc-im.git scim
```
Then, I read the `Readme.md`, how I should install `scim`. It said that I should edit `Makefile` which I couldn’t _see_ any file called `Readme.md` (which is _usually_ located in base directory), so I searched for it:
```bash
find . | grep -i makefile
```
… so I found it in `$scim/src`. After I read it, I decided to leave it as is. In `$scim/src` directory, I ran:
```bash
make
```
and I got the following output:
```bash
gcc -DLINUX    -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DMAXROWS=65536 -DHELP_PATH=\"/usr/share/scim\" -DSNAME=\"scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o exec.o exec.c
In file included from exec.c:8:0:
macros.h:48:29: fatal error: ncursesw/curses.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'exec.o' failed
make: *** [exec.o] Error 1
```
At first, I checked if I have `ncurses` installed:
```bash
$ which ncurses
which: no ncurses in (/usr/lib:/usr/lib32:/root/.config/sublime-text-3/Packages:/home/ts/qt5.4.1/5.4/gcc/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games)

$ whereis ncurses
ncurses: /usr/include/ncurses.h /usr/share/man/man3/ncurses.3x.gz
```
… what is kind of strange (I couldn’t find, why `which` couldn’t find ncurses, but never mind). Then I realised (after reading some issues here on github.com for `scim`), that the `make` output was talking about `ncursesw`. So I checked again if I got i installed:
```bash
$ which ncursesw
which: no ncursesw in (/usr:/root/.config/sublime-text-3/Packages:/home/ts/qt5.4.1/5.4/gcc/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games)

$ whereis ncursesw
ncursesw:
```
… so I looked online how to install `ncursesw` on Arch linux. I found nothing, so I search for its installatino instructions on any linux, so I found out that is _should_ be isntalled by installing `ncurses`. So I search `/` for `ncurcesw`:
```bash
$ find / | grep ncursesw
/var/abs/community/newsbeuter/newsbeuter-2.9-ncursesw6.patch
/usr/bin/ncursesw6-config
/usr/lib/libncursesw.so
/usr/lib/libncursesw.so.6
/usr/lib/pkgconfig/ncursesw.pc
/usr/lib/libncursesw.so.6.0
/usr/lib32/libncursesw.so
/usr/lib32/libncursesw.so.6
/usr/lib32/libncursesw.so.6.0
^C
```
… indeed, it _is_ installed. My `$PATH` is as follow:
```bash
/usr:/root/.config/sublime-text-3/Packages:/home/ts/qt5.4.1/5.4/gcc/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

#### Actual question
The question is, why it is not working? I think that the `$scim/Readme.md` should include more detailed installation instructions (like where is the `Makefile`, where and how should `make` be executed, etc). Thank you in advanced

**Comment by andmarti1424** [comment]
Hello. Makefile is in src directory.

I do not know where you have ncursesw headers in your system.
I have them in /usr/include/ncursesw, and that is why you see
"ncursesw/curses.h" in the headers files, such as macros.h

May be you should make some symbolic links?

**Comment by tukusejssirs** [comment]
Thank you for your reply.

I found [this](https://bugs.archlinux.org/task/4418) site and then I realised that `ncursesw.h` is in Arch linux named as `cursesw.h`. So in `/usr/include` I’ve got `curses.h`, `cursesw.h` and a symlink to `curses.h` called `ncurses.h`. Creating such a symlink to curses.h didn’t help.

Then I edited `$scim/src/macro.h` file, name commented out 48th line and added new 49th line:

```bash
#include <cursesw.h>
```

… which solved the initial `ncursesw.h` error, but 13 new emerged with the final one being fatal. Here’s the output:

```bash
# make 
gcc -DLINUX    -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DMAXROWS=65536 -DHELP_PATH=\"/usr/share/scim\" -DSNAME=\"scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o exec.o exec.c
In file included from /usr/include/cursesw.h:36:0,
                 from macros.h:49,
                 from exec.c:8:
/usr/include/etip.h:118:8: error: expected identifier or ‘(’ before string constant
 extern "C" {
        ^
In file included from /usr/include/cursesw.h:36:0,
                 from macros.h:49,
                 from exec.c:8:
/usr/include/etip.h:142:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesPanel;
 ^
/usr/include/etip.h:143:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesMenu;
 ^
/usr/include/etip.h:144:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesForm;
 ^
/usr/include/etip.h:146:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesException
 ^
/usr/include/etip.h:147:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
/usr/include/etip.h:180:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesPanelException : public NCursesException
 ^
/usr/include/etip.h:180:44: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 class NCURSES_IMPEXP NCursesPanelException : public NCursesException
                                            ^
/usr/include/etip.h:231:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesMenuException : public NCursesException
 ^
/usr/include/etip.h:231:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 class NCURSES_IMPEXP NCursesMenuException : public NCursesException
                                           ^
/usr/include/etip.h:282:1: error: unknown type name ‘class’
 class NCURSES_IMPEXP NCursesFormException : public NCursesException
 ^
/usr/include/etip.h:282:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 class NCURSES_IMPEXP NCursesFormException : public NCursesException
                                           ^
/usr/include/etip.h:335:25: fatal error: iostream: No such file or directory
compilation terminated.
<builtin>: recipe for target 'exec.o' failed
make: *** [exec.o] Error 1
```

**Comment by andmarti1424** [comment]
This is an error of ncurses..
Perhaps you are using the wrong header file..

In my system I have ncurses.h in /usr/include/ncursesw directory.
And that file is a symlink to /usr/include/ncursesw/curses.h, which I attach here for you to compare..
(i renamed it to curses.txt so it can be uploaded here).
[curses.txt](https://github.com/andmarti1424/sc-im/files/243045/curses.txt)

**Comment by tukusejssirs** [comment]
Indeed, mine is different. I tried to compile `scim` with your `curses.txt` (renamed to "curses_t.h") and the ncursesw.h error disappeared, but it needs `ncurses_dll.h`:
```bash
ncursesw/curses_t.h:60:34: fatal error: ncursesw/ncurses_dll.h: No such file or directory
```
Now, I’m trying to create the folder structure `scim` needs the `ncurses` files to be in (using your `curses.h` file located in /usr/include/ncurses/curses.h):
```bash
mkdir /usr/include/ncursesw
ln -s /usr/include/ncurses_dll.h /usr/include/ncursesw/ncurses_dll.h
ln -s /usr/include/unctrl.h /usr/include/ncursesw/unctrl.h
```
After doing this (and undoing every modification in `macro.h`), I’ve got this error:
```bash
gcc -DLINUX    -O2 -Wall -pipe -g -I/usr/include/libxml2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc/scim\" -DMAXROWS=65536 -DHELP_PATH=\"/usr/share/scim\" -DSNAME=\"scim\"     -DHISTORY_FILE=\".sciminfo\"   -c -o exec.o exec.c
In file included from macros.h:48:0,
                 from exec.c:8:
/usr/include/unctrl.h:60:38: error: conflicting types for ‘unctrl’
 NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                      ^
In file included from /usr/include/ncursesw/curses.h:2006:0,
                 from macros.h:48,
                 from exec.c:8:
/usr/include/unctrl.h:57:38: note: previous declaration of ‘unctrl’ was here
 NCURSES_EXPORT(NCURSES_CONST char *) unctrl (chtype);
                                      ^
<builtin>: recipe for target 'exec.o' failed
make: *** [exec.o] Error 1
```

**Comment by tukusejssirs** [comment]
Could you send me, please, your `unctrl.h` file?

**Comment by andmarti1424** [comment]
I send you unctrl and ncurses_dll files. But first I would check the installation of ncursesw.
Do you have it properly installed?
I dont think you should use my files..


[ncurses_dll.txt](https://github.com/andmarti1424/sc-im/files/243130/ncurses_dll.txt)
[unctrl.txt](https://github.com/andmarti1424/sc-im/files/243131/unctrl.txt)

**Comment by tukusejssirs** [comment]
Agreed that I shouldn’t use your files, but for some reason I cannot make it working.

I am sure they’re installed properly. On Arch, its done by installing `ncurses` package ([here](https://www.archlinux.org/packages/core/x86_64/ncurses/files)’s a link to the package file list, which indeed contains `cursesw.h` file).

As of now, I know a working solution:
```bash
if [[ `whereis ncursesw` == "ncursesw: /usr/include/ncursesw" ]]; then
    mkdir /usr/include/ncursesw
    cd /usr/include/ncursesw
    ln -s ../{cursesapp.h,cursesf.h,curses.h,cursesm.h,cursesp.h,cursesw.h,cursslk.h,eti.h,etip.h,form.h,menu.h,nc_tparm.h,ncurses_dll.h,ncurses.h,panel.h,termcap.h,term_entry.h,term.h,tic.h,unctrl.h} ./
```

PS According to [this](https://bugs.archlinux.org/task/13994), Arch Linux won’t auto-create the folder and symlink, ‘[g]iven the vast majority of programs do deal with this properly.’

**Comment by andmarti1424** [comment]
Could you managed to build it creating those symlinks?

**Comment by tukusejssirs** [comment]
Yes, successfully, without any errors or warnings. :)

Thank you for your assistance.

**Comment by andmarti1424** [comment]
That script was your solution then?I will add it to the build instructions since there is no configure script yet..

**Comment by tukusejssirs** [comment]
Yes, indeed. Okay, but besides [wiki](https://github.com/andmarti1424/sc-im/wiki), where I’ve found instructions for some distros, I’d recommend to put then into $scim/Readme.md as well (for all distros). But the `configure` (probably using `autogen.sh`) would be better.

**Comment by tukusejssirs** [comment]
Probably you could rename this issue according to this foundings (it’s `ncursesw` error emerging in `make` output) and also close it. :)

**Comment by kyrias** [comment]
@andmarti1424 Sorry, but you're wrong.  To include ncursesw you should include `curses.h` and then use either `pkg-config` or `ncursesw6-config` to get the correct compilation flags for the system.  This is the official way to do it, and hardcoding `ncursesw/curses.h` is wrong.  (See eg [this](http://invisible-island.net/ncurses/NCURSES-Programming-HOWTO.html#COMPILECURSES tutorial.)
