### ISSUE TITLE
Segmentation fault with circular references

### ISSUE THREAD

**Issue by nshram** [andmarti1424/sc-im#201]
Tried to build on Debian-Jessie-Armel VM, with an idea to copy the executable over to Amazon Kindle Paperwhite (PW3, jailbroken).
Finished the build. It seemed to working OK.
Copied it over to the Kindle. tried running it. Got a Segmentation fault.
Back on the Jessie VM, tried entering numbers into A1 and A2 and putting a sum into A3. Got a Seg fault here too.
Is there a basic issue in this running on ARM platforms?

**Comment by andmarti1424** [comment]
I use sci-im in ARM all the time without problem.
Please give more details of that segfaults. Any chance you can run it under
valgrind?

**Comment by waveform80** [comment]
Did your sum happen to reference itself? I managed to do this accidentally and got a segfault (while playing with sc-im on a Pi3, another ARM platform) but I suspect that's a separate issue and nothing specific to ARM.

**Comment by andmarti1424** [comment]
"Did your sum happen to reference itself?" -> what do you mean?

**Comment by waveform80** [comment]
i.e. =A0 in cell A0

**Comment by andmarti1424** [comment]
You're right. It shows: "Circular reference in eval (cell A0) Segmentation fault"

**Comment by andmarti1424** [comment]
Will check it out.

**Comment by waveform80** [comment]
Yup, nice that it recognizes the circular reference though :)

**Comment by nshram** [comment]
Hello Andrés and Waveform80!
Yes, What I did was: enter 1 in A0, 2 in A1. Then tried to sum them in A2 by entering =@sum(A1:A2)!
All this happened in the Debian-Jessie-Armel virtual machine running under qemu on Ubuntu.
Later I tried with the Ubuntu build. The same error occurred.
But on the Amazon Kindle, the executable(copied from the armel VM) immediately quits with a seg fault, without even showing the opening screen. So this may be a different issue.

**Comment by andmarti1424** [comment]
yep. seems another issue.
"But on the Amazon Kindle, the executable(copied from the armel VM)" -> same architecture?

**Comment by nshram** [comment]
Yes, same architecture.
The kindles have armel, so any commandline executables that work on debian armel (usually wheezy or jessie) also work on the kindle. You also need to copy any necessary library files.

**Comment by andmarti1424** [comment]
note to myself: (line 2514 of interp.c) if (!loading && cellerror != CELLERROR) {...

**Comment by andmarti1424** [comment]
Please update to latest commit in freeze branch and try this again! Thanks.

**Comment by nshram** [comment]
Still get Seg fault on Ubuntu.
Compiled.
Entered =1 in A0, =2 in A1, =@sum(A1:A2) in A2

**Comment by andmarti1424** [comment]
@nshram @waveform80 Please update to latest commit and try this again. Hopefully it should be fixed.

**Comment by nshram** [comment]
Thanks! Will compile and try it.

**Comment by nshram** [comment]
Tried cross compiling it to armel(Kindle) architecture on Ubuntu 20.04 using arm-linux-gnueabi-gcc-10.
Got the following errors:
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: cannot find -lncursesw
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
make: *** [Makefile:194: sc-im] Error 1

Please let me know how to fix.

**Comment by andmarti1424** [comment]
Please install ncurses and ltinfo

**Comment by nshram** [comment]
ncurses and ltinfo is installed for x86_64. How to install for gnueabi/armel architecture? Not able to find it.

**Comment by andmarti1424** [comment]
@nshram i don't have a clue there.. Manual building?

**Comment by nshram** [comment]
Ok. I'll try booting up the Debian Jessie VM and try there.

**Comment by waveform80** [comment]
> @nshram @waveform80 Please update to latest commit and try this again. Hopefully it should be fixed.

Compiled the "freeze" branch and the circular reference issue does indeed appear to be fixed! I tried:

* `A0=A0`
* `A0=1, A1=2, A2=A0+A1+A2`
* `A0=1, A1=2, A2=@SUM(A0:A2)`

All correctly reported a circular reference error without crashing :)

> ncurses and ltinfo is installed for x86_64. How to install for gnueabi/armel architecture? Not able to find it.

You might be able to do something like `apt install libncurses6:armel` ?

**Comment by andmarti1424** [comment]
@waveform80 At one moment I thought you were the eevblog man.
Thanks both for your time.

**Comment by waveform80** [comment]
> @waveform80 At one moment I thought you were the eevblog man.

Heh - the hazards of a common name, but wrong hemisphere in this case :)

**Comment by andmarti1424** [comment]
that one is too cocky as well. >:(
