### ISSUE TITLE
Cannot open help file

### ISSUE THREAD

**Issue by sedm0784** [andmarti1424/sc-im#202]
I just installed sc-im via the new Homebrew formula. Very smooth!

However, typing `:help` returns the error:

> Cannot open help file

I'm not sure if this is actually a problem with the Homebrew formula&mdash;my recollection is that `:help` worked in a older version I compiled myself&mdash;so let me know if I should report over there instead.

**Comment by andmarti1424** [comment]
Seems to be a problem with the formula itself. Please open an issue in that repository.
