### ISSUE TITLE
relative and absolute references in the same formula?

### ISSUE THREAD

**Issue by schmeisers** [andmarti1424/sc-im#205]
Is there a way to use absolute and relative references in the same formula?

For example, if I want to sum across cells in a row and divide by the absolute reference to A0: `=@sum(A1:D1)/$A$0` where `$A$0` is an absolute reference.  I see that there are different copy operations to make references relative or absolute, but I can't figure out how to mix them.

**Comment by andmarti1424** [comment]
Yes, it seems you can define something like this @sum(F0:F2)/$B$0
Then copy the F0:F2 range and paste it with 'Pc' command. It will still show the $B$0 reference, but with change the others..

**Comment by schmeisers** [comment]
Thank you, that worked.  Incidentally, when I tried to copy the formula down with `:fcopy`, the new formula cells were computed correctly.  But then when I changed `$B$0`, only the original was updated, not the cells created via `:fcopy`.  Is that the expected behavior?  The formula is correct in the new cells but they don't update.

**Comment by andmarti1424** [comment]
I am working on fixing that update issue. try
:int rebuild_graph
to see if that makes the update

**Comment by schmeisers** [comment]
Yes, `:int rebuild_graph` forces the update.  As an aside, is there a better place to ask usage questions?  I have some other questions but don't want to abuse the issue tracker.

**Comment by andmarti1424** [comment]
Feel free to use the issue tracker.
