### ISSUE TITLE
Ubuntu compile instructions for XLSX read/write support are outdated.

### ISSUE THREAD

**Issue by stroobandt** [andmarti1424/sc-im#208]
The Ubuntu compile instructions for XLSX read/write support seem to be outdated:
https://github.com/andmarti1424/sc-im/wiki/Ubuntu-16.04.1-with-libxlsreader

I was able to compile sc-im on Ubuntu without XLSX import/export support.
However, adding support for XLSX with above instructions fails to compile.

**Comment by andmarti1424** [comment]
Hello. Thanks for reporting that. As I do not have Ubuntu installed, please feel free to update the Wiki if you manage to build it with XLSX support.

**Comment by stroobandt** [comment]
OK, I will write something in the Wiki to attract a bit more (X)Ubuntu users around here.
