### ISSUE TITLE
Entering @pi in a cell returns 0.00; 1*@pi or @pi^1 give the correct result though.

### ISSUE THREAD

**Issue by stroobandt** [andmarti1424/sc-im#209]
Entering `@pi` in a cell returns `0.00`
However, entering `1*@pi` or `@pi^1` both return the correct result though.

**Comment by andmarti1424** [comment]
Yes. Thanks for reporting this. This is a calculation problem that I plan to fix for next version.

**Comment by andmarti1424** [comment]
Its related with #193

**Comment by andmarti1424** [comment]
Could you please update to latest commit in freeze branch and try again?

**Comment by andmarti1424** [comment]
Hello @stroobandt . Could you test this? Thanks.

**Comment by stroobandt** [comment]
Acabo de probarlo. ¡Funciona de puta madre! ;)
¡Gracias!
Serge
