### ISSUE TITLE
implement undofiles inside an undodir

### ISSUE THREAD

**Issue by 257** [andmarti1424/sc-im#21]
explanation is the same as https://github.com/andmarti1424/scim/issues/17 plus having it saved over restarting of scim, using an undo file.

**Comment by andmarti1424** [comment]
I think this is not as important as other improvements, just as changing the Evaluation of cells.
I although will added this to a FEATURE_REQUEST file and see what others think about it.

**Comment by foo-bar-baz** [comment]
great, thanks.

**Comment by andmarti1424** [comment]
Anyone interested in this?

**Comment by andmarti1424** [comment]
I close this since I am not planning on implementing this in near future.. Theres so much other stuff that has priority. But please feel free to open a discussion so others can discuss and give their opinion on this topic. Thanks.
