### ISSUE TITLE
Ubuntu 0 enters input mode instead of first column

### ISSUE THREAD

**Issue by zefreak** [andmarti1424/sc-im#212]
Pressing 0 enters input mode rather than going to first column for row
Compiled for Ubuntu 16.04.3 LTS x86_64

**Comment by andmarti1424** [comment]
Do you have "numeric" configuration variable set to true?

**Comment by andmarti1424** [comment]
Do you have "numeric" configuration variable set to true?

**Comment by andmarti1424** [comment]
I uploaded a fix when numeric was set to false and 0 command did not work properly.
