### ISSUE TITLE
Port xlsx read from libzip to minizip?

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#214]
I'm finding libzip a bit difficult to integrate in the build stage with sc-im if you wish to have all dependencies in the same tree and build everything together, specially if I want to have a tree that can be easily crosscompiled to Windows as well as build natively on Linux and MacOS.

On the other hand, libxlsxwriter is easier to integrate in the build (I already did it), and it comes with minizip included, which is built together with libxlsxwriter.

Do you really need functionality from libzip, or would minizip be enough? If minizip is enough, you can drop one dependency, as libxlsxwriter already includes it. 

_NOTE: libxlsxwriter only builds a couple of source files from minizip (the ones related to creating zip files rather than the ones for reading them), but it comes with all the minizip files, so it's only a matter of adding the additionally needed files to the Makefile._

**Comment by andmarti1424** [comment]
May be minizip is enough. Do not know about it.

What problem do you have in installing dependencies in the same tree? Can't you just modify Makefile according to those changes?

**Comment by cesss** [comment]
The style in which I've built my tree of third-party software these years, doesn't mix well with "configure" and "cmake". Several builds for different platforms are managed in platform directories. Besides, I build Win32 binaries crosscompiling with mingw64. Whenever a package requires either "configure" or "cmake", most of the times I only have two options: either build it manually off-tree (manually invoking configure/cmake), or write a custom Makefile.

Someday I'll have to look at systems that automate these tasks while being friendly with configure/cmake, but, in the meantime, it's hard to manage my tree of 3rd-party code nicely.

I'll look if I can find a direct minizip translation of your calls to libzip. I've never used minizip nor libzip, so if I can find any other already written code, I'll look at it.

**Comment by cesss** [comment]
I'm working with libzip for the moment, because my highest priority in this moment was getting sc-im running rather than having a very comfortable build tree. Anyway, I think it's overkill for just opening and reading the zipped content of xlsx, and switching to minizip is on my TODO list in order to have an easier to build source tree. Not sure on when I'll have the time for doing it, though.
