### ISSUE TITLE
Cells whose value is just @pi evaluate to zero

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#216]
If I type in a cell just `@pi`, it evaluates to zero.
If I type `0+@pi`, or `@pi+0`, then it correctly evaluates to 3.14
So, it seems that the eval() function in interp.c does nothing when `@pi` is alone. Maybe eval() is not called at all.

However, other functions behave correctly if they're alone in a cell. My guess is that the reason could be the lack of parentheses in `@pi`.  It's the only function in sc-im that doesn't have parentheses. I don't know if this function was added by you, or by a previous contributor to sc, but whoever added it, it looks like they forgot to make sc-im ready for correct evaluation of functions that don't have parentheses.

Would it be possible to implement `@pi` with void parentheses? I mean `@pi()`
If that was possible, maybe sc-im would evaluate it correctly when it's alone in a cell. Also, import/export to Excel would be easier, as `@pi` in Excel is written PI()

**Comment by andmarti1424** [comment]
What version of scim are you using?

**Comment by cesss** [comment]
freeze branch from 30/November/2017

**Comment by cesss** [comment]
Oh!! Issue #209 
Fixed in commits just before my download.

Man, that is bad luck :-)

**Comment by andmarti1424** [comment]
Please update it to latest commit and try it again..

**Comment by cesss** [comment]
Yep, it's fixed by the commits that I had missed.
