### ISSUE TITLE
Can @if() return a string? How?

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#217]
In Excel, it is correct to do this:

IF(A10=B4, "You got it", "Keep trying")

Is it possible to do something like this with sc-im? How? (I tried with no success)

It's in fact a very convenient feature, because it lets you display human-readable messages depending on the result of calculations in the spreadsheet.

**Comment by andmarti1424** [comment]
Updating to latest commit, yes, you can, by typing something like: @if(@eqs(A1,"a"),"es a", "no es a")
You have to enter string formula with \"  not with =

**Comment by andmarti1424** [comment]
" and then backslash for entering string formula

**Comment by cesss** [comment]
Thanks, although maybe my comment was confusing, because I meant to perform a numerical test condition, and output a string (I wrote A10=B4 meaning a numerical test). I think the main issue here is that `sc` (from the initial versions) wasn't designed with data type abstraction in mind: operators are different for numbers and strings (the equal operator could have been overloaded instead of needing the @eqs function, for example), and functions get duplicated versions (the version for strings has an `s` letter added). The same happens for cells: A cell must be of number type or of string type.

Excel does all of this in a more abstract way (although still far from perfect, IMHO, because you still find situations when you face this string vs number conflict... if Excel was really abstract, you would never find such conflicts, because you would be always working with abstract cells).

Should have been possible, before your commit, to enter an @if as a string formula, having the test as a numerical test?

**Comment by andmarti1424** [comment]
Actually my latest commit was wrong. I reverted it. you should use something like this to achieve what you wanted:
\"
@if(A1>5,"es mayor", "es menor")

**Comment by cesss** [comment]
It's true, it works! The only requirement is to define it as a "label" cell rather than a "let" cell.

**Comment by andmarti1424** [comment]
Yes, indeed, and thats the way it should be, since the formula returns a string.
