### ISSUE TITLE
NULL pointers issue when reading formulas from some XLSX files

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#218]
I'm using a lot the feature of importing/exporting formulas in XLSX format (in fact I modified the default setting of xlsx_readformulas to 1 because that's the way I'm always using sc-im), and I got a segmentation fault today when importing an XLSX.

Finding the cell that was causing the segmentation fault drove me to one that was a formula, but it still had a NULL pointer on its child. I don't know how the XML parser works, but it looks like the order of the cells in the XLSX does matter, like if a formula could be referencing a cell which doesn't exist.

The workaround is to include the NULL pointer check at line 299 of xlsx.c, like this:
`if (atoi(get_conf_value("xlsx_readformulas"))&&(child_node->xmlChildrenNode->xmlChildrenNode!=NULL)) {`

It's a **_partial workaround_**, because if `child_node->xmlChildrenNode->xmlChildrenNode` is NULL, the formula isn't imported, you just get the result.

Do you have an idea on what could cause `child_node->xmlChildrenNode->xmlChildrenNode` to be NULL in this line?

**Comment by andmarti1424** [comment]
Hello. What formula are you trying to import?

**Comment by cesss** [comment]
[bug-nullpointers.xlsx](https://github.com/andmarti1424/sc-im/files/1545240/bug-nullpointers.xlsx)
This XLSX file is an example that shows this bug. The cells at C3, C4 and C5 (or C2, C3, C4 with Excel row numbering) have a NULL pointer.

Can you reproduce the bug with this file?

**Comment by andmarti1424** [comment]
I can reproduce the SEGFAULT if setting xlsx_readformulas.

**Comment by cesss** [comment]
The formulas in this file are trivial (just making a cell equal to another cell). Maybe it has something to do with the order in which cells are saved?

**Comment by andmarti1424** [comment]
Yes, may be its just the order. We'll see.

**Comment by cesss** [comment]
If you discover any news about this, please tell... I'm not able to figure out what's happening in this issue. It looks like the order in which cells are saved from Excel makes a difference when importing from sc-im. Very strange.

**Comment by andmarti1424** [comment]
not yet, @cesss.

**Comment by cesss** [comment]
I'm trying to figure out what's happening, and it doesn't seem related to the order in which cells are stored in the XLSX file. To make it worse, I couldn't see any difference between cells whose formula is read correctly, and cells that fail.

I took a XLSX that fails, and edited it indenting it for having a clearer view... no way, even in two rows that are identical, the `child_node->xmlChildrenNode->xmlChildrenNode` pointer is `NULL` in one cell and `non-NULL` in the other!!

Maybe the XML input has not been passed correctly to libxml2?

A total mystery to me.

**Comment by cesss** [comment]
FWIW, I tried all options (one by one, without combining them, just one at a time) in the xmlReadMemory() call in the following line, instead of XML_PARSE_NOBLANKS, but it didn't make any change:

`doc = xmlReadMemory(sheet, sb.size, "noname.xml", NULL, XML_PARSE_NOBLANKS);`

**Comment by cesss** [comment]
Anyway, my current suspect is the XML parsing. The problem looks to be in the parser and not in SC-IM, unless you are inadvertently overwriting the `child_node->xmlChildrenNode->xmlChildrenNode` pointer somewhere.

**Comment by andmarti1424** [comment]
I believe that as well, @cesss.

**Comment by cesss** [comment]
If I have time today, I'll try to use a simpler parser. I'm no expert in XML, but at first glance the XML syntax within XLSX looks really simple to me. I found a really simple XML parser [here](https://github.com/leethomason/tinyxml2). It's C++ and I didn't find C bindings, but it's so simple (just a source file and a header, with no other dependencies) that writing minimal C bindings for only the features needed by SC-IM should be easy. If I have the time today, I'll try.

**Comment by cesss** [comment]
Got it. And not looking nice :-(

https://stackoverflow.com/questions/18362112/what-is-the-meaning-of-t-shared-in-a-formula-element

https://blogs.msdn.microsoft.com/brian_jones/2006/05/29/spreadsheet-performance-shared-formulas/

**Comment by 1a7r0ch3** [comment]
Soo, no workaround? "Shared formulas" are so common on spreadsheets!

**Comment by 1a7r0ch3** [comment]
(one year later) I suggest a workaround, quick enough to make it acceptable: use the ssconvert command-line utility shipped with Gnumeric to convert from xlsx to... xlsx! seems to get rid of the "shared formulas", at least in the few cases I needed (and for some reasons the resulting file was actually smaller than the original)
```
ssconvert file_with_shared_formulas.xlsx file_without_shared_formulas.xlsx
sc-im --xlsx_readformulas file_without_shared_formulas.xlsx # no segfault, formulas!
```

**Comment by andmarti1424** [comment]
I'll try this following week to get his handled

**Comment by andmarti1424** [comment]
@1a7r0ch3 I have made a commit to prevent the segfault. If you know how shared formulas are handled please comment so I can add it. I see there's a calcchain file but now sure how it works. thanks.

**Comment by 1a7r0ch3** [comment]
Unfortunately I have no such knowledge; in particular, I have no idea how come `ssconvert` removes shared formulas. Maybe the developers there might help?

**Comment by andmarti1424** [comment]
Actually, removing them is what I have done. Pretty straightforward. I am not sure how to read them though

**Comment by 1a7r0ch3** [comment]
Yeah, it is already better with the final result rather than a segfault!

For actually reading the formula, maybe the excel plugin of gnumeric (on which the ssconvert utility mentioned above relies) might help, https://github.com/paulfitz/gnumeric/blob/master/plugins/excel/ms-formula-read.c .

**Comment by andmarti1424** [comment]
Thanks @1a7r0ch3 but I am afraid it does not help me much.. will continue searching.

**Comment by andmarti1424** [comment]
I close this. I am afraid im a little lost to implement the shared formulas. At least this does not segfaults anymore.
If anyone find its details on how that works, please share them so I can add this. Thanks
