### ISSUE TITLE
segmentation fault on changing color

### ISSUE THREAD

**Issue by OrionRandD** [andmarti1424/sc-im#219]
:color "bg=GREEN fg=WHITE" 
or any other colours gives me "segmentation fault and exits the program :(

**Comment by andmarti1424** [comment]
You mean with :cellcolor?

**Comment by andmarti1424** [comment]
For changing color of a cell you should use cellcolor. The :color command is for changing color definition of headings and other stuff and has a different syntax. It should not crash of course, so I will check it out.

**Comment by OrionRandD** [comment]
Ok. so. Give me an example of changing The :color command is for changing color definition of headings and other stuff...

**Comment by OrionRandD** [comment]
I saw in the help that it can be written in the ".scimrc"

**Comment by andmarti1424** [comment]
Please check help. There is an example there

**Comment by OrionRandD** [comment]
Ok. But, I want to change the color of the left side bar with is red here - by default...

**Comment by andmarti1424** [comment]
Yes, just put the same command in your $HOME/. scimrc but without the ':' at the beginning..

**Comment by OrionRandD** [comment]
Ok. Thx a lot...

**Comment by OrionRandD** [comment]
Great!

**Comment by andmarti1424** [comment]
Please update to latest commit and try again. It should not crash right now with SEGFAULT when :color parameters are incomplete. Thanks.
