### ISSUE TITLE
Export to XLS and XLSX

### ISSUE THREAD

**Issue by 257** [andmarti1424/sc-im#22]
...with function/eqn mapping, as much as possible of cours.

**Comment by andmarti1424** [comment]
Please give more details of this.

**Comment by foo-bar-baz** [comment]
well, say i have a function @nval(@coltoa(@mycol-1),@myrow), it would be
nice to have interpretation, or an equivalent function if you will, of it
in xl so cells are evaluated and then exported but everything is
recalculated in xl.

**Comment by andmarti1424** [comment]
By XL you mean MS Excel?

**Comment by foo-bar-baz** [comment]
On Feb 10  09:44 -0800, Andr�s M. wrote:
> By XL you mean MS Excel?

yes, xls and xlsx file formats.

**Comment by andmarti1424** [comment]
Do not think will implement XLS export, but only XLSX export.
It is not a priority since scim files can be exported to CSV and then open in Excel with that format.
It has more priority for example the interpretation of Excel functions during import of XLS and XLSX files, than just its values.

**Comment by foo-bar-baz** [comment]
On Feb 10  10:57 -0800, Andr�s M. wrote:
> Do not think will implement XLS export, but only XLSX export.

that makes sense if xlsx is the new version. i dunno because i never use
it.

> It is not a priority since scim files can be exported to CSV and then
> open in Excel with that format. It has more priority for example the
> interpretation of Excel functions during import of XLS and XLSX files,
> than just its values.

problem with exporting to csv is the functions. if at least we could export
to csv with functions interpreted to xlsx functions, that would be grant. i
suppose could be reused to import from xls and xlsx as well.

**Comment by JohnLunzer** [comment]
Any progress on XLSX export?

**Comment by andmarti1424** [comment]
None at the moment. My home computer is broken since a couple of weeks ago.

**Comment by andmarti1424** [comment]
Anyone else interested in this feature?? Please leave a comment and vote for it.

**Comment by JohnLunzer** [comment]
Still have interest. Would make it easier to share work with Windows users.

**Comment by roman65536** [comment]
Take a look on this lib https://github.com/jmcnamara/libxlsxwriter
should make export very easy.

**Comment by andmarti1424** [comment]
Yes, this is what we need.
Not something like the actual sc-im import which is all manually..

**Comment by andmarti1424** [comment]
Basic xlsx export was added in latest commit. Please give it a try. REQUIREMENTS: libxlsxwriter[https://github.com/jmcnamara/libxlsxwriter/](url)

**Comment by andmarti1424** [comment]
Added format export as well. (alignment, bold, underline, foreground and background color..)
Date format convertion as well.

**Comment by andmarti1424** [comment]
Could you give it a try?

**Comment by svenn71** [comment]
xlsx_readformulas=1, read very simple xlsx spreadsheet with some calculation, and then export, I see the "@" in sum(A1:A5) being exported, which give error in libreoffice calc. remove the @ and it is ok for the formula.

**Comment by andmarti1424** [comment]
Hello. Actually, it should be removed by now. What is your complete formula in SC-IM? just "@sum(A1:A5)"?

**Comment by andmarti1424** [comment]
For instance, if you export the example file called "export.sc" in folder file/xlsx.. you still get the "@" in the last cell of column A??

**Comment by ber532k** [comment]
I reproduced the error with a minimal example that you can find [here](https://gist.github.com/ber532k/8516ba8ee17baf5e4946751f6df0fa96), using the current git version (built a few minutes ago).

I run ``:e! xlsx test.xlsx`` to export the file and when I open it in LibreOffice Calc, cell B1 contains ``=@SUM(A1:A10)``.

**Comment by andmarti1424** [comment]
yep. seems there was a problem with the case when replacing strings in the formulas. please try again with latest commit.

**Comment by svenn71** [comment]
Testing on 4f7142a
libreoffice calc read the file, but has to be forced to recalculate with F9
microsoft excel read and recalculate the file.
[export.xlsx](https://github.com/andmarti1424/sc-im/files/880226/export.xlsx)
[input.xlsx](https://github.com/andmarti1424/sc-im/files/880227/input.xlsx)

**Comment by ber532k** [comment]
Looks good here, thanks.

**Comment by andmarti1424** [comment]
@svenn71, that seems to be a problem with libxlsxwriter or with libreoffice itself..
not really can do much of it.
