### ISSUE TITLE
Segmentation fault (with proposed fix) when using --nocurses

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#220]
I've never used curses, but it seems it's not allowed to initialise colours before initialising curses. In some commit from last months, there was added a color initialisation that is called even if curses wasn't initialised because of the --nocurses flag, and this causes a segmentation fault.

I fixed it in my local copy enclosing the color initialisation within the if() that checks for the --nocurses flag, like this:

Starting at line 227 in main.c:
```
    // initiate NCURSES if that is what is wanted
    if (! atoi((char *) get_conf_value("nocurses"))) {
        ui_start_screen();

#ifdef USECOLORS
    if (get_d_colors_param() == NULL) {
        start_default_ucolors();
        /*
         * in case we decide to change colors
         * this creates a dictionary and stores in it
         * the relationship between macros and the keys values
         * that are defined in .sc files
         */
        set_colors_param_dict();
    }
#endif
  }
```

**Comment by andmarti1424** [comment]
You are right! thanks for noticing it and reporting it. It should be fixed by now.
