### ISSUE TITLE
.scimrc options

### ISSUE THREAD

**Issue by OrionRandD** [andmarti1424/sc-im#221]
I have tried to set up the "format" in .scimrc for the whole sc like this:

set format "R$ ###.00" 
 
But, it is not working :)

It works only when I issue ":format "R$ ###.00"  in the sc itself

Is it possible to set up a general format in the ".scimrc"?
Thx

**Comment by andmarti1424** [comment]
You can set format in your scimrc file like this: FMT A2:A10 "R$ ###.00"

**Comment by OrionRandD** [comment]
Does this mean that the format will be applied to the whole document or just to a cell range?

**Comment by andmarti1424** [comment]
Only the selected range

**Comment by OrionRandD** [comment]
Thx.

**Comment by OrionRandD** [comment]
Does scim have autocompletion feature? Cannot find here...

**Comment by OrionRandD** [comment]
Like in Vim...

**Comment by andmarti1424** [comment]
You can type :cell and then press tab key for instance, and it will auto complete to the command. Just like in vim
