### ISSUE TITLE
About the commented-out EvalAll() at line 727 in file.c

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#222]
While using sc-im in non-interactive mode, I find it very convenient to have all the spreadsheet calculated without calling `recalc` from a script. Of course, if I change some cell from a script, an explicit `recalc` invocation would be necessary, but, when I load the file, I prefer to have the spreadsheet calculated (don't forget that I'm talking about non-interactive mode here... I assume EvalAll() is invoked somewhere at the curses IU initialisation, as you can see the spreadsheet calculated when you open it).

Looking at line 727 in file.c, I see that in a recent commit you added a call to EvalAll() but commented it out. That's the EvalAll that I want to execute :-) Does it cause any harm to uncomment it? I uncommented it, and then I get the behavior I wish...

**Comment by andmarti1424** [comment]
Do you have autocalc set?

**Comment by cesss** [comment]
Yes. The problem is that for the particular (and non-interactive) use that I'm doing of sc-im, I need the spreadsheet to be completely evaluated when I load it. In this moment, this only happens when you run sc-im in interactive mode, or when you trigger a "recalc" in non interactive mode. I uncommented that EvalAll() line in file.c, because it's the behaviour I prefer, but I admit my way of using sc-im might be different to the typical user.

**Comment by andmarti1424** [comment]
@cesss Could you please attach the file wasnt calculated correctly at startup? Thanks.
