### ISSUE TITLE
headers / footers - freeze multiple ranges

### ISSUE THREAD

**Issue by coachshea** [andmarti1424/sc-im#223]
I had mistakenly started this issue in the old repo, in which I asked about ranges (as per original sc). You answered ranges were dropped and that freeze could accomplish similar (but not identical) behavior. To give just a little background to the question. I am a long time sc user who absolutely loves the advancements that sc-im is making. I have switched over most of what I once did in sc to scim. However, I have a few files with several hundred entries for which I always want to see the column names (ie headers) and the totals (ie footers). Unless I am misunderstanding, freeze could not work because only one can be defined at a time. I am wondering if there is a way to accomplish this in scim, or if not, if bringing back ranges or something similar would be a consideration. Thanks again for all your time and for your great work on scim.

**Comment by andmarti1424** [comment]
Hello again @coachshea. Taking back frames is not a plan right now. I drop that because I think it was not coded in a sane way, so the ui update. May be sc-im can be modded to support multiple freeze ranges. It should not be a difficult task to store them, but may be it will, to show them correctly in the grid, and even more if you have hidden rows/cols! regarding your issue, hidding the rows in the middle didn't help you?

**Comment by coachshea** [comment]
Thanks once again for the quick response. I agree that frames (sorry for calling them ranges in the post, I should be more careful) was implemented poorly, so I certainly won't be disappointed if scim eventually adds something with similar functionality, but of it's own making. Hiding rows can work in some cases if I'm spending a lot of time in a given region, but can be cumbersome if I need to move around inside the non-header/footer areas frequently.

Let me explain my use-case and see if others can benefit from it. If not, I certainly wouldn't expect major feature additions for one user. When I defined an outer an inner frame, which was a real pain to do in the original, but powerful once it got going (in fact, it was so difficult to do in sc, that I found it easier to open up the file in a text editor and put the code in by hand). I also found it helpful to use a named range for the inner frame (technically this could be done without frames, but I found them to work together nicely). I could then not only work within the document while always having my headers and footers visible, but I could add or delete rows at any time and the definition for the inner frame/named range would update automatically. This was not only convenient while editing, but I could then define sort commands that referenced the named range and execute them without have to highlight the entire range or keep track of the starting and ending rows (ie sort myrange "..."). I had these mapped to function keys in the original, but your mapping feature would allow this feature to be very powerful. In addition, you have added a filter command, which could also take advantage of named ranges (with or without frames, but again, I thought they worked in conjunction nicely), and of course, could also now be mapped. In many ways, scim is the answer to what I always wanted sc to do. Unfortunately, for some of my projects, the features within which I want to use your extended capabilities aren't there. I find myself working on those within the old sc and wishing I had scim's power. I hope this helps explain it. As I stated, I don't expect you to add features for a single user, but I believe that these or similar features could benefit many users. Thanks again, for all your time.

**Comment by andmarti1424** [comment]
@coachshea i have started to code this multiple frozen rows/cols feature. It's in my fev branch called "new". Please feel free to test it. You can freeze a row or column with `fr` or `fc` in normal mode

**Comment by coachshea** [comment]
@andmarti1424 thank you so much for your work on this and for all the great work you've done with sc-im. It is a great program that I very much enjoy using. I've only had a little time to try it out so far, but the `fr` and `fc` commands seem to be working very well. I noticed that the program no longer seems to be reading my scimrc file. I hope that helps. I'll let you know what else I find as I have more time to use it.

Thanks again,

**Comment by andmarti1424** [comment]
Be sure to place all in ~/.config/sc-im/scimrc

**Comment by coachshea** [comment]
that did it. up until now I've had it in ~/.config and it worked fine, but moving it worked. It actually makes more sense to have it in ~/.config/sc-im, but for some reason it had been working in the other folder. Thanks once again.

I'll continue to work with it, but so far those two commands seem to be working perfectly. I'm sure you know that the help file is now off. It still makes reference to `:freeze` and `:unfreeze` which no longer seem to be implemented and there is no reference to `:freezecol`, `:freezerow`, `:unfreezecol`, and `:unfeezerow` all of which seem to work great on the current col/row, but don't take an argument as the previous commands used to.

**Comment by andmarti1424** [comment]
Try `make install`, otherwise help will not be refreshed

**Comment by coachshea** [comment]
Thank you. I've done that now and have the up to date help. The only thing is the new freeze/unfreeze commands ignore whatever argument I give it and work on the current rows/cols. Also, if I'm in visual mode and I type `f` it has no way to know if I want the rows or cols frozen, so it does both. None of this is a big deal to me, I am thrilled with how it's working, but I just want you to be aware.

**Comment by andmarti1424** [comment]
It should take the arguments as described in help file. Will check it out.

**Comment by andmarti1424** [comment]
@coachshea Please update to latest commit and try again. Updated doc as well.  Thanks.

**Comment by coachshea** [comment]
seems to be working great!! Thank you again!

**Comment by andmarti1424** [comment]
I will merge this to the default branch and make an official release, as soon as I finish other changes.thanks for your testing
