### ISSUE TITLE
scim in Debian, Ubuntu and Linux Mint

### ISSUE THREAD

**Issue by rwe1234** [andmarti1424/sc-im#224]
Hey! In Debian, Ubuntu and Linux Mint official repositories we already have a program named scim (smart common input method). I'm sure that it would confuse a lot of potential users of your great app on those platforms, not to mention that it looks impossible to have both apps installed (same name scim in terminal).

**Comment by andmarti1424** [comment]
Hello. If you want to add sc-im to those repos, my recommendation is to name it just sc-im. Then you'll have the original sc, sc-im, as well as scim.
