### ISSUE TITLE
remap to accentuated characters

### ISSUE THREAD

**Issue by gaalcaras** [andmarti1424/sc-im#225]
Just found out about sc-im, it's really great and a blast to use! I'd like to suggest a feature:

This works:
```
nmap "a" "w"
nunmap "w"
```
But this doesn't:
```
nmap "é" "w"
nunmap "w"
```

Vim supports both of the following examples:
```vimrc
nmap é w
nmap <Char-130> w " 130 is the decimal value of "é". See http://www.asciitable.com/
```

It would be really nice if scim allowed this kind of keys to be remapped, since some of them are way more accessible on international keyboard layouts. For instance, in my layout <kbd>é</kbd> is at the exact same place than <kbd>w</kbd> on a standard QWERTY layout, while <kbd>w</kbd> requires to extend the pinky all the way to the right edge of the keyboard.

**Comment by andmarti1424** [comment]
This should not be a major task. May be it could be added in a future version.

**Comment by andmarti1424** [comment]
@gaalcaras please update to latest commit and try the ñ mapping again. Thanks.

**Comment by andmarti1424** [comment]
é mapping, sorry

**Comment by andmarti1424** [comment]
@gaalcaras could you test it? Thanks
