### ISSUE TITLE
segfault deleting row used by @sum()

### ISSUE THREAD

**Issue by hymie0** [andmarti1424/sc-im#227]
Sc-im - version 0.7.0  -- as far as I know, the most up-to-date version from Git trunk.

This happens to me every time:

Open a new sheet

Go to cell D4

`=@sum(d0:d3)`

Delete row 3

Segmentation Fault.

**Comment by andmarti1424** [comment]
uf. awful bug. will check!

**Comment by andmarti1424** [comment]
this might not break anymore. but it still has some issues though..

**Comment by noperator** [comment]
Hey, I just experienced this in version 0.7.0, recently installed through the [SC-IM AUR package](https://aur.archlinux.org/packages/sc-im). While trying to delete row `8` of this [spreadsheet](https://github.com/andmarti1424/sc-im/files/4640554/spreadsheet.txt) (referenced in `=@sum(F1:F8)` in cell `F9`),  SC-IM crashes with:
```
Segmentation fault (core dumped)
```

Interestingly, none of the other referenced rows (i.e., `1–7`) cause this error when deleted. Note that in both this example and the one at the top of this issue, it's the _last_ row used in the `@sum()` (`3` and `8`, respectively) that crashes the application when deleted.

**Comment by andmarti1424** [comment]
@hymie0 @noperator Could you please update to latest git commit and try again? Thanks.
