### ISSUE TITLE
SegFault in the save :w and :load commands - android (bionic)

### ISSUE THREAD

**Issue by buribu** [andmarti1424/sc-im#229]
test 1
open scim and enter command

:w filename.sc

result:
segmentation fault

test2

:load table.sc # This file was generated with the version 0.3.0

result:
segmentation fault

2 devices used in the test and both had the same result

If you guys want to test this the sc-im about android devices ...

where to get the binary from version 0.7.0
1) f-droid
https://f-droid.org/

2) load the f-droid repositories

3) search termux and install

4) this script is to configure the extras repository where the package is
https://github.com/its-pointless/gcc_termux/blob/master/setup-pointless-repo.sh
apt install sc-im

$scim

In version 0.3.0 I was able to do ":w filename.sc". But ":load filename.sc" never worked.

I could load using the file as parameter "$scim filename.sc"

In version 0.7.0 none of this works for me.

In file.c there is a lib that is incompatible with bionic called <wordexp.h> I think it may have been this.
proposed:

rewrite file.c for better portability
file.c in version scim 0.3.0 was compatible with bionic

at #69 you told me that only bison ncursesw and gcc were enough to compile it
Has something changed? O.o

![screenshot_20171224-142034](https://user-images.githubusercontent.com/782908/34426833-d6a63362-ec21-11e7-9e57-6171780879d7.png)

**Comment by andmarti1424** [comment]
The problem sure is something else. Not the architecture. I use sc-im in arm without a problem. Could you send the files you are working on?

**Comment by andmarti1424** [comment]
What is your environment / OS? I believe bionic does not support wide chars. These might be a cause of things not working correctly for you.

**Comment by buribu** [comment]
I used two devices.
![screenshot_20171224-112720](https://user-images.githubusercontent.com/782908/34439466-5c0f4aac-ec95-11e7-9161-11f989aa993e.png)
![screenshot_20171224-141744](https://user-images.githubusercontent.com/782908/34439468-6792ef32-ec95-11e7-8384-cac0ad6de45b.png)

termux version 0.59

I'm using the @its-pointless binary package now.
I also tried to compile but...
![wordexpfail](https://user-images.githubusercontent.com/782908/34439521-b6947c22-ec95-11e7-95c3-646e726275b4.jpg)

@its-pointless should use a docker container with ubuntu and generate an arm package with clang.

I even tried to compile emscripten to get wordexp.o but it also did not work.
https://github.com/kripken/emscripten lol

Look
Missing functionality:
<aio.h>
<wordexp.h>
https://android.googlesource.com/platform/bionic/+/master/docs/status.md

The problem is not in the file. I can use any spreadsheet file to try to load. including empty spreadsheet files. The problem It happens anyway.

If you want to install sc-im on Android just follow steps 1 to 4.

**Comment by buribu** [comment]
This problem was apparently solved by the package maintainer.
