### ISSUE TITLE
Precision lost writing CSV files

### ISSUE THREAD

**Issue by leorosa** [andmarti1424/sc-im#230]
First of all: it is great that sc-im can be used to edit CSV files directly. However, there is a problem when saving these files, regarding the number format. To explain what I mean, consider a file containing these values

0,0.123456789

sc-im can successfully read it. But when the file is written (without any modification), these values are stored as

0.00,0.12

Ie., the precision is lost for the second value. Moreover, if a file contain several 'integers', the file size is increased, due to the inclusion of unnecessary zeros to them.

**Comment by leorosa** [comment]
Well, I'm probably misusing the config file, but it helped to solve this issue for me. I have .csv files in which data is stored with this arrangement:

`    int,int,int,float,string,float,string`

Luckily scim sets the precision correctly from the .scimrc file, which has these lines:

```
    format A 6 0 0
    format B 4 0 0
    format C 4 0 0
    format D 10 2 0
    format F 10 2 0
    leftstring E
    leftstring G
```

Columns width and string justification are overridden, but these are minor issues for me.

**Comment by andmarti1424** [comment]
Hello. Actually you can set the format at runtime with commands like these:
:int format D 10 2 0

**Comment by andmarti1424** [comment]
Hello @leorosa , could you try this?

**Comment by leorosa** [comment]
Sure, at runtime it works perfectly. In my second message, I have more or less solved my problem, thanks.

However, I think that the original 'problem' stands: when you open a csv file with values in scim, and overwrite it, the values precision are lost: integers 'gain' two decimal digits, and 'floats' are saved with only two decimal digits of precision.
