### ISSUE TITLE
Possible unnecessary defines

### ISSUE THREAD

**Issue by cesss** [andmarti1424/sc-im#233]
I was trying to increase the maximum size for the cell contents (for my own use), and I found that there're two related definitions, which I think could be rewritten so that they are the same definition: FBUFLEN in sc.h and BUFFERSIZE in macros.h

I've increased both values to the same value, but IMHO they should be merged as just one definition.

**Comment by andmarti1424** [comment]
Yes indeed. Feel free to do a pull request if wished!

**Comment by andmarti1424** [comment]
I have thought about it, and I think I prefer to have them separated.
