### ISSUE TITLE
Small improvements to command-cancellation behaviour

### ISSUE THREAD

**Issue by dlbeer** [andmarti1424/sc-im#234]
This is a great improvement on the original "sc", but I was confused by the program's behaviour when accidentally starting a multi-key command and trying to abort it. A "?" appears at the top-left. Eventually I figured out that I can either wait 3 seconds, in which case the "?" disappears, or I can press ESC, and after a short delay, the command is aborted (but the "?" remains until I hit another key).

I made the following changes to:

- Allow the use of Ctrl+G to abort (which responds faster than ESC, due to the terminal interface library's need to wait for characters following ESC).
- Refresh the top line to remove the "?" as soon as the multi-key command is aborted.

Patch here: https://gist.github.com/dlbeer/3a4b99751a678df84233a703ad8496ce

**Comment by andmarti1424** [comment]
Commited. Thanks.
