### ISSUE TITLE
compile time error against tui.h and lua5.1

### ISSUE THREAD

**Issue by nightsdark** [andmarti1424/sc-im#236]
I tried sc before but, wanted to try sc-im unfortunatly the install didn't a work exactly right. I had no color and though I'd start over. 
I did these commands. system is ubuntu 16.04 - awesome wm - st terminal - tmux - zsh

- git clone git.github.com/andmarti1424/sc-im.git
cd sc-im/src 
make clean
make 

I got tui.h:48:17 fatal error: lua.h No such file or directory
I had lua5.1 installed at /usr/include/lua5.1 but, there is only a lua.hpp file and a include folder in that directory. So I ------>

fixed ======
sudo ln -s  /usr/include/lua5.1/include/*  /usr/include/lua5.1
make clean
make
sudo make install

Now it has color, can't wait to speadsheet somthing :)

**Comment by andmarti1424** [comment]
Please feel free to update Ubuntu wiki explaining this distribution specific step to build sc-im.
Thanks.
