### ISSUE TITLE
After installing the app to the system, :help does not work

### ISSUE THREAD

**Issue by yoshi314** [andmarti1424/sc-im#237]
All i get is 'Cannot open help file'. 

What am i missing? I did the regular make install.

**Comment by andmarti1424** [comment]
Please check the HELP_PATH defined in Makefile. scim is not finding.
Also the name variable in the same file.
Did you change those default values?

**Comment by yoshi314** [comment]
No, i'll check it out now.

**Comment by andmarti1424** [comment]
@yoshi314, Could you check it?

**Comment by yoshi314** [comment]
Ok, i've got it resolved on my end.
