### ISSUE TITLE
Problem setting "DEFAULT_PASTE_FROM_CLIPBOARD_CMD" setting in homebrew SC-IM

### ISSUE THREAD

**Issue by krontzo** [andmarti1424/sc-im#239]
MacOS Sierra
Homebrew SC-IM is configured with TMUX for clipboard copy and paste.

```bash
$ scim --version
Sc-im - version 0.7.0
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DUSELOCALE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="scim"
-DHELP_PATH="/usr/local/Cellar/sc-im/0.7.0/share/scim"
-DLIBDIR="/usr/local/Cellar/sc-im/0.7.0/share/doc/scim"
-DDFLT_PAGER="less"
-DHISTORY_FILE=".sciminfo"
-DINS_HISTORY_FILE=".sciminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

I'm trying to switch to `pbcopy and pbpaste`,  but there is one issue (and one minor problem):

Using these options in `.scimrc`, 

```vim
set autocalc
set numeric
set numeric_decimal=0
set overlap
set copy_to_clipboard_delimited_tab=1
set default_copy_to_clipboard_cmd="pbcopy<"
set default_paste_from_clipboard_cmd="pbpaste"
```

I get `Abort trap: 6`, also when trying to set `"DEFAULT_PASTE_FROM_CLIPBOARD_CMD"` while running SC-IM.

The minor problem is that setting the value `"pbcopy <"` is truncated to `pbcopy` in the RC file and with the `:set` command. But `"pbcopy<"` works.

I didn't try to recompile with the current sources since the last commits after 0.7.0 do not seem to be related.

**Comment by krontzo** [comment]
I should had compiled the last version before reporting then issue: compiling last commit <https://github.com/andmarti1424/sc-im/commit/d724bfda24003ddbb94f6ea5b4407b63b8ab416b> with the `pbcopy <` and `pbpaste` activated in the Makefile, the `"DEFAULT_PASTE_FROM_CLIPBOARD_CMD"` problem does not exist anymore.

Just the truncation when setting `default_copy_to_clipboard_cmd` in the config file or with the `:set` command continues to appear.

**Comment by andmarti1424** [comment]
Hello. Did you try with backslash or with simple quotes?

**Comment by andmarti1424** [comment]
In my debian installation, if I set the value like this: `set `default_copy_to_clipboard_cmd="pbcopy<"
During runtime, i see the variable correctly: `default_copy_to_clipboard_cmd=pbcopy<`````

**Comment by krontzo** [comment]
Thank you for developing SC-IM! And for your fast reply.

I tried backslash but it still is truncated. I cloned latest commit and compiled in Ubuntu 16.04 and of course "pbcopy<" without blank space works, but whitespace gets truncated as in macos. Would you please try setting the cmd with "pbcopy <" ?

Using simple quotes produces `syntax error`.
Copying the makefile cmds in sc-im also give `syntax error` and in the config file they just get ignored.

It was an inconvenience in macos, since I don't use tmux there; but in Ubuntu, it is kinda of a problem if I were to switch between `xclip` (e.g. normal desktop use) and `tmux` (e.g. ssh remote session) during runtime, given that those commands require whitespace to pass the arguments.

**Comment by andmarti1424** [comment]
Please update to latest commit in depgraph branch and try again!

**Comment by krontzo** [comment]
It works!

Thank you!

There's another issue, with `default_paste_from_clipboard_cmd`. I'll open it soon.
