### ISSUE TITLE
xlsx times are off by 1 hour

### ISSUE THREAD

**Issue by jameh** [andmarti1424/sc-im#241]
This is a strange issue, but it seems that all of the time-formatted fields of my xlsx file when opened with sc-im are 1 hour _before_ the correct time.

On MacOS El Capitan 10.11.6

example file: [times.xlsx](https://github.com/andmarti1424/sc-im/files/1831473/times.xlsx)

screenshots:
![screen shot 2018-03-20 at 3 36 33 pm](https://user-images.githubusercontent.com/1538657/37686466-d4b18520-2c54-11e8-82d3-a2945528f107.png)
![screen shot 2018-03-20 at 3 36 50 pm](https://user-images.githubusercontent.com/1538657/37686469-d8965a76-2c54-11e8-9743-2832c32f90a2.png)

**Comment by andmarti1424** [comment]
Please check help regarding this. Gmt offset has to be modified.

**Comment by jameh** [comment]
aha - thanks
