### ISSUE TITLE
Selectively apply filters?

### ISSUE THREAD

**Issue by for-coursera** [andmarti1424/sc-im#246]
It's not possible to selectively apply filters now, I presume? Like, if I have 3 filters defined (0, 1, 2), and I want to apply only two of them, with IDs 0 and 2?

Would be a great feature, though ;)

(Also, am I missing something, but let's say I have a table with A:G columns and 0:45 rows, and I want to apply my filters to the whole document excluding the first row, then I suppose I should type something like `filteron A1:G45`? Somehow just nothing happens after that - yet if I select the same range via `ggjvG`, filters indeed apply.)

Thanks!

**Comment by andmarti1424** [comment]
regarding 1, no. there is no way to add a filter and have it disabled. if you add, then it would be enabled until you remove it. you can change this though easily. feel free to do a pull request. it would not be a big change.

**Comment by andmarti1424** [comment]
regarding number 2, could you please send me the file you are trying to filter? i want to debug with it..
thanks.

**Comment by for-coursera** [comment]
Sent to sc*.s*et@gmail.com :).

**Comment by andmarti1424** [comment]
Could  you please update to latest commit in freeze branch, and try the filter issue? Thanks.

**Comment by for-coursera** [comment]
Yep, it's working now, thanks!
