### ISSUE TITLE
Support  function keys <F1> ... <F13> and <SPACE> in mappings

### ISSUE THREAD

**Issue by for-coursera** [andmarti1424/sc-im#247]
`sc-im` seems not to recognize the function keys `<F1> ... <F13>` and beyond. Adding 
    
    nnoremap "<F10>" ":wq<CR>"

to `.scimrc` results in something like this after `:showmaps` command is entered

    7 + nnoremap "" = ":wq<CR>"

Besides that, if pressed in INSERT mode, they actually echo strange characters like these: `ČčĎĎďĒē`.

**Comment by for-coursera** [comment]
And you also can't map `<Space>`, right?

**Comment by hugoweslien** [comment]
You can map spacea as " ", that worked for me.

**Comment by Iperero92** [comment]
I see exactly the same issue when trying to map "ñ": it appears as an empty string in the ouptut of :showmaps:

`nnoremap "ñ" "l"`

shows

` 3 + nnoremap "" = "l"`

If I unquote ñ, it doesn't even show that line, of course.

This is an important mapping for vim users with Spanish layouts (jklñ is usually mapped to hjkl). I guess it's also useful for other non English users. For me, it is a deal breaker. :(

I'm using macOS Catalina 10.15.3 and I have tried the two installation methods, whith the same result.

**Comment by andmarti1424** [comment]
@Iperero92 please update to latest commit and try the ñ mapping again. Thanks.

**Comment by andmarti1424** [comment]
Could you test it? About F1-F13 keys.. those will not be added. I want to give them use for other things..
Make sort easy, plotting, etc..

**Comment by Iperero92** [comment]
Hey Andrés, thanks for working on this issue. I’ll let you know.

**Comment by Iperero92** [comment]
I've just installed from the latest commit on MacOS 10.14.6 with Lua 5.1 (tried also without Lua). The "ñ" appears on showmaps now and works fine on a scimrc with just one line: 'nnoremap "ñ" "l"'. Thank you.

**Comment by andmarti1424** [comment]
Space should also be handled now. Thanks.

**Comment by 097115** [comment]
@andmarti1424 

> About F1-F13 keys.. those will not be added. I want to give them use for other things..
> Make sort easy, plotting, etc..

Well, that doesn't contradict a user being able to use those for mappings, right? :)

I mean, you sure can provide the default mappings for these keys, but it also would be great if a user could remap those defaults and use the functional keys for their own bindings.
