### ISSUE TITLE
Toggle settings?

### ISSUE THREAD

**Issue by kflak** [andmarti1424/sc-im#252]
Just stumbled over this a couple of days ago in my search for a vim-style replacement of libreoffice. Great work! 
I can't find any documentation about any possibility to toggle between different settings. For example, I would like to be able to do :set numeric! or something like that to toggle between 1 and 0. Right now I have assigned  ,n and ,m to 1 and 0, respectively, but it would be a lot more neat to be able to switch it with one keyboard shortcut...

I'm running this on ArchLinux.

**Comment by andmarti1424** [comment]
No toggle settings. Did you try a mapping?

**Comment by andmarti1424** [comment]
No toogle option. Sorry.
Did you try mapping with ctrl key? I did not test it though.

**Comment by andmarti1424** [comment]
I close this. Please open a discussion so other can vote/discuss on this addon. Thanks.
