### ISSUE TITLE
Problem compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by cavanaug** [andmarti1424/sc-im#253]
Here is the errors Im getting..   Any thoughts??

╰─[11:29:23]── make
gcc  exec.o range.o xmalloc.o screen.o cmds_visual.o vmtbl.o yank.o cmds.o undo.o sort.o main.o filter.o xls.o pipe.o input.o color.o maps.o marks.o cmds_edit.o format.o cmds_command.o shift.o conf.o hide_show.o xlsx.o cmds_normal.o gram.o block.o cmds_insert.o file.o help.o interp.o buffer.o dep_graph.o lex.o history.o utils/string.o utils/dictionary.o utils/extra.o -o scim -lm -lncurses  -lzip -lxml2 
screen.o: In function `show_content':
/home/cavanaug/src_internet/git_src/sc-im/src/screen.c:551: undefined reference to `win_wchnstr'
input.o: In function `handle_input':
/home/cavanaug/src_internet/git_src/sc-im/src/input.c:56: undefined reference to `wget_wch'
cmds_edit.o: In function `get_key':
/home/cavanaug/src_internet/git_src/sc-im/src/cmds_edit.c:22: undefined reference to `wget_wch'
collect2: error: ld returned 1 exit status
Makefile:172: recipe for target 'scim' failed
make: *** [scim] Error 1

**Comment by andmarti1424** [comment]
Please try linking against ncursesw.

**Comment by cavanaug** [comment]
That solved it

**Comment by p-m-brown** [comment]
sorry, what does "linking against ncursesw" mean? ie how do you solve the problem described above?
