### ISSUE TITLE
Multiple Sheets

### ISSUE THREAD

**Issue by declanol** [andmarti1424/sc-im#256]
Is it possible to implement multiple sheets? In particular, is it possible to open and save to arbitrary sheets of an xlsx rather than default to Sheet1 always?

**Comment by andmarti1424** [comment]
Not possible. Sorry. Multiple sheets would require a rewrite of most of the app core..

**Comment by declanol** [comment]
I was particularly wondering can opening/saving of xlsx files be parameterised such that it doesn't always default to the first sheet, i.e., not implement a multisheet paradigm but be able to open arbitrary sheets using the current code.

In particular, are there knock-on effects to adding parameters to readfile and open_xlsx to modify https://github.com/andmarti1424/sc-im/blob/freeze/src/xlsx.c#L417 that I can't forsee?

**Comment by andmarti1424** [comment]
believe its fixed in a line..
`name = `"xl/worksheets/sheet1.xml";`

**Comment by remembertoremind** [comment]
+1 for multiple sheets. That would be really nice :)

**Comment by roman65536** [comment]
@andmarti1424 
Multiple sheets is not difficult as it may appears in the first place. 
Is just surrounding the tbl with sheet structure. see : https://github.com/roman65536/sc_offline/blob/master/luasc3.c  
Basic core is still the tbl (and original sc code) wraparound sheet structure, that holds the sheet information in a linked list.

roman

**Comment by andmarti1424** [comment]
My plan is to keep developing sc-im version 1 as is without multiple sheet support.
And in paralle lstart a new core from scratch that could handle multiple sheet, multiple files.. (@roman65536 already done some stuff regarding this). May be that could be the start of the new core.

**Comment by neo1312** [comment]
It will be aweso multiple sheets
