### ISSUE TITLE
@now returns 0

### ISSUE THREAD

**Issue by therealraven** [andmarti1424/sc-im#257]
I am new to sc-im.

Entering `=@now` into a cell displays "0.00".

Am I doing something wrong? missing configuration? or is this a bug? Or is @now removed in sc-im?

**Comment by andmarti1424** [comment]
Hello. Please check DATES INPUT in the documentation..  @dts is not used for entering dates..

**Comment by andmarti1424** [comment]
Regarding @now, will check it out.

**Comment by therealraven** [comment]
Actually @dts works (for converting a dd/mm/yyyy to a unix timestamp), I was using it incorrectly. Apologies for the ninja edit 🙂

**Comment by therealraven** [comment]
@now seems to just be a functionality that has been removed in sc-im.

I guess this is not an appropriate place to do a feature request so I will close this issue.

**Comment by reportaman** [comment]
@therealraven ``@now`` works now: https://github.com/andmarti1424/sc-im/issues/466#issuecomment-786798553
