### ISSUE TITLE
reference issue at start

### ISSUE THREAD

**Issue by immae** [andmarti1424/sc-im#260]
Consider this file:
```
let A0 = 10
let C1 = F5+A0                 
let F1 = 10
let F3 = 20                    
let F5 = F1+F3                 
goto A0
```

When starting, the "C1" cell will hold invalid data until you "recalc".
Note: I didn’t write the file by hand, it was saved by sc-im like that.

**Comment by dpacbach** [comment]
I am also seeing this -- essentially it appears to be a bug where cells are not updated in order of dependencies among cells, but rather in some other order (perhaps the order in which the cells are first encountered when reading in from the save file).  E.g., if I have cell A0 depends on A1 depends on A2 depends on A3 then I have to update the value of A3 four times in order for the change to propagate to A0.

This makes sc-im unusable as a spreadsheet.

**Comment by immae** [comment]
I wouldn’t say it so flat, but you have to think of updating your spreadsheet when you open it (or add reload at the end of your file)

**Comment by dpacbach** [comment]
That may work in some cases, but in the case that you have a dependency chain consisting of more than two  cells, it actually takes multiple updates in order to fully update all cells.  On each update, one more cell gets updated, until eventually the updates propagate to all dependent cells.  Again, in my example above, one has to update cell A3 four times in order for the effects to propagate to all dependent cells.  If anyone needs an example (.sc file) to demonstrate this I am happy to provide.

**Comment by DuBistKomisch** [comment]
Also seeing this in 0.7.0, seems like a pretty major issue, I would also say it almost makes sc-im unusable.

I was trying to do something I'd consider simple and common: produce a total of a column, then have another column of percentages based on the value to the left and the already calculated total. I get ERROR in each of the latter on loading without `recalc`, manually reordering my .sc file's contents doesn't seem to help. Only workaround is to re-calculate the total in every cell, which is not very maintainable.

I also notice I tend to get segfaults (looks like an infinite loop in gdb's backtrace) with certain operations once creating this situation, so must be some fundamental issue going on here.

**Comment by andmarti1424** [comment]
thanks for reporting this. will try to fix it when I have time..

**Comment by andmarti1424** [comment]
please update to latest commit and try again.

**Comment by DuBistKomisch** [comment]
Seems to work correctly in my use case now, thanks!

I do get this message each time I enter a formula though, not sure if it's related or just from the unstable version:

>Error while adding edge: the edge already exists!

**Comment by andmarti1424** [comment]
Yes. I was aware of it. Its related. Will fix it soon
