### ISSUE TITLE
color issue with locked cells

### ISSUE THREAD

**Issue by immae** [andmarti1424/sc-im#261]
Consider this file:
```
format C 23 2 0
let A0 = 10                    
leftstring C0 = "Some important thing"
leftstring C2 = "Foo"          
lock A0:D0                     
cellcolor C0 "fg=WHITE bg=GREEN"
lock A1:D1                     
lock A2:D2                     
goto A0                        
```
It was saved as is by sc-im: after filling some random text (not necessary), I changed cell C0's background, then locked A0:D2 (including the cell I just colored). When reopening the sheet later, the coloration is lost as the cell is already locked.

**Comment by andmarti1424** [comment]
this is a bug. will check it out.

**Comment by andmarti1424** [comment]
please update to latest commit and try again. it should be saved in the correct order
