### ISSUE TITLE
Integration with Google Sheets

### ISSUE THREAD

**Issue by bogdanr** [andmarti1424/sc-im#264]
sc-im is quite nice but it would be awesome if it had the ability to save and load data from Google Sheets.

With the v4 API quite a lot is possible:
https://developers.google.com/sheets/api/

**Comment by andmarti1424** [comment]
Well, indeed it is a good idea.. but so much work. I leave this a feature request.
Take in mind that not Google sheets is not like scim format.. so you'll have little differences.
Just like when you work with Excel.

**Comment by andmarti1424** [comment]
I am having trouble to find a C example of the API.. did I miss it?

**Comment by andmarti1424** [comment]
Could not find any single C example of its use. If you do please share and I will try to add this.

**Comment by andmarti1424** [comment]
Please if you find an example, please reopen. If its not too difficult I can add it for v1 of sc-im. thanks.
