### ISSUE TITLE
txtdelim option doesn't work on macOS 10.13.4

### ISSUE THREAD

**Issue by Kerruba** [andmarti1424/sc-im#265]
Hello, 

I'm trying to read a tab delimited file with extension txt on mac but when I run the command
```
scim --txtdelim="\t" <name-of-file>.txt
```
sc-im open up but is empty

**Comment by Kerruba** [comment]
Sorry, is this happening only to me?

**Comment by andmarti1424** [comment]
I do not have macOS. I will test it in my Arch installation. Did not have time yet, sorry.

**Comment by Kerruba** [comment]
I don't know why but is working now... but my current version of macOS is now 10.13.5...maybe was related to previous version of os.

**Comment by andmarti1424** [comment]
Please, feel free to open a new issue if you get this behaviour again. May be you didnt have a tab as a delimiter in your file after all? This happened to me once, since my text editor (vim) converted tabs to white spaces when saving the file..
