### ISSUE TITLE
Reducing column size too much crush the program

### ISSUE THREAD

**Issue by Kerruba** [andmarti1424/sc-im#266]
To replicate:

I've a coulmn whit very long text values on a row and very short text values on other rows.
When I'm trying to reduce the size of the column to make it almost collapse, scim crash

The only thing I can see at the top is an A column and some potentially error code: "36388 segmentation fault scim"

**Comment by andmarti1424** [comment]
Hello .Whats the size of your terminal and what is the approx. size you are trying to increase the screen to? Thanks.

**Comment by Kerruba** [comment]
Here is a gif showing you the issue, hopefully is big enought
![scim_col_collpse_crash](https://user-images.githubusercontent.com/2854782/41223607-320dbd1c-6d62-11e8-9c22-c6d0ab12efab.gif)

**Comment by Kerruba** [comment]
I think this is also screwing up the terminal itself, in the sense that when it crashes an `ls` command is spreading the results around

**Comment by andmarti1424** [comment]
"I think this is also screwing up the terminal itself, in the sense that when it crashes an ls command is spreading the results around" > this always happen whan an ncurses app crashes.

**Comment by andmarti1424** [comment]
Hello. What version of sc-im are you using? freeze branch? Also, take note that you can use 'aa' command in normal mode to autofit content to column.

**Comment by andmarti1424** [comment]
well, just in case, I did change a validation so this behaviour can be caught. Please, feel free to update to latest commit in freeze branch and try again. Thanks.

**Comment by andmarti1424** [comment]
@Kerruba, could you test this?

**Comment by Kerruba** [comment]
Hi @andmarti1424 , sorry for not replying. 

I'll give it a go and if there are further issues I'll let you know by reopening this issue.
