### ISSUE TITLE
Question: What is CELL_NEGATIVE?

### ISSUE THREAD

**Issue by slackhead** [andmarti1424/sc-im#271]
I thought it might be for cells with value < 0 and I tried to set the colour to red:

color "type=CELL_NEGATIVE fg=RED bg=BLACK"

But it doesn't do what I expected. Is it for something else?

**Comment by andmarti1424** [comment]
Hello. Command is correct. There is a bug in the ui, not in the color command.. Will fixed it today.

**Comment by andmarti1424** [comment]
Please update to latest commit and try again!

**Comment by slackhead** [comment]
Works. Thanks :)

**Comment by slackhead** [comment]
Ah it doesn't work if the cell contains a @sum or some other formula and the number is negative.

**Comment by andmarti1424** [comment]
could you please try again updating to latest commit?

**Comment by slackhead** [comment]
That's got it. Thanks.
