### ISSUE TITLE
Problem with delete, home and end keys

### ISSUE THREAD

**Issue by slackhead** [andmarti1424/sc-im#272]
My delete key doesn't work in either normal or insert mode. In insert mode I can press it a few times, then hit escape, and the characters are deleted afterwards.

I'm using urxvt + screen + zsh, and TERM is set to screen-256color-bce. I've tried setting TERM to a few things to see if it would help, like xterm, xterm-color, xterm-256color, rxvt-unicode-256color. No change.

I've had this problem with dialog too so I wonder if it's an ncurses problem. Other apps like vim work fine. If I run cat and press delete I get

^[[3~

which is the correct code. For normal mode I could always nmap it to 'x' which I've tested and works, but it's annoying in insert mode.

The home/end keys are also broken. They don't go to the start or end of a line. In fact I've nmapped [ and ] and when I press home or end the '[' map gets triggered. I guess because they are  generating escapes that sc-im isn't interpreting. I see '7?' and '8?' printed in the top line in scim.

**Comment by andmarti1424** [comment]
Regarding the DEL key in insert mode, please update to latest commit and try again.
Regarding the DEL key in normal mode, that is not a valid key for that mode.

NOTE: vim does not use ncurses

**Comment by andmarti1424** [comment]
about the home/end keys, may be there is a problem in the mapping?

**Comment by slackhead** [comment]
Delete works now thanks. Thanks for all your hard work too.

I tried home and end without screen and they work fine. It could be the TERM setting I'm using for italic text may be the problem.

For italics I set TERM=screen-256color before starting screen. That's the only way I've found that works (so far).

I'll figure it out.

**Comment by slackhead** [comment]
OK. What works is when I do:

TERM=screen-256color screen <options>

rather than exporting it  beforehand, and setting term to rxvt-unicode-256color in screenrc.

The first gives italics and the second makes home/end work.
