### ISSUE TITLE
Question: converting between formats (dates)

### ISSUE THREAD

**Issue by slackhead** [andmarti1424/sc-im#273]
My bank lets me export statements as cvs formatted files, which is good but the dates are strings like:

2018-06-27

I can't find an easy way of converting these to real dates except by opening them in libreoffice and converting them to the format I want.

Is there a way of doing this in sc-im? I know that dates are stored as numbers so how complex is the equation to turn a string into an int and then to a date?

**Comment by andmarti1424** [comment]
Hello. yes. please take a look at the "DATES INPUT" section in the doc. There its explained how to achieve what you want.
