### ISSUE TITLE
Reference other .sc files

### ISSUE THREAD

**Issue by remembertoremind** [andmarti1424/sc-im#281]
Hi :)

I just gave this application another go, and I _really_ like it. Thanks!

I might have missed it in the :help, but is it possible to reference other .sc files? Like column b and c from another file. Perhaps something like in excel

    =SUM('C:\Reports\[Budget.xlsx]Annual'!C10:C25)

**Comment by andmarti1424** [comment]
no. not like that. perhaps you can use a script?

**Comment by remembertoremind** [comment]
Okay thanks :) I'll see what I can do with a script.

**Comment by singpolyma-shopify** [comment]
At least in "classic" `sc` you can solve this like so:

    = @ston(@ext("echo 'eval A0' | sc -q t.sc 2>/dev/null", 0))

Maybe a similar approach will work for sc-im?

**Comment by andmarti1424** [comment]
No @remembertoremind . Sorry.
There's a future plan of replacing sc-im core to permit multiple sheets and files opened at the same time.
But no right now.

May be a workaround (not the same of course) as suggested by @singpolyma-shopify could work..
