### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [andmarti1424/sc-im#283]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [create_dictionary](https://github.com/andmarti1424/sc-im/blob/7890bdc0467d13e083b7226579fef2951ab02de4/src/utils/dictionary.c#L57)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [read_argv](https://github.com/andmarti1424/sc-im/blob/eb807201c320d1991203e1bf9d98c92b0fc0afad/src/main.c#L529)

**Comment by andmarti1424** [comment]
could be. pull requests are welcome.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by andmarti1424** [comment]
sure. thats always better.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by andmarti1424** [comment]
may be after fixing the main issues.. (mainly regarding calculation)

**Comment by elfring** [comment]
Would you like to reopen this clarification request before?
