### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [andmarti1424/sc-im#284]
The function “[endwin](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/endwin.html "Suspend Curses session.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[sig_tstp](https://github.com/andmarti1424/sc-im/blob/eb807201c320d1991203e1bf9d98c92b0fc0afad/src/main.c#L653 "Update candidate")”.

**Comment by andmarti1424** [comment]
endwin is an ncurses function.

**Comment by elfring** [comment]
How would you like to get these function implementations async-signal-safe?

**Comment by andmarti1424** [comment]
I dont understand.. what are the different alternatives?

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)

**Comment by andmarti1424** [comment]
Please open a discussion for this topic.
