### ISSUE TITLE
Trying to compile with XLS import support on Debian

### ISSUE THREAD

**Issue by b79** [andmarti1424/sc-im#286]
Hi, sc-im looks great! I can build on Debian Stretch fine, but am having problems with XLS import support.
After reading issue 238, I got libxls from here:

    https://sourceforge.net/projects/libxls/files/libxls-1.4.0.zip/download

After installing that, modified the makefile like so:

    CFLAGS += -DXLS -I/usr/local/libxls/include
    LDFLAGS += -L/usr/local/libxls/lib
    LDLIBS += -lxlsreader

But after compiling, now when trying to launch sc-im there's this error:

    ./sc-im: error while loading shared libraries: libxlsreader.so.1: cannot open shared object file: No such file or directory

I do see on my system /usr/local/libxls/lib/libxlsreader.so.1 (which is a symlink to libxlsreader.so.1.2.1).

Anything else I need to try?

**Comment by andmarti1424** [comment]
Hello. Did @roman65536 's tip help?

**Comment by b79** [comment]
* Andrés M. <notifications@github.com> [180913 11:54]:
> Hello. Did @roman65536 's tip help?

Yes, that did indeed solve the problem. Meant to respond earlier...
Thanks!
