### ISSUE TITLE
Problem with valueize on cells that point to other cells containing sums when the source data is deleted

### ISSUE THREAD

**Issue by slackhead** [andmarti1424/sc-im#287]
So far sc-im has been an absolute life saver. No more waiting 30 seconds+ for clunky old libreoffice to start up, and it's much easier to work with, so I'm very grateful for the work that you've put into it.

When I valueize a cell that points to another cell that contains a sum, and I delete the source data (using visual select + x), the valueized call often changes back to a pointer/reference and displays 0.00. This happens a lot in one spreadsheet that I use, and with the same cells every time.

I reproduced this in a blank test file only once, but I can't seem to reproduce it after trying again:

Ceate a column of values: :fill A1:A10 1 1
Make a sum of that in A11: @sum(A1:A10)
Then reference A11 from say B11: =A11
Valueize B11
Visually select A1:A10 and delete with 'x'
B11 changes to a bold red 0.00

I've just thought that it would have been useful if I'd looked to see what the cell properties read at the top of the window when the cell is selected. I will add that info here the next time it happens.

The sheet that it happens in every time is rather large and complex - around 68K with 400+ rows - and it happens to the same cells in the same column every time. Added to that I usually have it open for days at a time and I'm shifting large blocks of data around.

I guess the workaround is to copy the original @sum to a new cell, rather than pointing to it.

I've tried saving the file before doing the deletion but it didn't help.

**Comment by andmarti1424** [comment]
hello. what do you think it should show when you delete it with 'x'?

**Comment by slackhead** [comment]
After a cell has been valueized it should keep the value that valueize gave it, and all links/references to other cells should be removed from the format etc.

In other words, when you valueize a cell you are hardcoding the actual numerical value and removing all references to other cells that it may originally have had, exactly as if you had typed the number in manually in the first place.

**Comment by slackhead** [comment]
Yes, it doesn't do it all the time. But I found that when it does do it, it keeps doing it with the same cells every time. Thanks for looking into it.

**Comment by andmarti1424** [comment]
can you  reproduce it with your file? i might commit a change so you can test it.. since i cannot reproduce it myself.

**Comment by slackhead** [comment]
It's so long since I used that file that now I can't recall which cells it happened with. I may have changed too much in it since then. I'll try to recreate it and get back to you.

**Comment by andmarti1424** [comment]
Hello @slackhead. Please try to reproduce it with latest commit. Thanks

**Comment by slackhead** [comment]
Hi @andmarti1424 

I got as far as creating the @sum(), but as soon as typed in the reference =A11 in B11 it segfaulted.  I tested 3 times.

**Comment by andmarti1424** [comment]
@slackhead Could you please update to latest commit and try again? Thanks!

**Comment by slackhead** [comment]
That seems to have fixed it.  Tested twice.  Thanks :-)

**Comment by slackhead** [comment]
As a side note, you mentioned that you were unable to reproduce it, and that leads me to wonder if if maybe different gcc versions (I use 5.5.0) and/or libraries might be affecting this, so here's my ldd output:

```
linux-vdso.so.1 (0x00007fff0bd3a000)
libm.so.6 => /lib64/libm.so.6 (0x00007f7b6e112000)
libxlsreader.so.1 => /usr/lib64/libxlsreader.so.1 (0x00007f7b6df02000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f7b6dcfe000)
libncursesw.so.5 => /lib64/libncursesw.so.5 (0x00007f7b6da97000)
libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f7b6d732000)
libzip.so.4 => /usr/lib64/libzip.so.4 (0x00007f7b6d51f000)
libz.so.1 => /lib64/libz.so.1 (0x00007f7b6d308000)
liblua.so => /usr/lib64/liblua.so (0x00007f7b6d0db000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7b6cebe000)
libc.so.6 => /lib64/libc.so.6 (0x00007f7b6caf5000)
/lib64/ld-linux-x86-64.so.2 (0x00007f7b6e41b000)
liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7b6c8d0000)
libreadline.so.6 => /usr/lib64/libreadline.so.6 (0x00007f7b6c687000)
libhistory.so.6 => /usr/lib64/libhistory.so.6 (0x00007f7b6c47e000)
libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f7b6c227000)
```

**Comment by andmarti1424** [comment]
@slackhead thanks to you. actually i managed to reproduce it without problem the other day.. so i dont know.
