### ISSUE TITLE
Problem with ^ when there are fixed rows

### ISSUE THREAD

**Issue by slackhead** [andmarti1424/sc-im#288]
Git pull from 2018-08-17.
Using the included makefile.

Scenario:

The first two rows in a sheet are fixed.
I press # to go to last legit row, which turns out to be say 71.
Now I see fixed rows 0 and 1 at the top, and under those rows 60-71. The cursor is on 71. All this is expected behaviour.
I press ^ to go to row 0.
It /does/ go to row 0, but the screen doesn't move. I still see rows 0 and 1, with 60-71 underneath.

How do I go to row 0 and also scroll the screen at the same time? I can't see any way of doing it. I tried using zz or zt after ^, but they don't have the desired effect. All I can do is hold down page up until I reach the top. However, I did notice that using gg works, as does using g to goto a row under the fixed rows.

What I would expect to happen is that ^ should not only go to row 0, but position the screen to the top too. Perhaps there should be something similar to # that goes to the topmost legitimate cell (not including fixed headers)?

**Comment by andmarti1424** [comment]
@slackhead Please update to latest commit and try again.
Modified # with frozen row and you can also use commands
H, M, L to go to different parts of visible screen.

**Comment by andmarti1424** [comment]
@slackhead ?

**Comment by slackhead** [comment]
Yep, works fine now. Thanks :-)

Could I make a suggestion though, that 'unfreeze' could take the same arguments as 'freeze', so that only certain rows/columns can be selectively unfrozen, instead of unfreezing everything? That would very useful.5

**Comment by andmarti1424** [comment]
@slackhead could you describe what you have frozen?
actually you can only freeze one thing at the time and that is a current limitation it may need to be changed in future.
for instance, you cant freeze two rows.
if you freeze say row 0, and then row 8. the freeze over row 0 is lost.
so :unfreeze just acts over the last thing you froze.

**Comment by slackhead** [comment]
For example, after 'freeze 0:1', doing 'unfreeze 1' would leave row 0 still frozen.

**Comment by andmarti1424** [comment]
Im not really sure about that. It would be useful to freeze multiple rows / columns. But thats another thing.
Please feel free to open a discussion on that topic, so others can discuss and give their opinions. thanks.

**Comment by andmarti1424** [comment]
I close this since ^ issue is fixed.
