### ISSUE TITLE
Basic functionality not working: what I am missing?

### ISSUE THREAD

**Issue by jpluscplusm** [andmarti1424/sc-im#295]
Hey folks,

I love the ethos of `sc-im`, but I'm wondering if I'm missing something fundamental about driving it:

Given the following trivial, why am I seeing a 0.00 in cell A0?

```
let A0 = @sum(A1:A2)
let A1 = 1
let A2 = 2
goto A0
```

It doesn't seem to be affected by order: either file order or cell order. If I move the `let A0` line to the end, I see the same 0 in A0, and also if I move the sum to after the data (A3).

When I do certain actions, like cut and pasting cells, a recalculation happens and I see "3" in cell A0. 

Here's the contents of my `~/.scimrc`:

```
set autocalc
```

What am I missing?

Version 0.7.0, compiled from source on Debian Wheezy from the `freeze` branch at commit `b16acc5fdb188a17cf74f798ec96abf2a59cece9`:

```
~/tmp/sc-im$ sc-im --version
Sc-im - version 0.7.0
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DUSELOCALE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/share/sc-im"
-DLIBDIR="/usr/local/share/doc/sc-im"
-DDFLT_PAGER="less"
-DHISTORY_FILE=".sc-iminfo"
-DINS_HISTORY_FILE=".sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by andmarti1424** [comment]
Please update to latest commit and try again. Thanks.
