### ISSUE TITLE
Financial formulas?

### ISSUE THREAD

**Issue by bruno-** [andmarti1424/sc-im#299]
Hi,
I love `sc-im`. Im currently learning finance basics (specifically "time value of money") and would absolutely prefer to use `sc-im` over the recommended MS Excel.

However, I'm browsing the docs and searching the project repo and it seems `sc-im` doesn't have financial formulas included? Some formulas I'd expect to find (MS Excel name in brackets): "future value" (FV), "interest rate" (RATE), "present value" (PV), "payment amount" (PMT). Internet search yielded nothing as well for scim.

Is doing financial formulas currently possible? Is there an external (Lua) library repo that has these functions defined? Any other suggestions?

I myself would love to get my fingers dirty in this but I neither know Lua, nor how to implement the above mentioned formulas.

**Comment by bruno-** [comment]
I found [finance formulas repo for Lua](https://sourceforge.net/projects/libfinancialmathematicsforlua/) on sourceforge, ugh. I'll try to make some of this work with `sc-im`

**Comment by andmarti1424** [comment]
Sorry for the delay @bruno-. those functions do not exist in sc-im. if you happen to develop it, please share the code and I'll add it to mainstream. Thanks!

**Comment by bruno-** [comment]
Thank you for the response. I never got to implementing those formulas in sc-im. Since I think this is not an actionable bug/problem (it's more like a big new feature) I'll close the issue.
