### ISSUE TITLE
Question: how to paste one cell to a range of cell ?

### ISSUE THREAD

**Issue by mbarakatt** [andmarti1424/sc-im#300]
Hi, 

I have been trying to find this for a while in the docs without success. It seems there's no shortcuts to copy the content of a cell and apply it to multiple cells. Is this wrong ? If so, is the information available in the docs and I just missed it ? Thank you!

**Comment by mikedorais** [comment]
I'm new to sc-im, but the closest command I found was :fill
For example fill the range E9:E16 with the value 3 just use 0 as the increment value:
:fill E9:E16 3 0

**Comment by nightsdark** [comment]
@mikedorais ,
I haven't used sc-im in a while but, just returning now. It was not effective for me to work on large documents quickly like in calc or ms-xcel sheets. But that was over a year ago. I do have more confidence this will work for me now. I found your comment and thought... gee that exactly what I was thinking. I keep trying to use motion keys like vim but, I see the dissimilarity of ^ top of sheet and gg begaining of sheet.

 Anyway I did need to know how to paste a row to multiple cells. So your comment helped me. And if you still use sc-im and figured out the patterns for copy and pasting stuff. I would like to hear about it. Thanks.

**Comment by andmarti1424** [comment]
Hello there.
This was already implemented. You can yank a cell. Select a range in visual_mode and paste it with p command.
(or P if you want  to keep references)..

There were also improvements on file loading @nightsdark. Please give it a try.
