### ISSUE TITLE
Question: ALT+ C is deleting previous character in insert mode despite my locale [0.7.0]

### ISSUE THREAD

**Issue by PanBartosz** [andmarti1424/sc-im#301]
Hello!
ALT + C in line editing should result in character "ć" (pl_PL.utf8) but in reality it deletes previous character (like backspace key).  I could not find a way to remap it. What can I do to fix it?

**Comment by andmarti1424** [comment]
Will try to check it out. Thanks

**Comment by andmarti1424** [comment]
Hello, @panbartosz could you please try it again? The mapping as well. Thanks.

**Comment by andmarti1424** [comment]
Unless I am mistaken, I believe ALT is not detected by ncurses

**Comment by andmarti1424** [comment]
@PanBartosz could you try the mapping? thanks.

**Comment by Bellavene** [comment]
Same on macos + iTerm

**Comment by andmarti1424** [comment]
Ncurses might not mind on your locale/alt

**Comment by Bellavene** [comment]
All other ncurses programs works fine...
