### ISSUE TITLE
Wrapping back when search for string (with '/') reaches the end

### ISSUE THREAD

**Issue by 1a7r0ch3** [andmarti1424/sc-im#302]
The help page documents the feature.

> Searches for either strings or numbers proceed forward from the current cell, wrapping back to a0 at the end of the table, and terminate at the current cell if the string or number is not found.

It works for numbers, but not with strings (version 0.7.0, I get the "string not found" message).

**Comment by 1a7r0ch3** [comment]
It seems to me that the back search issue #412 is more of a feature request, to be able to search in the other direction (towards the top of the document) rather than wrapping around. In vim, this is achieved by searching with `?` rather then `/`, and subsequent `n` searches _previous_ occurences while `N` searches _next_ ones.

**Comment by andmarti1424** [comment]
Yes. Indeed, but I will check it out.

**Comment by andmarti1424** [comment]
@1a7r0ch3, I have added backwards search with ? command. Please give it a try.
I am not sure about the wrapping back..

**Comment by 1a7r0ch3** [comment]
Hi, I am sorry but you successfully resolved issue #412, but in my opinion this current issue shoud be kept open. What puzzles me is that the wrapping back of the search is already working when searching for numbers, I see no reason why this could not work with the same mechanism for strings.

**Comment by andmarti1424** [comment]
@1a7r0ch3 you are right. did not recall that it wraps for number searches. I never really liked wrapped search, I prefer to go <C-a> and 'n' manually.. but that is just my personal taste.
