### ISSUE TITLE
Graphical glitches on NetBSD

### ISSUE THREAD

**Issue by sjmulder** [andmarti1424/sc-im#304]
**Steps**

1. Start sc-im.
3. Move the cursor around.

**Expected**

- A clean, empty work area is visible with rows and columns filling up the screen.
- When the cursor is moved, its old position is cleared.

**Actual**

- Seemingly random things sometimes appear in the working area, such as the text "\<Enter\>".
- Only the A column has its regular width; the B, C, D, E, F and G columns are visible but squished. When moving the cursor inside a column, its normal width is restored.
- When moving the cursor, the old position remains highlighted in addition to the new position.

![sc-im netbsd 1](https://user-images.githubusercontent.com/50692/49739786-03444d00-fc93-11e8-97ea-e20f2356167d.PNG)
![sc-im netbsd 2](https://user-images.githubusercontent.com/50692/49739787-03dce380-fc93-11e8-9871-ebaa5e07ceca.PNG)

**Environment**

- NetBSD 8.0
- PuTTY SSH session
- sc-im 0.7.0 or `freeze` (1ad3e155) built against:

```
sc-im:
        -lm.0 => /usr/lib/libm.so.0
        -lc.12 => /usr/lib/libc.so.12
        -lncursesw.6 => /usr/pkg/lib/libncursesw.so.6
        -lxml2.2 => /usr/pkg/lib/libxml2.so.2
        -lz.1 => /usr/lib/libz.so.1
        -llzma.2 => /usr/lib/liblzma.so.2
        -lpthread.1 => /usr/lib/libpthread.so.1
        -lzip.5 => /usr/pkg/lib/libzip.so.5
        -lbz2.1 => /usr/lib/libbz2.so.1
        -lssl.12 => /usr/lib/libssl.so.12
        -lcrypto.12 => /usr/lib/libcrypto.so.12
        -lcrypt.1 => /lib/libcrypt.so.1
        -llua5.1.5 => /usr/pkg/lib/liblua5.1.so.5
        -ledit.3 => /usr/lib/libedit.so.3
        -lterminfo.1 => /usr/lib/libterminfo.so.1
```

**Comment by andmarti1424** [comment]
I think I saw this long time ago when I test sc-im in netbsd. This seems a problem with ncurses.. May be building it manually with latest source code?

**Comment by sjmulder** [comment]
It's built (from source, using pkgsrc) from ncurses 6.1, which is the latest.

**Comment by andmarti1424** [comment]
Could be a terminal issue?

**Comment by sjmulder** [comment]
Tried some different terminals to check.

Works:
 - wscons, the built in virtual console (`TERM=wsvt25`)
 - wscons + tmux (`TERM=screen`)
 - xfce4-terminal + SSH + tmux (`TERM=screen`)

Glitches:
 - xfce4-terminal + SSH (`TERM=xterm-256color`)
 - PuTTY + SSH (`TERM=xterm-256color`)

The common thing here seems to be xterm-256color. Other curses behave well.

**Comment by andmarti1424** [comment]
This seems a terminal issue. I dont see anything I can do from stop happening.
Please update ncurses. It might change the behaviour.

**Comment by sjmulder** [comment]
It's just PuTTY. Other curses apps behave well. It's using system curses.

**Comment by sjmulder** [comment]
I've tried again with sc-im 0.8 on NetBSD 9 with PuTTY 0.74 (as well as a few other terminal) and the problem seems to have since been resolved :)

**Comment by andmarti1424** [comment]
@sjmulder Glad to hear!
