### ISSUE TITLE
Customizable Keyboard Shortcuts

### ISSUE THREAD

**Issue by stormdragon2976** [andmarti1424/sc-im#307]
I am part of a small team that is developing the world's most affordable
talking computer for the blind (https://public.f123.org/guide.html). Our
computer is based on the Raspberry Pi 3B Plus, and as you can imagine, we are
doing everything we can to select only the most efficient software, i.e.
mainly command line tools like nano, mutt, and now hopefully also SC-IM.
                                                                                                                                                                
Our main objectives are affordability, productivity/usefulness, and
simplicity. Affordability because the blind in developing countries are
statistically the poorest among the poor; productivity, because we do not want
to create a toy, but a device which opens-up opportunities for study and work
for people; and simplicity, because we are not trying to help advanced users,
who do not actually need any help for the most part, but normal non-technical
users.
                                                                                                                                                                
SC-IM is a wonderful project for us in terms of affordability and usefulness,
but we would like to request if it would be possible to allow users to
customize key bindings. Our average user will not be able to edit
configuration files to modify key bindings, but we can do that for them. We
want to setup our distro with pre-configured key bindings which make sc-im
behave in a way that is much more similar to GUI tools like LibreOffice Calc
and Excel.
                                                                                                                                                                
I understand that there are numerous differences which are not related to key
bindings, but have more to do with the way the interface was designed. This is
ok. We are not trying to have it all, we just want to be able to offer
something which is familiar enough for people to not get too lost or
discouraged. By improving a bit first-impressions, we believe that even
non-technical blind persons will appreciate the value of SC-IM for their
calculation needs.

**Comment by andmarti1424** [comment]
Hello. Soo sorry for the delay. We are adding better support for braille thanks to @npitre.
@stormdragon2976 havent you try adding mappings?
You now can also use mappings in visual mode..
How can be help to get better user experience?
