### ISSUE TITLE
fcopy - but copy across rows instead of columns

### ISSUE THREAD

**Issue by BlitzKraft** [andmarti1424/sc-im#312]
Is this possible? I am doing a comparison of various products. I need to perform same calculations across different columns in the same row. fcopy is useful for copying across rows, but not columns. Is there something I'm missing in the docs regarding this? 

I have a columns containing, say, length width and height of various items, separated in each row. I need to calculate the total volume in the fourth row across all the columns. The transpose of this would work perfectly with fcopy. But doesn't solve my use case entirely. 

Edit: Some clarfication

I have a sheet as follows:

```
Dim  Model1  Model2  Model3
len  100     200      300
wid  130     220      400
hgt  120     100      200
vol
```

I want to write the volume formula in one cell and drag/copy-paste it across all the columns in the same row.

**Comment by andmarti1424** [comment]
I see.. I believe you cannot do it. May be this function can be rewritted to copy in both directions..

**Comment by Nunu-Willump** [comment]
With my PR you could use `:fcopy r` to do this :p

**Comment by BlitzKraft** [comment]
Thanks for that @Nunu-Willump . I'll check it out.
