### ISSUE TITLE
Request: Minimal mouse support

### ISSUE THREAD

**Issue by polemon** [andmarti1424/sc-im#313]
Hi, when using Vim, I occasionally like to use my mouse to put the cursor to a specific location.

I was wondering if this would be also possible with sc-im. I can use my mouse wheel to scroll up and down within a column, this seems to be working out-of-the-box. But I'd like to click on a cell to highlight that one.
Perhaps also some lateral scrolling, so holding down ctrl or something to scroll left and right with the mouse wheel.

Just some minimal mouse support would be really nice.

**Comment by yamlCase** [comment]
clicking on a cell and putting in edit mode would really make this a killer app

**Comment by reportaman** [comment]
@andmarti1424 There is another fork of sc that has mouse enabled: https://github.com/n-t-roff/sc. Search ``set mouse`` on the page.

**Comment by andmarti1424** [comment]
Already done! Please check latest commit
