### ISSUE TITLE
Show part of column when column content exceeds column size

### ISSUE THREAD

**Issue by radostyle** [andmarti1424/sc-im#314]
When you enter text that is longer than a cell then it makes the whole cell just ******** rather than showing what it can.  See image.
![image](https://user-images.githubusercontent.com/151909/52688995-3d91cb00-2f1e-11e9-986d-ee67330502c9.png)

After using it I think it would be much preferable to just show what it can and cut off the rest - maybe have just one asterisk at the end to show that there is more.  Are there any reasons this can't be done - or am I missing some setting that allows this?

**Comment by andmarti1424** [comment]
This can be done of course. It was just a decision of the time it was made..

**Comment by andmarti1424** [comment]
To anyone interested in doing this.. Patches are welcome. Please use a configuration variable so we can keep the current behaviour. Thanks!

**Comment by coderkalyan** [comment]
Hi I have been working on implementing this, the only trouble I am having rn is how to read preferences... especially the `gram.c` file. Is there any documentation I can read on that?

**Comment by andmarti1424** [comment]
try this to get the values...
! atoi(get_conf_value("nocurses")))
sprintf(a_char_pnt_variable, "%s", get_conf_value("default_paste_from_clipboard_cmd"));

**Comment by coderkalyan** [comment]
So I created a config variable called "mask" and in conf.c `store_default_conf_values()` I used `put(user_conf_d, "mask", "1");' In the code for drawing I am wrapping the asterisk drawer in a `!atoi("mask")`. However, "mask" always seems to be set to zero, no matter what I put in `~/.scimrc` I believe it is not reading and storing the preference, which is what led me to `gram.c`. What should I do next?

**Comment by andmarti1424** [comment]
if you want to set 'mask' to 1 in .scimrc you should before


add it in the setitem list (line 1017 of gram.y)..
| K_MASK '=' NUMBER ...

and also define it as token in line 217 (aprox.) of gram.y

**Comment by earthshrink** [comment]
Looks like there's already an option `truncate` for this.

**Comment by andmarti1424** [comment]
Yes. This was added
