### ISSUE TITLE
Typing in a long text string to a cell causes error

### ISSUE THREAD

**Issue by radostyle** [andmarti1424/sc-im#32]
Type in a long text string to a cell

"<here is a very long text string that will crash the spreadsheet after you type this in it will crash"

and press enter

It errors out with:
Error !!! Quitting SC-IM.

**Comment by andmarti1424** [comment]
Thanks for reporting this. Indeed this make SC-IM crash!
Will check this deeper and upload the patch.

2015-08-26 3:30 GMT-03:00 Jon Alvarado <notifications@github.com>:

> Type in a long text string to a cell
>
> "<here is a very long text string that will crash the spreadsheet after
> you type this in it will crash"
>
> and press enter
>
> It errors out with:
> Error !!! Quitting SC-IM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/issues/32>.
>



-- 
Andrés Martinelli

**Comment by andmarti1424** [comment]
Fixed. Please report again if still find issues! Thanks!
