### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by Erikria** [andmarti1424/sc-im#323]
# Compilation Problems
Hello, @andmarti1424. I installed SC-IM successfully on my x86-64-Debian computer, and it works well. However, when I tried to compile it on Termux(an Aarch64 platform) with clang+bison+\*ncurses\*, errors occured like this:
## Error Messages:
```
-c -o cmds_visual.o cmds_visual.c In file included from cmds_visual.
c:407: /data/data/com.termux/files/usr/include/langinfo.h:105:1:
error: function definition is not allowed here{
                                              ^
/data/data/com.termux/files/usr/include/langinfo.h:178:1:
error: function definition is not allowed here{ 
                                              ^
cmds_visual.c:412:21:
warning: implicit declaration of function 'nl_langinfo' is invalid in
 C99 [-Wimplicit-function-declaration] f = nl_langinfo(D_FMT);
                                           ^
cmds_visual.c:412:19:
warning: incompatible integer to pointer conversion assigning to 'char *' from
'int' [-Wint-conversion] f = nl_langinfo(D_FMT);
                             ^ 
~~~~~~~~~~~~~~~~~~ 
2 warnings and 2 errors generated.
make: *** [: cmds_visual.o] Error 1
```
## PS:
In sum up, SC-IM is a perfect program. I am thankful to your work and help.

**Comment by mschilli87** [comment]
x-post: https://github.com/andmarti1424/sc-im/issues/322#issuecomment-474440186

**Comment by andmarti1424** [comment]
Please contact Termux devs.

**Comment by Erikria** [comment]
I found that the problem was caused by the lack of **"wordexp.h"**. SC-IM can be compiled correctly after I added **"CFLAGS += -DNO_WORDEXP"** into **"Makefile"**.
