### ISSUE TITLE
Save formatting & Adjusting Columns width [Question]

### ISSUE THREAD

**Issue by hubitor** [andmarti1424/sc-im#324]
I've just started using sc-im and I have some questions:

1. Is it somehow possible to preserve the formatting settings for .csv files? I mean things like: column width, numeric precision, cell alignment etc.
2. Is there a faster way for increasing/decreasing the column width? I've seen there is the command fh and fl for this but this is getting annoying when  it must be done several times. I was thinking something like fh and a number.

**Comment by andmarti1424** [comment]
Hello.
1. No. You can preserve content and export everything as text though. please check import_delimited_as_text config. variable.
2. :int format C 14 2 0
for instance.
hope that helps!

**Comment by alexandre-mbm** [comment]
> :int format C 14 2 0

@andmarti1424, where I can to read about this syntax?

**Comment by 1dancook** [comment]
@alexandre-mbm Look in the help file by typing `:help`+enter in sc-im. You can search with `\` and look up `:formatcol` as it uses the same as the `FORMAT` command that `:int` will take.

**Comment by sisrfeng** [comment]
I put  `int format C 14 2 0` in my sc-im/scimrc, but there will be "syntax error" when opening sc-im.  How to set it in the sc-im/scimrc?

**Comment by andmarti1424** [comment]
@sjmulder That syntax is indeed not valid.
Havent thought about setting format in scimrc file but try it without `int`

**Comment by sisrfeng** [comment]
In sc-im/scimrc:

I. they cause syntax error:
1.  format 'C 14 2 0'
2.  format "C 14 2 0"

II. Nothing happen:
format C 14 2 0

**Comment by andmarti1424** [comment]
like this `format C 14 2 0`
in your .config/sc-im/scimrc file.

**Comment by sisrfeng** [comment]
Nothing happen in sc-im  with this in  .config/sc-im/scimrc:
`format C 14 2 0`

**Comment by andmarti1424** [comment]
@sisrfeng it does for me. Please double check sc-im is reading your scimrc file properly

**Comment by sisrfeng** [comment]
lines before or after  `format C 14 2 0` are working, but `format C 14 2 0` not:
![image](https://user-images.githubusercontent.com/53520949/204178340-e2fe8ec1-bb32-4cc2-94a7-43680644c816.png)



![image](https://user-images.githubusercontent.com/53520949/204178217-2e33faa0-bc2f-4c49-abae-5d817b272add.png)
