### ISSUE TITLE
is visual mode re/maping implemented?

### ISSUE THREAD

**Issue by wis** [andmarti1424/sc-im#326]
I was delighted to know that normal mode re/maping is implemented, but confused to realize that it's not, for visual mode.
here's my .scimrc, everything was working great until I tried visual mode mapping.
``` .vimrc
nunmap "h"
nunmap "j"
nunmap "k"
nunmap "l"

nnoremap "n" "h"
nnoremap "e" "j"
nnoremap "i" "k"
nnoremap "o" "l"
nnoremap "t" "e"
```
I use the colemak keyboard layout and found a great logical mnemonic vim key mappings for it.

**Comment by mvrozanti** [comment]
I wanted to integrate the clipboard with my system's but the lack of `v.*map`pings  makes it impossible

**Comment by andmarti1424** [comment]
Sorry for the long delay on answering. Will check this out.

**Comment by andmarti1424** [comment]
Already merged!!
