### ISSUE TITLE
Using sc-im to create invoices

### ISSUE THREAD

**Issue by insanerwayner** [andmarti1424/sc-im#327]
I've been tracking my hours and labor for a company I've been doing work for in sc-im. Looking for a good way to print this in a legible format.  

I thought maybe exporting it to CSV then to PDF would be simple but I'm not seeing a good way to align the columns when there is empty data in some cells.  

Anyone out there have a workflow for invoicing they like?

**Comment by ekaitz-zarraga** [comment]
I use `pandoc` for this kind of things that lets me use latex templates and so on.

**Comment by earthshrink** [comment]
PR #360 might address this.

**Comment by mipmip** [comment]
You could use the a script that exports to markdown and then use pandoc to convert to PDF.

Since #383 is merged you can create a script like this to convert from one format to another:
```
EXECUTE "load 2010_dos.csv"
EXECUTE "e! mkd out.md"
QUIT

```
(Newline is mandatory)

And then execute:
```
cat script | sc-im --nocurses
```

**Comment by andmarti1424** [comment]
Thanks!
