### ISSUE TITLE
Support for OpenDocument Spreadsheet (ODS) files

### ISSUE THREAD

**Issue by Terr** [andmarti1424/sc-im#328]
I think it would be useful if SC-IM, next to opening XLS(X) files, would also support OpenOffice/LibreOffice Calc's ODS files.

(I don't think this idea was raised before because I couldn't find any reference to it, though I doubt I'm the first one to have it. My apologies if it was discussed and rejected before

**Comment by Nunu-Willump** [comment]
There actually is already an issue with this idea: #185. I've looked into implementing this myself some time ago, but sadly ODS is such a complicated file format that there seems to be no complete C library for dealing with it; I tried creating my own and it is easy to do simple stuff like getting the values from the spreadsheet, but when you get to other parts like e.g. implementing all the functions support by LibreOffice (which there are a lot of), it becomes too much work, at least for me :(

**Comment by Terr** [comment]
I wasn't aware ODS was such a complicated, let alone that there is no good C implementation for it. 

I will close this issue because it's duplicate. I have no idea why I didn't find that other issue. Sorry :)

**Comment by andmarti1424** [comment]
Anyone know an ods library for C?
