### ISSUE TITLE
securely evaluate a string as function

### ISSUE THREAD

**Issue by c-nv-s** [andmarti1424/sc-im#329]
I'm working on a project using sc-im and i'm looking for an existing solution to this (ideally without having to call @ext function), otherwise kindly submitting it as a feature request.

Example:
If A0 has value 1, and B0 has value 2 and C0 has the string '@sum(A0:B0)'
would like to be able to put in D0 =@evaluate(C0) which should return the value 3

There was an old excel feature which performed this exact behavior see below

[https://superuser.com/questions/253353/excel-function-that-evaluates-a-string-as-if-it-were-a-formula](https://superuser.com/questions/253353/excel-function-that-evaluates-a-string-as-if-it-were-a-formula)  

and:
[https://forum.openoffice.org/en/forum/viewtopic.php?f=9&t=3497](https://forum.openoffice.org/en/forum/viewtopic.php?f=9&t=3497)

and also:
[https://www.myonlinetraininghub.com/excel-factor-12-secret-evaluate-function](https://www.myonlinetraininghub.com/excel-factor-12-secret-evaluate-function)

**Comment by c-nv-s** [comment]
@wimstockman I saw you mention you might work on a feature to pass contents of a worksheet to an external command and back into the worksheet. Is that not what @ext function does already? Or did you mean something similar to what I described in this old feature request but with the string in the cell being the including the actual external command too?

**Comment by wimstockman** [comment]
Hi, thanks for mentioning this.
The function @ext sends data to a script and the result gets back to one cell. Hence it's a formula.
I wrote the command :!r {cmd}which reads data from a script into multiple cells like the cpaste command works
and I'm currently working on a :!rw {inrange} {cmd} {outrange} command which can read a range of data and paste it to an external script and reads back the data into the sheet into multiple cells
But the feature you request is possible to make. 
I will look at it in the weekend. Would you consider contributing code for it. or is this just a feature request ?

**Comment by c-nv-s** [comment]
> Hi, thanks for mentioning this.
> The function @ext sends data to a script and the result gets back to one cell. Hence it's a formula.
> I wrote the command :!r {cmd}which reads data from a script into multiple cells like the cpaste command works
> and I'm currently working on a :!rw {inrange} {cmd} {outrange} command which can read a range of data and paste it to an external script and reads back the data into the sheet into multiple cells
> But the feature you request is possible to make.
> I will look at it in the weekend. Would you consider contributing code for it. or is this just a feature request ?

That makes sense, thanks for the explanation. Both !r and !rw are very useful features. If you could look at my old feature request that would be amazing. I am not able to contribute any code but it would help me out immensely

**Comment by andmarti1424** [comment]
@c-nv-s hello. After a few hours, I have done this. Still I am unsure to merge it, cause.. for instance, in your example when you change A0 it wont change D0. Cause D0 has a dependency on C0, which is just a string.
But C0 has no dependency on A0 or B0.. its not that useful

**Comment by c-nv-s** [comment]
> @c-nv-s hello. After a few hours, I have done this. Still I am unsure to merge it, cause.. for instance, in your example when you change A0 it wont change D0. Cause D0 has a dependency on C0, which is just a string.
> But C0 has no dependency on A0 or B0.. its not that useful

Thanks for this!
It should be reasonable to expect that the value in D0 does not dynamically update. It is calculated on opening the file or running via a script, any subsequent changes to values in A0 or B0 would require a page recalculation or rerun of the script.

In terms of usefulness i would say that for scripting it is actually phenomenal, and for visual editing it can be really useful in terms of organisation for some people though I would agree that a quick page recalculate keyboard shortcut would complement it nicely.

**Comment by andmarti1424** [comment]
@c-nv-s you would still be able to use `@` for manual recalculations.

**Comment by c-nv-s** [comment]
> @c-nv-s you would still be able to use `@` for manual recalculations.

Oh awesome, well that does make it easier then

**Comment by c-nv-s** [comment]
I was also curious of if this feature would still work if you decided in future to implement "worksheets"? Could it still e.g. add one cell from worksheet A with another cell from worksheet B?

**Comment by andmarti1424** [comment]
Yes. The benefit of having multiple sheets is to be able to reference cells from other sheets. This would also work, as this is a formula just as `@sum` `@avg` etc

**Comment by andmarti1424** [comment]
@c-nv-s This was merged on lua branch. Coming to freeze branch in a couple of days.

**Comment by c-nv-s** [comment]
thanks soooooo much!
