### ISSUE TITLE
Opening csv via the command line gives unhelpful error message

### ISSUE THREAD

**Issue by JoopClaireIT** [andmarti1424/sc-im#33]
running `sc-im nameofthe.csv` tries to use the csv as a sc formatted file.
expected would be either an error message on how to correctly open CSV files, or detecting on extension which way to open it.

**Comment by andmarti1424** [comment]
Indeed the correct behaviour would be to start SC-IM and import the csv file.
And this is the result I am getting!! Which branch/version did you build?

**Comment by JoopClaireIT** [comment]
master

Op ma 31 aug. 2015 om 15:04 schreef Andrés M. <notifications@github.com>:

> Indeed the correct behaviour would be to start SC-IM and import the csv
> file.
> And this is the result I am getting!! Which branch/version did you build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/issues/33#issuecomment-136364911>.
>
-- 
Met vriendelijke groet,
Joop Kiefte

Claire Automotive Support - Boekdrukker 1 - 3861SE - NIJKERK
Tel 085 0020 211 - www.claireit.nl

**Comment by JoopClaireIT** [comment]
make install doesn't solve this...

**Comment by JoopClaireIT** [comment]
Ah, when doing :i csv name of this file, I get the same error message, so it's a problem when parsing the csv... Will send you the csv privately.

**Comment by andmarti1424** [comment]
OK. Please send the csv file and Ill check it out.

**Comment by JoopClaireIT** [comment]
I sent the csv to scim.spreadsheet@gmail.com some time ago already :)

**Comment by andmarti1424** [comment]
Working on this.

**Comment by andmarti1424** [comment]
Solved. Please report again if still find issues! Thanks!
