### ISSUE TITLE
Black screens and missing rows

### ISSUE THREAD

**Issue by tbrodbeck** [andmarti1424/sc-im#330]
I just tried out sc-im for the first time. It looks really beautiful when opening a new document but when I try to open one of my big datasets (csv) I have to use for work, it just gives me a black screen. When I press ctrl-C then tells me `Got SIGINT. Press «:q<Enter>» to quit SC-IM` but q and Enter wont do anything and I have to kill my terminal window. 
For another file that has 20 rows, it only shows the first for some reason. I will attach the file here:
[xTrain.csv.zip](https://github.com/andmarti1424/sc-im/files/3144288/xTrain.csv.zip)

`➜  ~ inxi -F
System:    Host: tBook Kernel: 4.19.36-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma ERR-101 Distro: Manjaro Linux 
Machine:   Type: Laptop System: Apple product: MacBookPro10,2 v: 1.0 serial: <root required> 
           Mobo: Apple model: Mac-AFD8A9D944EA4843 v: MacBookPro10,2 serial: <root required> UEFI: Apple v: 274.0.0.0.0 
           date: 09/17/2018 
Battery:   ID-1: BAT0 charge: 68.9 Wh condition: 69.0/73.9 Wh (93%) 
CPU:       Topology: Dual Core model: Intel Core i5-3210M bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 2894 MHz min/max: 1200/3100 MHz Core speeds (MHz): 1: 2894 2: 3078 3: 2893 4: 3010 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.4 driver: intel resolution: 1680x1050~60Hz, 1280x1024~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile v: 4.2 Mesa 19.0.3 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k4.19.36-1-MANJARO 
Network:   Device-1: Broadcom and subsidiaries NetXtreme BCM57786 Gigabit Ethernet PCIe driver: N/A 
           Device-2: Broadcom and subsidiaries BCM4331 802.11a/b/g/n driver: bcma-pci-bridge 
           IF-ID-1: wlp3s0b1 state: up mac: 20:c9:d0:7b:39:41 
Drives:    Local Storage: total: 113.00 GiB used: 51.28 GiB (45.4%) 
           ID-1: /dev/sda vendor: Apple model: SSD SM128E size: 113.00 GiB 
Partition: ID-1: / size: 101.77 GiB used: 50.83 GiB (49.9%) fs: ext4 dev: /dev/sda2 
           ID-2: swap-1 size: 8.80 GiB used: 459.6 MiB (5.1%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 75.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 225 Uptime: 16h 26m Memory: 7.67 GiB used: 5.31 GiB (69.3%) Shell: zsh inxi: 3.0.33 
` (i dont know how to fix the formating, sorry)

**Comment by andmarti1424** [comment]
Please give it a try again.  This was muuuch improved on  v0.8.
You can also send us your file. I always keep big files for testing.
Thanks.

**Comment by tbrodbeck** [comment]
Hi. I gave it another shot, but it still ist not seaming to work for me. Somehow 'sc-im' gets stuck on pressing `i` for insert mode all the time and it is not reacting anymore (untill I switch the focus away from the terminal and back).

I am using macOS now btw and I installed it with brew.

**Comment by andmarti1424** [comment]
@tbrodbeck You dont enter insert mode with the 'i'.
You enter insert mode with = or < > \, just like in sc.
