### ISSUE TITLE
ntos?

### ISSUE THREAD

**Issue by eric-b-hymowitz** [andmarti1424/sc-im#332]
Greetings.

I see the "ston" function which turns a string into a number.  Is there an opposite function that turns a number into a string?

Picture a spreadsheet with three cells that each contain a number, let's say A0 = 2019 and A1 = 5 and A2 = 12 .  I'm trying to create a string that looks like "2009-5-12"  But I can't find any "string functions" that take a number and build a string out of it.

Am I just missing it?

**Comment by andmarti1424** [comment]
Did you try @fmt function?

**Comment by andmarti1424** [comment]
@eric-b-hymowitz ?

**Comment by eric-b-hymowitz** [comment]
I don't see any @fmt function.

**Comment by andmarti1424** [comment]
I added to the doc a couple of days ago. It was already there but not in the doc file.
![image](https://user-images.githubusercontent.com/9466161/112523014-0b99f680-8d7d-11eb-97d7-13207f11f823.png)
which version are you using?

**Comment by eric-b-hymowitz** [comment]
I've been using version 0.7.0 .  I just updated a few minutes ago to version 0.8.0 , but it looks like the colors and nmap have all changed. :(

Now I see the @fmt command in the 0.8.0 help.  But it doesn't seem to be working.  With 2019 in A0, I tried setting B0 to

\"@fmt("%06d",a0)

I get 000000 as the result.  When I tried

\"@fmt("%06d",2019)

I get "Illegal numeric expression"

**Comment by andmarti1424** [comment]
You must enter `@fmt("06g",A0`
And enter it as string function like this `\"`

**Comment by andmarti1424** [comment]
What do you mean with nmap and colors?

**Comment by eric-b-hymowitz** [comment]
Regarding nmap and colors, my .scimrc file isn't being processed.  I opened a separate issue.

**Comment by eric-b-hymowitz** [comment]
Apparently, I need to use `%g` instead of `%d` , but I think I got it now.  Thanks.

**Comment by andmarti1424** [comment]
Great!
