### ISSUE TITLE
FR: Keep formulas on save instead of their result

### ISSUE THREAD

**Issue by sarpik** [andmarti1424/sc-im#333]
Hello, is there a way to have the formula get saved instead of just being replaced by it's result?

Also, whenever a formula is entered incorrectly, it gets reset. Could there be a way to just save it instead of re-setting it?

Thank you!

Also, I'm aware of the
```console
LUA Scripts and Triggers
     SC-IM was extended with LUA capabilities and also provided with helper
     Function for manipulate SC-IM data with Lua at runtime. Since it is a
     fully functional Lua, you can use all Lua packages also for sc-im lua
     scripts. Use luarocks to install additional packages.

...
sc.lsetform (c, r, str) - set formula to a cell. Basically it does "let cell= str"
```

but I have no clue on how to implement this.

**Comment by holalluis** [comment]
If you save the file as "filename.sc" the formulas get saved. If you save the file as "filename.csv" then, not.

**Comment by sarpik** [comment]
Amazing. Will try it out soon - thank you!:)

2019-05-13, pr 05:23, Lluís Bosch <notifications@github.com> rašė:
