### ISSUE TITLE
Build fails on SmartOS with various errors

### ISSUE THREAD

**Issue by sjmulder** [andmarti1424/sc-im#334]
Various errors, see:

 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk32/20190604.2010/sc-im-0.7.0nb2/build.log
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk32/20190610.2010/sc-im-0.7.0nb3/build.log
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk64/20190611.0210/sc-im-0.7.0nb3/build.log

I'm intent of chipping away at some of these once I get SmartOS set up.

**Comment by andmarti1424** [comment]
Sorry. I see no error that give a clue. This must be something with the OS itself. Could you please report this to SmartOS devs?

**Comment by sjmulder** [comment]
The original logs are gone, they had very concrete errors. I'll recheck to see if there are any recent logs.

**Comment by andmarti1424** [comment]
Ok. Please share them if you find them

**Comment by sjmulder** [comment]
Looks like recent builds have been successful, I think https://github.com/andmarti1424/sc-im/pull/370 may have fixed it.
