### ISSUE TITLE
Is it possible to make sc-im interpret a cell as a string instead of a number? If it's an integer, it always right-aligns content, and you can't change alignment.

### ISSUE THREAD

**Issue by alrasch** [andmarti1424/sc-im#335]

**Comment by alrasch** [comment]
Upon further inspection, it looks like a cell has a numberic value AND a string value.

Essentially, what I want to do is send a cell's numberic value to its string value instead.

**Comment by andmarti1424** [comment]
if you enter as text using \ for instance?

**Comment by earthshrink** [comment]
This is related to #368 and something I've been looking for too. Not sure if `sc-im` really needs to display both label (string) and value (number or date) in the same UI cell - they end up overlapping. I wonder if this was a data representation choice. If so, it should be easy to unify the alignment.

**Comment by andmarti1424** [comment]
This comes from the old sc.. So I decided to leave it like that..

**Comment by andmarti1424** [comment]
Numbers align to right. As I said earlier this comes from old sc.
I too think text and numbers shouldnt be need to be shown in a same cell. But my idea is not to change that and keep it as stock.
Hopefully in v2 of sc-im with its new core, that would be changed.
Please feel free to open a discussion about the change in alignment of numbers..
Thanks
