### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by durableoreo** [andmarti1424/sc-im#340]
Many undefined constants (LINES, COLS) and functions/macros (wmove, noecho, etc).  

Using code from latest freeze (Latest commit 9beb5c0  on Feb 22).  I just clicked on the Clone/Download button, edited the make file, installed ncurses and bison, and tried to compile.  Maybe a user error but it feels like something is missing.

**Comment by andmarti1424** [comment]
Seems you are not linking against ncurses. Those are ncurses defines.
If the build fails saying those constants are undefined, you are certainly not linking to ncurses properly.
