### ISSUE TITLE
Pasting text in a range of cells and vim-like macros

### ISSUE THREAD

**Issue by hinojojojo** [andmarti1424/sc-im#341]
Hi
I have found no way to copy the text of one cell and paste it to a range of cells. While this can be done with the :fcopy and :fill for formulas and numbers, I have found no way to do it with text. One way could be doing it manually, yanking and pasting on each cell, but it becomes tedious when there is tons of places to paste.

Another way of kind of solving this would be to have a macros as in vim (https://vim.fandom.com/wiki/Macros), where you can record a combination of movements and commands and just execute them the number of times you want. I have found myself doing a lot of repetitive stuff in spreadsheets, which could be done very fast if there could be a way of doing vim-like macros. Pasting in a range of cells could also be done this way.

**Comment by dev-harish** [comment]
Even I am looking for this function.
U can use the dot operator for repeating the previous command. The paste also works with the dot operator.

**Comment by andmarti1424** [comment]
This was already merged. See this: 438
