### ISSUE TITLE
Use math library for math operations

### ISSUE THREAD

**Issue by zvezdochiot** [andmarti1424/sc-im#342]
Use https://github.com/mnhrdt/ccmath for math operations?

**Comment by andmarti1424** [comment]
@zvezdochiot For what operations?
Some say "If it's working, then don't touch it".

**Comment by zvezdochiot** [comment]
Hi @andmarti1424 .

Looked through the head files. Yes, now it will be extremely difficult to use a separate math library. Although this suggests itself. But everyone chooses a "special" path.
