### ISSUE TITLE
[conda] sc-im: error while loading shared libraries: libzip.so.4

### ISSUE THREAD

**Issue by Hoeze** [andmarti1424/sc-im#346]
Hi, would it be possible to have a CI version of this in conda-forge?

I tried already https://anaconda.org/lebedov/sc-im, but 1) I do not like personal channels and 2) it does not work.

**Comment by andmarti1424** [comment]
I really dont know what conda-forge is. A GNU/Linux distribution?
If you got ther libzip error just disable xlsx support

**Comment by Hoeze** [comment]
@andmarti1424 Anaconda is a cross-platform / cross-distro package manager: https://anaconda.org/
Its only dependency is a functional glibc. It is very popular in e.g. data science applications as it resolves dependencies of all installed programs to find a working set of dependencies, in contrast to distro package managers that simply install the newest available package version.

conda-forge is a community-driven Anaconda package channel:
https://conda-forge.org/

**Comment by andmarti1424** [comment]
I see. I believe this should be prompted to that project. They might need a package maintainer for sc-im.
