### ISSUE TITLE
Help doesn't open

### ISSUE THREAD

**Issue by JoopClaireIT** [andmarti1424/sc-im#35]
After building from source, typing :help gives the error Cannot open help file
![screenshot 2015-08-31 at 13 40 35](https://cloud.githubusercontent.com/assets/13216791/9577933/ffe82fee-4fe5-11e5-8c81-b4d567f16860.png)

**Comment by andmarti1424** [comment]
This is weird. Did you run make install? Do you have the file named "doc" where the sc-im binary is??

**Comment by JoopClaireIT** [comment]
probably missed the make install there :)

Op ma 31 aug. 2015 om 14:47 schreef Andrés M. <notifications@github.com>:

> This is weird. Did you run make install? Do you have the file named "doc"
> where the sc-im binary is??
>
> —
> Reply to this email directly or view it on GitHub.
>
-- 
Met vriendelijke groet,
Joop Kiefte

Claire Automotive Support - Boekdrukker 1 - 3861SE - NIJKERK
Tel 085 0020 211 - www.claireit.nl

**Comment by JoopClaireIT** [comment]
make install solved this issue, maybe improve your build instructions ;)

**Comment by andmarti1424** [comment]
With latest dev branch commit, help now should open without need of 'make install'.
