### ISSUE TITLE
Set default format for control-d

### ISSUE THREAD

**Issue by hymie0** [andmarti1424/sc-im#350]
The documentation says

>     The :datefmt command takes the cell's text content that represents a date,
>     and uses a given format to set the numeric value of the cell.
>     Its format is ':datefmt "{strftime_format}"', taking a strftime-compatible
>     format string.  The format is applied to the cell (as could be done with
>     the :format function) so that the value is displayed as a date.
> 
>     Example:      :datefmt "%d/%m/%Y"
> 
>     The c-d command, used in Normal and Visual modes, acts as the :datefmt
>     described above, but uses the locale's D_FMT format.
> 

How do I determine my locale's D_FMT format?

Please allow me to set my own default value for the c-d function.

**Comment by andmarti1424** [comment]
I dont think I can do that since its related to langinfo. Can you change format using datefmt command?

**Comment by andmarti1424** [comment]
locale -k LC_TIME

**Comment by andmarti1424** [comment]
You can create a mapping in normal mode to use a control key and write a :format command..

**Comment by andmarti1424** [comment]
Hello. Did you manage to try it? Just let me know if you have any problems..
