### ISSUE TITLE
Could not plot

### ISSUE THREAD

**Issue by ayroblu** [andmarti1424/sc-im#352]
I tried to run the `:plot line` function but I just get this: 
`could not load default plotline file`

I'm not sure what to do. I tried making a directory called `~/.scim` then tried adding a file called `plotline` but this didn't help, then added a cheeky `plot sin(x)` and still nothing, so I'm not sure if I need content or something? I tried `gnuplot`, `set terminal dumb` then `plot sin(x)` and that all seems to work so not sure what to do

**Comment by ayroblu** [comment]
As a follow up, I read some of the source code, looks like the filename needs to be `~/.scim/plot_line`
Then you need to define the whole gnuplot definition (i.e. if you have column headings, its a different config, multiple columns to plot for multiple lines, it's a different config). I guess this is where someone might want to pipe the output to matplotlib or something, though I guess there's not really a way to do that right now

**Comment by andmarti1424** [comment]
plot_line is part of scim.. dont you have it in
 ~/.scim/ or /usr/local/share/scim/?

**Comment by Iron-E** [comment]
I can't plot either, but with a different error message as of a recent build:

```log
"/usr/local/share/sc-im/plot_line" line 7: warning: Skipping data file with no valid points

plot filename
             ^
"/usr/local/share/sc-im/plot_line" line 7: x range is invalid
```

**Comment by andmarti1424** [comment]
Does the plot_line.sc example work for you?

**Comment by Iron-E** [comment]
[This one](https://github.com/andmarti1424/sc-im/blob/freeze/examples/plot/plot_line.sc)? I get the same error from `:plot line` from that one too.

**Comment by andmarti1424** [comment]
Please check you have gnuplot installed then..

**Comment by Iron-E** [comment]
This is the output of my terminal when I run `gnuplot`:

![screen-cap](https://user-images.githubusercontent.com/36409591/92636287-1be8f900-f2a5-11ea-9f82-9119567a5c2c.png)

**Comment by andmarti1424** [comment]
Well sc-im only passes the data to gnuplot like this:
gnuplot -e "filename='../examples/plot/plot_line.csv'" plot_line

I have same version of gnuplot as you.
If that command doest not work for you, you might not have it well configured or something, but its a gnuplot thing. Cant help there.

**Comment by Iron-E** [comment]
When I run `gnuplot -e "filename='../examples/plot/plot_line.sc'" plot_line` from the `src/` folder, I get the following message:

```log
plot filename
     ^
"plot_line" line 7: Bad data on line 5 of file ../examples/plot/plot_line.sc
```

I noticed, that you had a `csv` rather than an `sc` file— is that pertinent here? I didn't have any `csv`s in my `example/` folder.

**Comment by andmarti1424** [comment]
No. In the command (filename parameter) you have to specify a csv file. Convert the plot_line from sc format to csv format. You can use sc-im or your favorite tool for this..

**Comment by Iron-E** [comment]
That would explain it. Thanks!

**Comment by andmarti1424** [comment]
Could you finally managed to plot?

**Comment by Iron-E** [comment]
Yes, I just didn't know that I needed to use a `csv` file. Sorry for the late response and/or ambiguous comment!

**Comment by andmarti1424** [comment]
Great!
