### ISSUE TITLE
Convert script to csv on command line

### ISSUE THREAD

**Issue by tobiasbrummer** [andmarti1424/sc-im#359]
Hi,

I want to use sc-im for creating invoices. I want to generate a .sc file and convert it to a csv automatically, great would be if it could be piped. Is this possible? I tried with the --output flag but that didn't work. When exporting in sc-im it works and I can use the generated file. But I don't know how to automate this.

Thanks in advance.

**Comment by mipmip** [comment]
Since #383 is merged you can create a script like this to convert from one format to another:
```
EXECUTE "load 2010_dos.csv"
EXECUTE "w! str.sc"
QUIT

```
(Newline is mandatory)

And then execute:
```
cat script | sc-im --nocurses
```

**Comment by mipmip** [comment]
I think this issue can be closed.

**Comment by andmarti1424** [comment]
Thanks

**Comment by bl0x** [comment]
FWIW, I've found that this works well for me:

`sc-im --nocurses --export_csv --quit_afterload input.sc > output.csv`

Adding the option `--output=output.csv` works as well
Adding the option `--output` without a value produces a file named `1`.
Using the `--output=output.csv` option without the redirect to file just prints to stdout and creates an empty file named `output.csv`.
Leaving out the `--nocurses` option produces a file with the exported content, but also a preamble of binary (presumably curses control chars?)
Leaving out the `--quit_afterload` option keeps the editor open.
