### ISSUE TITLE
How can I format as currency?

### ISSUE THREAD

**Issue by habreu71** [andmarti1424/sc-im#361]
Hi there,

I'm currently formatting currency the old way, like I used to do in sc. For example:

:format "USD\. 0.00"
:format "€\ 0.00"

Apparently it's working in sc-im but I just want to confirm this is the way users are formatting currencies, since I can't see any reference to currencies in the :help documentation.

Thank you in advance for any info.

**Comment by andmarti1424** [comment]
it seems that is the correct way to go. found a little bug in the ui when you use the € symbol. its not selecting correctly when you position over the cell that contains it. you found that as well?

**Comment by habreu71** [comment]
> it seems that is the correct way to go. found a little bug in the ui when you use the € symbol. its not selecting correctly when you position over the cell that contains it. you found that as well?

Thank you for your comment.

I don't see any bug from this end, both format examples (USD and €) are displayed correctly when selected or not selected. I'm not sure if that's exactly what you describe.
