### ISSUE TITLE
Exporting Formulas in csv file

### ISSUE THREAD

**Issue by nihilazo** [andmarti1424/sc-im#362]
Hello, is there a way to export a csv from sc-im with formulas intact? If there is not I'd like to make a request for this feature. I know sc-im formulas beyond the basics wouldn't load in other spreadsheet software, however it's more of a starting point than just getting the numbers.

**Comment by maxfl** [comment]
It also would be useful to use terminal text editor sometimes to edit the exported file and then reload it back to sc-im.

**Comment by 1a7r0ch3** [comment]
By very definition, CSV just consists in values, separated by commas. So allowing formulas (instead of plain values) in a CSV would just not make it a CSV but some other format you seem to try to invent.

**Comment by nihilazo** [comment]
no, it's still a csv, just that some of the values contain formulas. Other spreadsheet packages can do this.

**Comment by 1a7r0ch3** [comment]
I guess other spreadsheet softwares can do all sorts of things. What I am trying to say is that wanting formulas to be taken into account in a format that is as vaguely defined as CSV needs at least some more specifications. I mean, I am pretty sure that formulas themselves are not described the same way from one spreadsheet format to another. Which one should be used then?

**Comment by alexandre-mbm** [comment]
SC-IM is a small project that is being choked!

See this: https://github.com/andmarti1424/sc-im/issues/348#issuecomment-734440592

**Comment by andmarti1424** [comment]
Yes. Please open a discussion for this.
