### ISSUE TITLE
Cannot save or create files on sc-im termux

### ISSUE THREAD

**Issue by rmc1961** [andmarti1424/sc-im#364]
sc-im on termux  (android 8.1.0)
When trying to save a file with :w or :x, the word "Trap" prints and sc-im quits to prompt.
This happens when both trying to create a file on running (like "scim test.cs") and when supplying a filename  with :w
Hardware is Samsung Tab4 
Thanks in Advance

**Comment by Symbian9** [comment]
> Fixed in `0.7.0-5`.

- https://github.com/termux/termux-packages/commit/0e74b0f25542b3375e9eaadbb8ae5dfb24439b4b

**Comment by alexandre-mbm** [comment]
It don't happen on Android 5.1. Certainly it is fixed. **Close the issue please.**
