### ISSUE TITLE
Default column size

### ISSUE THREAD

**Issue by fn-ix** [andmarti1424/sc-im#365]
Hello!

I was going through the documentation, but couldn't find any reference to how to set the default column width, or even to change the widths of columns in bulk (in `sc`, it was possible to do the latter by preceding the __f__ command with a numeric argument; in sc-im the same operation applies the numeric argument to the width delta of the selected column only). It's a rather simple issue, so apologies if I just managed to overlook something.

**Comment by ilya-bystrov** [comment]
Same for me, didn't find the way of doing it

**Comment by andmarti1424** [comment]
hello.
fh and fl in  normal mode.. ?

**Comment by andmarti1424** [comment]
you might enter something like this as well:
:int format C 14 2 0

**Comment by andmarti1424** [comment]
I leave this opened until proper :format command handle a column.. (hopefully for v0.9)

**Comment by andmarti1424** [comment]
@fn-ix @ilya-bystrov I have added proper :formatcol command for this.
It acts over selected column or range of columns.
Please update to latest commit on "new" branch to test it. Thanks.
