### ISSUE TITLE
Engineering Format

### ISSUE THREAD

**Issue by taylor1791** [andmarti1424/sc-im#366]
Is it possible to use engineering format on a cell in sc-im?

Based on my read of the code, it is not possible to format a column or cell in engineering format like in `sc`. I see the function is still located in `src/format.c`.

Are there plans to re-add this at some point?

**Comment by earthshrink** [comment]
I have been wanting it too. thanks.

**Comment by earthshrink** [comment]
I just submitted PR #395 implementing this.

**Comment by andmarti1424** [comment]
Merged. Thanks!
