### ISSUE TITLE
Cannot align numbers

### ISSUE THREAD

**Issue by Newexplorer** [andmarti1424/sc-im#368]
I am able to align text within a cell with: { } or |.
But I cannot align numbers.

**Comment by alexandre-mbm** [comment]
I understood from https://github.com/andmarti1424/sc-im/issues/335#issuecomment-613710417 that this behavior is inhereted from sc and that it will not changed.

Hint: to close the two issues.

**Comment by andmarti1424** [comment]
Yes, you are right. If you want to align numbers you have to convert them to text.
