### ISSUE TITLE
Previous item in search

### ISSUE THREAD

**Issue by reckbo** [andmarti1424/sc-im#37]
When searching in vim you use 'n' to go to the next match and 'N' to the previous match.  'n' works in
sc-im but not 'N'.   May I suggest this as a feature?

**Comment by andmarti1424** [comment]
Hello. Do you mean moving throw results of a search done with  " / " command?

**Comment by Phrohdoh** [comment]
@andmarti1424 Yes that is what is being requested here.

**Comment by andmarti1424** [comment]
I am working on this. Thanks.

**Comment by andmarti1424** [comment]
Please update to latest dev branch commit and try this out! Thanks.

**Comment by andmarti1424** [comment]
Hello. Could you test this?

**Comment by reckbo** [comment]
This works for me -- thanks!
