### ISSUE TITLE
Segmentation fault on nested functions.

### ISSUE THREAD

**Issue by dikeert** [andmarti1424/sc-im#371]
I don't know how to explain what I'm trying to do, I think the best was to explain it is with SQL query.

So I'm trying to do something like that: `select name, sum(amount) from table1 where name is in table2`.

So I go into a cell and add this function: `@sum(H2:I7, @vlookup(Q2:R30, H2, 1)=@vlookup(Q2:R30, D6, 1))`.

Q2:R30 is a range where first column is a name, second column is a numerical id.

H2:I7 is a range of name -> amount pairs, where single name can appear in multiple rows.

D6 contains the name I want the total amount for.

It segfaults on that expression.

Here is the file: https://pastebin.com/BktHzQfV

Just try to add that function above into any cell and it'll segfault. I don't think I have any circular deps here.

**Comment by dikeert** [comment]
I just realised that what I'm trying to do looks like what `:subtotal` does but dynamic.

**Comment by andmarti1424** [comment]
this is the expression that segfaults to you:
@sum(H2:I7, @vlookup(Q2:R30, H2, 1)=@vlookup(Q2:R30, D6, 1)).
?
if so, where are you entering it? thanks

**Comment by andmarti1424** [comment]
@dikeert Please try this with latest git commit and report back.

**Comment by andmarti1424** [comment]
thanks!

**Comment by andmarti1424** [comment]
@dikeert could you try it? Thanks

**Comment by dikeert** [comment]
Hello!

I'm a bit busy right now, I think I'll be able to get to that next week.

**Comment by dikeert** [comment]
Hello!
Do you happen to know if `scm-im-git` on arch installs last commit? If yes then it still segfaults.

**Comment by dikeert** [comment]
Version:

```
$ sc-im --version
SC-IM - version 0.8.2-dev
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLSX
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/share/sc-im"
-DLIBDIR="/usr/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

I'll try to build it myself now...

**Comment by dikeert** [comment]
Nope, HEAD of branch freeze still segfaults. 

As to other questions that I totally missed, pardon me, I was really re-occupied with something else.

The expression that causes segfault is this:
```
@sum(H2:I7, @vlookup(Q2:R30, H2, 1)=@vlookup(Q2:R30, D6, 1))
```
Enter it in any free cell and it'll segfault. Use file from pastebin that I linked in the description.

**Comment by andmarti1424** [comment]
> Hello!
> Do you happen to know if `scm-im-git` on arch installs last commit? If yes then it still segfaults.

probably yes. but from freeze branch.

**Comment by andmarti1424** [comment]
@dikeert this segfaults in old sc too. Could you please update to my latest commit on the "new" branch and try again..??

**Comment by dikeert** [comment]
Hello!

First of all, I had to edit my formula, the correct one is this: `@sum(H2:I7, @vlookup(Q2:R30, $H2, 1)=@vlookup(Q2:R30, $D$6, 1))` one.

Second, both, the correct formula and incorrect formula now work properly without segfault. That is if you build from HEAD of `new` branch.

Third. I'm a stupid moron and that monstro of a formula can be replaced with `@sum(H2:I17,@eqs($H2, @fixed D6))` (which also segfaults the "old" version")

Thank you very much!

**Comment by andmarti1424** [comment]
Thank you.
