### ISSUE TITLE
Mapping for move column/row left/right

### ISSUE THREAD

**Issue by Payne-X6** [andmarti1424/sc-im#372]
I have tried to create mapping for move column left but for some reason it wont work. When I'm in Normal mode, I just use sequence of keys `ycdchp`, where `yc` stands for 'yank column', `dc` for 'delete column', `h` 'move left' and `p` for 'paste'.
When i create mapping (one of these two)
```
nnoremap "mh" "ycdchp"  
nmap "mh" "ycdchp"
``` 
nothing happens even when binding for this keys should work.

**Comment by andmarti1424** [comment]
yep. indeed. this is not working properly. :(

**Comment by andmarti1424** [comment]
@Payne-X6 could you please update to latest commit and try again? thanks.

**Comment by andmarti1424** [comment]
btw its not neccesary that "yc" since when you "dc" it already yanks it for you.
this should do:
`nnoremap "mh" "dchp" `

**Comment by andmarti1424** [comment]
This should be fixed now.
