### ISSUE TITLE
Keep Number Strings as Strings

### ISSUE THREAD

**Issue by JBlocklove** [andmarti1424/sc-im#373]
Whenever I put numbers into a csv, even if I enter them as strings, whenever I open that file again `sc-im` automatically converts them to numbers and adds decimal points. I don't mind `sc-im` thinking they're numbers, but the decimal points are annoying, since I then have this file parsed by another program.

Is there some toggle or configuration setting which can make it so that everything defaults to strings unless I specify otherwise? I've looked through the help file, but I don't think I found anything that would do this for me there. The closest thing I found was using `:format "##."`, but I would still need a way to set that as my default format.

Any help is greatly appreciated!

**Comment by gaetanlord** [comment]
I ditto would like to have such a feature

**Comment by andmarti1424** [comment]
@JBlocklove you can use import_delimited_as_text to avoid that conversion. Then everything is imported as text. Hope  that helps.

**Comment by OrkeshNurbolat** [comment]
how to use this "import_delimited_as_text" is this a command ?

**Comment by andmarti1424** [comment]
That's is a configuration variable used when importing csv files. You can set it at runtime or in your shell as a parameter to the executable
