### ISSUE TITLE
`sl` Command adds trailing commas

### ISSUE THREAD

**Issue by JBlocklove** [andmarti1424/sc-im#374]
When editing a csv, using the `sl` command to shift a range of cells to the right adds a trailing comma for each shift. I assume this happens because the program just adds additional commas to the left to accomplish the shift (at least from the csv perspective), but it doesn't account for the fact that in those cells there might not be anything to the right which needs to be preserved.

This makes parsing the csv after it's been edited using `sc-im` a bit more annoying, as now any other programs need to account for removing any trailing commas from the end of lines.

**Comment by andmarti1424** [comment]
hello. yep. that is because maxcol (internal value) get incremented when you shift right.

**Comment by andmarti1424** [comment]
@JBlocklove, this should be handled now. please update to latest commit and give it a try.
thanks.
