### ISSUE TITLE
[MINOR-BUG] ':cellcolor' does not work correctly

### ISSUE THREAD

**Issue by pacrox** [andmarti1424/sc-im#375]
Neither
`:cellcolor "fg=YELLOW"`
nor
`:cellcolor "bg=YELLOW"`
change the selected cell to YELLOW.

To achieve the desired result, you need to specify both `bg` and `fg`:
`:cellcolor "fg=YELLOW bg=DEFAULT_COLOR"`
or vice-versa.

It does work, but once you save the file and reload it, the colors are lost.
Here follows an example:
[Before saving]
![Before_saving](https://user-images.githubusercontent.com/36406936/73113399-012f6300-3f14-11ea-9ffb-60065e728a51.png)
[After loading back]
![After_saving](https://user-images.githubusercontent.com/36406936/73113405-08567100-3f14-11ea-8e53-415f4fdc712f.png)

Interestingly, although I don't have `bold=1` set for the `STRG` option in my .scimrc, watching carefully the images it's clear that my default string's look is bold, but this attribute is lost after issuing the `cellcolor` command.

The saved file still retains the color information, but the interface seems unable to properly parse it.

`...`
`leftstring B7 = "Prova"`
`leftstring C7 = "<cellcolor 'bg=YELLOW bold=0'"`
`cellcolor B7 "bg=YELLOW"`
`...`
`goto B7`

**UPDATE**
Actually
`:cellcolor "fg=YELLOW bg=BLACK"`
works fine. Once defined this way, the attributes are kept after reloading the file.

[Sc-im - version 0.7.0 // Linux Pop-Os 19.10]

**Comment by andmarti1424** [comment]
What is your OS?

**Comment by pacrox** [comment]
Linux PopOS 19.10 (ubuntu)

**Comment by andmarti1424** [comment]
In the sc file it should get saved as:

**Comment by andmarti1424** [comment]
cellcolor A3 "fg=BLUE bg=WHITE"

**Comment by pacrox** [comment]
If I issue the command specifying both `fg` and `bg` it get saved correcty.
But, if I issue the command:
`cellcolor "fg=YELLOW"`
on the saved file I get:
`cellcolor B7 "bg=YELLOW"`

I use (prefer) dark background, so I've kept the terminal default.

This is my `.scimrc` file, it may matter.
```
set autocalc
set xlsx_readformulas
set ignorecase
set overlap
set external_functions

color "type=HEADINGS fg=WHITE bg=BLUE"
color "type=MODE fg=WHITE bg=DEFAULT_COLOR"
color "type=NUMB fg=YELLOW bg=DEFAULT_COLOR"
color "type=STRG fg=CYAN bg=DEFAULT_COLOR bold=0"
color "type=DATEF fg=MAGENTA bg=DEFAULT_COLOR"
color "type=EXPRESSION fg=GREEN bg=DEFAULT_COLOR"

color "type=CELL_ERROR fg=WHITE bg=RED"
color "type=CELL_NEGATIVE fg=RED bg=DEFAULT_COLOR"
color "type=CELL_SELECTION fg=BLACK bg=YELLOW bold=1"

color "type=CELL_ID fg=BLACK bg=YELLOW bold=1"
color "type=CELL_FORMAT fg=CYAN bg=DEFAULT_COLOR"
color "type=CELL_CONTENT fg=CYAN bg=DEFAULT_COLOR"

color "type=NORMAL fg=WHITE bg=DEFAULT_COLOR"
color "type=INPUT fg=YELLOW bg=DEFAULT_COLOR"

color "type=INFO_MSG fg=BLUE bg=DEFAULT_COLOR"
color "type=ERROR_MSG fg=WHITE bg=RED"
```

**Comment by andmarti1424** [comment]
I believe then, it should have checked you entered both bg and fg..
"If I issue the command specifying both fg and bg it get saved correcty." ->
This is how you should set them.

**Comment by andmarti1424** [comment]
Could you test this again? There were modifications regarding this topic. Thanks
