### ISSUE TITLE
[BUG] '@ext' seems not to work

### ISSUE THREAD

**Issue by pacrox** [andmarti1424/sc-im#376]
Both the examples shown in the help don't produce the expected result.
The first just returns `0.00`, the second one produces a `syntax error`.
![Screenshot 2020-01-25 at 02 11 08 530x142](https://user-images.githubusercontent.com/36406936/73114103-127a6e80-3f18-11ea-8a66-09943f4dc11e.png)

The option `set external_functions` is set in my `~/.scimrc` file and it appears also in the saved files.

Every combination I've tried, sees to always returns `0.00`.
(maybe it's the process' exit status, rather that the standard out?)
`@ston(@ext("echo ", a1))`:
![Screenshot 2020-01-25 at 02 23 19 312x160](https://user-images.githubusercontent.com/36406936/73114355-00013480-3f1a-11ea-9a19-1055b91417ea.png)
![Screenshot 2020-01-25 at 02 23 36 312x138](https://user-images.githubusercontent.com/36406936/73114357-068fac00-3f1a-11ea-82bf-1d7c75903514.png)

`@ston(@ext("echo ", a1+a2))`:
![Screenshot 2020-01-25 at 02 33 01 320x156](https://user-images.githubusercontent.com/36406936/73114463-0ba12b00-3f1b-11ea-936d-76c7dd8fcd83.png)
![Screenshot 2020-01-25 at 02 31 08 324x166](https://user-images.githubusercontent.com/36406936/73114441-ced53400-3f1a-11ea-887b-1028422d04f4.png)

`@ston(@ext("echo 1", 0))`:
![Screenshot 2020-01-25 at 02 04 27 294x144](https://user-images.githubusercontent.com/36406936/73114188-9d5b6900-3f18-11ea-8797-d8bb0950366c.png)
![Screenshot 2020-01-25 at 02 04 50 296x150](https://user-images.githubusercontent.com/36406936/73114192-a2b8b380-3f18-11ea-84f1-032fbf609481.png)

`@ston(@ext("echo 1", 10))`:
![Screenshot 2020-01-25 at 02 05 13 306x152](https://user-images.githubusercontent.com/36406936/73114221-d4ca1580-3f18-11ea-9683-d3ca2ff996ff.png)
![Screenshot 2020-01-25 at 02 05 26 308x158](https://user-images.githubusercontent.com/36406936/73114223-d8f63300-3f18-11ea-98b4-fa5a89efde05.png)

`@ston(@ext("echo 12.3 #", 0))`:
![Screenshot 2020-01-25 at 02 09 01 344x174](https://user-images.githubusercontent.com/36406936/73114238-fcb97900-3f18-11ea-94b6-b27d57d09d82.png)
![Screenshot 2020-01-25 at 02 09 58 320x154](https://user-images.githubusercontent.com/36406936/73114265-3be7ca00-3f19-11ea-99d1-426e78994ab9.png)

[Sc-im - version 0.7.0 // Linux Pop-Os 19.10]

**Comment by peterjschroeder** [comment]
I also can't get this to work. I'm trying to use it to pass off calculations to a python script. It seems it has been a bug for awhile as reported in bug #262

**Comment by 097115** [comment]
Either we are missing something, or that `@ext` was broken from the very beginning: I've just checked every version back to 0.1.8, and these examples (including the one provided by @immae in #262) were simply failing with the every build.

@andmarti1424, please, help! :)

**Comment by andmarti1424** [comment]
Could you please update to latest git commit  and try again?
@ston(@ext("echo 1", 10)) is now returning correct value.
Thanks.

**Comment by reportaman** [comment]
@andmarti1424 ``=@ston(@ext("echo 1", 10))``, it evaluates and puts correct value but the status on the top left remains stuck till I move the cursor around, it reads ``Running external function...``

**Comment by 097115** [comment]
> `@ston(@ext("echo 1", 10))` is now returning correct value.

@andmarti1424 if entered "live", then yes, it does. However, if the we save the file and then re-open it, the cell shows `0` for me. Running 6d18113.

Nonetheless, it's great to see you, and thanks for your time and support!

**Comment by reportaman** [comment]
@097115 We recently asked @andmarti1424 start a Patreon project page. Feel free to support: https://www.patreon.com/user?u=51340616

**Comment by andmarti1424** [comment]
Working in 'lua' branch, this `=@ston(@ext("echo 1", 10))` works ok both typing it at runtime and loading it from a file.
The 'lua' branch will be merged soon to freeze.
