### ISSUE TITLE
priority of exponential and unary minus operators

### ISSUE THREAD

**Issue by btiffin** [andmarti1424/sc-im#38]
Hello, Andrés

Brian Tiffin here, I've started in on writing up a `sc-im` User Guide.  I use Sphinx and ReStructuredText for technical writing, and I'm very interested in seeing this project moving forward, and improving.

I have plans to leverage this awesome update to `sc` in both GnuCOBOL and Open Object Rexx applications.  Or at least, to show people how this system can be leveraged.

I'm still a GnuCOBOL developer, first and foremost, but I plan on helping out with `sc-im`, if and when, I can.

Can't really promise much at this point, as the work has just begun, and things can always go sideways, but I think I've got a pretty good plan in place, and I'm hoping to be able to show you some actual output over the next few weeks and months.  The level of keen is fairly high, having just had a chance to play around with your latest.

GnuCOBOL 2.0 is nearing a release, as is Open Object Rexx version 5.0, so things will be busy.

For a sample of the writing you can expect to see, take a look at http://opencobol.add1tocobol.com/gnucobol/ which currently weighs in at about 865 pages when output as PDF.  The source code highlighting of the COBOL is a contribution I made to the Pygments team, and we even get to enjoy those coloured listings on SourceForge and Wikipedia now, thanks to Team Pocoo.  There are features in Sphinx that will allow Markdown files as part of the documentation set with a  remarkdown tool.  I'll be adding those features to the GnuCOBOL FAQ to make it easier to get Wiki shared edits on some of the more interesting topics in the current book, topics that deserve some _wisdom of the many_.

`sc-im` highlighting in Pygments will be part of the effort I put into this new book.  Just spent a few hours getting an Introductory chapter written, but again, too early to show you much yet, but this note is to inform you that efforts have begun, and that you have a fan that will try and help out.

I'm also a fan of Doxygen, and might even take a kick at adding some API documentation to your source listings.  Might even make a pass and try and autotool-ize your source tree, which might make it easier on distro package maintainers once you think `sc-im` is ready for the likes of Debian and Fedora.

I hope you don't mind, but I plan on reformatting the internal doc file to fit within an 80 column display, about 15% through the file so far.  You can see a copy in the draft.

Keep up the good works, Andrés, and more soon on the documentation angles.

As a maintainer with the GNU project, and free software fan, I'll be willing to re-assign copyrights to you and your project, as long as `sc-im` remains freedom free.

Current (work in progress, very much incomplete) samples at:
http://peoplecards.ca/sc-im/   (Generated by Sphinx (agogo theme))
and 
http://peoplecards.ca/sc-im/sc-im-rst.html (straight up Docutils, rst2html)

Cheers, and have good,
Brian

**Comment by andmarti1424** [comment]
Hello Brian. Any help would be appreciated, of course. I am really busy lately with my little daughter and couldnt continue working. Another guy is also improving documentation but did not send me anything yet.
So I dont know if he is still working.

Now I am really excited to see a preview !
Thanks for your work!!

**Comment by btiffin** [comment]
Andrés, quick question on order of precedence, and possibly a change request if you get time.

-3^2

In mathematics that is -9, stemming from

-x^2 being minus (x squared)

Lots of spreadsheets get this wrong, but it would be nice if sc-im got it right.

a0 = 3
a1 = -a0^2

Gives 9 in sc-im, which is not what a quadratic equation should really do.  Exponentials should bind higher than unary -, but if not, it'll have to be clearly stated as counter to math class.

Do I make a bug report or just document it as unary minus as a higher priority than exponential operators?  Parens do force the correct behaviour.

a1 = -(a0^2) gives the -9, but again, that's counter to math class.

Cheers,
Brian

**Comment by andmarti1424** [comment]
Thanks. You are right.
Please document it as unary minus as a higher priority.
Although I will try to change it in future releases to the correct
behaviour.

2015-12-10 5:15 GMT-03:00 Brian Tiffin <notifications@github.com>:

> Andrés, quick question on order of precedence, and possibly a change
> request if you get time.
>
> -3^2
>
> In mathematics that is -9, stemming from
>
> -x^2 being minus (x squared)
>
> Lots of spreadsheets get this wrong, but it would be nice if sc-im got it
> right.
>
> a0 = 3
> a1 = -a0^2
>
> Gives 9 in sc-im, which is not what a quadratic equation should really do.
> Exponentials should bind higher than unary -, but if not, it'll have to be
> clearly stated as counter to math class.
>
> Do I make a bug report or just document it as unary minus as a higher
> priority than exponential operators? Parens do force the correct behaviour.
>
> a1 = -(a0^2) gives the -9, but again, that's counter to math class.
>
> Cheers,
> Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/issues/38#issuecomment-163530288>.
>



-- 
Andrés Martinelli

**Comment by btiffin** [comment]
Will do.

Thanks, Andrés.

**Comment by andmarti1424** [comment]
Hello @btiffin. Could you have any progress in the documentation you were working on?
Thanks!

**Comment by andmarti1424** [comment]
This is the patch that accomplish what you pointed out:
gram.y:
```

         |       '+' term        { $$ = $2; }
-        |       '-' term        { $$ = new('m', $2, ENULL); }

     |    e '%' e        { $$ = new('%', $1, $3); }
+    |      '-' e        { $$ = new('m', $2, ENULL); }
     |    e '^' e        { $$ = new('^', $1, $3); }
```

**Comment by andmarti1424** [comment]
Added to freeze branch. Will be there for v0.6 release.
