### ISSUE TITLE
[feature request] LaTeX export

### ISSUE THREAD

**Issue by ntguardian** [andmarti1424/sc-im#394]
Hello,

The original `sc` supported exporting LaTeX tables, and I would like that functionality to be restored in sc-im.

**Comment by mipmip** [comment]
Can you give an example how with a sc-file and the export result how you think it should look like?

**Comment by ntguardian** [comment]
If you make a spreadsheet using `sc` then use its TeX export feature, that's all I really want. I think in `sc` you set `tblstyle=tex` and then export using `T` that should be all you need to do. But you can just make a simple `sc` sheet and see what its LaTeX export does.

**Comment by mipmip** [comment]
I don't have the old sc working. I'm a tex-dummy and always get confused by it's extensions of dialects. Please paste a piece of TeX table definition.

Things I would think of:
- do you need table headings?
- do you need cell or column alignment?

**Comment by ntguardian** [comment]
[TestTable.zip](https://github.com/andmarti1424/sc-im/files/4601183/TestTable.zip)
I'm uploading the zip file with a `sc` file and a LaTeX conversion as produced by the old `sc`. Note that all the `tex` file is not a proper LaTeX document; it only contains a table, not the rest needed to produce a document. (If you want code that turns the table into a proper TeX for, say, debugging purposes, I can do that.)

Regarding the syntax, all tables start with `\begin{tabular}{.........}` and end with `\end{tabular}`. `{......}` defines how many columns there are and their alignment; the provided table has `{cccc}` for four centered columns, while `{rcl}` would be a right-justified, centered, and left-justified column, respectively. Generally LaTeX does not recognize a table "header" per se; it is just another row, though a user may make that row look nicer to get something resembling a header, such as making font bold and adding a horizontal rule via `\hline`.

A table row has fields separated by `&`, and the number of `&` must be one less than the number of columns of the table. Notice the `sc` file has three effective columns while the resulting TeX table has four; I don't know why the converter made this decision, as the result is an empty column. You can view `&` as being equivalent to `,` in CSV files. Every row except the last must be concluded by `\\`; I'm not sure if it's incorrect for the last row to be terminated with `\\`, though.

As for empty rows, the `sc` converter handles them via a LaTeX row consisting only of `&` and `\\`.

**Comment by andmarti1424** [comment]
If old sc did it.. We should get it back.

**Comment by andmarti1424** [comment]
I am working on this.

**Comment by andmarti1424** [comment]
@ntguardian @mipmip, please update to latest commit and try with
`:e tex file.tex`
thanks.

**Comment by ntguardian** [comment]
Is it available on AUR yet?

**Comment by andmarti1424** [comment]
sc-im-git perhaps..
the plain sc-im package is still the v0.8 release.

**Comment by andmarti1424** [comment]
@ntguardian could you take a look at it?

**Comment by reportaman** [comment]
In my testing its decent start, there is no custom alignment though (everything number and label cell is center aligned). Perhaps an elaborate converter could be written by user when something like this is available: ``https://github.com/andmarti1424/sc-im/issues/494``.

**Comment by andmarti1424** [comment]
Haven't noticed that. 
The routine is an adaptation of sc's one. It seems sc doesn't have alignment either then.

**Comment by andmarti1424** [comment]
Thanks for testing it

**Comment by andmarti1424** [comment]
I think we can close this. Thanks

**Comment by ntguardian** [comment]
I also tested this and it seems to work great.

**Comment by andmarti1424** [comment]
@ntguardian Thank you!
