### ISSUE TITLE
[BUG] Error building on fedora 32

### ISSUE THREAD

**Issue by barrosoman** [andmarti1424/sc-im#397]
When I try to compile sc-im on fedora 32, it gives these errors.
I already installed ncurses-devel and bison (tried with byacc too)

`cc  clipboard.o exec.o pipe.o cmds_command.o shift.o undo.o digraphs.o maps.o range.o cmds_normal.o conf.o tui.o block.o plot.o cmds_insert.o vmtbl.o yank.o xmalloc.o cmds.o help.o lua.o hide_show.o interp.o xls.o format.o file.o filter.o sort.o main.o buffer.o subtotal.o dep_graph.o trigger.o input.o color.o lex.o freeze.o marks.o history.o cmds_visual.o cmds_edit.o xlsx.o utils/string.o utils/dictionary.o utils/extra.o gram.o -o sc-im -lm -pthread -ldl -lncursesw -ltinfo  -lxml2 -lzip 
/usr/bin/ld: exec.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: pipe.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_command.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: shift.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: maps.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_normal.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_normal.o:/home/jb/sc-im/src/cmds_normal.c:73: multiple definition of `interp_line'; cmds_command.o:/home/jb/sc-im/src/cmds_command.c:84: first defined here
/usr/bin/ld: tui.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: tui.o:(.bss+0x280): multiple definition of `ranges'; range.o:(.bss+0x0): first defined here
/usr/bin/ld: plot.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_insert.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: vmtbl.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: xmalloc.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds.o:/home/jb/sc-im/src/cmds.c:71: multiple definition of `interp_line'; cmds_command.o:/home/jb/sc-im/src/cmds_command.c:84: first defined here
/usr/bin/ld: help.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: hide_show.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: interp.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: xls.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: file.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: filter.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: filter.o:/home/jb/sc-im/src/filter.h:47: multiple definition of `filters'; cmds_command.o:/home/jb/sc-im/src/filter.h:47: first defined here
/usr/bin/ld: sort.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: main.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: main.o:/home/jb/sc-im/src/filter.h:47: multiple definition of `filters'; cmds_command.o:/home/jb/sc-im/src/filter.h:47: first defined here
/usr/bin/ld: subtotal.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: dep_graph.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: trigger.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: input.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: input.o:/home/jb/sc-im/src/input.c:70: multiple definition of `shall_quit'; main.o:/home/jb/sc-im/src/main.c:110: first defined here
/usr/bin/ld: color.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: lex.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: freeze.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_visual.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: cmds_edit.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: xlsx.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
/usr/bin/ld: gram.o:/home/jb/sc-im/src/filter.h:47: multiple definition of `filters'; cmds_command.o:/home/jb/sc-im/src/filter.h:47: first defined here
/usr/bin/ld: gram.o:/home/jb/sc-im/src/color.h:60: multiple definition of `ucolors'; clipboard.o:/home/jb/sc-im/src/color.h:60: first defined here
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [Makefile:184: sc-im] Fehler 1
`

**Comment by teleportex** [comment]
I have the same issue on ArchLinux. 
I've tried to build from the Arch User Repository package and directly from source.

**Comment by teleportex** [comment]
On issue #411 i found the solution which is related to the gcc compiler version.

**Comment by happycoder97** [comment]
From gcc website https://gcc.gnu.org/gcc-10/changes.html:

> GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking.

**Comment by andmarti1424** [comment]
THis should be fixed by now then
