### ISSUE TITLE
Missing -lz library flag for xls/xlsx support

### ISSUE THREAD

**Issue by SpectreVert** [andmarti1424/sc-im#398]
I'm compiling sc-im on OpenSUSE Tumbleweed release 20200414.

Installed the dependencies -- from [this issue](https://github.com/andmarti1424/sc-im/issues/80) I got something like libxls-devel, libxml2-devel and libzip-devel -- but could not compile with XLS and XLSX support.

I ended up having linkage error for deflate function so I linked against libz and it worked. I even dropped the libzip-devel package.

**Comment by andmarti1424** [comment]
@SpectreVert Is this really confirmed?
Could this be related to https://github.com/andmarti1424/sc-im/issues/397 perhaps?
Please try again with latest commit and report back. Thanks!
