### ISSUE TITLE
Go to cell command is overloaded and cannot go to certain rows

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#399]
As documented, entering `gab24` should take the cursor to cell `AA24`. But the commands `gG`, `gg`, `gM` and `gl` overload on this, so there is no way to use the `g` command to go to cells `G24`, `M24` or `L24`. It would take away from Vi/Vim paradigm to change `gg` or `gl` to something else. It seems to me a lesser break from the old _sc_ to change the goto-row-col command to something else. Not critical, maybe we should just note the inconsistency in the documentation/help file.

**Comment by andmarti1424** [comment]
Yessss. May be renaming 'g' command to 'gt' ???

**Comment by andmarti1424** [comment]
'g' command of NORMAL_MODE changed to 'gt'"
