### ISSUE TITLE
don't set CC explicitly

### ISSUE THREAD

**Issue by 257** [andmarti1424/sc-im#40]
i'm working on packaging this for exherbo. setting CC should be left to host and build to be determined. please commnet CC in src/Makefile, that way we have much more general approach. thanks.

**Comment by 257** [comment]
well same goes for prefix i guess but then a autocon type configure script might be needed.

**Comment by andmarti1424** [comment]
Pull request for adding autoconf will be well received.

**Comment by cody-code-wy** [comment]
While working on issue #52 I found that it was impossible to do with the current make file. So I was thinking about adding autoconf. Looks like I will.

**Comment by andmarti1424** [comment]
That would be great!

**Comment by andmarti1424** [comment]
Hello @cody-code-wy! Could you have any progress in this?

**Comment by andmarti1424** [comment]
Hello @cody-code-wy! Could you have any progress in this?

**Comment by andmarti1424** [comment]
Hello @cody-code-wy! Could you have any progress in this?
