### ISSUE TITLE
Request jump to URL or open file under cursor

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#400]
In Vim, the command `gf` opens a file whose pathname is given by the string under cursor. I have been seriously using _sc-im_ and the ability to open a file or a link given by the string in a cell would be extremely handy. In combination with `set copy_to_clipboard_delimited_tab=1` setting, and the `:ccopy`/`:cpaste` commands, it allows refactoring content across multiple spreadsheets.
In accounting, for example, it would be handy to keep the receipt PDF filenames on the same sheet, so with `gf` you can bring up the receipt in another window to double check. Without this feature, you would have to open another window and copy-paste to view the receipt. File `tests/gps.sc` illustrates keeping URLs for reference. Again, it would save opening new window, application and copy-paste of URL.

**Comment by andmarti1424** [comment]
Already merged your work.  Thank you.
