### ISSUE TITLE
Incorrect colors; can't read online help

### ISSUE THREAD

**Issue by akkartik** [andmarti1424/sc-im#402]
I'm having trouble reading `:help`, and there are probably other issues with my colors.

I read #297, and while I started out with a light colorscheme, that doesn't seem to be the culprit. Here's my baseline state with a temporary dark colorscheme, after clearing out all my shell configuration.

<img width="969" alt="0" src="https://user-images.githubusercontent.com/3161/80563901-49da3a80-89a1-11ea-84fc-ef852f79f1b5.png">

When I hit `<Enter>`, here's what I see.

<img width="1049" alt="1" src="https://user-images.githubusercontent.com/3161/80563962-6b3b2680-89a1-11ea-9ab4-5006a9a2d2f0.png">

If I type `:help`, I can see what I type. (This doesn't happen with a light background.) So far, so good.

<img width="1276" alt="2" src="https://user-images.githubusercontent.com/3161/80564100-bce3b100-89a1-11ea-9488-d25148a91a4a.png">

However, when I hit `<Enter>`, this is is what I see.

<img width="1256" alt="3" src="https://user-images.githubusercontent.com/3161/80564126-cb31cd00-89a1-11ea-85c0-de3a563d5493.png">

I also tried [@jnduli's suggestions](https://github.com/andmarti1424/sc-im/issues/297#issuecomment-449555863), but the final screenshot above didn't change. (I have a bootstrap problem here since it looks like the documentation for colors might be mostly in the online help system, but I can't seem to find any way to read it 😄)

Any guidance or ideas most appreciated. I'd be happy to answer any follow-up questions or try out any commands you suggest.

**Comment by sudoerena** [comment]
I have the same problem on CentOS7. (Also typically on light mode, but the error persists on dark mode.)
I don't believe it's a colour issue, as the help file displays fine when I launch sc-im from within  `sc-im/src`, albeit with unreadable colours, but I have the same blank screen when sc-im is launched elsewhere.

**Comment by andmarti1424** [comment]
Could you please try again with latest git commit? You can redefine ncurses colors or even you can redefine a type background to a custom rgb. Please check wiki
