### ISSUE TITLE
.scimrc file ignored

### ISSUE THREAD

**Issue by ntguardian** [andmarti1424/sc-im#407]
I installed the AUR package `sc-im-git` and have the following `.scimrc` file in my home directory:

```
set overlap
set autocalc
```

It appears to be ignored. Once there was a `.scim` directory and I moved my `.scimrc` file there, renaming it `scimrc`. No change.

This is a fresh Arch Linux build.

**Comment by andmarti1424** [comment]
Copy it to .config and rename it to scimrc (without the dot).

**Comment by coachshea** [comment]
Thank you. I was having the same problem and this fixed it for me.

**Comment by DarkWiiPlayer** [comment]
This is not currently reflected in the `:help` document, shall I fix that and open a PR?

**Comment by andmarti1424** [comment]
Please keep file in .config/scimrc

**Comment by andmarti1424** [comment]
@DarkWiiPlayer already done. thank  you.
