### ISSUE TITLE
Clean xlsx file's content 

### ISSUE THREAD

**Issue by strogiyotec** [andmarti1424/sc-im#408]
Good day , thank you for this awesome software.
I faced a problem. I try to open and edit .xlsx file . When I write changes using default keys (< and >) and then save changes using `"w` sc-im shows me the following message `File "Vocabulary.xlsx" written` then I close the file using `:q`. When I reopen it the file is absolutely empty . I checked the same logic with `.csv` file and it works perfectly well.
Sc-im version :
```
Sc-im - version 0.7.0
```
How can I fix it ?

**Comment by andmarti1424** [comment]
If you want to save in csv format you need to save it like  this:
:e csv ..

**Comment by andmarti1424** [comment]
Did you try it? Just let me know if you still got problems.

**Comment by strogiyotec** [comment]
Hey , will try it today
