### ISSUE TITLE
When exporting to xlsx, a line gets zapped from the .sc file

### ISSUE THREAD

**Issue by ghost** [andmarti1424/sc-im#413]
I was writing a spreadsheet with formulas, and then I exported the file to an xlsx with the runtime option `set xlsx_readformulas` in the scimrc file, and as soon as I executed the command, scim zapped the first line of the file. This only happens when I had zapped a row previously though.

**Comment by andmarti1424** [comment]
Hello. How did you zap the row previously? Thanks.
