### ISSUE TITLE
Count unique

### ISSUE THREAD

**Issue by pniedzwiedzinski** [andmarti1424/sc-im#414]
Is it possible to count unique elements in column?

**Comment by andmarti1424** [comment]
@pniedzwiedzinski, If you sort it first?

**Comment by andmarti1424** [comment]
@pniedzwiedzinski have you tried something related to the suggestions here:
https://www.got-it.ai/solutions/excel-chat/excel-tutorial/count/count-unique-values-excel ??

**Comment by pniedzwiedzinski** [comment]
well, but that's excel right? so how to make it work in scim?

**Comment by andmarti1424** [comment]
yes, but in sc-im you also have "sum" and "countif" functions..

**Comment by andmarti1424** [comment]
@pniedzwiedzinski btw I have also checked in gnumeric and libreoffice calc and it seems the function is not there either.
I believe you could probably get away with it as suggested in the link above.
