### ISSUE TITLE
autocalc bug

### ISSUE THREAD

**Issue by Karl-Stefan** [andmarti1424/sc-im#415]
Upon opening a file not all formulas are calculated.

I either need to edit the file n amount of times to get all the calculations (where n is the number of formulas that depend on other formulas in different cells), or re-run ':set autocalc' n amount of times

**Comment by reportaman** [comment]
@Karl-Stefan I had a similar issue. Can you check if adding 0 to every numeric formula resolves the problem? If yes, then it is the same issue as the one I encountered, and narrowed down to: https://github.com/andmarti1424/sc-im/issues/497. @andmarti1424 Can then fix both of our tickets together.

**Comment by andmarti1424** [comment]
@Karl-Stefan do you still have this issue?

**Comment by Karl-Stefan** [comment]
@andmarti1424 just did a pull and make, and am not able to reproduce the error with the new binary. Thank you :)

**Comment by andmarti1424** [comment]
To you.
