### ISSUE TITLE
Exit 'waiting-for-valid-command' automatically when no valid command can be reached

### ISSUE THREAD

**Issue by itsfarseen** [andmarti1424/sc-im#418]
How it currently works:
* Press `f` - `?` is shown at the top.
* Press `f` - `?` is still shown.
* Press `h/j/k/l` - Nothing happens.
* Press `Esc` - Nothing happens.

Expected behavior:
* Press `f` - `?` is shown at the top.
* Press `f` - `?` disappears, because there is no `ff` shortcut. (is there?)
* Press `h/j/k/l` - Movements happen as usual.

Workaround:
* Press `f` - `?` is shown at the top.
* Press `f` - `?` is still shown.
* Press `Esc` - `?` is still shown, but it is out of "waiting for more keypresses" mode.
* Press `h/j/k/l` - Movements happen as usual.

**Comment by andmarti1424** [comment]
What are you trying to achieve? Freeze an area?

**Comment by happycoder97** [comment]
No, I mean the UI stops responding.

**Comment by andmarti1424** [comment]
Its no that its not responding, it just waits for a valid command. If none arrives after a couple of seconds..it just cancels.

**Comment by happycoder97** [comment]
Okay. But it is not exiting out of that waiting-for-command mode when I press a key which doesn't have any mappings.

**Comment by cincodenada** [comment]
This tripped me up as well - Vim exits the "entering command mode" if you end up with a sequence that can't be a valid command, so I expected sc-im to behave similarly. I just now went and tried out a very hacky patch that accomplishes this (just for the `f` command), here's hoping I'll get around to tidying and submitting it as a PR. Here's the very hasty patch so far, just for reference (this is off of the `freeze` branch):

```
diff --git a/src/cmds.c b/src/cmds.c
index 5d6a564..3f7e28f 100644
--- a/src/cmds.c
+++ b/src/cmds.c
@@ -2785,7 +2785,8 @@ int is_single_command (struct block * buf, long timeout) {
                ((buf->pnext->pnext->value - (L'a' - 1)) < 1 ||
                  buf->pnext->pnext->value > 26)) res = EDITION_CMD;
 
-        else if (buf->value == L'f' && bs == 2 &&    // Format col
+        else if (buf->value == L'f' && bs == 2) {
+            if
                ( buf->pnext->value == L'>' ||
                  buf->pnext->value == L'<' ||
                  buf->pnext->value == L'h' ||
@@ -2801,8 +2802,12 @@ int is_single_command (struct block * buf, long timeout) {
                  buf->pnext->value == L'r' ||         // Freeze row / col / area
                  buf->pnext->value == L'c' ||
                  buf->pnext->value == L'a'
-                 )
-               ) res = EDITION_CMD;
+                 ) {
+                res = EDITION_CMD;
+               } else {
+                   res = EXIT_CMD;
+               }
+        }
 
     } else if (curmode == VISUAL_MODE && bs == 1) {
              if (buf->value == L'j' ||
diff --git a/src/macros.h b/src/macros.h
index 486c846..ba0e97c 100644
--- a/src/macros.h
+++ b/src/macros.h
@@ -82,6 +82,7 @@
 #define NO_CMD           0
 #define EDITION_CMD      1
 #define MOVEMENT_CMD     2
+#define EXIT_CMD         3
 
 #define HEADINGS          0
 #define WELCOME           1
```

**Comment by andmarti1424** [comment]
Yes, I believe its a design decition.
It could get out of 'waiting for valid command' automatically when there is no possibility of a valid one...
but you still can keep it as is, indicating that not a valid command was introduced.
the cons of the first one: if you go back automatically you might believe a valid command was issued.. when was not the case.
the cons of the second is that you have to wait or...
You can always press ESC key and go back.
Please open a discussion to see what other users think regarding this topic. It can always be changed based on what majority wants.
