### ISSUE TITLE
Unable to read written data once document has been saved and opened up

### ISSUE THREAD

**Issue by nizhnichenkov** [andmarti1424/sc-im#420]
Hi, 
I often find myself unable to retrieve back the data I wrote with SC-IM. 

Flow: 
1. **% scim hey.csv**                               # create a new csv document 
<img width="611" alt="Screenshot 2020-06-20 at 14 32 06" src="https://user-images.githubusercontent.com/36489945/85203119-545ee380-b303-11ea-8a8e-4685585864f2.png">

2. add some rows and values 

3. **:wq**                                                  # to save what I have added

4. **% scim hey.csv**                               # to open up the file again to see the data
<img width="606" alt="Screenshot 2020-06-20 at 14 32 18" src="https://user-images.githubusercontent.com/36489945/85203123-5aed5b00-b303-11ea-9e03-c860bf074c44.png">

I am unable to see any data - just the very first row is present - everything else is gone. 
It is weird because when I use another app to open the saved file - like Numbers / Excel - the data is there and can be seen.  

Could you help me please? 

Thanks

P.S. This is my **.scimrc** 

```set autocalc
set numeric
set numeric_decimal=0
set overlap
set xlsx_readformulas

color "type=HEADINGS fg=BLACK bg=YELLOW"
cellcolor A1:Z1000 "bg=BLACK fg=WHITE"
cellcolor A0:ZZ0 "bg=WHITE fg=BLACK"

**Comment by andmarti1424** [comment]
Hello. When you use :w command it always gets saved in .sc format.
Doesnt matter if you open a csv file.
If you want to keep the .csv format you always have to prompt ':e csv..'
This might change in future, but from now that is how you suppose to do it.
Hope that helps.
