### ISSUE TITLE
Dear Andrés M... Let's reorganize.

### ISSUE THREAD

**Issue by mipmip** [andmarti1424/sc-im#421]
Dear Andrés M.,

You prevented Sc from being forgotten and added great features to the reborn Sc-im. First time I visited your project it had 1K stars, since than the stars have doubled. A lot of people love this unique piece of good old fashioned unix software. Unfortnately the project is standing still and PR's stay open. 

You seem to be too busy to invest time into this one-man-project and that's not good for Sc-im. Sc-im deserves to be actively developed by a larger community of enthousiast volunteers. Vim and Neovim are more popular than ever, so now is the moment for Sc-im to grow it's own community. 

I'd like to invite you and everyone who is interested to discuss a new form of collaboration so that more people can contribute and the development goes faster. I know a lot of experienced developers would like help or be part of such a project.

Kind regards,
Pim Snel

**Comment by andmarti1424** [comment]
Yes. That's a good idea. Hope there is more people like you interested in collaborate. I am in

**Comment by mipmip** [comment]
Wow that's a quick reply. Great to hear you like the idea. :+1:

**Comment by mipmip** [comment]
As you are the founder of this project, your thoughts on how this project should be lead are now most important. Do you have idea's how you think it can be a larger community. And do you have a long term vision on how sc-im should evolve? This thoughts could be part of a mission statement.

**Comment by andmarti1424** [comment]
Well that's the thing. I do not know how it to become bigger. Do you have any ideas? About scim itself? I think the best would be to give more support.

**Comment by mipmip** [comment]
There might be templates to convert a personal project into a larger community project. I volunteered  in a few projects but I'm not manager myself :)

This might be a could start: https://opensource.guide/starting-a-project/ from section 3.

**Comment by mipmip** [comment]
I think a good start is too claim an organization name. sc-im is still free, so go on and claim it :) Within an organization it is easy to add volunteers you trust.

**Comment by msharov** [comment]
You don't need an organization to add volunteers; anybody can already be given write access to the project if that's what's necessary. Neither will volunteers magically appear if there is an "organization" attached. As things stand now, the main issue is more with lack of interest in sc rather than any difficulty in working on it, and that is not a problem we can solve.

**Comment by yamlCase** [comment]
I have to lend my support to this idea!  I have been on the hunt for a bare-bones, no frills, no formatting spreadsheet app for years and sc-im is the ONLY one available.  Bonus (for me) is that it is linux CLI.

**Comment by reportaman** [comment]
@msharov I think there will be immense interest, I didn't even know if such a thing existed in past. Given I don't see any commits since Sep 4, and there are show-stopper bugs (like https://github.com/andmarti1424/sc-im/issues/497). I have asked if neovim team is interested in bringing this utility under their umbrella: https://github.com/neovim/neovim/issues/14011

We software developers, and nerds forget that at times that tools are a human-interface. I think more improvements will only invite more people over time. I  started working on a [Dracula](https://draculatheme.com) theme for sc-im last night. (one can see sample in the neovim ticket I mentioned above). 

@mipmip @andmarti1424  I have posted and invitation for enthusiastic developers to chip in on ycombinator: https://news.ycombinator.com/item?id=26260201 and also posted on neovim (given there is so much commonality with the interface of this program): https://github.com/neovim/neovim/issues/14011

**Comment by andmarti1424** [comment]
@reportaman That would be great. Hope more people chime in so this piece of software move to another level.

**Comment by Iron-E** [comment]
> also posted on neovim (given there is so much commonality with the interface of this program)

I could see the benefit of using Neovim as a backend. For one, it could potentially allow plugin creation for this application using Lua(!!) which is a big bonus.

I know that Neovim supports creating external UIs on top of it (see `:help ui` for more info) but I am not sure if it is feasible to create a tabular UI which calls back to Neovim. I am completely unversed in C though, so I don't really have much to offer in terms of concrete solutions.

> Hope more people chime in so this piece of software move to another level.

As someone who uses this program pretty frequently, I think a big thing that would help propel it forward is cross-compatibility with :"industry standard" tabular editors such as Excel. If we can somehow get our `.sc` files to export with formulas intact (kind of hit-or-miss at the moment) that would go a long way towards increasing usability. It's a shame monolithic XML zips have taken over, `.sc` is a nice format (there might be some benefit to `.xlsx` I'm not aware of though).

**Comment by andmarti1424** [comment]
With LUA you can make read and write calls to SC-IM. This could be the communication to other applications.
But again, I would replace the core for something new (remember the evaluation core is from the 80's!)
Something that supports multiple sheets and cross references would be necessary.

About Excel, the thing is in sc-im there are not the same formulas as used on Excel. Nevertheless, the main 8 functions should be exported to .xlsx files without issues (see line 628 of xlsx.c)..

**Comment by DarkWiiPlayer** [comment]
@andmarti1424 [Lua](http://lua.org/about.html#name)*

**Comment by Iron-E** [comment]
> With LUA you can make read and write calls to SC-IM. This could be the communication to other applications.

I must have forgotten it can already do this. Perhaps making a Neovim plugin for `sc-im` would actually be more readily doable than I originally thought.

I left a mock on the Neovim issue of something that would be cool to do (rendering tables with `sc-im`). It'll take me some time to investigate but it would be worth trying IMO.

**Comment by reportaman** [comment]
@andmarti1424 Add a GitHub sponsorship button to your repo!

**Comment by andmarti1424** [comment]
@reportaman I just dont know which funding model to use..
Patreon may be?

**Comment by reportaman** [comment]
@andmarti1424 I have been following the project Asahi Linux, this is what its contributions page says: https://asahilinux.org/support/. They use both Patreon, and GitHub sponsorship. Given your GitHub page already has 2.6k likes, it is a good place to begin I think, you can create both together.

**Comment by andmarti1424** [comment]
I have created a patreon. I still have to see how much are the fees. For instance, Paypal directly, cuts 5.7% in my case. which is a lot!
