### ISSUE TITLE
Comparing Military Time

### ISSUE THREAD

**Issue by peterjschroeder** [andmarti1424/sc-im#428]
Is there an easy way to compare the difference between military times in sc-im?

Example: 0730-1600 = 8.5 hours

Right now I have this mess just to compare 2 cells.

@if(C6<B6, 2400-@ceil(B6*.01)+@ceil(C6*.01), @ceil(C6*.01)-@ceil(B6*.01))+1-(1-(@if(C6<B6, 2400-(B6+G6)*.01, (C6-B6)*.01)-@if(C6<B6, @floor(2400-(B6+C6)*.01), @floor((C6-B6)*.01))))/.60, -1

**Comment by mschilli87** [comment]
I would go with

```
=@div(B6,100)-@div(C6/100)+100*(@mod(B6,100)-@mod(C6,100))/60
```

where `@div(a,b)` is integer division a / b and `@mod(a,b)` the corresponding modulo.

As I am not aware of such functions in `sc-im`, I would implement `@div(a,b)` as `@floor(a/b)` and `@mod(a,b)` as `a/b-@div(a,b)`

All in all, this would yield

```
=@floor(B6/100)-@floor(C6/100)+5/3*(B6/100-@floor(B6/100)-(C6/100-@floor(C6/100)))
```

for your example.

Also not particularly pretty, but maybe a step forward? :wink:

**Comment by peterjschroeder** [comment]
Thank You,
Yours is definently less prone to failure as mine. It still ends up twice as long tho, as I have to put checks for if it goes to the next day:
@if(C6>B6, 24-....
I was hoping there were function already for this. In Libreoffice I just format the cell as military time than do C6-B6+(B6>B6)

**Comment by peterjschroeder** [comment]
It looks like there is a max formula size.

H,I is as far as it will go before bombing out and showing nothing.

let P6 = @if(B6>0, @if(B6<C6, @floor(C6/100)-@floor(B6/100)+5/3*(C6/100-@floor(C6/100)-(B6/100-@floor(B6/100))), @floor((2400+C6)/100)-@floor(B6/100)+5/3*((2400+C6)/100-@floor((2400+C6)/100)-(B6/100-@floor(B6/100)))), 0) + @if(D6>0, @if(D6<E6, @floor(E6/100)-@floor(D6/100)+5/3*(E6/100-@floor(E6/100)-(D6/100-@floor(D6/100))), @floor((2400+E6)/100)-@floor(D6/100)+5/3*((2400+E6)/100-@floor((2400+E6)/100)-(D6/100-@floor(D6/100)))), 0) + @if(F6>0, @if(F6<G6, @floor(G6/100)-@floor(F6/100)+5/3*(G6/100-@floor(G6/100)-(F6/100-@floor(F6/100))), @floor((2400+G6)/100)-@floor(F6/100)+5/3*((2400+G6)/100-@floor((2400+G6)/100)-(F6/100-@floor(F6/100)))), 0) + @if(H6>0, @if(H6<I6, @floor(I6/100)-@floor(H6/100)+5/3*(I6/100-@floor(I6/100)-(H6/100-@floor(H6/100))), @floor((2400+I6)/100)-@floor(H6/100)+5/3*((2400+I6)/100-@floor((2400+I6)/100)-(H6/100-@floor(H6/100)))), 0)+ @if(J6>0, @if(J6<K6, @floor(K6/100)-@floor(J6/100)+5/3*(K6/100-@floor(K6/100)-(J6/100-@floor(J6/100))), @floor((2400+K6)/100)-@floor(J6/100)+5/3*((2400+K6)/100-@floor((2400+K6)/100)-(J6/100-@floor(J6/100)))), 0) + @if(L6>0, @if(L6<M6, @floor(M6/100)-@floor(L6/100)+5/3*(M6/100-@floor(M6/100)-(L6/100-@floor(L6/100))), @floor((2400+M6)/100)-@floor(L6/100)+5/3*((2400+M6)/100-@floor((2400+M6)/100)-(L6/100-@floor(L6/100)))), 0) + @if(N6>0, @if(N6<O6, @floor(O6/100)-@floor(N6/100)+5/3*(O6/100-@floor(O6/100)-(N6/100-@floor(N6/100))), @floor((2400+O6)/100)-@floor(N6/100)+5/3*((2400+O6)/100-@floor((2400+O6)/100)-(N6/100-@floor(N6/100)))), 0)

**Comment by andmarti1424** [comment]
@peterjschroeder did @mschilli87 worked for you? @mschilli87,do you know the name of @div/@mod functions on openoffice/gnumeric/excel? May be we can add them here. Thanks.

**Comment by peterjschroeder** [comment]
Yes, but it ends up going over the FBUFLEN. A new function to handle this would be preferred as time sheets are pretty common. I'll see if I can track down where in LibreOffice it does this.

**Comment by andmarti1424** [comment]
@peterjschroeder I believe you can already achieve this doing :datefmt "%H%M" and then doing the substraction.

**Comment by peterjschroeder** [comment]
That kind of works. It totals it out in seconds and doesn't account for overnight shifts.

**Comment by andmarti1424** [comment]
Yes, in seconds. Sorry I dont know what overnight shift is. I also do now undestand what you mean with "= wont take.."

**Comment by peterjschroeder** [comment]
Overnight as in start time 0730 (AM), finish time 0630 (AM, the next day).

After formatting the cell with datefmt, if I go to that cell and change the 1600 to 1500, it puts 1925.

**Comment by andmarti1424** [comment]
If you need to change it, you still have to enter it as label. i have just made a commit so that you can avoid reapplying :datefmt..

**Comment by andmarti1424** [comment]
that means you can `\1500`, then `:datefmt "%H%M"`, and then `\1600` if you need to edit it..
yo can't use `E` since `:datefmt` converts the date to numeric value.

**Comment by peterjschroeder** [comment]
That works, thank you.

I can now reduce it to just this to check for next day.

@if(B0<A0, 24--((B0-A0)/3600), (B0-A0)/3600)

**Comment by andmarti1424** [comment]
Great then!

**Comment by mschilli87** [comment]
@andmarti1424:
> @mschilli87,do you know the name of @div/@mod functions on openoffice/gnumeric/excel?

Just in case this is still relevant. AFAIK LibreOffice Calc has `MOD` for the modulo. For integer division, I think flooring the general one would be required there as well.

**Comment by andmarti1424** [comment]
@mschilli87 yes.thank you. Do you know if in Excel it's the same?

**Comment by mschilli87** [comment]
@andmarti1424: Nope, I don't care about non-free software.

**Comment by andmarti1424** [comment]
Ok. Thanks
