### ISSUE TITLE
CSV parser fails for fields that start with comma

### ISSUE THREAD

**Issue by DarkWiiPlayer** [andmarti1424/sc-im#429]
The following CSV
```csv
foo,",",bar
```
gets parsed as 4 fields: `foo`, `"`, `"` and `bar` instead of the correct `foo`, `,` and `bar`

(tested on `a4abe78`)

**Comment by andmarti1424** [comment]
Hello @DarkWiiPlayer. Could you please update to latest commit and try again? Thanks.

**Comment by DarkWiiPlayer** [comment]
Indeed, this seems to work as expected in the latest version :D
