### ISSUE TITLE
Improvised vs. Improved

### ISSUE THREAD

**Issue by arne-cl** [andmarti1424/sc-im#43]
Dear Andrés,

why did you call your version/fork of `sc` "Spreadsheet Calculator Improvised" and not
"Spreadsheet Calculator Improved" like the relationship between `vi` and `vim` would suggest?
Is this some kind of inside joke?

Best regards,
Arne

**Comment by andmarti1424** [comment]
Hello. Saying that sc-im is an "Improved" version of sc would be a
personal appreciation
and not really a real fact. Some people will still prefer to use sc!

2016-02-01 8:07 GMT-03:00 Arne Neumann <notifications@github.com>:

> Dear Andrés,
>
> why did you call your version/fork of sc "Spreadsheet Calculator
> Improvised" and not
> "Spreadsheet Calculator Improved" like the relationship between vi and vim
> would suggest?
> Is this some kind of inside joke?
>
> Best regards,
> Arne
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/issues/43>.
>



-- 
Andrés Martinelli
