### ISSUE TITLE
@countif

### ISSUE THREAD

**Issue by peterjschroeder** [andmarti1424/sc-im#430]
I see that @count allows an expression to see if the cell is counted. Can we modify this function to be able to pass a string instead of a expression so it can be used to see if a range contains a string or a number?

Looking at the code, it can be done here:

if (!e || eval(NULL, e))

I tried implementing it myself by:

if (!e || eval(NULL, e) || doeqs(dosval(c, r), e))

but that doesn't work for 2 reasons. Column number is no longer a string at this point (where does it get converted to a number?) and e I'm not sure how to get the string out of it.

**Comment by andmarti1424** [comment]
@peterjschroeder you can countif like this:
![image](https://user-images.githubusercontent.com/9466161/115609521-02d60b00-a2be-11eb-9397-e148955e3e65.png)
Do you happen to have both numbers and strings in the range?

**Comment by peterjschroeder** [comment]
What I'm looking for is to check for a string in a cell.

@count(B0:B4,B0="blah")

**Comment by andmarti1424** [comment]
@peterjschroeder you know what. I thought the correct would be this: `@count(B0:B4, @eqs(B0,"blah"))`
But it does not work. neither on old sc. So may be I am wrong.
But this indeed works, which is similar: `@sum(D0:D4, @eqs(A0,"blah"))`
@reportaman,  you might know. any idea?

**Comment by andmarti1424** [comment]
or also this works, if you want to make it fixed: 
![image](https://user-images.githubusercontent.com/9466161/115716469-97d51480-a34f-11eb-8718-ae5ae82b18f2.png)

**Comment by andmarti1424** [comment]
@peterjschroeder I have done some research. The thing is that even on old sc @count function only count numbers and not cell with strings.
I have changed that so that cells with strings get counted as well!
so you can update to latest commit and try:
`@count(B0:B4, @eqs(B0,"blah"))`

**Comment by peterjschroeder** [comment]
That works, thank you.

**Comment by andmarti1424** [comment]
Great!
