### ISSUE TITLE
Crash upon changing clipboard paste setting

### ISSUE THREAD

**Issue by asivitz** [andmarti1424/sc-im#431]
If I change the clipboard paste command:

`:set default_paste_from_clipboard_cmd="pbpaste"`

sc-im crashes with:

`Config value changed: default_paste_from_clipboard_cmd[1]    8902 abort      scim`

The :help file says it should be modifiable at runtime. But anyway, if I start scim backup the setting has not changed.

**Comment by asivitz** [comment]
```
$ scim --version
Sc-im - version 0.7.0
```
I installed from `brew`

**Comment by andmarti1424** [comment]
I assume your in OSX. Could you please run it with gdb and send the output? Thanks!

**Comment by andmarti1424** [comment]
Do you still have this issue?
