### ISSUE TITLE
SVAL function returns error 'Illegal numeric expression'

### ISSUE THREAD

**Issue by Pariah-Dog** [andmarti1424/sc-im#432]
The @sval function does not work. 
Steps to reproduce the error:
1. Type in some text in cell B1
2. In cell B3, use formula =@sval("B", 1)
Cell B3 then contains 'ERROR', and the error message 'Illegal numeric expression' appears at the top left.

Initial investigation shows that the first expression to be evaluated is the row number, which is correctly handed to the eval function. However, eval does not contain a case for e->op == SVAL, and therefore drops through the case statement to arrive at the error above. The seval function, which does contain the SVAL case, is never called.

**Comment by andmarti1424** [comment]
You should enter string formulas typing
 \"

Not =

**Comment by andmarti1424** [comment]
This was fixed. Just be sure to enter the string expression like this:
\" @sval("B", 1)
