### ISSUE TITLE
Large increase in memory use upon paste and delete operations in certain spreadsheets

### ISSUE THREAD

**Issue by m7a** [andmarti1424/sc-im#433]
Hello,

I have found a memory-management issue but could not get my head around debugging it completely.

Here is how to reproduce it:

 1. `$ sc-im debugsc.sc`
 2. go to G1
 3. visual mark G1:G20
 4. `y`
 5. goto H1
 6. `Pc`
 7. Got:      Large increase in memory use (from 5 MiB to ~ 2 GiB), sc-im becomes unresponsive.
    Expected: Program responds immediately

Note: When saving the changes and opening the changed file, memory use is down to 5 MiB again... until one attempts to delete the newly added cells. If doing this with visual select and then `x`, memory use will again increase to around 2 GiB...

My local configuration (`~/.config/scimrc`) has this (but the problem seems to appear without any `scimrc`, too):

```
set autocalc
```

![Memory profiler screenshot](https://user-images.githubusercontent.com/18630636/89466212-b076ad80-d773-11ea-9624-f06dad6a4914.png)

Attachments

 * [debugsc.sc.txt](https://github.com/andmarti1424/sc-im/files/5031268/debugsc.sc.txt) -- failing spreadsheet
 * [debuglo.zip](https://github.com/andmarti1424/sc-im/files/5031267/debuglo.zip) -- same sheet in LibreOffice
   (does not exhibit excessive memory usage, thus it should not be the computation's problem)
 * [massif.out.1307.txt](https://github.com/andmarti1424/sc-im/files/5031279/massif.out.1307.txt) -- memory profiler data
   (obtained through `valgrind --tool=massif --heap=yes --stacks=yes ./sc-im debugsc.sc`)

System data:

 * git commit a4abe781c3131fd3a559c7e596ec33e6c406f821
 * Debian 10 GNU/Linux 4.19.0-9-amd64
 * gcc version 8.3.0 (Debian 8.3.0-6)

I appreciate it very much if someone more knowledgeable of the source code could check this issue?

Thanks in advance

**Comment by andmarti1424** [comment]
Thanks for reporting this. This is interesting. It shows that maybe the undo feature is not handled at it should when altering extensive number of cells.

**Comment by m7a** [comment]
I can add that at least from the user's perspective it does not only occur when copying multiple cells at once: In the attached spreadsheet, if one goes to H19, yy, j, Pc then it also increases memory usage quite a lot (around 800M). It seems less the number of cells being copied than how the computation is linked. In my sample spreadsheet, computation depends on another cell which in turn depends on another cell etc. It seems to me that this linking of the cell's computations somehow causes the large memory use.
[debugsc2.sc.txt](https://github.com/andmarti1424/sc-im/files/5036003/debugsc2.sc.txt)

**Comment by andmarti1424** [comment]
This froze my linux machine.
Without UNDO works ok. The problem, as you said, seems to be when having multiple cells links one to another and making any kind of change. There's something wrong when preparing the undo structure.

**Comment by andmarti1424** [comment]
@m7a made some changes. Please feel free to update to update to latest commit and try this again. Thanks.

**Comment by m7a** [comment]
I can confirm that the issue is resolved in 66e87b09d24ef5bfc395bf2b187f25589008a186. Thank you very much for the fix! From my point of view, the issue can be closed :) .

**Comment by andmarti1424** [comment]
Thank you for your time and research.
