### ISSUE TITLE
Feature request: Paste to a range of selected cells

### ISSUE THREAD

**Issue by Finxert** [andmarti1424/sc-im#438]
Maybe I'm somehow missing this but I don't think we're able to paste what we yanked to a range of cells or a group of selected cells in visual mode or with a command.

For example: Pasting the number 2, yanked from cell A2, to a group of selected cells betweeen b2:b10 is impossible, this isn't very dramatic since you can paste that number throught the cell range with the "fill" command like this: ":fill b2:b10 2 0" .
But the problem is that if you want to "expand" or "drag" a cell with "Pc" like you would in excel, it's impossible, and you have to "Pc" on every individual cell one by one.

Tell me if I'm not being clear enough.

**Comment by wimstockman** [comment]
Yes , I also feel this need.
I will look into it.
Kind Regards,
Wim

**Comment by leg7** [comment]
This issue can be closed now.

**Comment by ECon87** [comment]
I second this. This feature would be amazing

**Comment by andmarti1424** [comment]
@Finxert?

**Comment by Finxert** [comment]
> @Finxert?

Has the feature not been implemented?

**Comment by andmarti1424** [comment]
I have not done anything so I assume no

**Comment by Finxert** [comment]
> I have not done anything so I assume no

I'm 99% sure wimstockman fixed this in his pull request 

#445

**Comment by andmarti1424** [comment]
I see
Will check it out

**Comment by andmarti1424** [comment]
I reopen so it doesnt get lost.

**Comment by andmarti1424** [comment]
Yes.  This is working great. The only drawback, if you can call it like that, is that if you paste a cell in a range (10x10)... for its undo, you have to press 'u' 100 times.
may be an improvement for the future.
