### ISSUE TITLE
sc-im cannot process my .scimrc file

### ISSUE THREAD

**Issue by eliseukadesh67** [andmarti1424/sc-im#439]
My .scimrc file is like this : 

1. color "type=HEADINGS bg=BLUE fg=YELLOW"
~
~
EOF

And when i try to source the scimrc, i get this : 

**.scimrc:1: command not found: color**

I think i may be writing the color command wrong to work on scimrc, but i didn't found any template for writing this config.

**Comment by andmarti1424** [comment]
Please keep your .scimrc inside .config folder.

**Comment by eliseukadesh67** [comment]
> What version of linux to you use and what local settings are you using. I had some issues with numbers recognized as strings because of differrent local settings.

I'm running on Ubuntu 18.04 LTS
Kernel verison : 5.4.0-42-generic

**Comment by andmarti1424** [comment]
Did you try this:
"Please keep your .scimrc inside .config folder." ??

**Comment by andmarti1424** [comment]
Just check CONFIG_FILE and CONFIG_DIR variables in your Makefile. Sc-im read the config file according to those.

**Comment by eliseukadesh67** [comment]
> Just check CONFIG_FILE and CONFIG_DIR variables in your Makefile. Sc-im read the config file according to those.

I finally did it, i just named my scimrc file as "scimrc" instead of ".scimrc".

Thanks for helping

**Comment by sudoerena** [comment]
I had the same issue. Just for posterity, if anyone runs into this in the future, the config file should be under `~/.config/scimrc` with no dot.

Alternatively, edit Makefile to source `.scimrc` under your config directory.
