### ISSUE TITLE
utf8 and alignment

### ISSUE THREAD

**Issue by amerindias** [andmarti1424/sc-im#44]
I opened a csv that was in utf8, and although the accented characters appeared alright, alignment was messed-up. Here some lines from that file:

```csv
,,,,,,,
,O que,Quando,Quanto,Moeda,,US$ 1 =,"R$ 3,90"
,Passagem de Rafael para Denver/México,07/10/2015,"$873,00",USD,,Livia =,+
,Rede do Índio pro pai de Livia,01/11/2015,"-$76,92",USD,,Rafa =,-
,Cachaças,24/11/2015,"-$30,59",USD,,,
```

**Comment by andmarti1424** [comment]
Thanks for reporting this. Could you please send the csv file and a
screenshot of how it was imported, to scim.spreadsheet@gmail.com ??

Thanks again.

2016-02-01 16:05 GMT-03:00 amerindias <notifications@github.com>:

> I opened a csv that was in utf8, and although the accented characters
> appeared alright, alignment was messed-up Here some lines from that file:
>
> ,,,,,,,
> ,O que,Quando,Quanto,Moeda,,US$ 1 =,"R$ 3,90"
> ,Passagem de Rafael para Denver/México,07/10/2015,"$873,00",USD,,Livia =,+
> ,Rede do Índio pro pai de Livia,01/11/2015,"-$76,92",USD,,Rafa =,-
> ,Cachaças,24/11/2015,"-$30,59",USD,,,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andmarti1424/sc-im/issues/44>.
>



-- 
Andrés Martinelli

**Comment by rafaeln** [comment]
I've emailed you the screenshot and the utf8-encoded csv file. Thanks for this fork of sc! (I am @amerindias too).

**Comment by andmarti1424** [comment]
Received the files. I was aware of this issue and its not easy to fix since I believe I would have to change from ncurses library to libncursesw !

**Comment by andmarti1424** [comment]
I am working on fixing this.

**Comment by andmarti1424** [comment]
Please update to latest dev branch commit and try again.
You will have to edit the Makefile and link to -lncursesw rather than -lncurses

**Comment by rafaeln** [comment]
Now the alignment works perfectly! An new related issue I noticed is that I can't enter accented characters. But I'll open another issue for that.
