### ISSUE TITLE
Shifting cells left or up just deletes the cell's contents.

### ISSUE THREAD

**Issue by 27Spiff** [andmarti1424/sc-im#440]
With the cursor over the cell to be moved, 'sj' and 'sl' (shifting down or shifting right) works as expected, but shifting up or to the left (with 'sk' and 'sh') just deletes the cells contents.

**Comment by wimstockman** [comment]
Yes, indeed but if you think about it. It kind of make sense.
"Right" and "Down" are expanding the table, "Left" and "Up" are shrinking the table.
"Right and "Down" are pushing out, "Left" and "Up" are pulling it in.
How else could you handle the first column or first row?

Say you have a table with in A1=1, A2=2, A3=3. And your current cell is A2.
You shift it to the left, should A2 take the place of A1 and what should happen to the value in A1?

Kind Regards,
Wim

**Comment by andmarti1424** [comment]
Yes. This is the expected behavior
