### ISSUE TITLE
example gui

### ISSUE THREAD

**Issue by fab1an2** [andmarti1424/sc-im#446]
How compiling TUI /sc-im/examples/gui_example ?
Meybe change a small example. Only put text or number.

```
$ make
make: *** No rule to make target 'gram.y', needed by 'y.tab.h'.  Stop.
```

**Comment by andmarti1424** [comment]
You would mainly need to replace tui.c and tui.h of src folder with gui.c gui.h..

**Comment by fab1an2** [comment]
Could you improve the TUI so that it would work on its own? ncurses +ui, just displaying the text and e.g. entering text or numbers.

**Comment by 0xtrzy** [comment]
feel free and make your code working
**Your example not working !**

**Comment by andmarti1424** [comment]
I am already free thanks God. The example works.

**Comment by fab1an2** [comment]
I ask: HOW compiling example
please tell me how compiling it?

**Comment by andmarti1424** [comment]
I just build the gui example. What I did was:
Leaving gui.c and gui.h files INTACT, you copy them to src directory, You then delete tui.c and tui.h files. Modify Makefile to include gtk headers of course. 
Remove references to tui.c and tui.h and replace them with gui.c and gui.h.
It might have worked better just to replace tui files with gui files. Havent tried it.

Minimal changes to some files to remove a couple of references to tui variables and you are done. 5 minutes job.
To test it, what I did was, inside src directory, in a terminal:
./sc-im ../examples/plot/plot_line.sc 
This opens empty gui and as you move with hjkl keys you get back cell content in the terminal..

**Comment by wimstockman** [comment]
Maybe create a separate branch with the gui example ?

**Comment by andmarti1424** [comment]
The thing is I am not going to work in a gui. That is why you dont already see a branch for it.

**Comment by wimstockman** [comment]
Yeah, I know the purpose of scim is just that it is a console application :-)

**Comment by andmarti1424** [comment]
Dont get me wrong. It would be great for us to have an option to use it with gtk interface as well.
I dont know much of gtk.
I did such example so someone with experience in gtk could spend a couple of hours and write a useful gtk gui.
Its mainly rewrite that gui.c file.

**Comment by fab1an2** [comment]
1. Please add in Makefile section example-tui 
2. I talk about terminal code

**Comment by andmarti1424** [comment]
I dont understand you. You mean this???

```
  ifneq ($(shell pkg-config --exists gtk+-3.0 || echo 'no'),no)
    CFLAGS += $(shell pkg-config --cflags gtk+-3.0)
    LDLIBS += $(shell pkg-config --libs gtk+-3.0)
  endif

```

This is just linking to gtk library just as you would do for a simple "hello world" in gtk..

**Comment by alexandre-mbm** [comment]
I think the author's targets are clear and that he did much already for the community. This issue must to be closed (my opinion).

**Comment by andmarti1424** [comment]
Thank you!
