### ISSUE TITLE
how to print the value of a cell to standard output in a script in script?

### ISSUE THREAD

**Issue by PaulBatchelor** [andmarti1424/sc-im#447]
For example, say I wanted to print the contents of cell B8 in a .sc file to standard output, and maybe pipe that to some other process.

Is there a programmatic way to do this from the commandline without having to start up the interface?

**Comment by andmarti1424** [comment]
Yes. You can use both lua scripts or external scripts.  Please check doc file.

**Comment by PaulBatchelor** [comment]
Apologies. Which doc file?

**Comment by PaulBatchelor** [comment]
Which doc file?

**Comment by PaulBatchelor** [comment]
Which doc file?

**Comment by PaulBatchelor** [comment]
Which doc file?

**Comment by andmarti1424** [comment]
The one in src folder?
The same you see when you enter :help

**Comment by wimstockman** [comment]
hi, sc files is plain ascii you can just grep or awk the cell you want and
sent it to a script.


Op do 3 sep. 2020 17:07 schreef Andrés M. <notifications@github.com>:

**Comment by wimstockman** [comment]
if you want you can also use the :ccopy to copy to xclip and use the xcip command in your script

**Comment by PaulBatchelor** [comment]
Cool cool. I'll look into these options. Thanks!

**Comment by PaulBatchelor** [comment]
Cool cool. I'll look into these options. Thanks!
