### ISSUE TITLE
When overlap is set, display of oversized strings becomes sensitive to individual cell justification

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#448]
## Synopsis

When overlap option is not set in _.scimrc_, oversized strings display as asterisks.

When the option is set, oversized strings are displayed over adjacent empty cells to the right, but only if and while
the text is left or centre-justified. If and only if the text is right-justified, the oversized string display reverts
to asterisks, which is unexpected.

## How to demonstrate

In the _examples_ directory, run `sc-im sc/b.sc`, move cursor to cell `D1`. The status display shows the cell contents as
`|"FECHA PAGADO"`, indicating centre justification, and the non-overlapping portion `FECHA PAGA` displays, occupying the
full cell. Typing `{` changes to left justification, the cell display is unchanged. Upon typing `}`, the cell display
switches to all asterisks, and is restored only upon changing back to left (`{`) or centre (`|`) justification.

The inconsistency stands out further if one or more cells to the right are empty. In the preceding example, delete
contents of cell `D2` (command `x`). Then the overflow substring appears in `D2` if the justification is left or centre,
and disappears if right.

## Cause and thoughts towards a fix

The code that checks the string length, cell size and overlap setting in `src/cmds.c` also checks if `align == 1`.
Removing this check makes the display behaviour consistent across justifications, i.e., no more switching between
asterisks and text with `{` and `}`. I think the dependence on cell justification, which appears only when overlap is
set, is an anomaly. We may want to also consider the language in deciding what should be the right behaviour:

- overflow to left, right and both ways, depending on language direction (left to right, as in English, or reverse, as
  in Hebrew or Arabic), and the cell justification
- overflow always to right, or always to left again depending on language, regardless of justification
- overflow always to right, regardless of language and justification, following the column ordering.

For now, dropping the check seems the sufficient and simple solution for consistent UI. We may want to revisit the
overflow direction choices when issue #314 is addressed.

**Comment by andmarti1424** [comment]
Done with PR
