### ISSUE TITLE
entering utf8

### ISSUE THREAD

**Issue by rafaeln** [andmarti1424/sc-im#45]
The version of sc-im in the dev branch doesn't allow entering accented characters. More generally, the problem seems to be entering non-ascii characters.

**Comment by andmarti1424** [comment]
Yes indeed. Working on this. This will be changed in the short term.

**Comment by andmarti1424** [comment]
Again, please try latest dev branch commit.

**Comment by rafaeln** [comment]
Yeah, now I can enter them. The cursor does some strange things, as you can see in the images below (the `space` key wasn't hit in any moment), although the end result (as you can see in the last image) is fine. Is that relative to the changes you mentioned you still have to make?

![screenshot from 2016-02-03 11 39 20](https://cloud.githubusercontent.com/assets/2940362/12789386/aa48f20c-ca6b-11e5-86f3-26680ddd4d51.png)
![screenshot from 2016-02-03 11 39 33](https://cloud.githubusercontent.com/assets/2940362/12789391/ae971622-ca6b-11e5-840d-8612a187cf50.png)
![screenshot from 2016-02-03 11 40 23](https://cloud.githubusercontent.com/assets/2940362/12789394/b1165ba6-ca6b-11e5-8675-5f3d92026e35.png)
![screenshot from 2016-02-03 11 40 37](https://cloud.githubusercontent.com/assets/2940362/12789395/b3599414-ca6b-11e5-9201-d675f698c6cc.png)
![screenshot from 2016-02-03 11 41 12](https://cloud.githubusercontent.com/assets/2940362/12789401/b5a19352-ca6b-11e5-9b14-0fea8a52f020.png)
![screenshot from 2016-02-03 11 41 25](https://cloud.githubusercontent.com/assets/2940362/12789407/b7e32efa-ca6b-11e5-9ebe-05fcd950306c.png)

**Comment by andmarti1424** [comment]
Yes, because of the things you mention.

**Comment by andmarti1424** [comment]
Being working a lot on this issue. I created a new branch called "widechar".

Please take note that most char * functions changed to wchar_t *.. so a lot of code changed !!
This will be the v0.3 release of SC-IM.

Remember that to support UTF-8, ncursesw must be used for linking.

**Comment by andmarti1424** [comment]
Please test this again, updating to latest commit in widechar branch. This is now the default branch.
Thanks!!

**Comment by rafaeln** [comment]
Hi, @andmarti1424. I'm testing it and so far it seems to be perfect! Thanks. I'll let you know if I come across any bugs.

**Comment by andmarti1424** [comment]
Thank you very much.  If you find something (it's much probable since a lot of code changed because of this ),  please report it!
