### ISSUE TITLE
Add spreadsheet page support

### ISSUE THREAD

**Issue by leg7** [andmarti1424/sc-im#452]
Every spreadsheet manager supports the feature of having multiple spreadsheets in one file. For example the file "spreadsheet.sc" could have multiple other spreadsheets inside of it like "Spreadsheet 1" "Spreadsheet 2' "Spreadsheet 3". The image below shows this feature in an other spreadsheet manager.

https://i.imgur.com/UXojtkn.png

Since this feature is missing in sc-im, a lot of excel spreadsheet files are unusable and you have to go through another spreadsheet manager like google sheets.

**Comment by kourtbailey** [comment]
Rather than implementing "3-dimensional references" within a sheet, perhaps it would be both simpler and more general to implement "external references" to other sheets?  Then rather than a "workbook" concept, users could store the related sheets together in a directory.

**Comment by kourtbailey** [comment]
to further clarify, a user could use screen/tmux to manage multiple instances of `sc-im`.  This is how external references are handled in a major commercial spreadsheet: [https://www.dummies.com/software/microsoft-office/excel/using-external-cell-references-in-excel/]

**Comment by andmarti1424** [comment]
Yes. The idea is to add this feature in a v2 of SC-IM.
That would have a new core that supports multiple sheet and multiple files opened.
