### ISSUE TITLE
cannot load a file. 

### ISSUE THREAD

**Issue by sanjeebSubedi** [andmarti1424/sc-im#453]
I am trying to open a 460kb file on sc-im but it doesnot load. Sc-im opens up but its all dark screen.
I can open smaller files with no problems.

**Comment by alexandre-mbm** [comment]
@sanjeebSubedi, you need to give more details to they. For example, speaking about the file, its origin, filetype...

**Comment by andmarti1424** [comment]
it should open without problem. could you please attach the file?

**Comment by sanjeebSubedi** [comment]
I found out that the problem was while opening large files.

**Comment by andmarti1424** [comment]
It should not crash doesn't matter the size the size. Please attach the file if you have a problem with one.

**Comment by sanjeebSubedi** [comment]
I just checked it and its working fine now. It has been such a long time since I opened this issue. Maybe It got fixed in an update. Thanks.
