### ISSUE TITLE
EDIT MODE undo

### ISSUE THREAD

**Issue by bataliero** [andmarti1424/sc-im#454]
Hi, 
I extensively use EDIT MODE for text editing. Vast majority of commonly used bindings are available and work perfectly. Is there a plan to implement undo and redo 'u'/c+r for EDIT MODE? 

If it is not planned soon, in some spare time I might be able to contribute. Any tips where to start would be much appreciated.

Thanks

**Comment by andmarti1424** [comment]
Hello. If you confirm the edition. It leaves EDIT MODE and enters NORMAL MODE. Then you can undo/redo the changes to cells done in edit mode.

**Comment by bataliero** [comment]
Hi, I am aware that it possible, but that seems too "coarse-grained". I am looking for a undo/redo in EDIT MODE.

**Comment by andmarti1424** [comment]
No undo there. Just between editions.
If you ask me, cant imagine a use case for that.

**Comment by andmarti1424** [comment]
May be the previous value can be restored.
But if you made more than one change in the same edition. That would be restored too.

**Comment by andmarti1424** [comment]
Mainly all stuff should be in cmds_edit.c file. Your might need to store the cell content after each edition (wchar_* ) on a list, and free the list after confirm with ENTER or cancellation with ESC key.
you might like (or not) to store the current cursor position after each change as well.
here the important part: you then have to change inputline variable content with each 'u' undo or 'C-r' redo commands, based on the list you saved..

**Comment by andmarti1424** [comment]
@bataliero Please open a discussion for this FR. We'll leave the FR in there so we can discuss them and prioritize them for future releases. Thanks.
