### ISSUE TITLE
Freeze range does not work in visual mode

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#459]
The `doc` lists Normal Mode command `fa` for freeze selected area, but this never works. The `:freeze <range>` command in Command Mode works, so only the visual mode code for handling freeze, similar to yank etc., is missing.

**Comment by andmarti1424** [comment]
I believe it is working in normal mode:

Please type ma over one cell
then mb over other
then Rab
and then fa
Move down with C-f and the range marked above should be frozen..

**Comment by andmarti1424** [comment]
In visual mode it could be added..
Its not in the doc, so this is a feature request rather than an issue I believe.

**Comment by andmarti1424** [comment]
Hello. Could you test this? Thanks.

**Comment by earthshrink** [comment]
Yes, it works this way. Thanks!

**Comment by andmarti1424** [comment]
@earthshrink please update to latest commit and try freezing with 'f' in  visual mode. thanks.

**Comment by earthshrink** [comment]
Seems to be working now. Thanks!
