### ISSUE TITLE
How to set xclip at runtime?

### ISSUE THREAD

**Issue by 80aff123-9163-4f3e-a93d-4a2f35af9be1** [andmarti1424/sc-im#462]
On [this line](https://github.com/andmarti1424/sc-im/blob/freeze/src/Makefile#L55) it mentions that the variables below can be set at runtime. 

I've been trying to do that but I can't seem to figure it out.

How can I use the bash export command to do this without having to recompile sc-im?

I tried this at the sc-im command mode but I had no luck:

```sh
:set default_copy_to_clipboard_cmd="xclip -i -selection clipboard <"
```

What am I doing wrong here?

Any help is greatly appreciated!

I'm using sc-im 0.7.0:
 
```sh
Sc-im - version 0.7.0
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLS
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DUSELOCALE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="scim"
-DHELP_PATH="/nix/store/qqnm1k3iiz6rycrhq4fc67cdn6q59hnb-sc-im-0.7.0/share/scim"
-DLIBDIR="/nix/store/qqnm1k3iiz6rycrhq4fc67cdn6q59hnb-sc-im-0.7.0/share/doc/scim"
-DDFLT_PAGER="less"
-DHISTORY_FILE=".sciminfo"
-DINS_HISTORY_FILE=".sciminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by wimstockman** [comment]
You have to make the change in the makefile around line 60.
And then recompile sc-im.

**Comment by wimstockman** [comment]
change the tmux clip and paste lines to 
”xclip -i -selection clipboard <"
For the paste
"xclip -o -selection -clipboard"

**Comment by ccao001** [comment]
@wimstockman shouldn't it be possible to change that variable dynamically by running the set command in the editor?

my `.scimrc`
```sh
autobackup=0
autocalc=1
copy_to_clipboard_delimited_tab=1
debug=0
default_copy_to_clipboard_cmd=tmux load-buffer
default_paste_from_clipboard_cmd=tmux show-buffer
default_paste_from_clipboard_cmdxclip=xclip
external_functions=0
half_page_scroll=0
ignorecase=0
import_delimited_as_text=0
newline_action=j
nocurses=0
numeric=1
numeric_decimal=0
numeric_zero=1
overlap=1
quit_afterload=0
tm_gmtoff=-18000
trigger=1
xlsx_readformulas=0
```

after running `set:`
```
autobackup=0
autocalc=1
copy_to_clipboard_delimited_tab=1
debug=0
default_copy_to_clipboard_cmd=tmux load-buffer
default_paste_from_clipboard_cmd=tmux show-buffer
default_paste_from_clipboard_cmdxclip=xclip
external_functions=0
half_page_scroll=0
ignorecase=0
import_delimited_as_text=0
newline_action=j
nocurses=0
numeric=1
numeric_decimal=0
numeric_zero=1
overlap=1
quit_afterload=0
tm_gmtoff=-18000
trigger=1
xlsx_readformulas=0
```

**Comment by wimstockman** [comment]
Yes, you can 
You have some typo in your scimrc file
it is:
set default_copy_to_clipboard_cmd=xclip -i -selection clipboard <
set default_paste_from_clipboard_cmd=xclip -o -selection clipboard

**Comment by ccao001** [comment]
> Yes, you can
> You have some typo in your scimrc file
> it is:
> set default_copy_to_clipboard_cmd=xclip -i -selection clipboard <
> set default_paste_from_clipboard_cmd=xclip -o -selection clipboard

@wimstockman thanks for the help!

I fixed my config with your suggestion but copying to my system clipboard still doesn't work....
I get this error when using `ccopy` in scim:
```
 000/default (No such file or directory)
```

My ~/.scimrc currently looks like this:

```sh
set autocalc
set numeric
set numeric_decimal=0
set overlap
set copy_to_clipboard_delimited_tab=1
set default_copy_to_clipboard_cmd=xclip -i -selection clipboard <
set default_paste_from_clipboard_cmd=xclip -o -selection clipboard
```

I'm wondering if the problem is not with scim.

I'm running NixOS but I installed xclip with guix. Will try installing xclip with nix to see if the default setup changes something in the way xclip behaves...

**Comment by wimstockman** [comment]
Have you tested to set the clipboard in sc-im and not in the .scimrc file.
Maybe your scim rc file isn't loading.

**Comment by ccao001** [comment]
@wimstockman I just tested setting it in sc-im and it worked.I was able to copy with ccopy! Now to see why my scimrc file is not loading...

I have one in `~/.scimrc` and one in `~/.config/scimrc`

Thanks!

**Comment by wimstockman** [comment]
For the scimrc file to work you might put a dot infront of it or remove it.
It depends on what is in your makefile for the scimrc to work.

**Comment by ccao001** [comment]
This is what is in my makefile i.e. `scim --version`:
```
Sc-im - version 0.7.0
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLS
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DUSELOCALE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="scim"
-DHELP_PATH="/nix/store/qqnm1k3iiz6rycrhq4fc67cdn6q59hnb-sc-im-0.7.0/share/scim"
-DLIBDIR="/nix/store/qqnm1k3iiz6rycrhq4fc67cdn6q59hnb-sc-im-0.7.0/share/doc/scim"
-DDFLT_PAGER="less"
-DHISTORY_FILE=".sciminfo"
-DINS_HISTORY_FILE=".sciminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
syntax error
syntax error
```

**Comment by wimstockman** [comment]
Are you using nixos ?
It seems so. 
This distro places all kind of files on different places then normal Linux distros.
Can you post the makefile ?

**Comment by ccao001** [comment]
Yes I am using nixos.

I'm not sure where the Makefile is because I installed via `nix-env -i sc-im`

The full nix expression for sc-im [is here](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/misc/sc-im/default.nix#L17).

Here's the relevant part in that nix file that modifies the Makefile:

```nix
buildPhase = ''
    cd src

    sed 's/LDLIBS += -lm/& -lncurses/' -i Makefile

    sed -e "\|^prefix  = /usr/local|   s|/usr/local|$out|" \
        -e "\|^#LDLIBS += -lxlsreader| s|^#||            " \
        -e "\|^#CFLAGS += -DXLS|       s|^#||            " \
        -i Makefile

    make
    export DESTDIR=$out
  '';

  installPhase = ''
    make install prefix=
  '';
```

**Comment by ccao001** [comment]
@wimstockman 

Any help is greatly appreciated. If there's a fix that is needed in the nix expression above I'd be happy to collaborate on that to send upstream.

**Comment by ccao001** [comment]
Nix has services that can be turned on in one's configuration.nix.

[Here's an example](https://search.nixos.org/options?channel=unstable&show=services.emacs.defaultEditor&from=0&size=30&sort=relevance&query=emacs).

`services.emacs.defaultEditor` When enabled, configures emacsclient to be the default editor using the EDITOR environment variable.

Maybe this is relevant for sc-im. 

i.e. `services.scim.defaultClipboard` can take a defualt value of a string set to "tmux"

A user can then set it to xclip like so:

```nix
services.scim.defaultClipboard = "xclip"
```

The above would expand to the following in the config:

```
set default_copy_to_clipboard_cmd=xclip -i -selection clipboard <
set default_paste_from_clipboard_cmd=xclip -o -selection clipboard
```

or it would set the right options in the makefile.
