### ISSUE TITLE
Merge two cells visually

### ISSUE THREAD

**Issue by wimstockman** [andmarti1424/sc-im#464]
Hi, 
it would be nice if we could merge cells to one. So we could create some sort of text area without affecting all the columns sizes. Or even just some text overflow method....
Is anyone keen on implementing this feature ?
Kind regards,
Wim

**Comment by earthshrink** [comment]
I would like this feature too. I have been copying empty adjacent cells to maintain the background colour etc.

**Comment by leonardorame** [comment]
Apart from cell merge, I noticed when I type a text longer than the width of the cell, it is replaced with `*****`, is there a way to let the text overflow the adjacent cells, just like Libreoffice or Excel?.

**Comment by andmarti1424** [comment]
@leonardorame yes. There is a config variable you can set for this. Please check help file

**Comment by reportaman** [comment]
@andmarti1424 Works for left-aligned, and center-aligned strings. Puts asterisks for long right aligned string. I bet this is a feature? Or is it a bug?

**Comment by andmarti1424** [comment]
@reportaman Thats whats it is expected I believe.
The merge feature can be done. The thing is how they get shown in the spreadsheet. The workarounds work ok IMHO.

**Comment by andmarti1424** [comment]
@wimstockman  Please open a discussion for this FR. We'll leave the FR in there so we can discuss them and prioritize them for future releases. Thanks.
