### ISSUE TITLE
Multiple conditions and relativity within @sum()

### ISSUE THREAD

**Issue by Ingvix** [andmarti1424/sc-im#465]
Okay, so I have the following kind of situation (the actual sheet contains more rows):

```
        A         B         C         D         E         F         G         H         I
  0     A       10979454    12.217   Left     Index                          Left     Right
  1     I        9721557    10.817   Left     Middle              Index        
  2     N        7931655     8.826  Right     Index               Middle
  3     T        7863815     8.750  Right     Middle               Ring
  4     E        7160531     7.968   Left      Ring               Pinky

```
And I want to sum values in C column based on the column and row titles on the right. I'd also want to do this in a way I could copy to all the other cells on the table on the right side

Now, I build this function that does it well for the H1 cell:
```
@sum($C$0:$C$28, @eqs(@if(@eqs($E0,$G$1), $D0, ""), H$0))
```
The first question is could this be done more elegantly without stacking functions like this and I just missed it?

The second question is can I somehow make a relative reference to a cell in the @sum() function that does not change while the function goes through the assigned range? The `H$0` works fine since the range is within a single column but if I'd change `$G$1` to `$G1` it wouldn't work since the row number starts changing while going through the range rows. In this case where there's only 8 cells to fill, I can easily fix it by hand but I was just wondering if there's a way to have it relative for the use of `Pc` while having it absolute for the @sum()?

**Comment by Ingvix** [comment]
Did some testing and found out that I can just combine expressions simply with `&`. It's just that I couldn't actually search for the character in `:help` since it seems to find all the headers with it rather than the actual character. Escaping it with \ doesn't seem to work either for the search. Anyways, that's pretty much solved now. Now this is just about the relativity issue.

**Comment by andmarti1424** [comment]
Hello. You have to use @fixed(B0) as the expression in the condition.

**Comment by Ingvix** [comment]
Thanks. So now I can have an absolute position for the expression while keeping it relative when copying to other cells. Can I do the opposite somehow? To keep a single cell position absolute while copying but relative when used with range. While having some other positions within the expression that need to be relative while copying so I can't just paste it with `p`.

**Comment by andmarti1424** [comment]
I believe that's a whole different thing. Do you mean what `Pc` in normal mode does?

**Comment by Ingvix** [comment]
I mean that when I use `Pc` to copy some expression to another cell, I'd like to have a certain cell coordinates absolute while copying while keeping them relative in the expression when working with ranges. So the end goal is keeping something like $B0 as $B0 when pasting with `Pc` and not have it change to $B1 on the next row and so own.

**Comment by andmarti1424** [comment]
Mmm. I really don't know if that's even possible on sc. Do you know? Any other spreadsheet program has that feature?

**Comment by Ingvix** [comment]
No, I don't know. I'm asking purely based on my use case where that would make things a bit easier. It's probably not something you'd need too often so it's no wonder if it's not implemented.

**Comment by Ingvix** [comment]
But I got the answers for the original questions so I'll close this issue.
