### ISSUE TITLE
Using @now in sc-im

### ISSUE THREAD

**Issue by taviso** [andmarti1424/sc-im#466]
Hello, if I create a cell with the value `@now` in classic sc, it contains the current UNIX time. I can keep pressing `@` to recalculate values, and it updates.

If I enter `@now` in sc-im, it seems to always be zero, is this a bug?

Reproduce:
1. Start a new spreadsheet.
2. Hilight cell A0, and type `=@now`
3. The cell shows 0.00.

Expected:

The cell shows the current UNIX time.

**Comment by andmarti1424** [comment]
Hello. I believe its a bug. It should enter then numeric value of current date time. And then after use of datefmt command you should see it correctly. The failure seems to be in the first one of those.

**Comment by reportaman** [comment]
@andmarti1424 Even these expressions put numeric value ``0.00``: ``=@mycol``, and ``@myrow``.

**Comment by andmarti1424** [comment]
Please update to latest commit and report back!
Dont forget to convert the numeric value to a dateformate (see doc if in doubt)

**Comment by Luc-Saccoccio** [comment]
On my side, `@now` now prints the current UNIX Time.

**Comment by andmarti1424** [comment]
Excellent!

**Comment by Luc-Saccoccio** [comment]
> I'm not sure if `datefmt` works, of if I don't know how to use it. Nevertheless, using `:datefmt "%d/%m/%Y"` on the cell with `=@now` just updates the value.

I might have not been clear : It update the time in seconds, it doesn't change the date format.

**Comment by andmarti1424** [comment]
You have to type:
:format "d%d/%m/%Y"

**Comment by andmarti1424** [comment]
BTW,  :datefmt is a command used to convert a date (that you entered as text) into the numeric value and with date format applied..

**Comment by Luc-Saccoccio** [comment]
Oh, I'm sorry ^^

**Comment by andmarti1424** [comment]
No need to apologize
