### ISSUE TITLE
refman.tex

### ISSUE THREAD

**Issue by alexandre-mbm** [andmarti1424/sc-im#469]
I would to get the ``refman.pdf``, but at ``sc-im/src/latex`` directory we have a ``Makefile`` only.

Was all migrated to the ``doc`` file?

**Comment by andmarti1424** [comment]
I was always at doc.  But the tex file should be generated..

**Comment by andmarti1424** [comment]
@alexandre-mbm I really cant recall. It might be related to doxygen..

**Comment by andmarti1424** [comment]
@charlespax do you have a clue? might it be related to the work you have done to include Doxygen? Thanks.

**Comment by andmarti1424** [comment]
@alexandre-mbm sorry I can't give you a proper answer to your inquire. I would probably remove that stuff in future since I cant really recall its origin.
