### ISSUE TITLE
Add ZZ and ZQ commands

### ISSUE THREAD

**Issue by kdkasad** [andmarti1424/sc-im#471]
In Vim, pressing `ZZ` when in normal mode will save and quit the current file (equivalent to `:wq`). `ZQ` quits without saving (equivalent to `:q!`). It would be nice to have this in sc-im as well.

**Comment by andmarti1424** [comment]
I believe you could create a mapping to achieve that. Did you try it?

**Comment by kdkasad** [comment]
I hadn't even thought of that. The following two mappings implement this:
```
nmap "ZZ" ":wq<cr>"
nmap "ZQ" ":q<cr>"
```

Although pressing `ZZ` with no filename and no changes to the spreadsheet will cause a `There is no filename` error instead of exiting.
