### ISSUE TITLE
EXECUTE syntax error

### ISSUE THREAD

**Issue by cmF3** [andmarti1424/sc-im#474]
>     EXECUTE "{STRING}"
>         Call an internal COMMAND MODE command. Examples:
>         EXECUTE "load! /tmp/test.xls"
>         EXECUTE "e! mkd /path/test.md"

$ cat example.sc
EXECUTE "load! /tmp/test.xls"
EXECUTE "e! mkd /path/test.md"
$ sc-im example.sc --nocurses --quit_afterload
syntax error
syntax error
$ cat example.sc|sc-im --nocurses --quit_afterload
Interp will receive: EXECUTE "load! /tmp/test.xls"

syntax error
Interp will receive: EXECUTE "e! mkd /path/test.md"

syntax error
$

**Comment by andmarti1424** [comment]
What version of SC-IM are you using?

**Comment by andmarti1424** [comment]
Btw Dont know what is the intention/purpose of this command.. Did not create it myself.

**Comment by andmarti1424** [comment]
It seems the way to write it is like this:
EXECUTE "load a.csv"

The ! after load is wrong

**Comment by cmF3** [comment]
> What version of SC-IM are you using?
```
$ sc-im --version
Sc-im - version 0.7.0
```
> Btw Dont know what is the intention/purpose of this command.. Did not create it myself.
It allows you to script sc-im, in the example given in the manual it would convert a .xls file to a markdown table, I guess.

> The ! after load is wrong
```
$ cat example.sc
EXECUTE "load /tmp/test.csv"
EXECUTE "e mkd /tmp/test.md"
$ cat example.sc|sc-im --nocurses --quit_afterload
Interp will receive: EXECUTE "load /tmp/test.csv"

syntax error
Interp will receive: EXECUTE "e mkd /tmp/test.md"

syntax error
$

**Comment by andmarti1424** [comment]
Hello. Could you test it? Thank you.
