### ISSUE TITLE
Not installing?

### ISSUE THREAD

**Issue by josephgerth** [andmarti1424/sc-im#476]
Newb here, so I apologize if this is a dumb question or in the wrong place.

I was able to get sc-im running on Pop OS 20.10. I followed the instructions from the wiki, which gave directions for installing on Ubuntu. I am not, however, able to launch sc-im from the terminal as it states. When I type sc-im into the terminal, it says "Command 'sc-im' not found, did you mean:..." 

However, I am able to open the program when I change directory to home/sc-im/src, and then typing in "./sc-im". I have not found the executable file in my file explorer, and a quick search after hitting the Super key does not show it either. It looks like the only way for me to open the program is to go through two steps on the terminal, each of which takes more time than it should.

Any suggestions?
Thank you for your time.

**Comment by josephgerth** [comment]
I should add that when I access sc-im this way, I cannot save anything. Using :w prompts "File could not be saved".

**Comment by andmarti1424** [comment]
May be a permission issue not letting the binary get copied to a binary path during install.
The same with 2nd message. Seems a permission issue.

**Comment by andmarti1424** [comment]
Could you solve this?

**Comment by kdkasad** [comment]
@josephgerth Can you post the (exact) output of the commands you ran to install sc-im? My guess is you didn't run `make install` as root, which is necessary to install system-wide.
