### ISSUE TITLE
Where is cell color info saved?

### ISSUE THREAD

**Issue by sarpu** [andmarti1424/sc-im#479]
I am changing the cell colors of a csv file via ` :cellcolor A0:H0 "fg=RED bg=BLACK" `, but upon saving and reopening the file, the colors are lost. From the past issues, I figured out that there is possibly a .sc file, but I don't know where to find it. Is it possible to save color info for csv files somewhere (on a per file basis, as opposed to using .scimrc)? Thank you for the project!

**Comment by andmarti1424** [comment]
Hello. Csv is text
you can't save colors there. You only can use colors in sc files..

**Comment by sarpu** [comment]
👍 thank you
