### ISSUE TITLE
Lua scripting documentation

### ISSUE THREAD

**Issue by leonardorame** [andmarti1424/sc-im#481]
I would like to insert data from an external source (a PostgreSql database, for examle). As far as I understand I need to create a Lua script.

Where can I find documentation or examples of Lua scripts that interact with SC-IM ?.

**Comment by reportaman** [comment]
@leonardorame I think its already there in the src/doc: https://github.com/andmarti1424/sc-im/blob/freeze/src/doc#L1446-L1482, and check https://github.com/andmarti1424/sc-im/blob/freeze/examples/lua/macro.lua as an example
