### ISSUE TITLE
Sum in date range

### ISSUE THREAD

**Issue by bin** [andmarti1424/sc-im#483]
I have a range of rows from which I would like to sum one column.  I want to add each value to the sum if and only if the date in another column in that same row is within a range.  The issue I have here is that I cannot figure out how to reference a column in the current row in the expression for `sum()`.  I want to do this: `@sum(A0:A10, @month(#B)=1)`, where `#B` references each row in a loop.  Is there a mechanism for doing this?  Thank you.

**Comment by andmarti1424** [comment]
I believe this could be done with the nval and sval functions. Let me try to remember and report back..

**Comment by andmarti1424** [comment]
No the correct answer is:
@sum(B1:B4,@eqs(C1,"JANUARY"))
![image](https://user-images.githubusercontent.com/9466161/109331036-1a06f800-783b-11eb-9798-b141bfcd3779.png)
But its not working correctly. Let me see.

**Comment by andmarti1424** [comment]
Actually it is working ok. Like this:

![image](https://user-images.githubusercontent.com/9466161/109331186-4fabe100-783b-11eb-9b53-8e7b6f12783a.png)

**Comment by andmarti1424** [comment]
Hello. Could you test it? Thank you.
