### ISSUE TITLE
Apple Silicon macOS, colors are not applied from .scimrc for manual build from source, and are applied in homebrews version

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#490]
I am trying to build sc-im from source on macOS BigSur Apple Silicon. Even though I linked sc-im to ``libncursesw``, any color setting I do in my $HOME/.scimrc file are not applied in sc-im that I build. Homebrew's scim build does pickup color changes... What do I need to do?

```
otool -L /usr/local/bin/sc-im 
/usr/local/bin/sc-im:
	/opt/homebrew/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/opt/homebrew/opt/libzip/lib/libzip.5.dylib (compatibility version 5.0.0, current version 5.3.0)
```

**Comment by reportaman** [comment]
Fixed! The default config dir for homebrew's installation was different chosen by default by src/Makefile.

```
-DCONFIG_DIR=".config"
-DCONFIG_FILE="scimrc"
```

Now colors get applied!

**Comment by hatunike** [comment]
I've been spelunking through the issues the last couple of days and it seems like it's pretty common for users to get hung up on the config file now being assigned to the ~/.config/scimrc (which is exactly where it should be!). But I think the problems is just that it's not clear from the README how to setup the config file.

**Comment by andmarti1424** [comment]
I will add it to the doc! THanks
