### ISSUE TITLE
Keymapping Challenges

### ISSUE THREAD

**Issue by kevinduffbeer** [andmarti1424/sc-im#492]
Hi, thanks for this great program. Much prefer using it for basic spreadsheet operations over other GUI alternatives. 

I've been trying to implement a few keymaps but haven't been successful. I've read the man page, help file and reviewed past issues, but still not sure what can be done.
`inoremap "jj" "<TAB>"`
`inoremap "<S-<CR>>" "<CR>lk"`
`nnoremap "<C-s>" ":w<CR>"`

The first keymap uses jj to exit insert mode (noticed that escape can't be remapped but tab can and seems to have the same behavior as escape in insert mode), a common keymapping in vim. The second attempts to leave insert mode / accept changes and move one cell to the right (similar to issue #296). The third tries to write the file using control-S... however I've noticed that on my system, typing C-s leaves sc-im unresponsive (regardless of if the above mapping is attempted or not).

Sorry if I'm not looking in the correct place for a solution. Any help would be appreciated. :)

**Comment by andmarti1424** [comment]
Hello. Actually I also have a mapping (kj) to ESC in vim. let me see if there is something that can be done. If I recall well.. I used to have an issue with the ESC key and ncurses.

**Comment by kevinduffbeer** [comment]
Thanks for having a look at this. :) If it's any help, the above three remaps work if I assign the left side of the keymap to a single alphanumeric key. So it seems that the issue is with the left side of the mapping and not the right side. I've tried modifying the left side of the remaps but can't get multiple key sequences to work (e.g. j followed by j). Having more remapping flexibility would be a great addition so that the program could be modified/extended depending on the users needs.

**Comment by andmarti1424** [comment]
Please feel free to update to latest commit and try this:
imap "kj" "<ESC>"
cmap "kj" "<ESC>"
In my last commit I have added mappings for command mode.
And it should also handle <ESC> key in mappings now.

The C-s blocking situation might be a terminal issue.. I shouldn't use that sequence.
<S-SPECIALKEY> is not supported. I dont believe ncurses can handle it. That is more of xterm thing.

**Comment by kevinduffbeer** [comment]
Hey, thanks for you work on this!

I've tried the suggested mappings but unfortunately they don't appear to be working. They're working on your side?

BTW, I can open a separate issue for this but after the recent update I'm noticing that my custom color scheme is no longer working. With the new feature "Add custom colors with RGB definitions." in the 0.8.0 commit, will the scimrc file require a change to how colors are coded? I can provide further details in a new thread.

**Comment by andmarti1424** [comment]
Where do you have your scimrc file?
The mappings above should be typed in less than a second, otherwise it would time the 'k' character

**Comment by kevinduffbeer** [comment]
Hey... my scimrc is in ~/.config/sc-im/scimrc
And yes... I am typing k and j within less than a second of themselves.

**Comment by andmarti1424** [comment]
And other mappings (lets say some mappings in normal mode) work for you?

**Comment by kevinduffbeer** [comment]
Yeah, other mappings work fine (when setting from x prompt within sc-im or when setting using the rc file). It appears that the issue for me is key sequences like the "k" followed by the "j".

**Comment by andmarti1424** [comment]
Pretty weird. The <ESC> mapping is working for you in the right size?

**Comment by andmarti1424** [comment]
The <ESC> part i mean

**Comment by kevinduffbeer** [comment]
I'm not quite sure what you mean when you ask if the mapping is working in the "right part"?

**Comment by andmarti1424** [comment]
Sorry
I meant if the mapping to the ESC worked OK for you.

**Comment by kevinduffbeer** [comment]
Actually...
`imap "j" "<ESC>"`
...doesn't work, however...
`imap "j" "<TAB>"`
... does work to leave Insert mode and enter Edit mode. I think you mentioned previously that it wasn't possible to use <ESC> with ncurses? However, trying to map a two sequence combination like...
`imap "jk" "<ESC>"` or `imap "jk" "<TAB>"`
...doesn't work regardless of if the right-hand side is <ESC> or <TAB>. My original intention was to use 'jj' to exit Insert mode and enter Normal mode (also exiting Edit mode) but this seems like it may not be possible with the current setup? The idea is to have a quick two key press combination on the home row to stop editing and get back into the business of navigating the document. Perhaps I'm making this a little too convuluted considering this can also be done with two presses of Esc. Overall was just trying to make my sc-im workflow more similar to what I'm currently using in nvim.

**Comment by andmarti1424** [comment]
Actually it should work with my latest changes. Please post the output of :showmaps

**Comment by andmarti1424** [comment]
you updated to latest commit, right?

**Comment by kevinduffbeer** [comment]
Yes, I updated to 0.8.0

With the following in my scimrc...
`	imap "kj" "<ESC>"
	cmap "kj" "<ESC>"`

The :showmaps command returns...
`      1 + imap "kj" =  ""`

I also see a 'syntax error' when entering sc-im but only when including the cmap remapping in the scimrc. Thanks for your help with this and my appologies if I missed a step somewhere along the line.

**Comment by andmarti1424** [comment]
Yes v0.8 is the latest release, from two weeks ago.but for you to use ESC key and command mode mappings you have to get latest changes from git. (I made them today). Please update to that and try again

**Comment by andmarti1424** [comment]
You should be able to use other special chars in mappings. Such as ñ á, etc..

**Comment by kevinduffbeer** [comment]
Hi, I'm so sorry about my misunderstanding. I've now updated to the latest commit and can confirm that the remap is working. Sorry for the extra work it resulted for you and thanks for your committment to sc-im.
