### ISSUE TITLE
Check the extension user is trying to write to, and at least warn

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#493]
I recently downloaded scim, and tried to write a few files to .xlsx format using a wrong command ``:w filename.xlsx``. Then I tried opening it with ``sc-im filename.xlsx``. It showed a blank file. I realized that the format ``:w`` writes to is sc-im's own format & there is a different way of exporting it to other formats. It would be a good check to at least warn user if he/she is trying to "write" to ``.xlsx`` or ``.csv`` format by mistake using ``:w``. I had filed an issue (which I closed) because of the confusion caused by this behavior: https://github.com/andmarti1424/sc-im/issues/485#issuecomment-784547491

**Comment by andmarti1424** [comment]
This is done. Now it saves in the format of current file. Btw, this was already done for other formats, such as csv.
It was missing for xlsx.
