### ISSUE TITLE
Enhancement: Add support to use more colors

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#495]
AFAIK, at any given point of time, only these colors: ``WHITE, BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, DEFAULT_COLOR`` can be used. Given we now have ncursesw 256 color support, it would be great if one can specify R G B (0-1000 in ncursesw syntax) directly or define & use new colors by name. That will enable using more colors in the user interface.

**Comment by andmarti1424** [comment]
Hello. Actually you can redefine colors like this:

REDEFINE_COLOR "RED" 65 800 0

Dont remember if this is in the doc file or not..

**Comment by reportaman** [comment]
@andmarti1424 Sorry if I wasn't clear. What I meant was, at any given point in time, there can be only 9 colors that can be used (names mentioned above) to apply to 18 color categories: ``HEADINGS, MODE, NUMB, STRG, DATEF, EXPRESSION, CELL_ERROR, CELL_NEGATIVE, CELL_SELECTION, CELL_SELECTION_SC, INFO_MSG, ERROR_MSG, CELL_ID, CELL_FORMAT, CELL_CONTENT, WELCOME, NORMAL, INPUT``, and any random cell that one wishes to color. But, in reality we have 1000*1000*1000 possibilities of colors to be used, each different for each cell in a pathological case (though of course on one would use it that way I guess).

If I do this sequence:
```
REDEFINE_COLOR "MAGENTA" 600 100 600
color "type=EXPRESSION fg=MAGENTA bg=DEFAULT_COLOR"
REDEFINE_COLOR "MAGENTA" 500 500 500
color "type=HEADINGS fg=MAGENTA bg=DEFAULT_COLOR"
```

Both EXPRESSION and HEADINGS will be colored by 500, 500, 500. 

Ideally, the program would accept a command like: ``color "type=EXPRESSION fg=(600,100,600) bg=DEFAULT_COLOR"``  ``"type=HEADINGS fg=(500,500,500) bg=DEFAULT_COLOR"`` 

or even better accept RGB in range 0:255, and internally multiply by (1000/255), and truncate after decimal. This will enable users to use standard RGB 256 numbers directly from internet, instead of converting to ncursesw's format RGB 1001

Or you could give them the option to "DEFINE" new colors by names, and use them like this:
```
DEFINE_COLOR "GRAY50" 500 500 500
color "type=HEADINGS fg=GRAY50 bg=DEFAULT_COLOR"
```

I think the former method is ideal, as defining colors and using them is awkward if you were to use it to color a single cell with ``:cellcolor``

**Comment by hatunike** [comment]
I too would love this as i've run into the issue of max number of color slots as described above. Another workaround could even just be to bump up the number of color slots. 16 should be the minimum imo. Although, I too like either proposed solutions by @reportaman better than just adding a few more color slots.

**Comment by andmarti1424** [comment]
I am working on adding RGB definitions.. It will take some time though.
I managed to get it working with latest ncurses functions.

**Comment by andmarti1424** [comment]
About how to implement this, I believe the least invasive would be to create 24 USERCOLOR slots..
And use them in types definitions like this:

DEFINE_COLOR USERCOLOR1 196 89 89
color "type=HEADINGS fg=USERCOLOR1 bg=BLACK"
or something like that.
The reason of this is because in ncurses, once you define your colors, you have to define the initpairs (a combination of fg and bg), and I believe those are 65536 max (assuming your terminal supports 256 colors as well).
Currently, we have 8 different colors and 64 initpairs defined with the different combinations between them.
We can then have 32 different colors, 1024 initpairs defined..

**Comment by reportaman** [comment]
@andmarti1424 32 colors should be sufficient for creating good themes! Also, it will be good to be able to detect if terminal supports 256+ colors or not, and make a selection in ``.scimrc``. In ``.vimrc`` users can do something like this:

```
if &t_Co > 16
    " Do something.
endif
```

**Comment by andmarti1424** [comment]
Yes. Of course I would check that.
If not handled by terminal, custom colors would be overriden to a plain black and white, or something.

NOTE: Actually, user defined colors would be 24.
Cause be will keep ncurses 8 colors intact. (You could redefine those 8 colors though).

**Comment by reportaman** [comment]
@andmarti1424  Most terminals I come across seem to support 16 colors (there are BRIGHT* equivalents, like RED and BRIGHTRED). If that is something that ncurses supports, you might want to expand the base colors to include BRIGHT* versions, that way terminals that do not support 256 colors, have 16 colors; that way users are left with 16 additional color names that they can define. This has the advantage that even for non-256 terminals, there can be a 16-color theme.

Btw, just to clarify one point: name ``USERCOLOR1`` is just a representative name right? Ideally users can specify some color representative color name (like SKYBLUE), and not ``USERCOLOR<number>``

**Comment by andmarti1424** [comment]
The bright attribute, also the bold attribute, are already supported both on ncurses and sc-im

**Comment by andmarti1424** [comment]
Yes to the other. Use custom names

**Comment by andmarti1424** [comment]
Please, feel free to test this with latest commit.

```
DEFINE_COLOR "cyan" 32 245 239                                                 
color "type=HEADINGS fg=BLACK bg=cyan"
```

**Comment by reportaman** [comment]
@andmarti1424 Seems close! Two issues, and one enhancement:

1. Colors defined with DEFINE_COLOR, and REDEFINE_COLOR do not look same. Try for instance:
```
DEFINE_COLOR "myred" 255 0 0
REDEFINE_COLOR "RED" 255 0 0
```
2. ``:define_color`` gives error "COMMAND NOT FOUND", ``:redefine_color`` does not give such an error & works.
> As a sidenote ``:h`` works, ``:h `` (with one space character after ``:h``) gives error "COMMAND NOT FOUND".

3. ``:redefine_color`` does not work on user defined colors. I guess that won't be needed if ``:define_color`` works... 

Here's a GIF that shows all 3 problems (not in any order):
![Screen Recording 2021-03-14 at 6 33 12 PM](https://user-images.githubusercontent.com/71736629/111093554-77b36980-84f6-11eb-85eb-6a102f85d75a.gif)

**Comment by andmarti1424** [comment]
Yes. I still have to add it to the command mode.
Please add this to your scimrc file:

DEFINE_COLOR "cornsilk" 255 248 220
DEFINE_COLOR "wheat" 245 222 179
DEFINE_COLOR "dark_khaki" 189 183 107
DEFINE_COLOR "gray50" 127 127 127
DEFINE_COLOR "gray80" 204 204 204
DEFINE_COLOR "gray90" 229 229 229
color "type=GRID_PAIR fg=verde bg=cornsilk"
color "type=GRID_ODD fg=verde bg=wheat"
color "type=HEADINGS fg=dark_khaki bg=gray50"
color "type=HEADINGS_ODD fg=gray50 bg=gray90"

or at runtime with this you should go ok:
:int define_color "wheat" 245 222 179


About the different representations of the same color..
Check please if you're using the bold attribute. It always give me problems
cause It really depends on how its handled by terminals.

About redefine_color not working for custom colors. That is the expected
behaviour. If you want to modify an already defined custom color, you still
have to use the define_color..
--
Andrés Martinelli

**Comment by andmarti1424** [comment]
I found out that the difference on colors is because redefine color expected 0-1000 values while define color range goes from 0 to 255.
I modified that so both expect the later. Please update to latest commit.

**Comment by andmarti1424** [comment]
the number 2 was added as well.

**Comment by reportaman** [comment]
@andmarti1424 Cool, one last point regarding this. ``:define_color "RED" 255 0 0`` gives a misleading error message ``Defined custom color...`` (though luckily doesn't apply it). Maybe a place for an error message :)

**Comment by reportaman** [comment]
Also, I tested with your latest commit, can confirm it resolved 1) & 2)

**Comment by andmarti1424** [comment]
Now I will wait for that Dracula theme!
