### ISSUE TITLE
Incorrect results of numeric expressions, adding 0 makes them evaluate correctly 

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#497]
A numeric expression that just "gets" an existing numeric value from another cell or internal variables like ``@myrow``, ``@mycol`` always evaluates to ``0.00``. Adding a ``0`` to such numeric expressions solves the problem. Copy-pasting the contents of such cell to itself also seems to update the value, though saving and reopening the file would again show ``0.00`` & one would have to repeat copy-paste cells contents to itself each time after reopening (this problem doesn't happen with adding 0 to numeric expression, its a permanent workaround for now).

> Note: I haven't tested if similar problem exists with other kind of expressions, like string expressions. Hopefully devs can test, and add two tests to their release flow.

Command: ``>>sc-im test.sc``

File contents of ``test.sc``:
```
# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

format B 12 2 0
let E4 = 300
let G4 = 300
let I4 = @nval(@coltoa(@mycol-4),@myrow)
let E5 = 34
let G5 = 34
let E6 = 45
let G6 = 45
let E7 = 54
let G7 = 54
let E8 = 5
let G8 = 5
let G9 = @avg(G0:G8)
goto I3
```

Screenshot: The value of I4 should be equal to that of E4
<img width="1104" alt="Screen Shot 2021-02-24 at 4 16 05 AM" src="https://user-images.githubusercontent.com/71736629/109000248-4dd5f800-7658-11eb-9a94-30589ea6711f.png">

Same problem also does not occur in adjacent cells in this case when I copy-paste cell I4 into them. Following GIF shows the anomaly, I5:I9 yield correct results for same expression that I4 has:

![Screen Recording 2021-02-24 at 2 58 12 PM](https://user-images.githubusercontent.com/71736629/109078473-3b88a800-76b2-11eb-90d9-654cc73dc853.gif)

--------
**Copy-paste hack** (doesn't last after closing a file, mentioned here only for devs): Some further testing reveals that copy-pasting a cell's contents into itself gives the right result. As a side note, having ``autocalc`` enabled or disabled has no effect on this. Here's another GIF that shows how expressions evaluate correctly upon pressing ``yyp`` on the cells containing expressions:

![Screen Recording 2021-02-24 at 5 30 19 PM](https://user-images.githubusercontent.com/71736629/109090006-24a08080-76c7-11eb-972a-c71dfe91ccba.gif)

--------
**Zero addition workaround** (robust, seems to work always, even with chained cell expressions, and after closing and reopening a file): This GIF shows the most robust workaround is to have a 0 added to every numeric expression for it to evaluate correctly. All the cells that show a value of 0.00 in the GIF have miscalculated the results, and can all be fixed by adding a 0 to their expression.

![Screen Recording 2021-02-24 at 6 05 33 PM](https://user-images.githubusercontent.com/71736629/109092790-1012b700-76cc-11eb-9b65-7312a4195978.gif)

Open the file ``>>sc-im test2.sc``

Here's the code for ``test2.sc``:
```
# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

format B 12 2 0
format G 35 2 0
format I 35 2 0
let E4 = 500
let F4 = @nval(@coltoa(@mycol-1),@myrow)
leftstring G4 = "=@nval(@coltoa(@mycol-1),@myrow)"
let H4 = @nval(@coltoa(@mycol-2),@myrow)
leftstring I4 = "=@nval(@coltoa(@mycol-2),@myrow)"
let E5 = 34
let F5 = @nval(@coltoa(@mycol-1),@myrow)+10
leftstring G5 = "=@nval(@coltoa(@mycol-1),@myrow)+10"
let H5 = @nval(@coltoa(@mycol-2),@myrow)+10
leftstring I5 = "=@nval(@coltoa(@mycol-2),@myrow)+10"
let E6 = 45
let F6 = @nval(@coltoa(@mycol-1),@myrow)
leftstring G6 = "=@nval(@coltoa(@mycol-1),@myrow)"
let H6 = @nval(@coltoa(@mycol-2),@myrow)
leftstring I6 = "=@nval(@coltoa(@mycol-2),@myrow)"
let E7 = 54
let F7 = @nval(@coltoa(@mycol-1),@myrow)+10
leftstring G7 = "=@nval(@coltoa(@mycol-1),@myrow)+10"
let H7 = @nval(@coltoa(@mycol-2),@myrow)+10
leftstring I7 = "=@nval(@coltoa(@mycol-2),@myrow)+10"
let E8 = 5
let F8 = @nval(@coltoa(@mycol-1),@myrow)
leftstring G8 = "=@nval(@coltoa(@mycol-1),@myrow)"
let H8 = @nval(@coltoa(@mycol-2),@myrow)
leftstring I8 = "=@nval(@coltoa(@mycol-2),@myrow)"
let E10 = @mycol
let E11 = @mycol+0
goto E11
```

--------

> As a sidenote, I have also seen segfault when I had empty cells in range of ``@avg``, though I am not 100% sure if that was the exact case or I had circular reference like others have reported segfault on.

System information:
```
                    'c.          reportaman@mac-mini.lan
                 ,xNMM.          ----------------------------
               .OMMMMo           OS: macOS 11.2 20D64 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 hours, 51 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2880x1620
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.  
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1
       .cooc,.    .,coo:.        Memory: 1872MiB / 16384MiB
```

**Comment by reportaman** [comment]
Some further testing reveals that copy-pasting a cell's contents into itself gives the right result. As a side note, having ``autocalc`` enabled or disabled has no effect on this. Here's another GIF that shows how expressions evaluate correctly upon pressing ``yyp`` on the cells containing expressions:

![Screen Recording 2021-02-24 at 5 30 19 PM](https://user-images.githubusercontent.com/71736629/109090006-24a08080-76c7-11eb-972a-c71dfe91ccba.gif)

**Comment by reportaman** [comment]
This GIF shows the most robust workaround is to have a 0 added to every numeric expression for it to evaluate correctly:

![Screen Recording 2021-02-24 at 6 05 33 PM](https://user-images.githubusercontent.com/71736629/109092790-1012b700-76cc-11eb-9b65-7312a4195978.gif)

**Comment by andmarti1424** [comment]
Hello. Yep. This is an evaluation bug.
That is why a "+0" works since its evaluating again or rebuilding something in dependency graph..

**Comment by andmarti1424** [comment]
Could perhaps be only a misevaluation of @mycol @myrow variables?
Did you find this behaviour when not using  those ?

**Comment by reportaman** [comment]
@andmarti1424 It doesn’t happen with this fork of sc https://github.com/n-t-roff/sc. The author there has made commits till 2019.

**Comment by andmarti1424** [comment]
@reportaman About that not happening in old sc gives me no much help since I replaced the evaluation code (which was recursive and not very efficient) with a dependency graph.
It should be more efficient now, but of course has some problems like the one you described as well.
Or the crash with circular references..

**Comment by andmarti1424** [comment]
@reportaman Of course I could restore it back relatively easy.
I have uploaded a new commit for this issue. Could you please update to latest commit and test this again?

**Comment by reportaman** [comment]
Thanks, I confirm it works now. Even if I do ``=@mycol`` or ``=@myrow``. Though if I do something like: ``\"@coltoa(4)`` it doesn't put any string inside the cell.

**Comment by andmarti1424** [comment]
Thats great. Yes, I have to modify each of those as well, to get saved in the dependency graph.

**Comment by reportaman** [comment]
Regarding,

> @reportaman About that not happening in old sc gives me no much help since I replaced the evaluation code (which was recursive and not very efficient) with a dependency graph.
> It should be more efficient now, but of course has some problems like the one you described as well.
> Or the crash with circular references..

Maybe maintain a developer mode that still runs old engine on the subset of old sc's functionality, and have a gatekeeper test that compares results for common cases as you change core algorithm.

IMO, having incorrect evaluation result (ever) is going to make most people dread switching over to sc-im, or continue using it. If I were in your place, I would keep make it functionally correct before focussing on performance. And improve performance over time...

**Comment by reportaman** [comment]
@andmarti1424 After your commit, https://github.com/andmarti1424/sc-im/commit/281b870c316c4cb7540fe354584c4a93a5a78565, ``>"@coltoa(@mycol)`` works well. Next I tried to print the entire cell name in the cell: ``>"@coltoa(@mycol) # @chr(@myrow)``, and it didn't work. I guess ``chr`` also needs to be in dependency graph. Or by default all functions should be? I wonder why this doesn't happen with other functions like ``@avg``. Also is there a way to have user defined functions? ``@userfunc``, if yes then they should all get saved in dependency graph, right?

**Comment by andmarti1424** [comment]
Added @chr to depgraph. The ^ seems to be a bug in that chr function. Do not recall if that function was in SC. Do you know?

**Comment by reportaman** [comment]
I have installed this version of sc: https://github.com/n-t-roff/sc on my machine, and can confirm it is not there in it.

Though! It has ``@fmt(se,e)``, which looks like what I was asking for in another issue. Check this screenshot:

<img width="999" alt="Screen Shot 2021-02-26 at 4 02 53 AM" src="https://user-images.githubusercontent.com/71736629/109298047-d6cf6980-77e7-11eb-9983-db750f27ebd2.png">

**Comment by andmarti1424** [comment]
You are right! My bad. Will try to track the origin of @chr  ..

**Comment by andmarti1424** [comment]
@chr should only return printable characters between values 32-126.. why are you calling it for values under 32?

**Comment by reportaman** [comment]
@andmarti1424 Ok, I didn't know that... How do you plan to use ``@chr``?

**Comment by andmarti1424** [comment]
I never used it. I believe it was added by someone else. May be he/she needed it for something. Do not know..

**Comment by andmarti1424** [comment]
Could be that you need the @coltoa behaviour?

**Comment by reportaman** [comment]
@andmarti1424 From your docs it sounded like it converts a number to its string format (something we are discussing [there](https://github.com/andmarti1424/sc-im/issues/501#issuecomment-786600530)). Now I get what it does.

**Comment by andmarti1424** [comment]
This can be closed?

**Comment by reportaman** [comment]
The way I engage with my bugs at work is to keep them open till I have a complete fix. If you think you covered all cases, the yes please close this. If you want I can do some more testing later today, will be away from computer for a few hours...

**Comment by andmarti1424** [comment]
I believe we can close this.
