### ISSUE TITLE
sc-im not installing due to missing file

### ISSUE THREAD

**Issue by user1180** [andmarti1424/sc-im#498]
Running Manjaro

When attempting to install  from the package manager, I get this error output:

```
Warning: sc-im is only available from AUR
Preparing...
Cloning sc-im build files...
Checking sc-im dependencies...
Resolving dependencies...
Checking inter-conflicts...

To build (1):
  sc-im  0.7.0-2    AUR


Edit build files : [e] 
Apply transaction ? [e/y/N] y


Building sc-im...
==> Making package: sc-im 0.7.0-2 (Wed 24 Feb 2021 07:25:11 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found sc-im-0.7.0.tar.gz
  -> Found arch.patch
  -> Found 258.patch
==> Validating source files with sha256sums...
    sc-im-0.7.0.tar.gz ... Passed
    arch.patch ... Passed
    258.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting sc-im-0.7.0.tar.gz with bsdtar
==> Starting prepare()...
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- Makefile.orig	2017-12-14 04:48:59.000000000 +1100
|+++ Makefile	2017-12-15 09:23:07.776195283 +1100
--------------------------
File to patch: 
Skip this patch? [y] y
Skipping patch.
2 out of 2 hunks ignored
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by andmarti1424** [comment]
Hello! It seems it not patching something correctly:

"can't find file to patch at input line 3"

Please comment this to sc-im maintainer of the Arch community.
I believe something could have changed in arch, since nothing changed on SC-IM since last months of 2020..

**Comment by user1180** [comment]
Aren't you the maintainer? https://aur.archlinux.org/packages/sc-im

**Comment by andmarti1424** [comment]
@user1180 no I am not. Rhinoceros guy is

**Comment by andmarti1424** [comment]
@user1180 Just mark it out of date so he can see it..

**Comment by reportaman** [comment]
@andmarti1424 FYI, the homebrew's version number reported by ``--version`` is ``0.7.0``, which is same as what I get today. Though homebrew's version does not have ``set truncate`` option in it, it gives error & is not listed in the ``:h`` help doc.

**Comment by andmarti1424** [comment]
Thank you. I believe truncate was added later on by a user..

**Comment by andmarti1424** [comment]
AUR package was updated. Culd you managed to build it?
