### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by alx741** [andmarti1424/sc-im#50]
I love this project, standard `sc` lacks so many things that `sc-im` really catches the eye, but I'm not really sure about how the license is compatible (or not) with free software ones (GPL specifically) and it makes me hesitate and a little bit uncomfortable to pour work on it.

Have you consider converting the project to GPL?

I think it would have pretty much the same conditions and freedoms but with the advantage of a very standard and strong free software license backup by the whole GNU and FSF community. Probably the only thing to change would be the `LICENSE` file with the standard `GPLv3` one. Appending to it the attribution and so.

That would even come with extra ease for distribution in GNU/Linux distros standard repos.

[GPLv3 howto](http://gplv3.fsf.org/wiki/index.php/Howto)

Not an *issue* but probably a wish :)

**Comment by andmarti1424** [comment]
Hello. SC-IM uses the 4 clause BSD license. I do not have plans in changing it right now since I believe this license is not restrictive at all in what using the code, modifying it and redistributing it concerns..

**Comment by alx741** [comment]
Didn't know it's BSD License, thanks!

**Comment by alexmyczko** [comment]
Would you mind re-opening this issue and checking this?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029570

**Comment by andmarti1424** [comment]
@alexmyczko Dont know why its missing that 3rd clause in the debian package.
This is the correct licence: https://github.com/andmarti1424/sc-im/blob/main/LICENSE

**Comment by andmarti1424** [comment]
@alexmyczko I see. Regarding that, I am afraid my last comment from 2016 continues to be valid.
