### ISSUE TITLE
tmux redefine color

### ISSUE THREAD

**Issue by hatunike** [andmarti1424/sc-im#502]
I ran into an issue where i couldn't use :
`redefine_color "RED" 0 0 0` like commands. This would happen if i was setting that in my scimrc as well as just calling the command manually after starting sc-im. Anytime I tried to redefine my colors, i'd get a "Could not redefine color" error message.

I looked into the problem further and it turns out it would work in another terminal window than the one i had been using. The difference was one was running tmux and the other wasn't.

This lead me down the road to discover that difference was how TERM was being set in the two different environments.

So if you have `TERM = tmux-256color` when running tmux. Then what you have to do to get sc-im to display redefined colors is just set it right before you call it :

`TERM=xterm-256color sc-im`

which i just put in as an alias to :

alias scim='TERM=xterm-256color sc-im'

So i'm not sure if this is an issue as far as how scim is implemented (and could be easily fixed). But at the very least, perhaps someone will have this same issue and find this workaround useful.

**Comment by andmarti1424** [comment]
Yes I also use tmux in a server and ran into a same issue regarding the 256 colors.
Its a terminal issue. "Could not redefine color" is just the ncurses indicating is unable to set the color..
Its not a SC-IM issue..this time

**Comment by hatunike** [comment]
Seeing as how this isn't directly SC-IM issue, i'm going to go ahead and close this issue.
