### ISSUE TITLE
Page scroll down doesn't fill full terminal screen with new rows

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#503]
Page scroll down doesn't fill terminal screen with new rows. This is the same behavior as old SC, and perhaps can be improved. In the following GIF, for the entire period I am just pressing page down:

![Screen Recording 2021-02-26 at 6 49 29 AM](https://user-images.githubusercontent.com/71736629/109318884-253e3180-7803-11eb-8be6-a7599420df90.gif)

**Comment by andmarti1424** [comment]
This is the expected behaviour. Once you get to the bottom row (last memory alloc'ed row) it shows that way until you move a row down and a bunch of other rows are alloc'ed.

**Comment by reportaman** [comment]
Ok, makes sense! Just noticed that if on every page down I want to see a full new page of new rows I can keep the cursor in the bottom row & press page down.
