### ISSUE TITLE
README config clarification

### ISSUE THREAD

**Issue by hatunike** [andmarti1424/sc-im#505]
The README has a configuration section that should better clarify how the `scimrc` config file should be setup. I'm not sure if this is different for each OS or installation method. But from what i can tell the most common directory for this file is now `~/.config/scimrc` whereas the current readme suggests the file is located `~/.scimrc`. 

I know you can confirm which path it's expecting by using the `sc-im --version`

```
...
-DCONFIG_DIR=".config"
-DCONFIG_FILE="scimrc"
...
```

If the config file is always at the new location, i'd be happy to update the README and submit a pr.

**Comment by andmarti1424** [comment]
Actually, today I modified the doc file regarding this. It should also be clarified in the Readme as you suggest.
