### ISSUE TITLE
Clarification on color categories

### ISSUE THREAD

**Issue by hatunike** [andmarti1424/sc-im#506]
Does anyone know what these colour keys specifically refer to? Some of them are more obvious than others. I'm in the process of setting them and would love some documentation for them. If there isn't any documentation I could submit a doc/wiki pr on them. (Assuming i can finish figuring out exactly what they refer to). 

`HEADINGS, MODE, NUMB, STRG, DATEF, EXPRESSION, CELL_ERROR, CELL_NEGATIVE, CELL_SELECTION, CELL_SELECTION_SC, INFO_MSG, ERROR_MSG, CELL_ID, CELL_FORMAT, CELL_CONTENT, WELCOME, NORMAL, INPUT`

I'm thinking of writing something up on how to create a new theme for SC-IM, would anyone be interested in this? And where would be best place to post it?

**Comment by reportaman** [comment]
@hatunike I have been making https://draculatheme.com theme for sc-im. I was able to set and immediately see the change in an existing ``.sc`` spreadsheet for the most important ones.

```
STRG: String/label of cell
NUMB: Number entered in cell
EXPRESSION: Value in cell is result of expression (didn't test string expressions yet, works for numbers)
HEADINGS: Topmost (header) row that lists column names, and leftmost (header) column that lists row numbers.
CELL_SELECTION: This color applies to a pair of cells: header row cell that has same column as current cell, header column cell that has same row as current cell.
CELL_SELECTION_SC:  This color applies to the current (focussed) cell.
```

Haven't tried coloring other features yet, I guess CELL_ERROR is the color of "ERROR" printed in cells (at times error is printed in cells, at times at the top left of the terminal), don't know what CELL_NEGATIVE, CELL_CONTENT, CELL_ID are. WELCOME should be some color on welcome screen, NORMAL & INPUT should be some color for commands that show on top of the terminal, INFO_MSG & ERROR_MSG seem to be for messages printed on top left. I wonder whether the docs call the top two lines as statusline/commandline...

**Comment by hatunike** [comment]
Thanks for sharing @reportaman! nice theme! Here is what i've found so far :

`HEADINGS` The numbers and letters  along the left side and top that show which row and column respectively
`MODE` The text in the top right that indicates which mode SC-IM is currently in
`NUMB` The cell styling used for cells formatted as numbers (That are positive)
`STRG` The cell styling used for cells formatted as strings
`DATEF` The cell styling used for cells formated as dates
`EXPRESSION` The cell styling used for cells that are the result of an expression
`CELL_ERROR` The cell styling used for when an expression results in an error (like dividing by zero)
`CELL_NEGATIVE` The cell that is used when a number (or expression) is a negative value.
`CELL_SELECTION` - The row and column selection styling used on the HEADINGS to indicate the coordinates of the selected row.
`CELL_SELECTION_SC` The currently selected cell.
`INFO_MSG` The text in the top left corner just above "A" that will provide info messages "At column A" when you try and go past the farthest column to the left
`ERROR_MSG` The text that will display in the top left corner when a command fails for some reason
`CELL_ID` The coordinates of the currently selected cell that displays in the upper top left corner. Just to the left of the CELL_FORMAT and CELL_CONTENT.
`CELL_FORMAT` The text just to the right of the CELL_ID and left of the CELL_CONTENT in the top left corner that shows the formatting of the currently selected cell.
`CELL_CONTENT` The text just to the right of the CELL_ID and CELL_FORMAT that shows the content of the currently selected cell. This will show the expression used to get the current cell.
`WELCOME` The text that shows up when you first open SC-IM
`NORMAL` Text that shows on top of the terminal (like in :help)
`INPUT` The text that shows up while you type text in the input bar at the top left of the screen

**Comment by andmarti1424** [comment]
@reportaman have you tried the latest commits that can handle custom colors with rgb values?

**Comment by andmarti1424** [comment]
Wrote a wiki explaining this:
https://github.com/andmarti1424/sc-im/wiki/Changing-colors
Thanks for the details.
