### ISSUE TITLE
Adding ston to depgraph breaks Lua interface

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#508]
Commit https://github.com/andmarti1424/sc-im/commit/383ae36a367e6d388c4baaf0de58276a60183814 that added ``@ston`` to dependency graph breaks interface with lua in many ways.

1. Lua scripts that write to the same cell in which they are triggered from using ``=@ston(@lua("scriptname.lua",0))``, end up writing the cell with ``0.00`` when ``@ston`` finishes; that overwrites whatever ``<value>`` user intended to write to the cell using ``sc.lsetnum(sc.curcol(),sc.currow(), <value>)`` .
2. Try running ``=@now`` in some random cell after running a  ``=@ston(@lua("scriptname.lua",0))``, it will run ``=@ston(@lua("scriptname.lua",0))`` again from cell that you run ``=@now`` in. If the ``scriptname.lua`` writes to the next cell, each run of ``=@now`` will write time to that cell, and whatever ``scriptname.lua`` writes to adjacent cell. 
3. Lua scripts with``sc.lquery`` are misbehaving. This is what I notice: If have a ``sc.lquery`` in a script, with every run of ``=@ston(@lua("scriptname",0))`` the number of times user has to enter carriage return increases by one. So, if I am running the script Nth time (sequentially from N different cells), I need to hit ``<CR>`` N times before it would actually capture the user input & complete to move to the next lua statement.

**Comment by andmarti1424** [comment]
I believe what the commit https://github.com/andmarti1424/sc-im/commit/383ae36a367e6d388c4baaf0de58276a60183814 added is correct. 
I think we should reconsidered how the lua evaluation/execution is done..

**Comment by andmarti1424** [comment]
I close this since its duplicated.
`@ston` should work flawlessly now in lua branch that will be merged soon.
