### ISSUE TITLE
Error building with old ncurses version that cannot handle 'BUTTON5_PRESSED': use of undeclared identifier 

### ISSUE THREAD

**Issue by for-coursera** [andmarti1424/sc-im#512]
Probably, some guards should be added if ncurses has no mouse support? :)

    tui.c:1496:24: error: use of undeclared identifier 'BUTTON5_PRESSED'
            event.bstate & BUTTON5_PRESSED) { // scroll down
                           ^
    tui.c:1501:37: error: use of undeclared identifier 'BUTTON5_PRESSED'
                currow = event.bstate & BUTTON5_PRESSED ? forw_row(n)->row : back_row(n)->row;
                                        ^
    tui.c:1502:32: error: use of undeclared identifier 'BUTTON5_PRESSED'
                if (event.bstate & BUTTON5_PRESSED) scroll_down(n);
                                   ^
    1 warning and 3 errors generated.
    make: *** [tui.o] Error 1

**Comment by andmarti1424** [comment]
I believe you set MOUSE macro, but your ncurses version is older than mine..

**Comment by for-coursera** [comment]
@andmarti1424 

Ah, yeah, commenting out `CFLAGS += -DMOUSE` in Makefile fixes it, thanks.

While we are at it, on another machine I also have a similar problem with `A_ITALIC`:

    tui.c:1390:32: error: use of undeclared identifier 'A_ITALIC'
        if (uc->italic)    attr |= A_ITALIC;

It's also due to the ncurses limitations on that machine? Commenting that line out fixes the compilation sure. Would be a pity to lose italics, though, since the terminal does support it...

**Comment by andmarti1424** [comment]
Please try building sc-im on both machines with latest commit. It will hopefully try detecting if using old ncurses version so it can complete building (off course disabling italic and/or mouse scroll if cannot be handled by your ncurses version).
btw which version do you have?

**Comment by for-coursera** [comment]
One problematic machine is an old Ubuntu, so here it goes (was complaining about `BUTTON5_PRESSED`):

    > apt list --installed | grep ncurses
    libncurses5/xenial,now 6.0+20160213-1ubuntu1 i386 [installed]
    libncurses5-dev/xenial,now 6.0+20160213-1ubuntu1 i386 [installed]
    libncursesw5/xenial,now 6.0+20160213-1ubuntu1 i386 [installed]
    libncursesw5-dev/xenial,now 6.0+20160213-1ubuntu1 i386 [installed]
    ncurses-base/xenial,now 6.0+20160213-1ubuntu1 all [installed]
    ncurses-bin/xenial,now 6.0+20160213-1ubuntu1 i386 [installed]
    ncurses-term/xenial,now 6.0+20160213-1ubuntu1 all [installed,automatic]

And another one is an old MacBook, `ncurses` installed with MacPorts (was complaining about `BUTTON5_PRESSED` and `A_ITALIC`... sort of strange, actually):

    > port list installed | grep ncurses
    ncurses                        @6.2            devel/ncurses

Your latest commit does fix it, can confirm.

**Comment by andmarti1424** [comment]
Thank you for the report. I thought you would be using older version.
btw I use 6.2-1
I also thought that 6.2 should handle italic but.. only those who port them to OSX can answer that.

**Comment by for-coursera** [comment]
@andmarti1424 

Eh... sorry, no so fast :(

On Ubuntu it crashes while compiling: https://termbin.com/2w4q

And on mac it builds OK but then core dumps when launched.

Sorry once again for being in such an idiot :(

**Comment by andmarti1424** [comment]
@for-coursera hahah. No problem.
But thats a different issue.  Its not finding ncurses library..
That is way its complaining about every ncurses functions and variable.

**Comment by andmarti1424** [comment]
About the mac issue please open another issue so OSX users can help you.
Please give details on how you built it and any other information about the crash.

**Comment by for-coursera** [comment]
About the Ubuntu case: any way to fix it may be? :)

**Comment by andmarti1424** [comment]
I dont have Ubuntu but just check you have ncurses correctly installed.

Have you checked the wikis:
https://github.com/andmarti1424/sc-im/wiki
?
There are some instructions for Ubuntu

**Comment by for-coursera** [comment]
@andmarti1424 

Concerning the macOS case: it's definitely something that was introduced with the commit 219072c (if I comment out MOUSE in Makefile and A_ITALIC in tui.c, commit b07d2f6 builds and launches OK).

Here's the full build log just in case for the commit dd4eb5e (the one that segfaults after building): https://termbin.com/f9ti

Concerning the Ubuntu case: I checked the wikis but don't really know what to say... :) headers are in `/usr/include/ncursesw` and I also did `sudo ldconfig` :)

    src> dir /usr/include/ncursesw
    total 368K
    -rw-r--r-- 1 root  95K Feb 19  2016 curses.h
    -rw-r--r-- 1 root 6.7K Feb 19  2016 cursesapp.h
    -rw-r--r-- 1 root  28K Feb 19  2016 cursesf.h
    -rw-r--r-- 1 root  20K Feb 19  2016 cursesm.h
    -rw-r--r-- 1 root 8.5K Feb 19  2016 cursesp.h
    -rw-r--r-- 1 root  49K Feb 19  2016 cursesw.h
    -rw-r--r-- 1 root 7.2K Feb 19  2016 cursslk.h
    -rw-r--r-- 1 root 2.9K Feb 19  2016 eti.h
    -rw-r--r-- 1 root 9.1K Feb 19  2016 etip.h
    -rw-r--r-- 1 root  18K Feb 19  2016 form.h
    -rw-r--r-- 1 root  12K Feb 19  2016 menu.h
    lrwxrwxrwx 1 root    8 Feb 19  2016 ncurses.h -> curses.h
    -rw-r--r-- 1 root 4.2K Feb 19  2016 ncurses_dll.h
    -rw-r--r-- 1 root 4.1K Feb 19  2016 nc_tparm.h
    -rw-r--r-- 1 root 4.0K Feb 19  2016 panel.h
    -rw-r--r-- 1 root  39K Feb 19  2016 term.h
    -rw-r--r-- 1 root 3.4K Feb 19  2016 termcap.h
    -rw-r--r-- 1 root 8.1K Feb 19  2016 term_entry.h
    -rw-r--r-- 1 root  13K Feb 19  2016 tic.h
    -rw-r--r-- 1 root 3.1K Feb 19  2016 unctrl.h

**Comment by andmarti1424** [comment]
There was a typo in 219072c
BUTTON_5_PRESSED
should be
BUTTON5_PRESSED
I fixed it couple of minutes after that commit.
Please update to latest commit and try again.
If it still fails please try running it with gdb. So I can have more info on that crash thanks!
