### ISSUE TITLE
Compilation error: undefined reference to `init_extended_pair'

### ISSUE THREAD

**Issue by ZaxonXP** [andmarti1424/sc-im#513]
I tried to compile the sc-im on Debian 8.11 but I got the following errors:
```
tui.o: In function `ui_start_colors':
/home/user/zzz/sc-im-freeze/sc-im-0.8.0/src/tui.c:1447: undefined reference to `init_extended_pair'
color.o: In function `redefine_color':
/home/user/zzz/sc-im-freeze/sc-im-0.8.0/src/color.c:578: undefined reference to `init_extended_color'
color.o: In function `define_color':
/home/user/zzz/sc-im-freeze/sc-im-0.8.0/src/color.c:640: undefined reference to `init_extended_color'
collect2: error: ld returned 1 exit status
Makefile:190: recipe for target 'sc-im' failed
make: *** [sc-im] Error 1
```
Anyone can point me out what do I miss?

Regards,
Piotr

**Comment by andmarti1424** [comment]
Hello. Please update you ncurses version.. I use ncurses 6.2-1

**Comment by andmarti1424** [comment]
I did a quick research and it seems that debian jessie has ncurses 5.9. Am I wrong?
If so, please try updating it.

**Comment by andmarti1424** [comment]
May be with a manual build of ncurses..

**Comment by ZaxonXP** [comment]
I did download the ncurses 6.2 from [here](ftp://ftp.invisible-island.net/ncurses/ncurses.tar.gz), then made:
```
./configure --enable-widec --with-shared --enable-termcapCD
make
sudo make install
```
After that I tried to recompile `sc-im`, but the result is the same. What did I do wrong?

**Comment by andmarti1424** [comment]
What you did seems correct but for some reason the building process it is not finding That version of the library. Or may be it is finding the previous version?

**Comment by andmarti1424** [comment]
Run 'pkg-config --cflags ncursesw' and 'pkg-config --libs ncursesw' and see if the output corresponds to where you installed ncurses..

**Comment by ZaxonXP** [comment]
It looks there was a version 5 installed by package manager. I removed it with apt-get remove, but after running these commands I got nothing:
```
Configuration summary for NCURSES 6.2 20200212:

       extended funcs: yes
       xterm terminfo: xterm-new

        bin directory: /usr/bin
        lib directory: /usr/lib
    include directory: /usr/include
        man directory: /usr/share/man
   terminfo directory: /usr/share/terminfo

$ pkg-config --cflags ncursesw
Package ncursesw was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncursesw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncursesw' found

$ pkg-config --libs ncursesw
Package ncursesw was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncursesw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncursesw' found
```
However when I recompiled the sc-im sources this time I got no error. :)
I ran it from the src directory, but when I checked the version it was 0.7.0 and not 0.8.0. Why is that?

**Comment by andmarti1424** [comment]
May be plain ncurses lib (without the W)

**Comment by andmarti1424** [comment]
Check this https://github.com/andmarti1424/sc-im/issues/514
about version number issue.

**Comment by ZaxonXP** [comment]
> Check this #514
> about version number issue.

Actually it was my fault as I had a previous version opened and for some strange reason it was running it even if I run the latest compiled version locally. But thanks for sharing the info.
