### ISSUE TITLE
Incorrect version string.

### ISSUE THREAD

**Issue by magpie514** [andmarti1424/sc-im#514]
Hello.

I've recently updated to the latest version of sc-im from git, and when starting it still says it's version 0.7.0, even after the latest formal release. 
I've noticed version.h still says 0.7.0 here in the git repo, so it seems to be just that.

Excellent updates, by the way.

**Comment by andmarti1424** [comment]
Man I forgot last git push.
Thats fixed now. I have also asked Rhinoceros (AUR maintainer) to update the package.
Thank you.
