### ISSUE TITLE
Color HEADINGS : How to change color of alternate columns?

### ISSUE THREAD

**Issue by ZaxonXP** [andmarti1424/sc-im#516]
If I do:
```
:color "type=HEADINGS fg=WHITE bg=CYAN"
```
then only every second column header is changed, but every other stays yellow.
How can I change the other columns header color?

Also where can I find the color scheme definition from version 0.7.0 (I really liked that one)?

Regards,
Piotr

**Comment by andmarti1424** [comment]
Yes. You now have to set  HEADINGS_ODD! forgot to add it in doc

**Comment by andmarti1424** [comment]
Just compare to default values in color.c. Really don't remember which colors where at that time

**Comment by ZaxonXP** [comment]
Thanks!
