### ISSUE TITLE
Subtract values from cells

### ISSUE THREAD

**Issue by paum3** [andmarti1424/sc-im#528]
@andmarti1424 thank you for fast reply, but maybe I was not exact.
I need to do something like @sub(A1:A2) to subtract values from different cells and I don't see it in documentation.

Thank you again..

**Comment by paum3** [comment]
ah, the simplest try just works. It is enough to write A1 - A2.
closing

**Comment by andmarti1424** [comment]
If you mean subtract numbers over a whole range. I dont think its possible.
