### ISSUE TITLE
Version 0.8.0 not reading .scimrc

### ISSUE THREAD

**Issue by eric-b-hymowitz** [andmarti1424/sc-im#532]
I just updated from version 0.7.0 to version 0.8.0, and the new version is apparently not reading or not processing my .scimrc file.  None of my color changes are being applied, and none of my key mappings are working.

(I still have 0.7.0 installed, and the .scimrc file is stil, being processed correctly.)

**Comment by andmarti1424** [comment]
Could you please attach it?
scimrc goes inside .config/sc-im folder
And not its without the dot (scimrc), rather than .scimrc

**Comment by eric-b-hymowitz** [comment]
When did you change the file's location and name?  There is nothing in the "CHJANGES" file about this.

**Comment by eric-b-hymowitz** [comment]
That fixed it. Thanks.

**Comment by andmarti1424** [comment]
Yes there is.
Line 24 of CHANGES:
+modified config and history file locations

**Comment by andmarti1424** [comment]
Glad to hear.
