### ISSUE TITLE
Significant response lag or map even does not work when using "crossed" mappings

### ISSUE THREAD

**Issue by Iperero92** [andmarti1424/sc-im#535]
**Commit**: 2413d1e9275f6ec30f8785a073c6b146c73b5445
**OS**: macOS 10.14.6
**Shell/Terminal**: zsh, both on standard macOS terminal and iterm2, both with and without tmux.
**Installation process**: as suggested on Readme, without any change on makefile and with Lua (the issue also appears without Lua).
**Minimum scimrc**:
	nnoremap "k" "j"
	nnoremap "l" "k"
**Description of the issue**:
	When I press 'k', I get the behavior one would expect from 'j' (move cursor down one row). When I press 'l', if I wait a second or so, I eventually get the cursor to move up one row. If I press '10l' for example, I see the same lag. If I press 'l' repeatedly and quickly or I leave it pressed (like I usually do on vim), sometimes it moves up and sometimes it moves to the right (as if there was no mapping). None of this issues happen with 'k' in this particular example.

**Comment by andmarti1424** [comment]
Please try those mapping with nmap, rather than nnoremap

**Comment by Iperero92** [comment]
The lag disappears, however both 'l' and 'k' now act as j''. This is not what I want and it's the reason I chose non-recursive mapping.
Thxs

**Comment by Iperero92** [comment]
I tried this workaround (or, should I say, straightforward approach):
nmap "k" "<DOWN>"
nmap "l" "<UP>"
And it works fine, same with the non-recursive version. Since this approach achieves the result I wanted, this is no longer an issue for me. Feel perfectly free to close it.

Thank you

**Comment by andmarti1424** [comment]
I have added a configuration parameter so you can set the mapping timeout
Please check it out at doc. I have increase it from 800ms to 1500ms.

**Comment by andmarti1424** [comment]
Now I get what your problem is. Please give me some time to check it out.

**Comment by Iperero92** [comment]
The previous comment was not showing correctly the mapping (needed to escape < and >)

**Comment by andmarti1424** [comment]
@Iperero92 please update to latest commit and try again with the maps you originally configured. thanks.

**Comment by Iperero92** [comment]
Fixed! Thx
