### ISSUE TITLE
How can i run the tests when compiling?

### ISSUE THREAD

**Issue by jgarte** [andmarti1424/sc-im#537]
Hi,

How can i run the tests when compiling?

**Comment by andmarti1424** [comment]
Hello. What tests?

**Comment by jgarte** [comment]
Hi! 

Oops, ok. Maybe that was the question I should have asked. Thanks for clarifying that!

Is there any plans to add tests to sc-im? 

I see that there is a tests folder.

**Comment by andmarti1424** [comment]
Yes @jgarte . Please see PR #385. You can be the first one on contributing a test case!

**Comment by jgarte** [comment]
@andmarti1424 

Hi, how do I run the test suite? 

Could we add this information to the README?

**Comment by andmarti1424** [comment]
Just run the shell script called run_all_tests inside tests folder. You'll need valgrind
