### ISSUE TITLE
Conditions in formulas, like @sum

### ISSUE THREAD

**Issue by abenson** [andmarti1424/sc-im#538]
So on older versions, I had conditional sums, for example

    let G1 = @sum(B8:B105,B8>0)

This correctly only counted a cell if it were positive.  After the latest update, on recalculation it updated the formula

    let G1 = @sum(B8:B105,@ref>0)

But it seems to have stopped considering the cell's value at all.  What is the correct way to condition the value now?

**Comment by abenson** [comment]
I believe it was 0.8.0. I think it was related to the circular references fixes -- given some time I can bisect and figure out where it broke, but that'll have to wait until tomorrow.

**Comment by andmarti1424** [comment]
I am not having problem here..
![image](https://user-images.githubusercontent.com/9466161/115397197-37fa3480-a1bc-11eb-9777-0c1953169744.png)
can you share your file?

**Comment by abenson** [comment]
What happens if you insert a row?

**Comment by andmarti1424** [comment]
When you insert a row, it continues correctly. the thing is when you remove some cell from the range! that is where it fails..

**Comment by abenson** [comment]
Okay, note to self: always add, never remove!

**Comment by andmarti1424** [comment]
If you replace the formula stays intact

**Comment by andmarti1424** [comment]
You know what. It doesnt fail for me. It shows @ref when you delete the first row. The one references in the formula, which is correct..

**Comment by andmarti1424** [comment]
Now i see, when you delete with 'x' then it removes the reference in the formula..

**Comment by abenson** [comment]
This is a time off tracker I use to help budget.

[test.txt](https://github.com/andmarti1424/sc-im/files/6346106/test.txt)

I can reliably trigger if I add a row in between and as soon as I add a label in column A, it'll change the formulas to @ref.  None of the formulas reference column A.

**Comment by andmarti1424** [comment]
I can confirm this bug is prior to Aug.2020.. 
Cant test it with v0.7 right now.

**Comment by abenson** [comment]
I was about to respond that 0.7 does in fact work fine.

**Comment by andmarti1424** [comment]
@abenson Could you please test this again?
I have merged all from "new" branch to freeze branch. So please update to latest commit there.
btw, nice you are using the multiple frozen rows. Seems to work ok.
Thanks.

**Comment by abenson** [comment]
I can confirm it works and behaves as expected! Thanks for the quick fix!

> nice you are using the multiple frozen rows

Yes, it's quite nice, really helpful when the sheet ends up getting really long.
