### ISSUE TITLE
confusion with commands "format" "unformat" "FORMAT"

### ISSUE THREAD

**Issue by OrkeshNurbolat** [andmarti1424/sc-im#539]
Hello Andres

Thanks very much for making sc into such an amazing tool. I am new to sc and sc-im and I am learning it .

however , here is few problems that I am having. I try to format a numeric cell and this happens
 
![2021-04-21-044715_415x123_scrot](https://user-images.githubusercontent.com/70803997/115500158-4d289f00-a260-11eb-948d-b19e288044d0.png)

and this COULD NOT be cancelled somehow when I am hovering over the cell and typed 
:unformat

searching the man page and wikis I didnt find any usefull information about how to use  "FORMAT"
to change the cell formatting tuple like (10 , 0 , 1) stuffs

how does one learn those hardcore basics ?

**Comment by andmarti1424** [comment]
Hello. What version of sc-im are you using? The latest commit at "new" branch? The latest at "freeze" branch or a release? You can change precision  in normal mode with f+ or f-.. You can also use :format if you use the "new" branch version. Please check the doc file for how it's used..

**Comment by andmarti1424** [comment]
:unformat is used for removing format of a cell previously set with :cellcolor

**Comment by OrkeshNurbolat** [comment]
> Hello. What version of sc-im are you using? The latest commit at "new" branch? The latest at "freeze" branch or a release? You can change precision in normal mode with f+ or f-.. You can also use :format if you use the "new" branch version. Please check the doc file for how it's used..

I am using the freeze branch, I know it could be chaned with f+ f-,
however when I set it to use the ###.###e6 I suppose to see 72e6 , since it was inputed as 72000000.
however it is displaying 72000000E6 which is a million times larger than correct one.

I had read :help page and the sc manual page and github wiki,
any other place to learn  ? Thanks .

**Comment by andmarti1424** [comment]
Try this: `:int format "##.00E+00"`

**Comment by OrkeshNurbolat** [comment]
Thanks for all the help
