### ISSUE TITLE
Scientifc physical semi-units for numbers using a char  in "f p n u m k(K) M G T" at rear of numbers

### ISSUE THREAD

**Issue by OrkeshNurbolat** [andmarti1424/sc-im#540]
Hey Andres

I had issues with formats due to my numbers are usually too big or too small . 
 
when inputting a number, I like to put this way
72.2M  , 6.295G , 40n  ,100k , 10u ,  
and each of them  just correspond to :
72.2e6 , 6.295e9 , 40e-9 , 100e3 , 10e-6 , 

I guess this doesnt come with scim ,  so there are 2 ways to work this out for me
    
    1.keep it as number , check if it is a valid input of number , and then save/display/change with the abrivation

    2.keep it as  string ,   as well check validity when input/change/load , and give it a different color than STRG.

I think I like to do it by plan 2. any suggestions ?

**Comment by andmarti1424** [comment]
I would store numbers as numbers. About the M G m u n p... k.. just curious, other spreadsheet programs has them?
Thanks.

**Comment by earthshrink** [comment]
I had had a similar need, and solved it by (a) keeping two sets of number columns, in convenient to read units and in SI base units, and (b) notating the units in adjacent columns. The base units column can be then used in formulas without having to insert the unit multipliers. Please see the tests/gps.sc, which also illustrates the engineering notation. Maybe it will help.

**Comment by OrkeshNurbolat** [comment]
> I would store numbers as numbers. About the M G m u n p... k.. just curious, other spreadsheet programs has them?
> Thanks.

Oh I don't think most of other spreadsheet programs has that, except one called "sciSheet"  which runs on gui and I guess written in python .

**Comment by OrkeshNurbolat** [comment]
> I had had a similar need, and solved it by (a) keeping two sets of number columns, in convenient to read units and in SI base units, and (b) notating the units in adjacent columns. The base units column can be then used in formulas without having to insert the unit multipliers. Please see the tests/gps.sc, which also illustrates the engineering notation. Maybe it will help.

Thanks I'll take a look

**Comment by OrkeshNurbolat** [comment]
> I had had a similar need, and solved it by (a) keeping two sets of number columns, in convenient to read units and in SI base units, and (b) notating the units in adjacent columns. The base units column can be then used in formulas without having to insert the unit multipliers. Please see the tests/gps.sc, which also illustrates the engineering notation. Maybe it will help.

Hey thank you very much, this example is exactly what I needed, still am not clear
how do I use the "FORMAT" command to set some cell to be something like (10, 0 , 2) instread of others.
I found FORMAT in manual but it is not a command, I'll be glad to write some into man after I learn how to use.

well probably you are mixing up the SI units (Aka things that have physics meanings such as Secound , V ,A )
to the numbering scaling abrivation stuffs, you know, it could aslo used  as 10GB data , 100MB storage ,
50k subscribers like stuffs. just for the convention. maybe my expression of semi-unit is just not accurate.

**Comment by andmarti1424** [comment]
@OrkeshNurbolat about the format  (10, 0, 2..) that is the default  format for an entire column, not a single cell.

You have to use the `:formatcol` command (but that was added in the "new" brach).
then, :formatcol for an entire column
`:format` for a cell
btw, i answered to you about your other inquire here: https://github.com/andmarti1424/sc-im/issues/539

**Comment by OrkeshNurbolat** [comment]
@andmarti1424   @earthshrink 
Oh Great thanks alot , :formatcol  works !
