### ISSUE TITLE
Crash upon terminal resizing when :plot

### ISSUE THREAD

**Issue by OliverLew** [andmarti1424/sc-im#543]
Tested with the latest HEAD c3fda0e70c7e8e5ab8d7a63f43a2b509c9cb11c1 and `st` terminal emulator/tmux in getty. Simply `:plot bar` some data, e.g. two columns of `1` `2` `3` `4`, and then resize the terminal window.

The only output is `Segmentation fault (core dumped)`. Although I tried to run `sc-im` with `gdb`, but `sc-im` does not respond with terminal resizing in that case. I don't know too much about gdb, so I have no idea how to debug this. I hope someone can reproduce.

Not directly related to this issue, would it be better if the gnuplot output was put into a pager, e.g. less (prob save it into a file first)? This maybe also be a workaround.

**Comment by andmarti1424** [comment]
I couldnt get it to segfault. I imagine you resize it while seeing the bar plot. right?
That means, outside ncurses..

**Comment by andmarti1424** [comment]
Please try updating to latest commit and try again.  Thanks.

**Comment by OliverLew** [comment]
> I couldnt get it to segfault. I imagine you resize it while seeing the bar plot. right?
> That means, outside ncurses..

Yes. And the latest commit did solve the problem. Thanks!

Although there are other small issues:

After quitting gnuplot, sc-im keeps the same size as before resizing, e.g. smaller than the window if I made the window bigger earlier. Maybe sc-im should update the UI somewhere?

In gnuplot, if I click the mouse or press some keys, the corresponding keycode (or whatever they are called) will be printed below the plot:
```
^[[M @(^[[M#@(^[[M @(^[[M#@(^[[M @(^[[M#@(^[[D^[[C^[[A^[[B
```

**Comment by andmarti1424** [comment]
I don't think I can handle that mouse issue, at least while the plot get printed outside ncurses.
About the refresh, you might want to update and try again.

**Comment by OliverLew** [comment]
Sorry to respond so late, different time zones. The refresh works now, thanks again.

As for the mouse/key issue, it does not happen directly in gnuplot (not through sc-im). But if it is handled from within sc-im, then I guess that issue is not related here.
