### ISSUE TITLE
Need help with mapping movement keys

### ISSUE THREAD

**Issue by dj-bauer** [andmarti1424/sc-im#544]
Hi there,
I would like to change the basic movement keys.
The reason behind that is, that I use the Colemak layout and therefore changed all my vim keybinds.
At the moment I am a bit overwhelmed by the documentation and did not find an example to let's say:
Map the <i> key to move one cell to the right.
Is there a way to remap this and when how?

P.S.: I have read about nmap "<key>" <action> but cannot find the relevant actions for tis.

Thank you for the usefull App,
Daniel

**Comment by andmarti1424** [comment]
Hello. `:nnoremap "b" "l"`?

**Comment by dj-bauer** [comment]
Thank you! Thank you so much for your fast response.
That was exacly what I was looking for.
