### ISSUE TITLE
All unselected cells get color from type=STRG, type=NUMB or EXPRESSION has no effect

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#546]
All unselected cells get color from type=STRG, type=NUMB or EXPRESSION has no effect.

**Comment by andmarti1424** [comment]
I dont think i am understanding this one.

**Comment by reportaman** [comment]
Sorry for not explaining it further. What I mean is on my machine, starting some version of sc-im, numbers and expressions also get color from type=STRG. So I am unable to set colors that distinguish strings from numbers and expressions.

**Comment by andmarti1424** [comment]
Sorry. I understand you now. You can update now and try again.

**Comment by reportaman** [comment]
@andmarti1424 What is the color type for cells that are empty? It can be default type? Now those cells are not colored, and get color from the terminal background.
<img width="258" alt="Screen Shot 2021-05-08 at 11 30 44 AM" src="https://user-images.githubusercontent.com/71736629/117549753-ff968b00-aff0-11eb-98f3-92130b198bc2.png">

**Comment by andmarti1424** [comment]
I believe GRID_ODD and GRID_PAIR.
(btw GRID_PAIR should be renamed to GRID_EVEN)

**Comment by andmarti1424** [comment]
Well I just did that in my latest commit.

**Comment by reportaman** [comment]
Yep, I confirm both. Closing this issue. Dracula will be released soon.

**Comment by andmarti1424** [comment]
Is it too long? You can attach it to an issue. Create a WIKI for themes.. Send it to email and I upload it.. What you prefer.

**Comment by reportaman** [comment]
@andmarti1424 Not too long. Btw, is there a way to source a file in scimrc? Like "input <path_to_theme>"?

**Comment by andmarti1424** [comment]
no. not really. that is something i have to add. to merge a file..
