### ISSUE TITLE
Bug/improvement: Differentiate between CELL_NEGATIVE, and negative result of EXPRESSION

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#553]
Currently CELL_NEGATIVE is applied to negative numbers entered by the user as well as the negative values of an expression. Given the positive values of expression have a different color group of its own (type=EXPRESSION). Either apply the same color group to negative values of expression, or add another group (type=EXPRESSION_NEGATIVE). Not sure how this would work when expressions evaluate strings. In that case the former approach of applying type=EXPRESSION to all expressions irrespective of value/type would be the easiest. Or separate color group for numeric expressions and string expressions. Though the problem with the easier approach is then it wouldn't be apparent whether user is looking at a string label that is a number, or a number itself. I would rather suggest adding 2 color groups, and renaming them: 

1. NUM_EXPRESSION,
2. NUM_EXPRESSION_NEG, 
3. STR_EXPRESSION

Check how there is no way to distinguish evaluated Sum, Avg values in left column with the negative values entered by the user. This problem does not exist in right column as Sum, Avg are positive there.

<img width="714" alt="sc-im-theme" src="https://user-images.githubusercontent.com/71736629/117611963-47b0cd00-b119-11eb-80dc-cc48c3fa4605.png">

**Comment by andmarti1424** [comment]
Yes, CELL_NEGATIVE applies to any negative number doesn't matter the origin. I think that should stay as is, as in old SC.

**Comment by reportaman** [comment]
@andmarti1424 Hmm... sc-im has come long way in its coloring, I think it will be good to have option for user as having same color for negative numbers and negative expressions lends itself to confusing/inconsistent UI (given we have different color for positive expressions). 

People derive meaning through similarity or differences of colors. Even though we as coders/engineers/power users of sc-im might know what is going on, our audience can be left perplexed in a presentation. When we are presenting a spreadsheet directly from sc-im to our colleagues, it will always be a difficult quirk to explain.

**Comment by andmarti1424** [comment]
@reportaman please open a discussion for this FR. We'll leave the feature requests in there so we can prioritize them for next release.
