### ISSUE TITLE
library not found for -lncursesw on Mac

### ISSUE THREAD

**Issue by marlun** [andmarti1424/sc-im#56]
I've uncommented `MACOSX := -DMACOSX` but when I run `make` I get `library not found for -lncursesw`. Any tips on what I should look into to fix it?

**Comment by andmarti1424** [comment]
You should download the ncursesw library.  This is the one that supports wide chars.You can also link to the common ncurses library. The first option is what I recommend. 



-------- Mensaje original --------
De: Martin Lundberg <notifications@github.com> 
Fecha: 14/02/2016  10:37  (GMT-03:00) 
A: andmarti1424/sc-im <sc-im@noreply.github.com> 
Asunto: [sc-im] library not found for -lncursesw on Mac (#56) 

I've uncommented MACOSX := -DMACOSX but when I run make I get library not found for -lncursesw. Any tips on what I should look into to fix it?

**Comment by marlun** [comment]
I'm looking into making a homebrew formula (#52) even thought I've never done it before. They specify in their guide that they don't like formulas that downloads dependencies so I'll try to look into what they'd recommend. If anyone knows more then me about homebrew I could use some help :)

**Comment by andmarti1424** [comment]
Couldnt you just link to ncurses library rather than ncursesw? Isnt the first one installed by default in your OS?

**Comment by marlun** [comment]
I could and it worked, thanks :)

**Comment by reckbo** [comment]
FYI to install ncursesw on a Mac, I did this:
  
    brew install ncurses
    brew link ncurses

Then you should see a bunch of `/usr/local/lib/libncursesw*` file links which scim can build against.

**Comment by andmarti1424** [comment]
Added to wiki.  Thanks!
