### ISSUE TITLE
`nnoremap	"T"	">"` results in `error replacing maps`. ">" can not be remapped.

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#568]
Simple Error:
Tried mapping something to ">", the rightwards insert.
All fail:
```
nnoremap	"T"	">"
nnoremap	"<LEFT>"	">"
nnoremap	"T"	"<GT>" 
nnoremap	"T"	"&gt;" # No error nor effect 
```

resulting in 
```
error replacing maps
```

Considerations: 
I do use a modified colemak layout. I'm also on Linux. Neither of those should matter, but in case the bug can not be reproduced, it is worth consideration. I have not had any issues with any other

**Comment by andmarti1424** [comment]
Hello. Yes. Indeed. Right now, '<' '>' are used for map special keys, like this <SPACE> or <LEFT>..
And any try to map those to enter left or right strings would get ignored..
Thinking the best way of handle both case.s.

**Comment by andmarti1424** [comment]
Please update to dev branch and try backing slash it like this:
`nnoremap	"T"	"\\>"`
thanks.

**Comment by Kill-Animals** [comment]
That worked. Thanks. 
Love your efforts.
