### ISSUE TITLE
Segfault when you delete last column/columns of sheet, undo it, and delete it again

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#569]
Simple bug. 
if you delete the column too many times, a segfault happens.
```
:nnoremap "_" "dc"
```
To demonstrate this easily, after remapping _ to delete a column, I need to only hold on the key for about 5 seconds before a segfault happens.

**Comment by andmarti1424** [comment]
This happen to you on an empty sheet? Or with a specific file? Ihave started to add some automatic tests. This could be a good one to add..

**Comment by Kill-Animals** [comment]
this happens on an empty sheet.

**Comment by andmarti1424** [comment]
@Kill-Animals could you please update latest commit on dev branch and try again?
If that works ok, please do not close the issue since I want to create a proper test for this. thanks.

**Comment by Kill-Animals** [comment]
I updated it. 
You do seem to have solved the issue about me merely holding down `_` until a segfault occurs.
However, if I do `55_` this will cause a segfault.

**Comment by andmarti1424** [comment]
Could you please update to latest commit and try again? Thanks.

**Comment by Kill-Animals** [comment]
Bug Fixed, however, I can still segfault, and the issue is related to undo. 

1. Goto ZY
2. `2_`
3. Undo
4. `2_` 
5. SEGFAULT

This undo effect results in some unintuitive behaviour. 

1. `31_`
2. `current column + multiplier exceeds max column. Nothing Changed`
3. `30_`
4. Undo
5. `31_` Now works
6. `91_`
7. `current column + multiplier exceeds max column. Nothing Changed`
8. `90_`
9. Undo
10. `91_` Now works

**Comment by andmarti1424** [comment]
@Kill-Animals you are a good tester. Join the team.
Could you please update to latest dev branch commit and do more tests? Thank you.

**Comment by andmarti1424** [comment]
btw, shifting cells far from last column has a similar issue. if the delete tests go ok I can apply the same to shifting process.

**Comment by Kill-Animals** [comment]
Yeah sure I'll join. Fun project.

**Comment by andmarti1424** [comment]
Could you test the cases again?

**Comment by Kill-Animals** [comment]
The unintuitive behaviour remains:
```
31_ current column + multiplier exceeds max column. Nothing Changed
30_ Works
Undo
31_ Works
91_ current column + multiplier exceeds max column. Nothing Changed
90_ Works
Undo
91_ Works
```
However the segfault has been fixed. 
The former is not exactly important.

**Comment by andmarti1424** [comment]
I will check it out. Ant way to reproduce it?

**Comment by Kill-Animals** [comment]
The Segfault was fixed. The unintuitive behaviour is reproduced by the following:
1. `31_` `current column + multiplier exceeds max column. Nothing Changed`
3. `30_` Works
4. Undo
5. `31_` Works
6. `91_`  `current column + multiplier exceeds max column. Nothing Changed`
8. `90_` Works
9. Undo
10. `91_` Works

Like I said, it isn't exactly important, but it is something that could lead to bugs.

**Comment by andmarti1424** [comment]
@Kill-Animals could you please update to latest commit and try again? Thanks.

**Comment by andmarti1424** [comment]
@Kill-Animals please let me know when you test this. Thanks

**Comment by Kill-Animals** [comment]
Hey I tested it. The behaviour is altered, and when doing a single undo, you managed to preserve the proper behaviour. However, 2 undos creates anomolies.
1. `31_` `current column + multiplier exceeds max column. Nothing Changed`
1. `30_` Works
1. `30_` Works
4. Undo
5. Undo
5. `89_` Works
6. `90_`  `current column + multiplier exceeds max column. Nothing Changed`
9. Undo
9. Undo
10. `90_` Works

**Comment by andmarti1424** [comment]
After 7. you only should have 1 action available to undo. Right? But you undid 2 times in 8. And 9...

**Comment by Kill-Animals** [comment]
You are right; That was my mistake there. I editted the sequence so it makes sense, by adding another `30_` so you have 3 undos..

**Comment by andmarti1424** [comment]
Sure you modified the example correctly? In step 8 I dont get that message, but the deletion is done.

**Comment by Kill-Animals** [comment]
Yes. I double checked and 8 did give me that message. I'll pull and try again

**Comment by andmarti1424** [comment]
I change the way it validates before allowing the deletion of the column.
before it checked over the number of alloc'ed columns.
now it checks over the last used column. so you cant passed it.
I also now save the values of maxrow, maxcol and modflg before and after changes.. and they are restored after undo/redo actions.

**Comment by Kill-Animals** [comment]
I tested it, and now it quite intuitive. 

Persisting Problems:
- I managed to segfault it twice. Very difficult to reproduce.
- I managed to corrupt the state. Very difficult to demonstrate.

In **both cases**, they require the use of a Redo bug. **To reproduce that:**
1. `c-r` `No REDOs left.` ( Not part of the bug. This just demonstrates that ordinarily, this is blocked. )
1. `nnoremap "_" "c-r"`
2. `_` `[ Silently iterates Redos to 1 of 1 ]
2. `_` `[ Silently iterates Redos to 2 of 2 ]
2. `>foobar`
2. `_`  Seems to be pasting either a piece of memory, or what I have put in the buffer. In one case, it was pasting `>"5F^Ub^E"` to whatever cell I was on. In another case, it was pasting `foobar`

**Comment by andmarti1424** [comment]
But what were the actions done in steps 3 and 4?
Delete a column?

**Comment by Kill-Animals** [comment]
No. Check step 2; I remapped `_` in this case to `c-r` aka Redo.

**Comment by andmarti1424** [comment]
The problem here is in step 2. You have to remap a Ctrl key like this:
`nnoremap "_" "<C-r>"`

**Comment by Kill-Animals** [comment]
That would make more sense to me, and I wondered that when I was working with my configuration file. However, are you absolutely sure about that?
For one, in the help file, it does not display `<>`
```
     u           UNDO last change
     c-r         REDO last change
                 Note: Events implemented for undo and redo:
                 1. cell or range deletion
                 2. cell input
                 3. cell editing
                 4. cell or range change in alignment
                 5. pasting a cell or range
                 6. range or cell shift with sh sj sk sl
                 7. row or column insertion
                 8. row or column deletion
                 9. pasting a row or column
                 10. zap(hide) or show a row or column
                 11. reordering of a range
                 12. changing the format of a range or cell
                 13. '-' and '+' commands in normal mode
                 14. locking and unlocking of cells
                 15. the datefmt command
                 16. the cellcolor command
                 17. Change in format of a column as a result of the 'f' command
                 18. Change in format of a column as a result of auto_jus
                 19. Change format of columns as a result of ic dc
                 20. fill command
                 21. unformat
                 22. change in the format of rows
```
And in my .vimrc, and `nnoremap "_" "c-r"` << it is allowing me to redo using the underscore.

**Comment by andmarti1424** [comment]
Yes. You paste the normal mode section. Check the MAPPINGS section.
I believe we could add another example with `<C-....>` to clarify this.

"..it is allowing me to redo using the underscore.." that is super weird!

**Comment by andmarti1424** [comment]
I think we can close this one. Original bug is probably already fixed.

**Comment by Kill-Animals** [comment]
Fair enough. The existing segfaults come from exceptional circumstances.
