### ISSUE TITLE
256 color support?

### ISSUE THREAD

**Issue by marlun** [andmarti1424/sc-im#57]
Hi,

I'm using iTerm with the "Pastel (Dark Background)" color preset which makes all the colors a little bit weak. Sometimes I want stronger colors and in vim I can just specify a number between 0-255 instead of a name but in scim it does not seem to work. Am I missing something or can I only use the color names?

Thanks!

**Comment by andmarti1424** [comment]
That is not possible right now.
The thing is that ncurses cannot handle 256 colors out of the box. I believe that would be only possible if you build SCIM with the ncursesw library as well.

VIM handles termcap directly and it not uses ncurses. But that is a different story.

May be we can leave this open for researching a little more in the future.

**Comment by marlun** [comment]
Ok, thanks. I'll leave it open. If I try building with ncursesw and it works I'll update the issue too.

**Comment by andmarti1424** [comment]
I am thinking that it might be possible to change ncurses color definitions with any RGB value..

**Comment by andmarti1424** [comment]
Please try latest dev branch commit. Now colors can be redefined like this:
:redefine_color "RED" 700 100 100

Some notes:
RGB values can vary from 0 to 1000.
You should link to ncursesw library.
ncurses shall be built with --enable-ext-colors and your terminal shall support 256 colors.
example: xterm-256color
