### ISSUE TITLE
Google sheets allows one to limit the number of columns and rows. Can this be done in "sc-im"?

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#570]
This is a feature request. 
I do not know what this feature is called, but it does exist on Google Sheets, and it is my favourite feature of that. 
If you look here:
![image](https://user-images.githubusercontent.com/85601521/121447929-8bcb0380-c94b-11eb-81b1-4f767832107b.png)
The amount of columns and rows does not infinitely expand to its limits. 

Assuming this does not exist in sc-im, could it reasonably be added as a particular mode? If so, I might go ahead and try adding it myself. 
Thanks.

**Comment by andmarti1424** [comment]
You mean the number of columns fixed? Or their width? Please open a discussion for feature requests, rather than issues.
