### ISSUE TITLE
:cpaste omits things inside `"` like so: `"foo"   "bar   "y"e"s" n"o"`  leaving `\t\t\to`

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#574]
Simple Bug [ I think ]
`:cpaste` the following string: `"foo"   "bar   "y"e"s" n"o"` ( The spaces are tabs `\t` ) and it will end up only pasting `n` in the fourth column. 

Unless this is intentional behaviour, I would expect that the quotes would be included when pasting strings.

**Comment by andmarti1424** [comment]
If you back slash them they will..

**Comment by Kill-Animals** [comment]
Good to know. 
What do you think of adding an option to ignore this? This will be good for me, because then I will not have to edit my content, namely the dictionary, before insertion into sc-im.

**Comment by andmarti1424** [comment]
Please update to latest commit on dev branch. It should auto back slash them and interpret them correctly.
