### ISSUE TITLE
segfault when searching cells by strings in multiple sheets

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#575]
Take this `.sc` file:
```
newsheet "foo"
newsheet "bar"
movetosheet "foo"
goto A0
movetosheet "bar"
goto A100
```

To reproduce the segfault,

1. Open `.sc` file.
1. `:int goto ""`
2. `:prevsheet`
3. `n`

Note: 
If the `.sc` was `goto A99` instead of `goto A100`, the segfault would NOT occur. 

Edit:
For good measure, I was able to reproduce the segfault from a new sheet:
1. `:newsheet ""`
3. `:int goto A100`
4. `:prevsheet`
5. `n`

**Comment by andmarti1424** [comment]
Again, this file was automatically generated. Right?

**Comment by Kill-Animals** [comment]
In short, yes, however the example I created is a distilled version of a much larger file.

**Comment by andmarti1424** [comment]
Yes. Actually this is caused by str_search needed to be rearranged for multiple sheets (still to be done).
Remember multisheet in sc-im is new, and a whole bunch of stuff was needed to be re-written.

**Comment by andmarti1424** [comment]
Well. made some changes to hopefully get rid of that segfault and make the strings and numbers search work for multisheet. btw, this code for searching comes mainly from old sc. Your tests are always welcome.

**Comment by Kill-Animals** [comment]
Tested it. Was not able to produce a segfault.
