### ISSUE TITLE
build err macos mojave (beginner)

### ISSUE THREAD

**Issue by molleweide** [andmarti1424/sc-im#577]
Hi there,

I want to try sc-im and i get this error message when building from source
```
install -d /usr/local/bin
install sc-im /usr/local/bin/sc-im
install: sc-im: No such file or directory
make: *** [install] Error 71
```
I put it here to see if somebody knows if this is a basic beginner message or whatever it is untill I have found out myself.

**Comment by andmarti1424** [comment]
Hello. Did you use `brew install`?

**Comment by molleweide** [comment]
oh sorry i should have added that info.

This is my process if I recall correctly:

1. first i installed with brew
2. realized that i want to use gnuplots
3. brew install gnuplot dependencies
4. brew uninstall sc-im
5. try to build from cloned repo

**Comment by molleweide** [comment]
wait now i think it works. i am not entirely sure. i must have missed cleaning up something and then there was a conflict because now it seems to work yay!
