### ISSUE TITLE
Scrolling down initially does not account for row height, placing the current cell offscreen.

### ISSUE THREAD

**Issue by Kill-Animals** [andmarti1424/sc-im#578]
to reproduce this bug:
1. `set autowrap=1`
2. paste the following: 34 rows
```
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.
The Quick Brown Fox Jumps Over The Lazy Dog.

```
3. `G` `CURROW=33` Showing Rows 27-33
4. Paste again
5. `G` `CURROW=66` Showing Rows 36-43

Result:
- **Visually** I am 23 rows behind 

Why is this a problem?
-

- Using `n` to search substrings, will not scroll the page down properly. 
- **This behaviour is not repeatable:**: For example, in one of my sheets:
1. `n` `CURROW=305` Showing Rows 269-302
2. `gg` 
1. `n` `CURROW=305` Showing Rows 272-305
1. `n` `CURROW=1458` Showing Rows 1422-1450
1. `gg`
1. `n` + `n`   `CURROW=1458` Showing Rows 1433-1458

**Comment by andmarti1424** [comment]
I dont know if this is the same as you describe.
1. set autowrap
2. paste the 34 rows with cpaste
3. 'G' scrolls down to A33 but leave the cell out of the screen. (the rows that appears on screen are 22 to 26 on my terminal 106x28).
4. 'gg' goes to A0.
5. 'G' again, now yes shows the grid correctly and scrolls correctly to A33.

**Comment by Kill-Animals** [comment]
Yes, that sounds right.

**Comment by andmarti1424** [comment]
@npitre Could you please take a look at this one? Check out my comment above.
Thanks!

**Comment by npitre** [comment]
I'm trying to understand how to reproduce...

How do you "paste"?

I started with a blank sheet, then \ to enter text. If I do a normal console
paste then the first line is entered, then subsequent lines are interpreted
as commands. I'm sure that's not what you're doing.

If I enter (or paste) the text all on the same line then I get another bug
i.e. the second screen line gets filled with garbage after sufficient text
gets entered, and the cursor moves to the top right corner and stays there.

**Comment by andmarti1424** [comment]
Hello @npitre. To paste just copy the text in a text editor. Could be X or tmux clipboard and use :cpaste command to paste it

**Comment by npitre** [comment]
Ah... Figured it out. I use neither X nor tmux so I crafted my own clipboard commands.

BTW the build fails if lua-devel is not installed.

**Comment by andmarti1424** [comment]
Will check lua-devel thing. What's your OS?

**Comment by npitre** [comment]
Fedora Linux release 33

**Comment by npitre** [comment]
OK I think I know what's wrong with the display.
Need to think of the best way to fix it.

**Comment by andmarti1424** [comment]
Now I'm extremely curious..

**Comment by npitre** [comment]
Fix in #579.

**Comment by andmarti1424** [comment]
Will check it out tomorrow. Thanks @npitre

**Comment by npitre** [comment]
Related to this, I wonder why you commented out the return to a 
single-line row when autowrap is disabled? That is commit 
6136687ae9db. The only way to get back to single lines now is to exit 
from sc-im and reload.

**Comment by andmarti1424** [comment]
@npitre cant recall very well right now, but there was a problem when no autowrap was set, and you wanted to have a row with rowformat bigger than 1..
it was forced it to 1.
what problem are you having with current behavior? you can set rowformat to 1 with `fk` or with `:formatrow` command.

**Comment by andmarti1424** [comment]
The thing is that you can have rows with format > 1 and do not use autowrap..
You shouldnt revert those to 1. I believe that was what happened before the commit you mention.

**Comment by npitre** [comment]
On Wed, 16 Jun 2021, Andrés Martinelli wrote:

> The thing is that you can have rows with format > 1 and do not use autowrap..

Oh I see. The row format is saved now.
