### ISSUE TITLE
sc-im reads xlsx files with unexpected behavior

### ISSUE THREAD

**Issue by jonnieey** [andmarti1424/sc-im#583]
sc-im opens xlsx files with following unexpected behaviour when using --xlsx_readformulas:

> Integers and floats are converted to ANOTHER numeric value with date format
  xlsx files exported from sc-im open with a syntax error and cell with formula is removed. If opened without --xlsx_readformulas the cell formula becomes 0

###sc-im version
> sc-im - version 0.8.3-main
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLSX
-DXLSX_EXPORT
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/share/sc-im"
-DLIBDIR="/usr/local/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP

###sc-im configuration file
> set input_bar_bottom
set truncate
set xlsx_readformulas
set half_page_scroll
set ignorecase
set autobackup=60

##Xlsx file from examples folder (xlsx/t3.xlsx)
###Screenshot
![2021-06-19-055722](https://user-images.githubusercontent.com/47189744/122629214-0c180400-d0c4-11eb-841d-0e2f49a0b557.png)

##Xlsx file from exported from sc-im
###Screenshot
![2021-06-19-055713](https://user-images.githubusercontent.com/47189744/122629220-12a67b80-d0c4-11eb-80f2-45a9db8f835f.png)

**Comment by andmarti1424** [comment]
Actually, there it seems to be something wrong with that file. If you happen to open it to gnumeric you'll see it returns a warning/error with a format type.
As soon as gnumeric opens it, (it nevertheless manage to load it correctly) if you save it again.. sc-im will load the new file without problem. See the example file I just uploaded in the examples folder (t3_b.xlsx)

**Comment by jonnieey** [comment]
I tested this with xlsx files from excel, gnumeric, libreoffice and exports from sc-im.

`sc-im --xlsx_readformulas file.xlsx`  

Results:
- Excel and  gnumeric xlsx files read correctly

- Libreoffice xlsx files are read and integers converted to another number
[OpenOfficeXMLSpreadsheet_Libreoffice.xlsx](https://github.com/andmarti1424/sc-im/files/6681707/OpenOfficeXMLSpreadsheet_Libreoffice.xlsx)

- sc-im xlsx files (exports from sc-im) are read with an error and the cell with formula is removed
[xlsx_export_sc-im.xlsx](https://github.com/andmarti1424/sc-im/files/6681706/xlsx_export_sc-im.xlsx)

**Comment by andmarti1424** [comment]
Could you please update to latest commit and redo the sc-im export test case again?
It shouldnt be neccesary since the program on which you later open the file exported by sc-im should recalculate formulas.. but now I explicitly store the formula result value as well.

Libreoffice case still pending to analyze

**Comment by jonnieey** [comment]
When exported from sc-im, gnumeric reads and retains the formula as expected. But if you reopen the file with sc-im with --xlsx_readformulas options it loads with an error and formula cell is removed.
However if you open with gnumeric and save it, sc-im with --xlsx_readformulas reads and retains the formula correctly.

**Comment by andmarti1424** [comment]
Please update and retry. Should keep the formula now.

**Comment by jonnieey** [comment]
Now it works as expected. Thanks.

**Comment by andmarti1424** [comment]
Regarding the first issue: not showing correctly the numbers in column D ("IMPORTE ORIGINAL"). Its seems to be something wrong inside the file where its has:
format id '43', 41, 44 and 42. All unknown for me (and Gnumeric)
I just cant think of a reason while they end up there.
Will replace the example file t3.xlsx with t3_b.xlsx

**Comment by jonnieey** [comment]
Thanks.
What about Librecalc xlsx export files behaviour. Should it be opened as another issue?

**Comment by andmarti1424** [comment]
I didnt remember about that.  Please attach here the sample file you have problems with and Ill check it out.

**Comment by jonnieey** [comment]
[Librecalc_xlsx_export.xlsx](https://github.com/andmarti1424/sc-im/files/6703588/Librecalc_xlsx_export.xlsx)

**Comment by jonnieey** [comment]
> Regarding the first issue: not showing correctly the numbers in column D ("IMPORTE ORIGINAL"). Its seems to be something wrong inside the file where its has:
> format id '43', 41, 44 and 42. All unknown for me (and Gnumeric)
> I just cant think of a reason while they end up there.
> Will replace the example file t3.xlsx with t3_b.xlsx

Files exported from Librecalc show this error when opened with gnumeric.

**Comment by andmarti1424** [comment]
I see. Its the same issue as the first one. invalid format id 41, 42, 43 and 44. I am not aware of those as valid formats. This might be an error in Librecalc perhaps. Will try to default it to numeric values. That seems to be what Gnumeric is doing here.

**Comment by jonnieey** [comment]
Yeah. This is an issue with librecalc. It uses formating code numFmtId 42, 43, and 44 which are undefined in [Closed xml](https://github.com/closedxml/closedxml/wiki/NumberFormatId-Lookup-Table) source code.  When opened in gnumeric and save the numFtId in xl/style.xml are converted to numFtId=0 (General). 
Can this be posible in sc-im, converting invalid numFmtId to 0 if they are invalid on :e xlsx filename.xlsx or on :w?

**Comment by andmarti1424** [comment]
Well. Here's the thing. The problem seems to not be with the numFmtID 42, 43 or 44.. Its seems Librecalc is using a custom defined format (164, and it is set there to General) for those cells, and not the predefined ones (numFtId below 164?). Thats is not something extrictly incorrect. Currently sc-im is not handling custom formats as it should. May be I can handle this case in particular.. Ill think about it.

**Comment by jonnieey** [comment]
Okay. :thumbsup:

**Comment by andmarti1424** [comment]
Could you please update to latest commit and test again? Thanks!!

**Comment by jonnieey** [comment]
Works fine now :thumbsup:. Thanks.
