### ISSUE TITLE
What is the name of the theme at scim4.png?

### ISSUE THREAD

**Issue by takusuman** [andmarti1424/sc-im#586]
And, actually, how do i set one? I've read the documentation, but i couldn't use a theme properly yet.

Thanks for the attention.

**Comment by andmarti1424** [comment]
It's not a theme specifically. Just take the `cellcolor` commands of any of the files inside `themes` folder, edit them to taste and add them to your scimrc file.

**Comment by andmarti1424** [comment]
Also, from the THEMES section of the doc:
 `  You can add the corresponding lines of those in your .scimrc or you can
    load them at runtime with :load path_to_theme_file
`
