### ISSUE TITLE
Can't nmap L to 5l or anything similar.

### ISSUE THREAD

**Issue by TheKhanj** [andmarti1424/sc-im#587]
I can't map anything to something which starts with number.
I would like to map HJKL to 5 movement for each direction but this doesn't seem to work.
Also I would like to map `<C-{hjkl}>` to scroll window, everything works fine except `<C-k>`. I have to pres `<C-k>` three times to work!!!
mapping:
`nmap "<c-h>" "zh"` OK
`nmap "<c-l>" "zl"` OK
`nmap "<c-j>" "5<c-e>"` doesn't work due to 5 in front of `<c-e>`
`nmap "<c-k>" "5<c-y>"` doesn't work even when I remove 5, Technically it works but i have to press `<c-k>` three times to trigger it.

**Comment by andmarti1424** [comment]
Its not the perfect approach but you could try this:
`nnoremap "<C-j>" "<C-e><C-e><C-e><C-e><C-e>"`

The C-k having to press it 3 times its a terminal issue. This also happens to me in tmux..

**Comment by andmarti1424** [comment]
btw, the doc explains this in the MAPPINGS section:
`Some notes:
    The Left and Right sequence of a mapping cannot contain numbers.`

**Comment by andmarti1424** [comment]
@TheKhanj could you test it? did that work for you?
