### ISSUE TITLE
Segmentation fault when using external functions

### ISSUE THREAD

**Issue by jonnieey** [andmarti1424/sc-im#588]
sc-im crashes with a segmentation fault when external functions options is set to 1.
for example:
if you use  =@ston(@ext("/path/to/script", A0+A3)) when option external_functions=0, it warns external functions are disabled. If you enable external function (:set external_functions) it evaluates correctly.
However, if you try to use external functions when the external_functions options is set (external_functions=1), it crashes.

**Comment by andmarti1424** [comment]
I wasnt able to replicate this.. until I run sc-im without Valgrind `=@ston(@ext("echo ", 2+2)))`
Will check it out.

**Comment by andmarti1424** [comment]
Please update to latest commit on dev branch. Should not SEGFAULT. I am still having a hard time to fix a memory leak related to this..

**Comment by jonnieey** [comment]
Okay, will check it out.

**Comment by andmarti1424** [comment]
This is same as #638. Will close this.
It does not segfault anymore. But I still have to fix a memory leak.
