### ISSUE TITLE
How to use theme file?

### ISSUE THREAD

**Issue by Darkstarinternet** [andmarti1424/sc-im#590]
I am trying to use the dracula theme file dracula.sc but I can't figure out how to include it in the scimrc config file. I have tried using:

source path/to/dracula.sc

but this gives a syntax error.

The manual says "You can add the corresponding lines of those in your .scimrc or you can load them at runtime with `:load path_to_theme_file`" but doesn't actually say how to do this.

Coping the contents of the dracula.sc file into scimrc works but I want to keep the theme file separate. Please can someone tell me the correct syntax for how to do this?

**Comment by andmarti1424** [comment]
Just try `:load path/to/dracula.sc`
There are only two ways: Adding entire content of the theme file (every line) to scimrc file or at runtime with the previous command.

**Comment by jonnieey** [comment]
> I am trying to use the dracula theme file dracula.sc but I can't figure out how to include it in the scimrc config file. I have tried using:
> 
> source path/to/dracula.sc
> 
> but this gives a syntax error.
> 
> The manual says "You can add the corresponding lines of those in your .scimrc or you can load them at runtime with `:load path_to_theme_file`" but doesn't actually say how to do this.
> 
> Coping the contents of the dracula.sc file into scimrc works but I want to keep the theme file separate. Please can someone tell me the correct syntax for how to do this?

I have created a basic sc-im tutorial to help one to get started. It's still a work-in-progress but hopes it'll help [Sc-im Tutoria](https://github.com/jonnieey/Sc-im-Tutorial)

**Comment by andmarti1424** [comment]
That is great! Will take a look at it more deeply.
Thanks

**Comment by andmarti1424** [comment]
btw, you can use `<C-p>` and `<C-n>` to scroll the history as well.

**Comment by andmarti1424** [comment]
About changing the theme at runtime, could you try the example above??
For instance, if you run sc-im from inside src folder, you could
`:load ../themes/dracula.sc`

I have just tested it and works ok.

**Comment by andmarti1424** [comment]
@jonnieey Your tutorial is great. Would you like me to link to it in the main Readme page of sc-im?

**Comment by jonnieey** [comment]
Sure. No problem.

**Comment by NMrocks** [comment]
@Darkstarinternet where did you get the Dracula theme for sc-im? I tried looking it up on the Dracula website but it's not there

**Comment by andmarti1424** [comment]
@reportaman did it

**Comment by reportaman** [comment]
@NMrocks @andmarti1424 I had opened a ticket https://github.com/dracula/dracula-theme/issues/522, seems like Dracula author Zeno Rocha might prefer getting a PR directly. Will do that.

**Comment by reportaman** [comment]
@andmarti1424 Now I remember... I was waiting for a logo for sc-im, but forgot to ask you. Thats because most apps listed on Dracula website seem to have some logo.

**Comment by andmarti1424** [comment]
@reportaman just give them the cat I have here in my avatar..

**Comment by ga47wot** [comment]
Loading the theme to another file works for me by using the load command as suggested. But however when I re-open this file the theme switches back to the default. How do we make sure the loaded theme is saved for that file.

**Comment by 1dancook** [comment]
@ga47wot Scim doesn't save theme related commands to an individual .sc file.
It does save `:cellcolor` commands.

At the moment Scim only supports a global theme as defined in your scimrc file.

So, `:load path/to/theme` is probably most useful for testing and tweaking a theme but not for using it regularly.

**Comment by andmarti1424** [comment]
Thanks for answering. I am ill and I'm afraid I will be offline for a couple of days until I recover.
