### ISSUE TITLE
[bug] Segmentation fault when pressing cc

### ISSUE THREAD

**Issue by chriskisskiss** [andmarti1424/sc-im#592]
New to sc-im, program crashes with segmentation fault, e.g. when i press cc in a cell (normal mode). All edits are gone. Is that normal behaviour?
version 0.8.1, macos.

Thanks!

**Comment by andmarti1424** [comment]
No seg fault is an expected behavior. Will take a look at it

**Comment by chriskisskiss** [comment]
thank you, here some further information:
- installed lua@5.1 via brew install lua@5.1.
- installed sc-im via brew install sc-im
- already reinstalled sc-im
- brew list with grep lua lists lua, lua@5.1, luarocks, luajit-openresty
- segmentation fault happens when pressing cc on a fresh startup of sc-im
- hardware is Apple Silicon

**Comment by andmarti1424** [comment]
Hello. No segfault with latest commit here. May be its something that got fixed after v8.1 release. Could you please retry updating to latest commit on dev branch? Thanks.

**Comment by andmarti1424** [comment]
Confirmed. This was fixed by v8.2.

**Comment by chriskisskiss** [comment]
Thank you very much! No problems on newest dev branch.

**Comment by andmarti1424** [comment]
Will be a new release as soon as I can get rid of that bug #588
