### ISSUE TITLE
installing on Mac OSX

### ISSUE THREAD

**Issue by incandescentman** [andmarti1424/sc-im#60]
I followed the instructions for installing on OSX, but I get this:

```
$ sudo make
gcc  block.o buffer.o cmds.o cmds_command.o cmds_edit.o cmds_insert.o cmds_normal.o cmds_visual.o color.o conf.o exec.o file.o filter.o format.o gram.o help.o hide_show.o history.o input.o interp.o lex.o main.o maps.o marks.o pipe.o range.o screen.o shift.o sort.o undo.o vmtbl.o xls.o xlsx.o xmalloc.o yank.o utils/dictionary.o utils/extra.o utils/string.o -o scim -lm -lncursesw 
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

$ sudo make install
install -d /usr/bin
install: chmod 755 /usr/bin: Operation not permitted
install scim /usr/bin/scim
install: scim: No such file or directory
make: *** [install] Error 71

```

**Comment by andmarti1424** [comment]
I do not have that OS but for the message,  make sure you have ncurses library installed in your system. 

-------- Mensaje original --------
De: Jay Dixit <notifications@github.com> 
Fecha: 25/02/2016  20:34  (GMT-03:00) 
A: andmarti1424/sc-im <sc-im@noreply.github.com> 
Asunto: [sc-im] installing on Mac OSX (#60) 

I followed the instructions for installing on OSX, but I get this:

$ sudo make
gcc  block.o buffer.o cmds.o cmds_command.o cmds_edit.o cmds_insert.o cmds_normal.o cmds_visual.o color.o conf.o exec.o file.o filter.o format.o gram.o help.o hide_show.o history.o input.o interp.o lex.o main.o maps.o marks.o pipe.o range.o screen.o shift.o sort.o undo.o vmtbl.o xls.o xlsx.o xmalloc.o yank.o utils/dictionary.o utils/extra.o utils/string.o -o scim -lm -lncursesw 
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

$ sudo make install
install -d /usr/bin
install: chmod 755 /usr/bin: Operation not permitted
install scim /usr/bin/scim
install: scim: No such file or directory
make: *** [install] Error 71

**Comment by rubenerd** [comment]
If you have homebrew, you can install the right libraries with:

    $ brew install ncurses

**Comment by andmarti1424** [comment]
Did you manage to install the program binding with the ncurses library?

**Comment by incandescentman** [comment]
Yes, I did install ncurses. 
```

$ brew link ncurses
Warning: ncurses is keg-only and must be linked with --force
Note that doing so can interfere with building software.

~/Downloads/sc-im-dev-1/src (master *) $ brew link ncurses --force
Linking /usr/local/Cellar/ncurses/6.0_1... 930 symlinks created
```

**Comment by andmarti1424** [comment]
I meant if you could install scim..

**Comment by incandescentman** [comment]
The solution was to change prefix to this: `prefix=/usr/local`

**Comment by adals** [comment]
where i should put prefix=/usr/local?

**Comment by andmarti1424** [comment]
I do not use MaxOSX but, the error is because the ncursesw library is not found. Do you have it installed?
