### ISSUE TITLE
Clarification on rows/columns limits

### ISSUE THREAD

**Issue by uvuxz** [andmarti1424/sc-im#601]
Hi Andrés,

Great project. 
I have been wanting to move out from google sheets into something simpler and since I am a vim user, your project seems like a perfect fit.
I was just wondering if you could clarify the limit in the number of rows/cols. Is this an arbitrary number dependent on the end-user RAM?
Additionally, how many cols can one see at a given moment in one monitor? And how are you able to horizontally scroll to the remaining?

All the best.

**Comment by andmarti1424** [comment]
Hello! thanks.
Max number of rows is 2^16 (65536) by default. Its defined on macros.h
Max number of cols is 702 if I recall well (just to keep two characters in the reference).The last one would be column ZZ.
About the second question, it really depends on the size of your (ncurses) screen and the content you have in the cells.
Regarding the third question, take a look at help page. You would probably find what you look for with the commands that start with 'z' in normal mode.

Please feel free to use Github discussions for these and other inquiries.
Thanks again.

**Comment by uvuxz** [comment]
Thank you for the prompt reply!
Will check the help page.
Good work once again!
