### ISSUE TITLE
compile error on ubuntu

### ISSUE THREAD

**Issue by sbng** [andmarti1424/sc-im#602]
cc -Wall -g -DNCURSES -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DSNAME=\"sc-im\" -DHELP_PATH=\"/usr/local/share/sc-im\" -DLIBDIR=\"/usr/local/share/doc/sc-im\" -DDFLT_PAGER=\"less\" -DDFLT_EDITOR=\"vim\" -DUSECOLORS -DHISTORY_FILE=\"sc-iminfo\" -DHISTORY_DIR=\".cache\" -DCONFIG_FILE=\"scimrc\" -DCONFIG_DIR=\".config/sc-im\" -DINS_HISTORY_FILE=\"sc-iminfo\" -DUNDO -DMAXROWS=65536 -DUSELOCALE -DMOUSE -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\" -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\" -DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD=\""scopen"\" -DAUTOBACKUP -DHAVE_PTHREAD -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DXLSX_EXPORT -I/usr/local/include   -c -o formats/xlsx.o formats/xlsx.c
formats/xlsx.c: In function ‘export_xlsx’:
formats/xlsx.c:569:28: error: ‘session’ undeclared (first use in this function)
  569 |     struct roman * roman = session->cur_doc;
      |                            ^~~~~~~
formats/xlsx.c:569:28: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: formats/xlsx.o] Error 1

**Comment by sbng** [comment]
╰─ ls -l /usr/local/lib/libxlsxwriter* 
-rw-r--r-- 1 root root 3916228 Sep  2 13:06 /usr/local/lib/libxlsxwriter.a
lrwxrwxrwx 1 root root      18 Sep  2 13:06 /usr/local/lib/libxlsxwriter.so -> libxlsxwriter.so.3
-rwxr-xr-x 1 root root 1770896 Sep  2 13:06 /usr/local/lib/libxlsxwriter.so.3

libxlsxwriter installed manually in /usr/local/lib/

**Comment by andmarti1424** [comment]
Hello @sbng . Wheat version are you using?
Regarding `:569:28: error: ‘session’ undeclared (first use in this function)`
'session' variable is declared on line 73 of formats/xlsx.c:
`extern struct session * session;`

**Comment by sbng** [comment]
using the lastest main commit 0d815ba3cb57b1facd3c55573f40975094b5f6d4. Yes, I can see the struct was declared on line 73 but compile failed giving the above error.

**Comment by andmarti1424** [comment]
Please try compiling with gcc

**Comment by andmarti1424** [comment]
@sbng Have you tried it?

**Comment by sbng** [comment]
sorry for the belated reply. Yes I tried gcc, same error.

sbng@oat[~/.local/src/sc-im/src]:$ make CC=gcc                                                                                                                                                                                  [Umain]
gcc -Wall -g -DNCURSES -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DSNAME=\"sc-im\" -DHELP_PATH=\"/usr/local/share/sc-im\" -DLIBDIR=\"/usr/local/share/doc/sc-im\" -DDFLT_PAGER=\"less\" -DDFLT_EDITOR=\"vim\" -DUSECOLORS -DHISTORY_FILE=\"sc-iminfo\" -DHISTORY_DIR=\".cache\" -DCONFIG_FILE=\"scimrc\" -DCONFIG_DIR=\".config/sc-im\" -DINS_HISTORY_FILE=\"sc-iminfo\" -DUNDO -DMAXROWS=65536 -DUSELOCALE -DMOUSE -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\" -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\" -DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD=\""scopen"\" -DAUTOBACKUP -DHAVE_PTHREAD -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DXLSX_EXPORT -I/usr/local/include   -c -o formats/xlsx.o formats/xlsx.c
formats/xlsx.c: In function ‘export_xlsx’:
formats/xlsx.c:569:28: error: ‘session’ undeclared (first use in this function)
  569 |     struct roman * roman = session->cur_doc;
      |                            ^~~~~~~
formats/xlsx.c:569:28: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: formats/xlsx.o] Error 1

**Comment by andmarti1424** [comment]
@sbng Could you solve this? May be you can try with -std flag to gcc.
Also.. could be that ubuntu sets some flags with different checks as default, in comparison to other distros?

**Comment by AdamMajer** [comment]
If `XLSX` is undefined, then this variable will not be defined. The `XLSX_EXPORT` is a different pre-processor block.

**Comment by ItzSwirlz** [comment]
As of when 0.8.2 was packages and pushed to Debian unstable, and now at the moment Ubuntu Jammy 22.04 and Kinetic Kudu (devel branch) 22.10, in order to make things work I actually patched/adjusted the makefile a bit.

https://salsa.debian.org/math-team/sc-im/-/blob/master/debian/patches/adjust-makefile-for-packaging.patch
