### ISSUE TITLE
Saving an ODS file results in it being re-written to an sc-im file

### ISSUE THREAD

**Issue by mhmdanas** [andmarti1424/sc-im#606]
Steps to reproduce:
1. Open an ODS file in sc-im (you can get one from https://file-examples.com/index.php/sample-documents-download/sample-ods-download)
2. Type `:x`
3. The ODS file is now actually an sc-im file, though the filename and extension didn't change

**Comment by andmarti1424** [comment]
Hello. This behaviour is clearly not consistent with other formats such as xlsx.

**Comment by andmarti1424** [comment]
Nevertheless, it seems correct since ODS file saving is not yet supported.

**Comment by mhmdanas** [comment]
Yet I think this particular behavior is undesirable, as it can lead to data loss.

**Comment by andmarti1424** [comment]
Yes. That could be. Prevent user to save a file that its name finish with ".ods".

**Comment by andmarti1424** [comment]
@mhmdanas Please update to latest commit on dev branch and retry!

**Comment by mhmdanas** [comment]
Sorry, I'm trying to build from source on macOS, but I can't seem to get it to build with ODS support (I was using sc-im from Homebrew previously). I'll try again later.

**Comment by cxsmxx** [comment]
I just tried to save .ods file, says still the same thing, compiled from source, can I help somehow?

**Comment by andmarti1424** [comment]
Can't be. You took the latest commit on `dev` branch??

**Comment by cxsmxx** [comment]
Im on MacOS, could that be the reason? `libxls` is named `xlslib` over here

**Comment by andmarti1424** [comment]
no no. just check you have this:
![image](https://user-images.githubusercontent.com/9466161/133796696-79dadd29-72e3-43a7-bad4-ebc81966bb2b.png)

**Comment by cxsmxx** [comment]
Yeah, the log is the "not yet"
![image](https://user-images.githubusercontent.com/12977596/133804893-3edbeb5d-fc63-4d20-afe1-8ac2b0cff1b9.png)

**Comment by andmarti1424** [comment]
Then it is validating correctly. Right?

**Comment by cxsmxx** [comment]
Yes it is, consider issue resolved from my end

**Comment by cxsmxx** [comment]
Anyway if the issue could be resolved with my help, I would be happy to contribute

**Comment by mhmdanas** [comment]
Just successfully built sc-im from source and I can confirm that it will show a warning if I try to save to an ODS file. Thanks!
