### ISSUE TITLE
Plain text export function

### ISSUE THREAD

**Issue by boeckmann** [andmarti1424/sc-im#61]
Thanks for the app! I have a question regarding plain text export. In original sc, one can write out a plain text version of the shreadsheet with command key w. I do not have found a way to do it in sc-im. If I export using tab delimited files with :e tab the format is messed up.

So my question is: is there any way to do plain text export I have overlooked?

Thanks, Bernd!

**Comment by andmarti1424** [comment]
Hello. Ita in my Todo list. Please give me a couple of days and it will be added. Thanks. 

-------- Mensaje original --------
De: Bernd Böckmann <notifications@github.com> 
Fecha: 19/03/2016  8:17  (GMT-03:00) 
A: andmarti1424/sc-im <sc-im@noreply.github.com> 
Asunto: [sc-im] Plain text export function (#61) 

Thanks for the app! I have a question regarding plain text export. In original sc, one can write out a plain text version of the shreadsheet with command key w. I do not have found a way to do it in sc-im. If I export using tab delimited files with :e tab the format is messed up.

So my question is: is there any way to do plain text export I have overlooked?

Thanks, Bernd!

**Comment by andmarti1424** [comment]
I am looking in to this.. What kind of format is messed up if you export as tab delimited?

**Comment by boeckmann** [comment]
Well, the cells are not properly aligned anymore. In sc, if you export as plaintext, the editor shows the spreadsheet exactly like sc does. That is not the case if you export from scim. But it is handy, for example if you want to include the spreadsheet in an email.

Perhaps it is ok to use no delimiter at all but export only the cell contents as text?!? I may look into this for myself. From what I get by a brief look into the source code, do_export should be the right place to start?

**Comment by andmarti1424** [comment]
I see... I will check it out. The most difficult will be to keep the alignment.

Yep. There in do_export and in cmds_command.c where do_export function is called would be the place to start..

**Comment by andmarti1424** [comment]
Please try latest dev branch commit. You can export to plain text like this:

:e txt filename.txt

**Comment by boeckmann** [comment]
Seams to work :-) Thank you very much.

**Comment by andmarti1424** [comment]
OK. I still have to make some changes. For instance, if you have in a cell both a number and text, only the number is saved..

**Comment by andmarti1424** [comment]
Please re-test updating to latest branch commit!! Thanks.

**Comment by boeckmann** [comment]
What I noticed with the latest commit is that there seem to be some unnecessary empty rows and columns in the exported txt document (vertically and horizontally at the end).

My .sc document contains 34 rows but 41 lines are exported. There are also several spaces at the end of each line which are not needed.

**Comment by andmarti1424** [comment]
Do you have columns or rows hidden?
With this version hidden rows and columns are saved to file, while with
previous version do not.

**Comment by boeckmann** [comment]
Sent you a sample .sc file and the exported txt by mail.

**Comment by boeckmann** [comment]
Yes, the extra white spaces after the last column and the extra newlines after 1331.73.

**Comment by andmarti1424** [comment]
I believe that would be difficult to change and its related to how the
program allocates memory.

You know you can enter visual mode selects the range only the range you
want and export that range.
If you do that, those white spaces will not appear.

2016-03-23 10:06 GMT-03:00 Bernd Böckmann <notifications@github.com>:

**Comment by boeckmann** [comment]
Yes! Tried that and it works like you explained. Thank you!
