### ISSUE TITLE
`c$` in Edit Mode bug

### ISSUE THREAD

**Issue by laktak** [andmarti1424/sc-im#611]
When in edit mode `c$` does not work correctly.

With the input `ABCD` and the cursor on `C`:
- when I press `c$` and type `Z` the result is `AZB`
- the expected result is `ABZ`

SC-IM - version 0.8.2

**Comment by andmarti1424** [comment]
Thanks for reporting this! Will fix it.

**Comment by laktak** [comment]
I just noticed that `cw` is also affected:

```
2021-10-14
        ^ cursor here in normal mode
```

if you then type `cw` everything looks OK but when you enter `15` it gives you:

```
2021-1015-
```

while the cursor is still shown at the end. 

It works though if I use `ce` instead.

**Comment by laktak** [comment]
Thanks! `C` and `cw` work great now!

While testing I discovered another bug - I think also related to this one.

- enter `ABCD` and go to edit mode
- with the cursor on `D` type `d$` 
- notice that the `D` is deleted but the cursor stays on the now empty space
- type `a` and enter some text - nothing will be shown on the screen

**Comment by laktak** [comment]
No problem, thanks for you help! `d$` works now as well!

`D` has the same issue as `d$` before (it should be 'mapped' to `d$`)
