### ISSUE TITLE
Stop the madness

### ISSUE THREAD

**Issue by bartenbach** [andmarti1424/sc-im#614]
|        Key       |                 Purpose                 |
|------------------|-----------------------------------------|
|         \        | Insert a text value                     |

All of the other keys mimic vim, but insert is a backslash.

*A backslash*.

There is nothing bound to 'i'.

Why.

Why would you do that.

**Comment by bartenbach** [comment]
I have not used sc before.

I see what it's used for in the documentation....it feels like heresy.

This is a fantastic console application by the way. Words cannot express how happy I am that this exists. You are doing the lord's work.

....but the insert mode thing is going to drive me insane.

**Comment by bartenbach** [comment]
> You might create a mapping and get away with it. Not recommend though.

Why's that?  I also feel like 'O' should do what 'ir' does.  It's so close to being like vim but not quite.

**Comment by andmarti1424** [comment]
sc-im goal is not to recreate vim.

vim is vim.
sc-im is sc-im

If you are uncomfortable with some key bindings you might want to define mappings.

**Comment by bartenbach** [comment]
> sc-im goal is not to recreate vim.
> 
> vim is vim. sc-im is sc-im
> 
> If you are uncomfortable with some key bindings you might want to define mappings.

That's fair.

I'll play with some mappings.  I'm sure I can make something work.

Also I tried to open an xlsx on OSX the other day and it said that xlsx support wasn't compiled in. No clue who is responsible for compiling binaries distributed by homebrew, but I thought that was odd.

**Comment by tuckerconnelly** [comment]
I concur with @bartenbach, and move to stop this nonsense and purify the keybindings.

To fix these wrongs, you can edit your `sc-im` configuration file `nvim $HOME/.config/sc-im/scimrc` with the following:

```
nunmap "ir"
nunmap "ic"
nmap "i" "\"
nmap "a" "\"
nmap "A" "\"
nnoremap "O" "ir<CR>\"
nnoremap "o" "or<CR>j\"
```

**Comment by bartenbach** [comment]
At first it's definitely very jarring. I'm used to it now, and I never bothered to remap.

I guess one of the main issues with my original plan would be that '\\' inserts a label, but it will not insert a number which is what '=' is used for. That certainly complicates things.

It's a fantastic program and I use it more and more.  I highly recommend checking out ":help" if you haven't already. It's surprisingly very detailed and extremely well written. I can almost always quickly find what I need there.

There is an sc-im tutorial repo as well. I have it cloned down, and I intended to go through it - but usually the help documentation is so good I haven't even needed to do that. I can usually learn new things quickly on the fly by browsing ":help"

**Comment by danielkrajnik** [comment]
I couldn't find it in documentation so for other travellers who comes across this thread pressing `i` is reserved to be followed by either `r` or `c` to insert row or column.

I'm a fresh new to sc-im and `=`, `\` and ``<and `>` also seemed very strange to me. Maybe I will understand the reasoning later, but for now @tuckerconnelly thank you very much for sharing the keybindings (it would have taken me a long time to figure out that you need to unmap them first).
