### ISSUE TITLE
Segmentation Fault (crash) using marked range in a calculation.

### ISSUE THREAD

**Issue by 1dancook** [andmarti1424/sc-im#624]
### The Issue

I get a segmentation fault every time when trying to use a marked range for a calculation.

### To Reproduce

Here is `test.sc`:

```
# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

set external_functions
let A0 = 1
let B0 = 1
let A1 = 1
let B1 = 1
goto C1
```

If I type this in manually, there is no issue and works as expected. In C1:

```
=@sum(A0:B0)<CR>
```

However, if I use a marked range in the function, I will get a segmentation fault:

1. Select A1:B1
2. Mark a: `ma`
3. Use the marked range in the function:

```
=@sum(<C-r>a)<CR>
```

This will result in a segmentation fault. The same behavior exists if I use two different marks to indicate a range i.e. `=@sum(<C-r>a:<C-r>b)<CR>`

### Other details:

- sc-im version: 0.8.2 installed via homebrew
- OS: MacOS
- I am using tmux, but behavior is the same either way

**Comment by andmarti1424** [comment]
Could you please update to latest commit on dev branch and retry?
Thanks.

**Comment by 1dancook** [comment]
Works in the dev branch. 👍👍 Will close.
