### ISSUE TITLE
Bug: Using @lua results in segmentation fault (crash)

### ISSUE THREAD

**Issue by 1dancook** [andmarti1424/sc-im#629]
### Description:

Using `@lua` in a cell will result in a segmentation fault. 

This issue is present for sc-im v0.8.2 on MacOS.

This issue is **FIXED** in the 0.8.3 dev branch.

### Steps to reproduce

1. git clone the repo
2. Go to the repo examples: `cd sc-im/examples/lua`
3. Open test.cs: `sc-im test.sc`

### Other info:

Output of `lua -v`:

```
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
```

**Comment by andmarti1424** [comment]
v0.8.2 will be replaced by v0.8.3 shortly

**Comment by 1dancook** [comment]
v0.8.3 doesn't crash when using @lua but on macOS the home-brew installation is not being built with lua support. See below for --version output.

So, in 0.8.3 loading a file with @lua being used won't cause a seg fault now. But I am able to produce a seg-fault if lua support is not built in with these steps on macOS:

1. `brew install sc-im --HEAD` to install 0.8.3-main
1. Make a `~/.config/sc-im/lua/helloworld.lua` script with these contents: `sc.sc("LET A0=1")`
2. Open sc-im and type `=@ston(@lua("hello world.lua",0))<CR>`

The above causes a segmentation fault. In my 0.8.3-dev build it works.

The home-brew formula probably needs to be updated somehow - I don't understand why it isn't building with lua since the makefile builds it fine locally. I don't know much about how those formulas work, though. 

Going forward it may be good to require lua and always build it in. If not, it will be good that if lua support is not built in, then sc-im gives feedback (i.e. "No lua support built in") rather than a seg fault.

---

Output of `sc-im --version` (built with `brew install sc-im --HEAD`) and lacking `-DXLUA`:

```
sc-im - version 0.8.3-main
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLS
-DXLSX
-DXLSX_EXPORT
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/Cellar/sc-im/HEAD-64b1a41_3/share/sc-im"
-DLIBDIR="/usr/local/Cellar/sc-im/HEAD-64b1a41_3/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by 1dancook** [comment]
It looks like when running the home-brew install, pkg-config is not finding lua. I found this out by forking the repo, modifying the lua part in the makefile to just assume pkg-config and add lua stuff (try to force it). Then I made a home-brew formula for the fork. 

I get this:
```
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
```

Very strange. If I run `pkg-config --list-all`, lua is there.

So, I find where this lua.pc is and tried `export PKG_CONFIG_PATH=/usr/local/lib/pkg-config"`

Running `brew install --HEAD --build-from-source` now worked with the env variable set. Then, opening sc-im and trying lua it all works.

BUT! This now has something else strange -- I get the same issue now that I had from before with #627

**Comment by 1dancook** [comment]
I tried my own home-brew formula for my fork and added two lines and this seems to make everything work for installing:

```
  depends_on "lua"
  depends_on "pkg-config"
```

This is below the `  depends_on "ncurses"`

May need to test that more. But I have lua working in 0.8.3 with no crazy colors installed via home-brew.

**Comment by 1dancook** [comment]
Last night I read through some homebrew documentation and tried this morning. Apparently you can just edit the local formulas with `brew edit <formula>`. 

So here is what I have now and it is slightly different than the current homebrew formula:

```ruby
class ScIm < Formula
  desc "Spreadsheet program for the terminal, using ncurses"
  homepage "https://github.com/andmarti1424/sc-im"
  url "https://github.com/andmarti1424/sc-im/archive/v0.8.2.tar.gz"
  sha256 "7f00c98601e7f7709431fb4cbb83707c87016a3b015d48e5a7c2f018eff4b7f7"
  license "BSD-4-Clause"
  revision 3
  head "https://github.com/andmarti1424/sc-im.git", branch: "main"

  bottle do
    sha256 arm64_monterey: "7ebc2e0f8248b991474defdab0519dbffc74761b0627100abb9a52e15cc1f945"
    sha256 arm64_big_sur:  "7a695c6f3c7c830c2c88bf60ec0bc8e844a82b1adf7ed4cd474d89326c0600ff"
    sha256 monterey:       "16d81d91ba10cc86b39c3408290a3dfc71458c0e72b9dce4bf0dde9a817600f6"
    sha256 big_sur:        "311253002c6a2e14f2003a7e7e8f88ecbe54a7bd6f373a695e14a2cb4ec0a377"
    sha256 catalina:       "d25892c33ee8ac59c5e6439a9fe7893fa49c4a8514c2aac880f95f997c3eef32"
    sha256 x86_64_linux:   "cfcf853d84da9ede68d92fed791600c887869a2fcb2c689eafb3f491a00b06af"
  end

  depends_on "libxls"
  depends_on "libxlsxwriter"
  depends_on "libxml2"
  depends_on "libzip"
  depends_on "ncurses"
  depends_on "pkg-config" => :build
  depends_on "lua" => :recommended

  uses_from_macos "bison" => :build

  def install
    cd "src" do
      system "make", "prefix=#{prefix}"
      system "make", "prefix=#{prefix}", "install"
    end
  end

  test do
    input = <<~EOS
      let A1=1+1
      recalc
      getnum A1
    EOS
    output = pipe_output(
      "#{bin}/sc-im --nocurses --quit_afterload 2>/dev/null", input
    )
    assert_equal "2", output.lines.last.chomp
  end
end
```

Previously pkg-config was not a requirement for build on macOS so that should be fixed with `depends_on "pkg-config" => :build` (only need it for build).

`depends_on "lua" => :recommended` makes it so that by default it will be dependent on lua and you can opt-out with `--without-lua`.

If the homebrew formula is updated to this, the readme for sc-im should be updated as well. The part about `brew install lua@5.1` would be unnecessary. (Actually it should be changed anyway since homebrew will install it but give a warning -- should be just `lua` which installs 5.4)

With the above formula I can install 0.8.2 with lua: `brew install sc-im --build-from-source`
---

I don't know if there are any other macOS users around who could also test this. It works on my machine but I hope someone else can check and give feedback. @andmarti1424 is there anyone you know that can test this out?

1. I'm curious to see if others have `-DXLUA` in the output of `sc-im --version` from the homebrew install (`brew install sc-im`).
2. If someone can try, do `brew edit sc-im` and copy the formula above. After doing `brew install sc-im --build-from-source` (which will build instead of using a bottle) then check if you have `-DXLUA` in the output of `sc-im --version`. 


---

Output of `sc-im --version` (this is the pre-compiled bottle from `brew install sc-im`):

```
SC-IM - version 0.8.2
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/Cellar/sc-im/0.8.2_3/share/sc-im"
-DLIBDIR="/usr/local/Cellar/sc-im/0.8.2_3/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

Output of `sc-im --version` after doing `brew install sc-im --build-from-source` using the formula above:
```
SC-IM - version 0.8.2
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLS
-DXLSX
-DXLSX_EXPORT
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="tmux load-buffer"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="tmux show-buffer"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/Cellar/sc-im/0.8.2_3/share/sc-im"
-DLIBDIR="/usr/local/Cellar/sc-im/0.8.2_3/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by andmarti1424** [comment]
I believe @reportaman uses MacOS.
What about sharing your formulae to `https://formulae.brew.sh/`.
I think you could upload it.

**Comment by 1dancook** [comment]
Yes I can do that. I need to find a bit more information because I don't know where those bottle hashes came from 😂

**Comment by 1dancook** [comment]
I have submitted a PR for the formulae to get updated. Maybe it takes a few days.
I had to make a few adjustments for it to pass an audit (couldn't use the `recommended` flag for lua - but I think that is okay).

**Comment by 1dancook** [comment]
New formula was merged to homebrew-core so I will close this now.
