### ISSUE TITLE
Make pbcopy/pbpaste default clipboard for macOS

### ISSUE THREAD

**Issue by 1dancook** [andmarti1424/sc-im#630]
### Description

The default installation of sc-im doesn't use `pbcopy` or `pbpaste` for macOS. As of 0.8.2 it uses X clipboard.

### Suggested change

Makefile needs to have logic:

```
if macos:
  use pbcopy/pbpaste
else:
  use x clipboard
```

I will try to submit a PR for this.

**Comment by andmarti1424** [comment]
Should be merged on dev branch
