### ISSUE TITLE
Using :cpaste should recalculate sheet if autocalc is set

### ISSUE THREAD

**Issue by 1dancook** [andmarti1424/sc-im#632]
### Description

Currently, using `:cpaste` doesn't update other cells if `autocalc` is on.

### Expectation

For example,

If `A0=B0`, `:cpaste` into `B0` should update `A0` automatically if I have `autocalc` on.

---

*I have this working in a branch, but I don't know C really and I don't want to submit a PR necessarily because I may be missing something. I was pretty confident that this will be just a one line addition. I have added the diff below. If this looks okay I can submit the PR. Let me know.*

```
diff --git a/src/clipboard.c b/src/clipboard.c
index 889d454..62005e1 100644
--- a/src/clipboard.c
+++ b/src/clipboard.c
@@ -131,6 +131,7 @@ int paste_from_clipboard() {
         if (r > MAXROWS - GROWAMT - 1 || c > ABSMAXCOLS - 1) break;
     }
     sc_info("Content pasted from clipboard");
+    if (get_conf_int("autocalc")) EvalAll();
 
 out:
     // close file descriptor
```

**Comment by andmarti1424** [comment]
Added to dev branch. Thanks.
