### ISSUE TITLE
sc.colrow2a has arguments reversed

### ISSUE THREAD

**Issue by 1dancook** [andmarti1424/sc-im#635]
sc-im version: 0.8.3-main + dev

### Description

According to `:help` the argument order for `sc.colrow2a` is `column` then `row` but they are actually flipped.

I believe the order should be `column` then `row` to be consistent with other lua functions.

### How to reproduce

Make `~/.config/sc-im/lua/colrow.lua` with contents:

```
current_col = sc.curcol()
current_row = sc.currow()
ascii = sc.colrow2a(current_col, current_row)
sc.lsetstr(3,0,ascii)
```

In scim in cell A1 do:

`\"@lua("colrow.lua",0)`

Expected result is that D0 will read "A1" but it reads "B0"

---

Again, I'm not comfortable with C but this patch seems to fix it:

```
diff --git a/src/lua.c b/src/lua.c
index 1d36125..d212185 100644
--- a/src/lua.c
+++ b/src/lua.c
@@ -241,8 +241,8 @@ static int l_colrow2a(lua_State *L) {
     int c, r;
     char buf[16];
 
-    r = lua_tointeger(L, 1);  /* get argument */
-    c = lua_tointeger(L, 2);
+    r = lua_tointeger(L, 2);  /* get argument */
+    c = lua_tointeger(L, 1);
     sprintf(buf,"%s%d", coltoa(c),r);
     lua_pushstring(L,buf);
     return 1;
```

**Comment by andmarti1424** [comment]
Yes indeed. Thank you. Fixed on dev branch.
