### ISSUE TITLE
Segmentation fault when add a new filter

### ISSUE THREAD

**Issue by RicardoOpus** [andmarti1424/sc-im#637]
Sc-im crashes with a segmentation fault when I add a new filter, after delete the previous one.
I do this:
Frist I create a filter via addfilter; ex `:addfilter "#F=1".`
Then I apply it by `:filteron F2:F10`.
This work fine.
But, when I delete the old filter and create another one,  it  crashes when set the _filteron_ again.

**Comment by 1dancook** [comment]
I confirm it's the same in 0.8.3-main.

**Comment by andmarti1424** [comment]
Does this happen to you also if you disable the filter just before deleting it?

**Comment by andmarti1424** [comment]
I am having trouble to reproduce this. Could you please detail also the latests steps when you delete the filter and create and apply a new one? Thanks.

**Comment by 1dancook** [comment]
Okay I have tried a few things:

```
:addfilter "#A=0"
:filteron A0:A1
:delfilters
:addfilter "#A=0"
:filteron A0:A1 ----> segfault
```

```
:addfilter "#A=0"
:filteron A0:A1
:delfilters
:filteroff
:addfilter "#A=0"
:filteron A0:A1 ----> segfault
```

```
:addfilter "#A=0"
:filteron A0:A1
:delfilters
:addfilter "#A=0"
:showfilters     ---> segfault
```

```
:addfilter "#A=0"
:delfilters
:showfilters  --> works as expected
```

```
:addfilter "#A=0"
:delfilters
:addfilter "#A=0"
:filteron A0:A1    --> segfault
```

```
:addfilter "#A=0"
:delfilter 0
:addfilter "#A=0"
:filteron A0:A1    --> works!
```

It might be that the problem lies with `:delfilters`

If I use `delfilter [n]` it will work as expected.

**Comment by 1dancook** [comment]
👆 I tried the above on MacOS.

Have just tried on Alpine Linux and is working as expected. 🤔

**Comment by 1dancook** [comment]
@andmarti1424 I have tried the following adjustment in `filter.c` and it solves the issue on my side.
I just basically copied what was below from `del_filter()`. I tried those different combinations from above again and that seems to have solved it.

Again, I'm not confident in C so please double check.

```
diff --git a/src/actions/filter.c b/src/actions/filter.c
index 411620d..02c6b08 100644
--- a/src/actions/filter.c
+++ b/src/actions/filter.c
@@ -217,9 +217,10 @@ int free_filters() {
     if (filters == NULL) return -1;
     int i;
     for (i=0; i < howmany; i++)
-        if (filters[i].eval != NULL) scxfree((char *) filters[i].eval);
-    scxfree((char *) filters);
-    filters = NULL;
+        if (filters[i].eval != NULL) {
+            scxfree((char *) filters[i].eval);
+            filters[i].eval = NULL;
+        }
     return 0;
 }
 
 
```

**Comment by andmarti1424** [comment]
Thank you @1dancook. Will check it out.

**Comment by andmarti1424** [comment]
That is why I could not reproduce the bug. I used `:delfilter 0`.
Please update to latest commit on dev branch and retry.
I have also made a modification so that when you delete the filters, sc-im shows again the previous hidden rows.

**Comment by 1dancook** [comment]
@andmarti1424
Thank you!

I am not able to produce a segfault the way I stated above.

I'm still able to produce a segfault with the following. I didn't think to try this before but wanted to test a variety of filters etc. 

```
:addfilter "#A=1"
:addfilter "#B=3"
:filteron "A0:B2"
:delfilters
:addfilter "#A=1"
:addfilter "#B=3"
:filteron "A0:B2" --> segfault      
  # (can also produce segfault at this step using :showfilters)
```


---

RE: Showing previously hidden rows after deleting filters

I have tried this modification of showing previously hidden rows when a filter is deleted. There is maybe one other change needed. 

You added a call to `disable_filters()` inside `free_filters()`.
I'm trying to think about if there needs to be a call of `disable_filters()` in `del_filter()`. (Or a singular `disable_filter()` that takes an id).

I suppose as a user I would expect that a deleted filter won't be applied anymore. It makes sense that way and it's congruent with GUI spreadsheets. This would especially be useful if there were several filters enabled over a range of columns. I'd expect that deleting one of those filters would show the rows it applied to, but leave the other enabled filters as-is. 

Anyway those are my thoughts. I have some other thoughts/questiosn about filters but that will be for another time and better in the discussion section. Thanks for working on these things!

**Comment by andmarti1424** [comment]
@1dancook, found the bug. Please update to latest commit on dev branch and retry. Should not break any longer.

**Comment by 1dancook** [comment]
I have tested this and have not been able to produce a segfault. Thank you!
