### ISSUE TITLE
Feature request: Use system locale for number formats or make thousands and decimal separators configurable

### ISSUE THREAD

**Issue by Eucyon** [andmarti1424/sc-im#640]
In some languages thousands and decimal separators are different from the English ones, e.g.:

English: 123,456.789 ~ German: 123.456,789.

Could you please enable this in sc-im, maybe via using locales or configuration?

Thank you!

**Comment by andmarti1424** [comment]
Do you know if its supported on sc?
Move to discussion so others can give their opinion on this matter.
