### ISSUE TITLE
Segfault while sorting selected range with formulas outside range

### ISSUE THREAD

**Issue by tralce** [andmarti1424/sc-im#645]
I have a file. Simply a table with some data. A couple sums and a percentage. 

When I use `v` to select the range `A1:D89`, and then `:sort "+$A"`, sc-im crashes with a segmentation fault.

If I delete the formulas, then save and exit, and reopen sc-im with the file, and repeat the above, it does not crash.

[maps.txt](https://github.com/andmarti1424/sc-im/files/7777473/maps.txt)

```
tralce@gman ~ ξ sc-im --version
SC-IM - version 0.8.2
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLSX
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/share/sc-im"
-DLIBDIR="/usr/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

Let me know if you need any other information.

**Comment by andmarti1424** [comment]
I cannot get it to segfault.
Could you please try may be to put those 3 cells with the formulas above or below the table?

**Comment by tralce** [comment]
Sincerest apologies, I completely forgot that I opened this issue. 

Whatever was the cause of it, updating fixed it. I was running the current AUR version of sc-im (0.8.2), but updating to sc-im-git (0.8.3) causes this to not happen.
