### ISSUE TITLE
Broken quoting and unquoting for delimiter-separated value files

### ISSUE THREAD

**Issue by pjvm742** [andmarti1424/sc-im#646]
If you make a file with the .tsv extension like this:
```
person 1	person 2	person 3
Bakker, Demeter de	Molenaar, Hermes	Korenaar, Persefone
```
... , open it in sc-im and save it, the program will save it as:
```
person 1	person 2	person 3
"Bakker, Demeter de"	"Molenaar, Hermes"	"Korenaar, Persefone"
```
... because sc-im will quote cells not when there is a tab in them, but when there is a comma in them. Basically any delimiter-separated value file is treated as comma-separated.

But it doesn't end there, because if you open *that* file in sc-im and save it again, it produces:
```
person 1	person 2	person 3
"Bakker, Demeter de	Molenaar, Hermes	Korenaar, Persefone"
```
This also happens with other d.s.v. formats *whenever a row contains consecutive quoted fields*, for example this .csv file:
```
person 1,person 2,person 3
"Bakker, Demeter de","Molenaar, Hermes","Korenaar, Persefone"
```
... sc-im will interpret and save as:
```
person 1,person 2,person 3
"Bakker, Demeter de,Molenaar, Hermes,Korenaar, Persefone"
```
The cells get merged into one.

**Comment by climbTheStairs** [comment]
I believe this issue has been resolved, and it can be closed, right?
