### ISSUE TITLE
On some debian/ubuntu systems, pkg-config can't find linker flag

### ISSUE THREAD

**Issue by ItzSwirlz** [andmarti1424/sc-im#650]
I'm packaging this for Debian (https://salsa.debian.org/math-team/sc-im) and the build failed on other machines but not my mains. Researching and installing all libncurses* packages found out that the issue was in the Makefile, where uncommenting the if statement on the 'else' for NetBSD and the -I/usr/pkg/include flags solved the issue.

I'm not going to open a PR as I don't know how you guys manage your builds but for now a distro-specific patch will be made :)

This also occurs with lua and other packages.

**Comment by andmarti1424** [comment]
Thanks will try to check it out.

**Comment by andmarti1424** [comment]
Hello. Whats your `uname -s` in your Debian system? Cause this line should not matter to your system: `else ifeq ($(shell uname -s),NetBSD)` Thanks.

**Comment by andmarti1424** [comment]
Hello Debian folks. You still have problems when building sc-im manually? Please report. Thanks.

**Comment by ItzSwirlz** [comment]
Hi, I'm sorry. I just saw the response, I've been busy. We actually patched the makefile to work with us and now sc-Im is in Debian but we mostly got rid of the if statements and cut it out to work with us

uname should just be like 'Debian'
