### ISSUE TITLE
[Function request] paste or export only the visible (shown) cells, excluding the hidden cells in between

### ISSUE THREAD

**Issue by amalgame21** [andmarti1424/sc-im#653]
I cannot find a way to copy and paste, or export only the cells that is visible.
if I hide all the rows with the command :hiderows , like :hiderow 1:10
and only shows some of the rows with :showrows, like :showrow 3 , :showrow 5, :showrow 7
when I copy and paste the shown(visible) rows (3,5,7)
the hiddenrows in between (4,6) are also being pasted.

This problem also happens when I use the :e csv command to export the selected cells in visual mode
hiddenrows in between are also being exported.

Thanks!

**Comment by andmarti1424** [comment]
This should be addressed with latest changes on dev branch.
See ignore_hidden configuration variable on doc.
