### ISSUE TITLE
Typo on the Readme

### ISSUE THREAD

**Issue by freddieventura** [andmarti1424/sc-im#656]
So In the Readme you have

gtab12 | go to cell AB12

When it should be 

goab12 | go to cell AB12

Thank you for the tool

**Comment by amalgame21** [comment]
seems the keymapping changed from "go" to "gt" for goto command.

or you can press "/ab12" and hit enter to goto AB12 cell

**Comment by andmarti1424** [comment]
Thank you both! Fixed.
