### ISSUE TITLE
Compilation fails when installing with libxlsxwriter

### ISSUE THREAD

**Issue by freddieventura** [andmarti1424/sc-im#659]
Hi there,

So I wanted to use your export feature with `libxlsxwriter` , and I installed the library according to their  [tutorial](https://libxlsxwriter.github.io/getting_started.html) , and I even tested it and it is working great. But I cannot compile your program with it.

What I have to do is to uninstall this library to re-compile your program. But it is a pitty to be honest.

```
$ sudo make -C src 
(....)
cc -Wall -g -DNCURSES -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DSNAME=\"sc-im\" -DHELP_PATH=\"/usr/local/share/sc-im\" -DLIBDIR=\"/usr/local/share/doc/sc-im\" -DDFLT_PAGER=\"less\" -DDFLT_EDITOR=\"vim\" -DUSECOLORS -DHISTORY_FILE=\"sc-iminfo\" -DHISTORY_DIR=\".cache\" -DCONFIG_FILE=\"scimrc\" -DCONFIG_DIR=\".config/sc-im\" -DINS_HISTORY_FILE=\"sc-iminfo\" -DUNDO -DMAXROWS=65536 -DUSELOCALE -DMOUSE -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\" -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\" -DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD=\""scopen"\" -DAUTOBACKUP -DHAVE_PTHREAD -DGNUPLOT -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DXLSX_EXPORT -I/usr/local/include   -c -o formats/xlsx.o formats/xlsx.c
formats/xlsx.c: In function ‘export_xlsx’:
formats/xlsx.c:569:28: error: ‘session’ undeclared (first use in this function)
     struct roman * roman = session->cur_doc;
                            ^~~~~~~
formats/xlsx.c:569:28: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: formats/xlsx.o] Error 1
make: Leaving directory '/home/fakuve/dotfiles/fakuve/programs/sc-im/src'

```
Am I doing something wrong?

Thank you

**Comment by andmarti1424** [comment]
I really dont know. session is declared on line 73 of xlsx.c

73 extern struct session * session;
don't know why you get: "error: ‘session’ undeclared"

**Comment by freddieventura** [comment]
Are you able to use `libxlsxwriter` yourself in your `sc-im` instance then?

**Comment by andmarti1424** [comment]
Yes, I have it working. I use Arch.

**Comment by freddieventura** [comment]
I'm using `Debian Buster` myself

**Comment by freddieventura** [comment]
First of all , I don't understand what the guy is trying there (he could be putting the code he modified) , there is no else statement commented (so what am I gonna uncomment)

Neither my error has to do with `lbncurses` it is with `libxlsxwriter`

**Comment by freddieventura** [comment]
I have tried using his fork but it doesn't work either

**Comment by andmarti1424** [comment]
Yes, does not matter the latter. Could be the same problem.
Make sure compilation happens to issue this:
-I/usr/pkg/include  or the path where u have the library headers.

**Comment by freddieventura** [comment]
Ok thank you very much , it is working . With his fork [sc-im for Debian](https://salsa.debian.org/math-team/sc-im)

**Comment by andmarti1424** [comment]
Could you please try with this repo as before but changing the Makefile to his:
`https://salsa.debian.org/math-team/sc-im/-/blob/master/debian/patches/adjust-makefile-for-packaging.patch`

**Comment by freddieventura** [comment]
It doesn't work the patch

```
$ patch Makefile adjust-makefile-for-packaging.patch
patching file Makefile
Hunk #2 FAILED at 58.
Hunk #5 succeeded at 121 with fuzz 2.
1 out of 5 hunks FAILED -- saving rejects to file Makefile.rej


$ cat Makefile.rej
Index: Makefile
--- Makefile
+++ Makefile
@@ -58,16 +58,16 @@ CFLAGS += -DMOUSE
 # Choose one of the following commands for copying to different clipboards:
 # You can later change it at runtime.
 #to copy to tmux clipboard:
-CFLAGS += -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""tmux load-buffer"\"
+#CFLAGS += -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""tmux load-buffer"\"
 #to copy to X clipboard:
-#CFLAGS += -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\"
+CFLAGS += -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\"
 #to copy to OSX clipboard:
 #CFLAGS += -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""pbcopy <"\"
 #
 # Choose one of the proposed commands for pasting from different clipboards:
 # You can later change it at runtime.
-CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""tmux show-buffer"\"
-#CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\"
+#CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""tmux show-buffer"\"
+CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\"
 #CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""pbpaste"\"

 # Command to open file or link under cursor

```

**Comment by freddieventura** [comment]
If despite that I go ahead and try to compile this new **hybrid** I get

```
cc -Wall -g -DNCURSES -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DSNAME=\"sc-im\" -DHELP_PATH=\"/usr/share/sc-im\" -DLIBDIR=\"/usr/share/doc/sc-im\" -DDFLT_PAGER=\"less\" -DDFLT_EDITOR=\"vim\" -DUSECOLORS -DHISTORY_FILE=\"sc-iminfo\" -DHISTORY_DIR=\".cache\" -DCONFIG_FILE=\"scimrc\" -DCONFIG_DIR=\".config/sc-im\" -DINS_HISTORY_FILE=\"sc-iminfo\" -DUNDO -DMAXROWS=65536 -DUSELOCALE -DMOUSE -DDEFAULT_COPY_TO_CLIPBOARD_CMD=\""xclip -i -selection clipboard <"\" -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\" -DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD=\""scopen"\" -DAUTOBACKUP -DHAVE_PTHREAD -DXLUA -I/usr/include/lua5.4 -DODS -DXLSX -I/usr/include/libxml2   -c -o clipboard.o clipboard.c
In file included from clipboard.c:53:
tui.h:48:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: clipboard.o] Error 1


```

**Comment by andmarti1424** [comment]
-I/usr/include/lua5.4 is probably not correct..

**Comment by freddieventura** [comment]
Yeah I made it compile changing it to lua5.2 , but unfortunately it doesn't get `:e xlsx` support

**Comment by andmarti1424** [comment]
mmm i cant recall. may be it was with `:w name.xlsx`

**Comment by andmarti1424** [comment]
actually u could try both this `:e xlsx name.xlsx` or the above

**Comment by andmarti1424** [comment]
Could you manage to export it as xlsx btw?

**Comment by freddieventura** [comment]
I would need to use the Debian Salsa fork for that , and thatone is quite an old version , so it is a bit unfeasible for me at this time to use `sc-im`. Good Project I wish you luck carrying on with it , but at the moment I cannot adapt my workflow to it.
Thank you!

**Comment by jbrubake** [comment]
I am having the same issue on Fedora. I was able to successfully build using the following fix. I'm not positive it isn't buggy as my C is a bit rusty. And the fix makes about as much sense to me as the compilation error in the first place. There is an identical assignment of `session->cur_doc` on line 192 and that doesn't throw an error

Add the following line just prior to line 569 (where the error is):

`struct session * session = session;`

**Comment by andmarti1424** [comment]
@jbrubake  `...don't know why you would need to put the extern here when it is already at the top of the file.` me neither.
I close this.
