### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by reckbo** [andmarti1424/sc-im#66]
Some examples of rendering issues I have:

* when I first load scim, a line of the previous terminal screen is displayed (on line 36)
* when I hit 'j', half the column numbers disappear. To get them back I have to scroll down
to those cells.
* Navigating through a large csv will leave some previous values rendered, and also show some
garbage values like '7;156H1949'

I use iTerm on Mac, OS X 10.9.5.

**Comment by andmarti1424** [comment]
Hello. Does this happen to you with v0. 2.2?

**Comment by andmarti1424** [comment]
I also believe that some of these could be caused because of trying to print special characters (non 7 bit ascii) and building SC-IM with ncurses and NOT ncursesw library.

Another thing is that I do not own a Mac, so its very hard for me to support it...

**Comment by andmarti1424** [comment]
Hello reckbo. Could you please give me more details of the version you are using?
Did you build SC-IM against ncursesw library?

**Comment by reckbo** [comment]
I was building against ncurses instead of ncursesw.  I installed the latter and rebuilt, and now I don't get any of the rendering issues I listed.  Thanks!

**Comment by andmarti1424** [comment]
I am adding UTF8 support to SC-IM,  but that needs ncursesw. Is this
available in OSX?

**Comment by reckbo** [comment]
I installed ncurses via homebrew which includes ncursesw.  It's easy to do:

    brew install ncurses
    brew link ncurses
