### ISSUE TITLE
Visual-Mode not working the Vim way

### ISSUE THREAD

**Issue by freddieventura** [andmarti1424/sc-im#664]
Hi there ,

So I am trying to select a range of fields for what I go to `Visual Mode` and then once on there I'm trying to select a big range of fields so I try by moving from that initial field downwards with `400j` and it is not working (it looks to be working with lower numbers such as `50j` or even 3 digits `100j` but most of 3 digits ones are not working)

Neither using `pageDown` will work on this mode  and `#           Move down to the last valid row of the current column.` is not working.

Thanks

**Comment by andmarti1424** [comment]
Please try redefining macro
#define MAX_MULTIPLIER   100
in macros.h and rebuilding sc-im

**Comment by freddieventura** [comment]
I don't understand what you mean by `redefining` ? you mean define it at the end of the same file? because I already have that line

**Comment by andmarti1424** [comment]
change that 100 number to the one that you'd like to use as multiplier

**Comment by freddieventura** [comment]
Ok thanks, I don't understand why is so low the number , it should be like in `vim` Thank you

**Comment by andmarti1424** [comment]
Whats that number in vim then?
Ur the first one to complain about that being low in 8 years or so.

**Comment by andmarti1424** [comment]
> If you claim your program to behave like `vim` it should behave like `vim` I guess . Otherwise don't put that on the description

i dont claim it to behave like vim. It has some common things to vim but there are other things that just are not. besides they 2 different animals.

**Comment by freddieventura** [comment]
`vim-like spreadsheet calculator.` :smile:

**Comment by andmarti1424** [comment]
that means it has common things with that text editor.. shortcuts, some modes, etc..
but a value of configuration of a multiplier seems to not be one of those.
