### ISSUE TITLE
\" B1 \" B1 \" B1 In different columns (mirroring that field string) buggy

### ISSUE THREAD

**Issue by freddieventura** [andmarti1424/sc-im#667]
Is difficult to explain thisone I attach the document I'm working with

https://drive.google.com/file/d/1zTYkhiO94VnfQ0rTuiG9GfNNkKTCVIlr/view?usp=sharing

If you check the second Column , B3 , B4 , B5 and B6 are defined as ` \" B1`  . The problem is that when opening the file , this fields show up to be blank . It seems that performing any operation in the spreadsheet will refresh this such as doing a `dd` in an empty field.

That doesn't happen with a simple calculation such as in `E4`

**Comment by andmarti1424** [comment]
This is a bug i believe.

**Comment by andmarti1424** [comment]
I cannot seem to download the file. This might have been fixed with latest commits, however I cannot test it.
