### ISSUE TITLE
sc.lsetnum can't add number to the cell it was called from?

### ISSUE THREAD

**Issue by 097115** [andmarti1424/sc-im#669]
Let's say, we have the following `test.lua` script:

    z = 1
    sc.lsetnum(sc.curcol(), sc.currow(), z)
    sc.lsetnum(sc.curcol(), sc.currow() + 1, z)

Next, if we select A0 cell and call the script like this: `=@ston(@lua("test.lua", 0))`, then the expected result should be 1.00 in A0 and 1.00 in A1, is this correct?

However, the observed result is 0.00 in A0 (the exit status? the returned result gets overwritten by it?) and -- correctly -- 1.00 in A1:

![](https://i.imgur.com/KWzfuZO.png)

(And if set A2 to `=@sum(A0:A1)`, then the result will be 1.)

Now, if we change the script like this:

    z = 1
    sc.lsetstr(sc.curcol(), sc.currow(), z)

it will indeed add 1 as a string to the selected cell:

![](https://i.imgur.com/AKzj2cZ.png)

Which means `sc.lsetstr` works correctly but `sc.lsetsum` somehow doesn't? Is this a [known] bug, or am I missing something? :)

The help page says this:

    sc.lsetnum (c, r, val)  - set numeric value to a cell c,t

and I assume that `t` at the end of the line is just a typo, am I wrong? :)

`sc-im - version 0.8.3-main`, the latest master.

**Comment by 1dancook** [comment]
I was also wondering if this is a bug but perhaps there is something I haven't thought about yet that it's necessary to be this way.

I now wonder if the same behavior is there if trying to set the cell value with sc.sc() but don't have time to try this now.

**Comment by andmarti1424** [comment]
> ut `sc.lsetsum`

yes. seems 't' is a typo there.
Could please type '@' to recalculate with the first script and see if the behaviour is the same? Thanks.

**Comment by 097115** [comment]
> Could please type '@' to recalculate with the first script and see if the behaviour is the same? Thanks.

You mean after...

> Let's say, we have the following test.lua script:
> 
>      z = 1
>      sc.lsetnum(sc.curcol(), sc.currow(), z)
>      sc.lsetnum(sc.curcol(), sc.currow() + 1, z)
> Next, if we select A0 cell and call the script like this: `=@ston(@lua("test.lua", 0))`, then the expected result should be 1.00 in A0 and 1.00 in A1, is this correct?
> 
> However, the observed result is 0.00 in A0 (the exit status? the returned result gets overwritten by it?) and -- correctly -- 1.00 in A1.

...press `@` to recalculate? It doesn't change anything :)

**Comment by andmarti1424** [comment]
@097115, please call the lua script like this:
`\"@lua("test.lua", 0)`
as the doc suggests.

**Comment by 097115** [comment]
Yep. You are absolutely right. Sorry for my mistake with that `@ston`, missed forrest for the trees :) (i.e., if we want `@lua` to return a number, we shouldn't convert the returned string to number but instead just code `@lua` script **to actually return a number**, thanks to `sc.lsetnum`.)

There's one caveat, though: what if I want to map a call to this `@lua` script, what the notation would be, what about escaping? This:

    nnoremap ",t" "\\\"@lua("\test.lua",0)

i.e. opening quote, escaping backslash, actual backslash, escaping backslash, quote, and so on -- this end with a syntax error...

**Comment by 097115** [comment]
@andmarti1424 

It works! Thanks again :)
