### ISSUE TITLE
Can't remap horizontal scrolling

### ISSUE THREAD

**Issue by BioBox** [andmarti1424/sc-im#670]
I use the Colmak keyboard layout and would like to remap "zh" to "zk" and such:
```
nmap "k" "<left>"
nmap "i" "<right>"
nmap "n" "<down>"
nmap "e" "<up>"

vmap "k" "<left>"
vmap "i" "<right>"
vmap "n" "<down>"
vmap "e" "<up>"

nmap "zk" "zh"
nmap "zi" "zl"
nmap "zK" "zH"
nmap "zI" "zL"
```
The maps involving capitals work fine, but the lowercase "zk" and "zi" do nothing. Changing the first two paragraphs to their "noremap" equivalents doesn't work either.

**Comment by andmarti1424** [comment]
Actually, this works for me. Anyone else could please try this?

**Comment by 1dancook** [comment]
I tried the zi and zk mappings and that works fine on my end.

**Comment by BioBox** [comment]
I think I've found what's causing it.

For starters, running `git log v0.8.2..` on a clone of the repo yields **a lot** of commits, so I installed sc-im-git to get the latest commit. When I delete the first two paragraphs in the example I showed it works, but remapping the movement keys will break the "zi" and "zk" mappings, **even when using nnoremap**.

**Comment by andmarti1424** [comment]
The other thing to try is to change the 
`
nmap "zk" "zh"
nmap "zi" "zl"
nmap "zK" "zH"
nmap "zI" "zL"
`
to the noremap equivalent.

**Comment by BioBox** [comment]
Putting those two maps at the beginning fixed it, and I didn't have to use any `noremap`s. Thank you!
