### ISSUE TITLE
Can't remap number with direction keys

### ISSUE THREAD

**Issue by amalgame21** [andmarti1424/sc-im#671]
Just some minor issue

I used to remap J and K with 10j and 10k in vim like this 
```
nnoremap J 10j
vnoremap J 10j
nnoremap K 10k
vnoremap K 10k
```

seems it is not working for sc-im
it would be great if it works.

**Comment by 097115** [comment]
Well, for this particular case you can just `nnoremap "J" "jjjjjjjjjj"` :) (which will also have a bonus by moving 20 rows down if you press `2J` :)

**Comment by amalgame21** [comment]
Thank you!!!!!!!!!!!!!!!

**Comment by andmarti1424** [comment]
This is in the doc.
`
Some notes:
The Left and Right sequence of a mapping cannot contain numbers.
`
