### ISSUE TITLE
Cannot extract only visible column and rows with some filter rules.

### ISSUE THREAD

**Issue by amalgame21** [andmarti1424/sc-im#674]
Issue explained in detail in #673 
This also related to #653. 

Refer to #673 
If the filter applied ( in user 097115 case, `:addfilter "#A<25"`)
1-25 row is visible, which is consecutive.
Then the `:e mkd` and `:e csv` output work as expected.
No problem in this case.

But if the filter applied is not in sequence (in my case, `:addfilter "@eqs(@substr($B,1,1),'B')"`)
5, 13, 14, 15, 17, 59 rows is visible, which is NOT consecutive
Then the `:e mkd` and `:e csv` output does not work at all
The output content remain the same as the original file.

If visible mode is used to select 5, 13, 14, 15, 17, 59 rows, and then copy and paste
5-59 row will be pasted.

**Comment by andmarti1424** [comment]
Let me see if I understand the problem. When you apply filters and end up with visible rows that are not consecutive. they are not exported properly.
but when the rows are consecutive, they are? is this the case?

**Comment by amalgame21** [comment]
yes exactly!!
not only not exported properly, it cannot be copy and paste properly in visual mode too!

**Comment by andmarti1424** [comment]
First thing to discuss in here is:
when you have hidden rows or cols if those should be exported or not to a csv.. Currently, I believe those are exported, and that is why when u apply filters (applying a filter it just hides a row), the rows get exported.

**Comment by andmarti1424** [comment]
Yeah. We need to find a proper solution to this.
This:
```
But in the case of :addfilter "#A<25" in the same test.csv, those hidden rows are not exported.
```
seems a bug.

**Comment by amalgame21** [comment]
I would like to help but I do not have any knowledge in programming...sorry

**Comment by andmarti1424** [comment]
Actually i would do the commits to the dev branch and i need ur testing only.. could you help in that?

**Comment by andmarti1424** [comment]
This should be addressed with latest changes on dev branch.
See ignore_hidden configuration variable on doc.

**Comment by 097115** [comment]
From my limited testing, it looks really good (and introducing an option is nice, too, can be toggled on the fly if needed).

Thank you, Andrés!
