### ISSUE TITLE
sc.lsetform coordinates swapped?

### ISSUE THREAD

**Issue by 097115** [andmarti1424/sc-im#678]
According to the manual:

        sc.lsetform (c, r, str) - set formula to a cell. Basically it does "let
                                  cell= str"

However, it seems that `sc.lsetform(0, 4, "A0/B0")` sets **E0** instead of **A4** (i.e., `c` and `r` parameters in the function call are swapped :)

**Comment by andmarti1424** [comment]
@097115 you are correct! please update to latest commit on dev branch. should be fixed.

**Comment by 097115** [comment]
Thanks, @andmarti1424, it works!

On a side note, I also noticed the following: let's say we have this test.lua `$XDG_CONFIG_HOME/sc-im/lua`:

    sc.lsetform(4, 0, "A0/B0")

And then we launch `sc-im`, set A0 to 100, B0 to 25 (or we may skip this, it really doesn't matter), and then on C0 we call our `test.lua` script: `\"@lua("test.lua",0)` (or `=@ston(@lua("test.lua",0))`). Then, the formula will appear in E0, and everything will look fine. However, if we choose to quit with, let's say, `:q!`, the segfault will happen (and if we first `:w test.sc`, and then `:q`, the data will be saved, but the segfault will still happen).

Can't actually say if it's indeed related to calling `sc.lsetform()` (and unfortunately I know nothing about debugging and such), but this is 100% reproducible for me on completely different OSes.

**Comment by andmarti1424** [comment]
Please open another issue, since that does not seem to have nothing to do with this one.
