### ISSUE TITLE
Header fields get stacked in large CSV

### ISSUE THREAD

**Issue by reckbo** [andmarti1424/sc-im#68]
I have a csv with 259 columns, and when I load it in scim the header fields are stacked into a layer of 6 rows, and the column values are interleaved.  Let me know if you want me to attach a screenshot.
Ryan

**Comment by andmarti1424** [comment]
Please attach a screenshot.  Which version of SC-IM are you using?

**Comment by andmarti1424** [comment]
If I understand the problem correctly, I might have found the problem...
Give me some hours to fix it..

**Comment by andmarti1424** [comment]
I made a change and upload a fix to the "widechar" branch.
(This will be the default branch in near time..).
Please upload latest commit, test again and report back!
Thanks!

**Comment by reckbo** [comment]
It's much better, the headers aren't stacked and the column values aren't interleaved.  But there is
an extra blank row between headers and column values.

**Comment by andmarti1424** [comment]
Could you please attach a screenshot??
Thanks!

**Comment by reckbo** [comment]
![scim-screenshot](https://cloud.githubusercontent.com/assets/274797/14513724/16296fda-022d-11e6-849c-f6f84ac52ff5.png)

**Comment by andmarti1424** [comment]
Its weird since SC-IM does not know if a row is a header or value..
Dont you have an extra '\n' char after first line? Please send the file to scim.spreadsheet@gmail.com
Thanks again.

**Comment by andmarti1424** [comment]
I believe its related to the new line character or carriage return.
Its not harmful though.
I opened it with gnumeric and get an extra row after every line!!

**Comment by reckbo** [comment]
FYI I see each line is terminated by a linefeed, no carriage return.  You're right it's not harmful, but I wonder why scim treats the first line differently from the others.

**Comment by andmarti1424** [comment]
I think I found the problem. Please update to latest commit in widechar branch!

**Comment by reckbo** [comment]
Yup, the problem is fixed.  Thanks!
