### ISSUE TITLE
sc-im colors in tmux

### ISSUE THREAD

**Issue by for-coursera** [andmarti1424/sc-im#682]
When running sc-im in tmux (v.3.4) I noticed that the grid "disappears" – probably its color is displayed as black? Here are two screenshots, the first one is a [normal sc-im](https://i.imgur.com/yiEybdi.png), and the second one is a [tmuxed sc-im](https://i.imgur.com/FCKfld5.png).

Also, if I redefine a color like this, the default blue to [this one](https://www.color-hex.com/color/3d85c6):

    redefine_color "BLUE" 61 133 198

It will still show the default blue.

This happens with the latest dev branch, commit [4494f01](https://github.com/andmarti1424/sc-im/commit/4494f010d191308b3dc4133e77afb4cab14ee6ca).

In .tmux.conf, I set my terminal to tmux-256color-italic, [here is an `infocmp` dump](http://ix.io/3OT8). And true colors in tmux in other applications are displayed just fine.

Any advise may be? :)

**Comment by andmarti1424** [comment]
These tmux issues are not new. Tmux seems to not interpret that terminal code correctly. I'm afraid this has nothing to do with sc-im.

**Comment by for-coursera** [comment]
@andmarti1424 

Thanks. Closing this then?

**Comment by andmarti1424** [comment]
I close it. I suggest you contact tmux devs and tell them that the ncurses underline is not working properly on your terminal.

**Comment by fourjay** [comment]
FWIW....
If I run TERM=xterm-256color sc-im inside of tmux, REDEFINED colors work fine.
