### ISSUE TITLE
Feature: add ability to invert default foreground and background

### ISSUE THREAD

**Issue by reportaman** [andmarti1424/sc-im#683]
For base-16 color schemes, it would be very beneficial to have the ability to invert DEFAULT_COLOR for background and foreground. Perhaps, the color names should be DEFAULT_FG, and DEFAULT_BG. That way those colors can be passed to bg and fg respectively to get the desired inverted foreground-background effect.

Thanks :)

**Comment by andmarti1424** [comment]
I dont think i understand you. DEFAULT_COLOR its just a way to say "not change the color". See tui.h where they are defined.

**Comment by reportaman** [comment]
@andmarti1424 Found it!!! There is an attribute ``reverse`` that sets ``A_REVERSE`` of ncurses. It works in sc-im.

**Comment by andmarti1424** [comment]
I didnt know what u mean. Yes. That works.
