### ISSUE TITLE
Multi-Sheet Functionality Gone After Switching To Latest Stable Release

### ISSUE THREAD

**Issue by krossgear** [andmarti1424/sc-im#684]
Upgraded my system a couple weeks ago and had to reinstall from scratch. Don't know what version I was using before, but I chose v0.8.2 this time and now the ability to create, let alone navigate between, multiple sheets is gone. Even the corresponding keybindings in :help are gone. Also all my existing sc files (which all used multiple sheets) appear to be corrupted and load with a syntax error.

Running on Debian 11 (QubesOS AppVM).

**Comment by andmarti1424** [comment]
Multisheet is available since version 0.8.3.
You cannot load files that has multisheet with 0.8.2 version.

**Comment by krossgear** [comment]
I figured I made an installation mistake somewhere. Latest commit fixed it.
