### ISSUE TITLE
Mouse select broken (macOS)

### ISSUE THREAD

**Issue by dylanmc** [andmarti1424/sc-im#687]
Mouse select / copy&paste work fine normally, but in sc-im, when I try to select text, I get a message in the status line `Cannot handle mouse scroll. Please update your ncurses library`

According to `brew info` I'm running `ncurses: stable 6.3 (bottled) [keg-only]`, which is indeed the latest stable release. Puzzling.

(macOS, multiple versions, reproduced in Terminal.app and Alacritty)

**Comment by andmarti1424** [comment]
You cannot use mouse to select text under sc-im. Mouse its used for selecting a cell or scrolling the spreadsheet.

**Comment by dylanmc** [comment]
Well that explains it! Is there a way to get a cell's contents into the system clipboard?

**Comment by andmarti1424** [comment]
Yes, with ccopy command. It's explained on the doc.

**Comment by dylanmc** [comment]
Aha - I stopped using the `homebrew` version of sc-im a while back when the screen flashing thing happened, but I didn't properly configure that part of the `Makefile` in my build. Thanks for the pointer!

**Comment by idr4n** [comment]
@dylanmc I just installed manually in macOS and the screen is flashing. I was using brew's version before and was working fine but I need v0.8.3 for multiple-sheet support. Do you have any idea how to solve the screen flashing issue? Thanks in advance!
