### ISSUE TITLE
I need the sc-im in termux.

### ISSUE THREAD

**Issue by buribu** [andmarti1424/sc-im#69]
Termux is a terminal environment like debian. Where you can install software via apt in android.

https://github.com/termux/

https://github.com/termux/termux-packages/issues/246

**Comment by andmarti1424** [comment]
Your minimum requirements are bison ncursesw and gcc.  Did you try building it?

**Comment by buribu** [comment]
/data/data/com.termux/files/usr/include/ncursesw   /data/data/com.termux/files/usr/bin/bison          /data/data/com.termux/files/usr/bin/gcc
minimal ok

run make

-DLINUX    -O2 -Wall -pipe -g -I/usr/include/libxml
2 -DUSECOLORS -DUSELOCALE -DUNDO -DSIGVOID -DDFLT_PAGER=\"less\"   -DREGCOMP -DLIBDIR=\"/usr/share/doc
/scim\" -DMAXROWS=65536 -DHELP_PATH=\"/usr/share/scim\" -DSNAME=\"scim\"     -DHISTORY_FILE=\".sciminf
o\"   -c -o cmds_visual.o cmds_visual.c            cmds_visual.c: In function 'do_visualmode':
cmds_visual.c:331:34: fatal error: langinfo.h: No s
uch file or directory
             #include <langinfo.h>
                                               ^
                                               compilation terminated.
                                               <builtin>: recipe for target 'cmds_visual.o' failed
*** [cmds_visual.o] Error 1
:'( cry forever

**Comment by andmarti1424** [comment]
This is a problem with locales.. Its not finding the langinfo header file.

**Comment by buribu** [comment]
hi                                                 langinfo.h in the package libandroid-support                                                          symlink langinfo.h file to include diretory                                                           this a new error message:                                                                                                                                gcc  cmds_edit.o gram.o history.o marks.o lex.o color.o input.o cmds_visual.o range.o pipe.o xmalloc.o buffer.o maps.o filter.o sort.o undo.o interp.o hide_show.o help.o file.o cmds.o yank.o vmtbl.o cmds_insert.o block.o conf.o screen.o cmds_normal.o xlsx.o main.o shift.o cmds_command.o format.o exec.o xls.o utils/extra.o utils/dictionary.o utils/string.o -o scim -lm -lncursesw                            cmds_visual.o: In function `do_visualmode':        /data/data/com.termux/files/home/sc-im-dev/src/cmds_visual.c:336: undefined reference to `nl_langinfo'cmds_normal.o: In function `do_normalmode':        /data/data/com.termux/files/home/sc-im-dev/src/cmds
_normal.c:147: undefined reference to `nl_langinfo'
collect2: error: ld returned 1 exit status         Makefile:172: recipe for target 'scim' failed
make: *** [scim] Error 1

**Comment by buribu** [comment]
Hi André
Now it's working. FornWall helped me. see the link. sc-im is a mobile application now. 




[https://github.com/termux/termux-packages/issues/246](url)

**Comment by andmarti1424** [comment]
I am glad to here!
