### ISSUE TITLE
Spreadsheet Won't Open, Throws Color Error Instead

### ISSUE THREAD

**Issue by krossgear** [andmarti1424/sc-im#691]
Was messing around with the colorscheme today and now my spreadsheet refuses to open. It throws an error saying-

"One of the values specified is wrong: GREY. Please check the values of type, fg, and bg."

The only thing I changed were were the RBG values for GREY. The syntax looked right, so I replaced all references to GREY in the colorscheme with standard colors and commented the GREY definition out. I still get the same error message.

This did NOT happen if I opened a new spreadsheet. 

I removed the GREY definition line from my scimrc entirely and still get the same error message, only this time opening a new spreadsheet throws a "syntax error" message, but otherwise works fine.

scimrc below:
```
set half_page_scroll=1

####################################################
##########          KEYBINDINGS          ###########
####################################################
#
# The following remappings are designed to mimic the physical positions of the standard "hjkl">
# Combos should be remapped before single characters
#
###########################################
########        NORMAL MODE        ########
###########################################
#
# Open a row: insert after the current row
nnoremap "Ir" "or"
# Open a column: insert after the current column
nnoremap "Ic" "oc"
# Shifts current cell/range up
nnoremap "se" "sk" 
# Shifts current cell/range down
nnoremap "sn" "sj"
# Shifts current cell/range left
nnoremap "sy" "sh"
# Shifts current cell/range right
nnoremap "so" "sl"
# Yank the selected cell
nnoremap "Yy" "yy"
# Yank current row
nnoremap "Yr" "yr"
# Yank current column
nnoremap "Yc" "yc"
# Move cursor left; same as <LEFT>
nnoremap "y" "h"
# Move cursor left; same as <DOWN>
nnoremap "n" "j"
# Move cursor left; same as <UP>
nnoremap "e" "k"
# Move cursor left; same as <RIGHT>
nnoremap "o" "l"
# Move to next search match
nnoremap "s" "n"
# Move to previous search match
nnoremap "S" "N"
# In normal mode, enter Edit mode to edit a numeric value
nnoremap "k" "e"
# In normal mode, enter Edit mode to edit a text value
nnoremap "K" "E"
# 
###########################################
########        VISUAL MODE        ########
###########################################
#
# Move cursor left; same as <LEFT>
vnoremap "y" "h"
# Move cursor left; same as <DOWN>
vnoremap "n" "j"
# Move cursor left; same as <UP>
vnoremap "e" "k"
# Move cursor left; same as <RIGHT>
vnoremap "o" "l"
# Yak the selected cell or ranger and exit Visual Mode
ovnoremap "Y" "y"
#
####################################################
##########          COLORSCHEME          ###########
####################################################
#
# Redefines sc-im default colors (RGB?)
REDEFINE_COLOR "WHITE" 243 244 245
REDEFINE_COLOR "BLACK" 28 32 35
REDEFINE_COLOR "RED" 199 149 174
REDEFINE_COLOR "GREEN" 174 199 149
REDEFINE_COLOR "YELLOW" 199 174 149
REDEFINE_COLOR "BLUE" 149 174 199
REDEFINE_COLOR "CYAN" 149 199 174
REDEFINE_COLOR "MAGENTA" 174 149 199
# Formatting assignments
color "type=DEFAULT fg=WHITE bg=BLACK bold=0 italic=0"
color "type=NORMAL fg=WHITE bg=BLACK bold=0 italic=0"
color "type=WELCOME fg=CYAN bg=BLACK bold=0"
color "type=MODE fg=WHITE bg=BLACK bold=0"
color "type=CELL_ID fg=CYAN bg=BLACK bold=0"
color "type=CELL_FORMAT fg=BLUE bg=BLACK bold=0"
color "type=CELL_CONTENT fg=GREEN bg=BLACK bold=0"
color "type=INFO_MSG fg=RED bg=BLACK bold=0"
color "type=ERROR_MSG fg=RED bg=BLACK bold=0"
color "type=INPUT fg=GREEN bg=BLACK"
color "type=HEADINGS fg=CYAN bg=BLACK bold=0"
color "type=HEADINGS_ODD fg=BLUE bg=BLACK bold=0"
color "type=CELL_SELECTION fg=BLACK bg=WHITE bold=1"
color "type=CELL_SELECTION_SC fg=BLACK bg=WHITE bold=1"
color "type=CELL_ERROR fg=BLACK bg=RED bold=0"
color "type=NUMB fg=MAGENTA bg=BLACK bold=0"
color "type=CELL_NEGATIVE fg=RED bg=BLACK bold=0"
color "type=EXPRESSION fg=MAGENTA bg=BLACK bold=0"
color "type=STRG fg=GREEN bg=BLACK bold=0 italic=1"
color "type=DATEF fg=YELLOW bg=BLACK"
color "type=HELP_HIGHLIGHT fg=BLACK bg=WHITE"
```

**Comment by andmarti1424** [comment]
You have a typo with ovnoremap.
To detect where the error is, I would start from an empty scimrc and start adding lines from your current scimrc.

**Comment by krossgear** [comment]
Update

The syntax error was due to a fault keybinding that somehow creeped in, so that explains that. Tried removing the entire  colorscheme from the scimrc, but I still get that error message. Found out that the file will eventually load, it just takes ~10 seconds.

**Comment by andmarti1424** [comment]
When you say 'fault keybinding', your referring to the typo I just told you?
When you say 'I still get that error', what error is it?

**Comment by krossgear** [comment]
Yes, "faulty keybinding" refers to the typo. I didn't see your response until after I posted.

The error whenever I try to launch my spreadsheet- "One of the values specified is wrong: GREY. Please check the values of type, fg, and bg."

I tried launch it from an empty scimrc, but I still kept getting the same error message. So I eventually decided to just export the data into a new spreadsheet since this was the only file I was having issues with. I put my old scimrc back, slightly modified, and after launching the spreadsheet a few times, I no longer get the error message, but I also can't create new tabs. I also get a info message at startup saying "width too large - maximum = 58", but other than that everything else seems to work okay. I'm going export the data to a new spreadsheet and see if I get the same behaviour.
