### ISSUE TITLE
Mappings break if { or } are present?

### ISSUE THREAD

**Issue by 097115** [andmarti1424/sc-im#700]
Seems that mappings stop after `{` or `}` (if those are present, obviously).

To reproduce:

1. set these test mappings:

        nnoremap "ir" "<HOME>}<RIGHT>"
        nnoremap "il" "<HOME><RIGHT><LEFT>{<RIGHT>"

2. launch `sc-im`
3. enter some string in the first column
4. move cursor away
5. press one of these set mappings
6. observe the cursor not moving after aligning the string in the first column

**Comment by andmarti1424** [comment]
@097115 you are right! this is so strange. will try to figure it out.
thanks for reporting it.

**Comment by andmarti1424** [comment]
found the cause.. line 1138 of cmds.c that contains.. `cmd_multiplier = 0;`
if it will work if you comment that line.

**Comment by 097115** [comment]
@andmarti1424 

Can confirm, this solves it! :)

**Comment by andmarti1424** [comment]
I leave this open until i can commit the fix.
