### ISSUE TITLE
'sk'/'sh' mappings don't work?

### ISSUE THREAD

**Issue by 097115** [andmarti1424/sc-im#704]
Is it just me, or the `sk`/`sh` mappings (shift the current cell or range up / left) don't really work?

For me, they just delete the contents of the cell(-s) in question (`sj`/`sl`, on the other hand, work just fine).

(I'm on the latest dev branch.)

**Comment by andmarti1424** [comment]
Its working fine for me. Anyone has a problem with those commands?
Just in case, check you dont have a mapping with those..

**Comment by 097115** [comment]
> Just in case, check you dont have a mapping with those..

I've even renamed the whole `~/.config/sc-im` folder before testing :). But yes, that was my first thought, too. (BTW, something like Vim's `-u` command line switch, allowing `-u NONE` would be sort of handy, what do you think?)

Anyway, I've built 352e425 from the scratch just in case. And with empty `~/.config/sc-im` run it like this:

        ./sc-im test.sc

Here I immediately press do `:w`, and here are the contents of `test.sc`:

        # This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
        # You almost certainly shouldn't edit it.

        newsheet "Sheet1"
        movetosheet "Sheet1"
        offscr_sc_cols 0
        offscr_sc_rows 0
        nb_frozen_rows 0
        nb_frozen_cols 0
        nb_frozen_screenrows 0
        nb_frozen_screencols 0
        goto A0


Next, I go to B1, press `=`, enter `100`. And then save again:

        # This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
        # You almost certainly shouldn't edit it.

        newsheet "Sheet1"
        movetosheet "Sheet1"
        offscr_sc_cols 0
        offscr_sc_rows 0
        nb_frozen_rows 0
        nb_frozen_cols 0
        nb_frozen_screenrows 0
        nb_frozen_screencols 0
        let B1 = 100
        goto B1

And then, while on B1, I press `sk`, my `100` disappears, and I save the file again:

        # This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
        # You almost certainly shouldn't edit it.

        newsheet "Sheet1"
        movetosheet "Sheet1"
        offscr_sc_cols 0
        offscr_sc_rows 0
        nb_frozen_rows 0
        nb_frozen_cols 0
        nb_frozen_screenrows 0
        nb_frozen_screencols 0
        goto B1

Tried on another machine with the main branch, and it was there, too :)

**Comment by andmarti1424** [comment]
It's shifting it correctly when you issue 'sk'. If you put something in B2 before doing it, you'll notice it

**Comment by 097115** [comment]
Oh, I see.

If we move down or to the right, then a blank cell is inserted because we have the space to move / to shift the current cell. But if we move to up or to the left, where the space is limited by the boundaries of the sheet, we actually delete the current cell because we can't move it anywhere without affecting other cells.

Interesting :) (don't know if this is a well known feature of Excel and others, never used it before  :)

Thanks, closing this.

**Comment by andmarti1424** [comment]
> Oh, I see.
> 
> If we move down or to the right, then a blank cell is inserted because we have a space to move / to shift the current cell. But if we move up or to the left, where the space is limited by the boundaries of the sheet, we actually delete the current cell because we can't move it anywhere without affecting other cells.
> 
> Interesting :) (don't know if this is a well known feature of Excel and others, never used it before :)
> 
> Thanks, closing this.

That is exactly what "shift cells" do in Excel.
