### ISSUE TITLE
File extension should be automatically added when using :w

### ISSUE THREAD

**Issue by fedemp** [andmarti1424/sc-im#71]
I have just learned that if I save a file as `:w myfile`, scim won't recognize it as a valid file. The extension has to be `.sc` for it to work.

**Comment by andmarti1424** [comment]
Hello. Question: What if you open a CSV or XLSX file and try to save it with :w myfile..
Should it keep the extention or save it with .sc extention?

**Comment by andmarti1424** [comment]
What if you open a CSV or XLSX file and try to save it with :w myfile..
Should it keep the extension or save it with .sc extension? Thanks!

**Comment by andmarti1424** [comment]
Done.
