### ISSUE TITLE
Cell type when importing from CSV

### ISSUE THREAD

**Issue by poliquin** [andmarti1424/sc-im#72]
### Actions done

Open a CSV file with `scim`, either from the command line or using the `i csv` command.

### SC-IM behavior

All of the cell contents are imported as labels. There appears to be no inference done on column types:

![scim1](https://cloud.githubusercontent.com/assets/360123/15808221/1109bea6-2b40-11e6-9ead-3bedcf10620d.png)

### Expected behavior

I assumed `scim` would recognize cell contents are numbers; I expected this:

![scim2](https://cloud.githubusercontent.com/assets/360123/15808223/2e1308e0-2b40-11e6-8699-15774b87c641.png)

### Compiler used and options

I am running `scim` on Mac OSX. Compiled with `gcc`:

```make
LINUX :=
MACOSX := -DMACOSX
```

### CSV contents:

```
files/csv/n.csv

1.00,2.00,3.00
4.00,5.00,6.00
7.00,8.00,9.00
```

**Comment by andmarti1424** [comment]
I am aware of this. It was done that way on purpose. Will probably change it in the future, when a proper isnumeric function will be written. Please take note that you still can convert those string ranges to numbers. Please check out the help doc.

**Comment by andmarti1424** [comment]
Please update to latest depgraph branch commit and try again.
