### ISSUE TITLE
date-time formatting

### ISSUE THREAD

**Issue by DanielDowling1** [andmarti1424/sc-im#721]
SC-IM has a number of numeric features that produce date-time values, like "@now". Is there a way to format these numerical results such that they actually appear in a human-readable format?

**Comment by andmarti1424** [comment]
Please take a look at DATES INPUT section in documentation.

**Comment by DanielDowling1** [comment]
Ah, after re-reading it and a bit of experimentation, I found the command I needed was `:format "d%d/%m/%Y %H:%M:%S"`
