### ISSUE TITLE
use HAVE_STRUCT_TM_GMTOFF

### ISSUE THREAD

**Issue by Kreijstal** [andmarti1424/sc-im#726]
Trying to compile in mingw results in 

```conf.c: In function 'store_default_config_values':
conf.c:131:33: error: 'struct tm' has no member named 'tm_gmtoff'
  131 |     sprintf(strgmtoff, "%ld", lt->tm_gmtoff);
      |                                 ^~
make: *** [<builtin>: conf.o] Error 1
make: Leaving directory '/home/u/sc-im/src'
```

[found something similar](https://github.com/fmtlib/fmt/issues/2670)

**Comment by Kreijstal** [comment]
apparently it doesn't work on Mingw but on MSYS since this uses posix, so libraries such as sys/time.h aren't available in just unix

**Comment by andmarti1424** [comment]
I see. Not planning on getting rid of its use though.
