### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [andmarti1424/sc-im#727]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@itzswirlz) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by andmarti1424** [comment]
Hello. Please take a look at the file named BUGS. Thanks!

**Comment by JamieSlome** [comment]
@andmarti1424 - appreciate it 👍 

You can find the report directly here:
https://huntr.dev/bounties/39169aba-22d4-4297-b7bd-5fd1edb95ee0/

It is currently private and only accessible to you, as you are the owner of the project :)
