### ISSUE TITLE
unable to format range or cells using :format command

### ISSUE THREAD

**Issue by jimgregory** [andmarti1424/sc-im#73]
I am unable to format a cell or range of cells different from that of the rest of a column.  

Suppose I have a column that is formatted with no trailing decimals (###), and I want to format either a cell or range of cells in that column to two decimal places (#.00).

If I select the cell or range of cells then enter ':format "#.00"', the format of the selected cells doesn't visibly change.

FWIW, I am using version 0.3.0.

**Comment by andmarti1424** [comment]
Will fix this as soon as I get my computer repaired.

**Comment by andmarti1424** [comment]
Until I can fix it, may be you can get it done with:

:int fmt A0 "###.00"
or
:int fmt A0:A4 "###.00", if you want to get it done over a range..

**Comment by jimgregory** [comment]
Yes, that will work.  Thanks!

**Comment by andmarti1424** [comment]
Please test it again using the :format command! It shoutld be fixed by now.
Thanks!

**Comment by andmarti1424** [comment]
Could you test the fix?
Thanks.
