### ISSUE TITLE
List Fedora COPR installaiton method in Readme

### ISSUE THREAD

**Issue by marcusmueller** [andmarti1424/sc-im#732]
Seeing there's brew /… instructions, maybe add
```shell
sudo dnf copr enable marcusmueller/sc-im 
sudo dnf --refresh install sc-im
```
as installation instructions for current Fedora Linuxes.

**Comment by andmarti1424** [comment]
Hello. Thanks for the details.
These instructions change constantly on each system. So please feel free to add it to a wiki page, along with Debian/Ubuntu/FreeBSD/OpenBSD wiki pages.

**Comment by marcusmueller** [comment]
Thanks! Will do.

**Comment by andmarti1424** [comment]
Thanks to you.
