### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by bitigchi** [andmarti1424/sc-im#735]
It would be great to be able to translate sc-im to different languages.

I am planning to have a take at this in a couple of months with `gettext`, any pointers in advance are appreciated.

**Comment by andmarti1424** [comment]
What would you like to translate? The doc file? We don't have menus in here

**Comment by bitigchi** [comment]
For starters, `sc_info`s and `sc_error`s would suffice (plus intro screen, mode names etc.). Documentation would definitely follow.

**Comment by andmarti1424** [comment]
Hello @bitigchi . Do you have any progress on this?
Thanks.

**Comment by bitigchi** [comment]
Hello @bitigchi . Do you have any progress on this?
Thanks.I have some progress but nothing ready to commit yet. This is on my to-do list still, I will get back to it eventually.

**Comment by bitigchi** [comment]
I've fiddled with it some more, but my lack of knowledge of C compiler ways really slows me down. Whilst implementing the feature is dead simple (just include `libintl.h`, set a macro and enclose the strings, then create a .pot file with `xgettext`), I get all sorts of compiler nagging on my macOS machine, and it will take some time for me to educate myself on C and various stuff.

**Comment by andmarti1424** [comment]
Hello @bitigchi . Do you have any progress on this?
Thanks.

**Comment by bitigchi** [comment]
No, not recently sorry. I plan to revisit in the future though if no one steps up in the meantime.

**Comment by andmarti1424** [comment]
ok @bitigchi no problem
