### ISSUE TITLE
Some issues for new users

### ISSUE THREAD

**Issue by EdwardWong1994** [andmarti1424/sc-im#736]
Hello, thanks for this wonderful plugin and i am new to this plugin and just finish the tutorial for sc-im. During doing the tutorials, i met across some issues. Can you help me out?
- When i try the `\"@if(C0>20,"strong","weak")`(Assume C0=50) , it did give me `strong` but when i change `C0=10`, and when i want to update it using `ini recalc`, the `strong` will not change to `weak`, do you know what's the problem?
-  Can you tell me the exact key for me jumping to specific cell say `C4`? i try around but failed it.
-  Is there any way for sorting?  I did not see any examples in tutorials.

Hope for your response.

**Comment by andmarti1424** [comment]
Hello. 
a. `@` key will recalculate. It should automatically refresh the value though.
b. `goc4`
c. examples\sc\sort.sc

**Comment by EdwardWong1994** [comment]
Thanks for your reply. I have readed the help file for sc-im.  I still have one problem related with plotting.

I want to plot the first column and third column and i change the `plot_line` file here.  When i use `:plot line` to plot figure, it gives me x range is invalid.   If i commented out `plot filename using 1:3 with linespoints` , it works but just give me the plot between first and second columns.

set terminal dumb enhanced
set datafile separator ","
set key autotitle columnhead
plot filename using 1:3 with linespoints 
```
The source `sc` file is [](https://github.com/EdwardWong1994/fairy_learn-bash/blob/master/RC_Force.sc)

I would appreciate for your reply

**Comment by andmarti1424** [comment]
Sorry. I am afraid  I am no gnu plot expert. This could be better answered on a gnu plot forum.
