### ISSUE TITLE
bugfix with cmd multiplier

### ISSUE THREAD

**Issue by mcrucifix** [andmarti1424/sc-im#74]
Hello, 

Thank you for the nice scim port of good old sc. I love it. 

A little bug,  which at least on my mac, and its solution. 

In cmds_normal.c, line 473, you need to replace line by 
 for (c1 = curcol; cmd_multiplier-- && cmd_multiplier > -1 && c1 < maxcols; c1++) {

(i.e., add explicit condition to stop at cmd_multiplier = 0), otherwise it keeps filling values until maxcols. 

[in case, my compiler version is 

Using built-in specs.
COLLECT_GCC=gcc-mp-5
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin13/5.3.0/lto-wrapper
Target: x86_64-apple-darwin13
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc5/gcc5/work/gcc-5.3.0/configure --prefix=/opt/local --build=x86_64-apple-darwin13 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc5 --includedir=/opt/local/include/gcc5 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-5 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-5 --with-gxx-include-dir=/opt/local/include/gcc5/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc5 5.3.0_0'
Thread model: posix
gcc version 5.3.0 (MacPorts gcc5 5.3.0_0)

]

**Comment by andmarti1424** [comment]
Will fix this, as soon as I can get my computer repaired..

**Comment by andmarti1424** [comment]
Which versión of SCIM are you using?

**Comment by mcrucifix** [comment]
Hi Andres

That is v0.3.0, downloaded a few days ago from githum. 

The line I was referring to in my mail was actually line 469, on the version presently on github. 


Michel. 

* Andrés M. <notifications@github.com> [2016-06-13 08:28:44 -0700]:

> Which versión of SCIM are you using?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Michel Crucifix
Université catholique de Louvain (Earth and Life Institute)
Fonds National de la Recherche Scientifique
Académie Royale de Belgique

http://perso.uclouvain.be/michel.crucifix
http://www.uclouvain.be/teclim

Phone: + 32 10 473300

**Comment by andmarti1424** [comment]
Already uploaded. Thanks!
