### ISSUE TITLE
I volunteer to create a logo for this app

### ISSUE THREAD

**Issue by master-of-m** [andmarti1424/sc-im#741]
Respond if interested

**Comment by andmarti1424** [comment]
Hello. Yes, sure. What is your idea for it?

**Comment by master-of-m** [comment]
Hi, I'm happy you like the idea.
I was thinking about something very simple like a generic terminal logo with a spreadsheet on it. I also like the concept of BASH logo very much, where they represent the terminal with a "box" shape.
If you have ideas feel free to share, the app is yours.
Also I can provide you in the next few days with a quick sketch of the logo I'm thinking about.
Greetings!

**Comment by andmarti1424** [comment]
Sure. That sounds great.

**Comment by master-of-m** [comment]
These are some ideas me and my girlfriend (mostly her) produced. Don't worry about the mess, we'll fix it. The big icons were the first ideas when we didn't bother to check if the icons were suitable to be small as icons should be. Tell me what you like and what you don't and we're gonna refine it!
[sc-im copy.pdf](https://github.com/andmarti1424/sc-im/files/9717540/sc-im.copy.pdf)

**Comment by andmarti1424** [comment]
I really liked these:
![image](https://user-images.githubusercontent.com/9466161/194121308-1ff8a2c5-0acd-4f8d-9665-557d358d3eda.png)

**Comment by master-of-m** [comment]
Ok, we are gonna polish them! I hope to be able to provide you the final files in the next few days.
If you have requests or advice for the logos feel free to tell me!

**Comment by master-of-m** [comment]
![scim1-01](https://user-images.githubusercontent.com/91836055/195397495-4424d1ec-ae6e-42ce-a1f2-1f1f0b2115cb.png)
![2-01](https://user-images.githubusercontent.com/91836055/195397524-bce14d75-9cfd-46a5-bdf5-473324cc3249.png)
![3-01](https://user-images.githubusercontent.com/91836055/195397537-f8fea44f-1772-4794-9468-03f2cc94ffcc.png)
![4-01](https://user-images.githubusercontent.com/91836055/195397554-9ca78d66-0c4d-4264-aadd-b9c05f67d30f.png)
![5-01](https://user-images.githubusercontent.com/91836055/195397569-a46649c4-84c9-45dc-aeaf-8a8ca80a5ad2.png)


the last two are the ones you liked, the second and the third are a version of them with bigger font for better readability

**Comment by andmarti1424** [comment]
Thanks! Can you add the cell to the first logo?? Check the dev branch. i have added to the front page.

**Comment by master-of-m** [comment]
![scim1-01](https://user-images.githubusercontent.com/91836055/195416594-80245ce8-bb4b-4651-8d0e-f89cb82f7394.png)

Oh sorry we forgot, here it is!

**Comment by andmarti1424** [comment]
Thanks. Updated the logo in front page!

**Comment by andmarti1424** [comment]
closing. thank you once again. merged to dev branch. will soon be in main.
