### ISSUE TITLE
Inadvertent conflicting saves to same file should be prevented

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#744]
If one opens a file in Vim while it's already open in another window, Vim alerts and limits the secondary open to `readonly`. This protects the user from inadvertently overwriting the file from a stale session, for example, after going home and remoting into work, and losing unsaved edits. The new multi-sheet capability makes it easier to fail to notice that the same file might be open in another window even on the same screen.
_Autosave_, like in a `Jupyter notebook`, can pose a reverse problem with the remote session repeatedly overwriting current work, if care is not taken to compare file modified time before overwriting.
A mechanism like Vim's `.swp` lock-file seems in order, and more general than the implicit lock on file handles obtained in `Windows`. A different extension, e.g., `.scw`, would ensure that a user is not prevented from working on a text file report and a project tracking or accounting spreadsheet of same _basename_ in the same directory.

**Comment by andmarti1424** [comment]
actually this was included on sc-im. may be its not working properly..

**Comment by andmarti1424** [comment]
do you have these set in your Makefile?
```
# Autobackup. If you unset this, no backup check nor autobackup feature will be available.
CFLAGS += -DAUTOBACKUP
# Have threads? Set these two, if you want the autobackup feature to work with threads.
CFLAGS += -DHAVE_PTHREAD
```

**Comment by earthshrink** [comment]
I missed that. Thanks!!
