### ISSUE TITLE
General question; using sc-im in a script

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#745]
Hi, thank you for keeping Sc-im alive, we need more TUI programs.

I'd like to, from a bash script, create a file, open it in sc-im, then read what modification were made by the user. I can't seem to find documentation about that, do you have any you can link to?

Cheers, Nadim

**Comment by andmarti1424** [comment]
Hello. No. There is no track of that. I dont know whats your final goal but you might try to activate autosave, try to find the temp file and read it..

**Comment by nkh** [comment]
It's OK for me to wait for the user to quit the application so I can read the data from there, I just haven't seen what
