### ISSUE TITLE
"syntax error" message should contain more information

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#746]
I'm writing a sc file by hand, the error message would be much much more helpful if the line containing the error was also listed.

**Comment by andmarti1424** [comment]
Try changing gram.y:1241 line to this:
`sc_error("syntax error: %s", line);`
and  rebuild.

**Comment by nkh** [comment]
About a zillion times better. for 2 zilion time better a line number is needed.

that may be more difficult though

**Comment by andmarti1424** [comment]
im afraid you'll have to get along with having it a zillion times better only..

**Comment by nkh** [comment]
A zillion times is not that bad at all, and it already helped fix one issue.

I tried to add yylineno but the parser groaked on an undefined variable. This article may be of help if you have the inclination to add it later.

https://stackoverflow.com/questions/66864607/yylineno-undeclared-when-using-flex-and-yacc

**Comment by andmarti1424** [comment]
Done commit with the change to dev branch
