### ISSUE TITLE
set the cursor at the intersection of the headers

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#748]
I use a terminal emulator, if I have multiple panes open with scim in them it becomes difficult to see which one is currently in focus, this could of course be made more evident in the emulator but that forces the eye to shift focus from the spreadsheets.

a block cursor with a user set color would be great and if not set would not change anything to how it looks today

**Comment by andmarti1424** [comment]
i really dont get what the problem is. dont you see the current cell in the header?

**Comment by nkh** [comment]
![screenshot_2022-10-19_14-56-13](https://user-images.githubusercontent.com/45409/196697021-3c913b2c-55e9-4924-b233-039bbe311acb.png)

If there are multiple sc-im running it's difficult to see whicg one is in focus

**Comment by andmarti1424** [comment]
this is out of sc-im scope.
if you are using tmux you can highlight the pane..

**Comment by nkh** [comment]
You decide the scope but as a user I find it less than optimum to not show that the application has focus.

when I closed the above panes I tried to guess which on I was closing and missed every time.

**Comment by nkh** [comment]
What would happen, in ncurses, if you put a block cursor? would curses handle it?

I usually go for ANSI codes so I can't help with ncurses unfortunately.

**Comment by andmarti1424** [comment]
i think ncurses handles block cursor..
may be you can try replacing
`curs_set(1);`
lines in tui.c
with
`curs_set(2);`

**Comment by nkh** [comment]
the change made no difference, maybe the cursor need to be placed somewhere visible first

**Comment by andmarti1424** [comment]
yes it does. if you are in COMMAND MODE or INSERT MODE you'll see the block cursor.

**Comment by andmarti1424** [comment]
Did you try show_cursor configuration variable?

**Comment by andmarti1424** [comment]
Take note that NORMAL_MODE does not show cursor.

**Comment by nkh** [comment]
it was the mode I would have like to see it otherwise the patch worked in the other modes

**Comment by andmarti1424** [comment]
As I said earlier NORMAL_MODE does not show cursor.
Again, terminal emulators already handle this issue.
