### ISSUE TITLE
freezecol can't be used in sc file

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#749]
"freezecol A" generates an error message 8without any more information), freezecol in command mode works as expected

The column name has a '!' appended, would setting the name of the column with '!' in the sc file work and how?

**Comment by nkh** [comment]
1 :freezecol A
  2 format A 57 0 0
  3 format B 9 0 0
  4 format C 9 0 0
  5 format D 9 0 0
  6 label B0 = "tag_uno"
  7 label C0 = "tag_deux"
  8 label D0 = "tag_drei"
  9 leftstring A1 = "ftl.png"
...

that also gives a syntax error, I compiled the latest version 2 hours ago

**Comment by andmarti1424** [comment]
the freezecol command is for use in command mode.
you should be creating sc files manually.
the sc command for freezing is like this:
![image](https://user-images.githubusercontent.com/9466161/196699489-99495a0d-9eaf-4c81-9826-38e5364e4128.png)

**Comment by andmarti1424** [comment]
what do you mean? as i said earlier..
freezecol command is for being used on COMMAND MODE.
not inside a file.

**Comment by andmarti1424** [comment]
what do you mean?

![image](https://user-images.githubusercontent.com/9466161/196707511-27f2c70f-a300-44f5-86d8-c414e350ad70.png)
.......
![image](https://user-images.githubusercontent.com/9466161/196707691-c59b49c5-6b13-46ba-9223-4620453ab87b.png)


"having freezecol available in the files too." -> what do you mean?

**Comment by nkh** [comment]
The documentation says "freezecol", nowhere in the documentation can we find "freeze" and the explanation that it should be used in sc files rather than "freezecol". That could be clarified in the documentation.

the alternative is to accept "freezecol" in the sc files and not need any documentation change.

**Comment by andmarti1424** [comment]
because freeze is just the way it gets saved in the files. its not for user use.

**Comment by nkh** [comment]
IMHO, it would be nice if there was no difference because it allows users to do something in scim and then look at the generated file.  And maybe it's simple than maintaining two sets of code and documentation.

There was a section about using scim in non-interactive way but it's short and my, maybe wrong, reflex was to look in the sc files, specially as they aren nice clear text files (what a breath of fresh air!).

**Comment by andmarti1424** [comment]
Yes indeed. May be some other documentation can be added on a separate file for advanced users that want to use scripting.
may be those people just read gram.y but .. anyways PR are welcome!

**Comment by nkh** [comment]
Asking for development documentation PRs is a bit asking for the impossible. That would mean spending an enormous  amount of time trying to figure out things when you have already spend the time. Code PRs and always simpler than documentation PRs.

But all my questions revolve around documentation and also around the lack of examples. In complex applications like sc-im that unfortunately means a large amount of documentation.
