### ISSUE TITLE
fill a range of cells with values

### ISSUE THREAD

**Issue by mcrucifix** [andmarti1424/sc-im#75]
Hello, two desired features. 

In visual mode, it would be cool to have a 'c' command (that would copy the marked on all selected cells), and also an 'i' command mode, that would fill all selected cells with value. I think it should not be too difficult, for 'i' in particular I noticed the 'fill' function in interp. 

As a temporary fix, I introduced a command 'C' in normal mode, which just like 'c' but if used with a multiplier, it copies on the same column, on different rows. Happy to share the code. 

Thanks so much for the good work,

**Comment by andmarti1424** [comment]
I do not understand the first one. Could you please give me more details?

**Comment by mcrucifix** [comment]
Hello Andrés, 


What I mean, is that I found currently no way to 'copy downwards', as we do in Excel. 

So my idea was the following. If you select (in visual mode) an array, then hit e.g. 'ca', 
the formula in the register should be copied to all selected cells. Similarly, if you hit 'i = 1', then
the value ' =1' should be copied to all cells. 

... or is there another way to do it ? 

Anyway, thanks for the nice work

Michel. 

* Andrés M. <notifications@github.com> [2016-06-13 06:44:28 -0700]:

> I do not understand the first one. Could you please give me more details?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Michel Crucifix
Université catholique de Louvain (Earth and Life Institute)
Fonds National de la Recherche Scientifique
Académie Royale de Belgique

http://perso.uclouvain.be/michel.crucifix
http://www.uclouvain.be/teclim

Phone: + 32 10 473300

**Comment by andmarti1424** [comment]
I added a new nfill function..

**Comment by andmarti1424** [comment]
Could you test it?

**Comment by mcrucifix** [comment]
yes (finally). Thank you.
