### ISSUE TITLE
Documentation: can't find how to set column and row text and change their color

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#752]
Could you please point at where in the documentation this is explained?

The project page first screenshot shows an example. Is the sc file for the example included in the source (I didn't find it)

Cheers

**Comment by andmarti1424** [comment]
you cannot change the text. for colors, see color COMMAND MODE command in doc:
![image](https://user-images.githubusercontent.com/9466161/196711025-fd22d07c-1cc8-4c9e-a7a3-15204fbd9c1c.png)

you also have themes in the themes folder.
cant recall about that screenshot though

**Comment by nkh** [comment]
I was wrong about the header text change, since there was no '!' after the 'A' I thought i was custom names.

it would be good to include the example in the distribution.




![screenshot_2022-10-19_15-57-47](https://user-images.githubusercontent.com/45409/196712198-51378fc3-4798-4c31-b5da-5fac205d2086.png)

**Comment by andmarti1424** [comment]
Thanks @nkh. I dont have that file at hand Im afraid..
