### ISSUE TITLE
quit if ctrl-C is pressed multiple time or too many errors

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#753]
if a sc file contains many errors, ALL errors are shown, which may take time to get out of.

either handle ctrl-C to quit after a few presses or. might be simple, display that too many errors were display and stop showing errors

**Comment by andmarti1424** [comment]
Im not sure about what other people think about this behavior that you suggest.
In case you want to implement it this would be the patch:

In file.c
![image](https://user-images.githubusercontent.com/9466161/197280115-a9fc7bf2-a7c9-440a-a6dc-2e595453c091.png)
in main.c
![image](https://user-images.githubusercontent.com/9466161/197280166-0dc3c919-040a-41e0-afa2-d1fd2a35486f.png)

dont hesitate to open a discussion so other people can share their thoughts about this.thanks.

**Comment by andmarti1424** [comment]
![image](https://user-images.githubusercontent.com/9466161/197280502-2cacec46-2e09-4856-aac2-d781a119f748.png)

**Comment by nkh** [comment]
thought  about this a bit more, I still think that one should not to press a key to go over multiple errors in the file. If it's not implemented yet, I think all those load errors should end up in some sort of log and when the second ctl-C is pressed the name of the log file should be displayed.

handling double ctl-C seems to be standard in quite a few application, I think it's a good solution.

will you integrate the patch or do you have it in a branch where I can get it?
