### ISSUE TITLE
Accept single quoted string in sc file

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#754]
label A0 = "xxxx" is legal but label A0 = 'xxxx' is a syntax error.

life is hard, quoting is harder, let make quoting simple

**Comment by andmarti1424** [comment]
This comes from old sc (made in the 80's)..
Dont know if this can be done easily.
Dont know if its worth the effort as well. You're the first one to complain that " is hard.
Again PR are welcome!
