### ISSUE TITLE
Running a script when a cell is changed

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#755]
I generate this scim file, thank for the help) and I'd like to run a script every time a cell is changed. is it possible? I couldn't find a clear description in the manual, I may have missed it.

![tmsu_scim](https://user-images.githubusercontent.com/45409/196942527-e5763215-e6d7-436e-a877-979d9a09cf76.png)

**Comment by andmarti1424** [comment]
Again, please refer to triggers.
