### ISSUE TITLE
Autofit: automatic on cell change

### ISSUE THREAD

**Issue by nkh** [andmarti1424/sc-im#756]
is it possible to set an option on the spreadsheet so that every time a cell is changes all the cells are autofit-ed

**Comment by andmarti1424** [comment]
dont think so. but there's a normal_mode command for that: 'aa'
maybe you can write a trigger to do that. But..
I wouldnt go that way.

**Comment by SeerLite** [comment]
Hi!

Is it not viable to have a builtin option for this? I was unable to make a trigger.
