### ISSUE TITLE
Segfault possibly caused by empty cell

### ISSUE THREAD

**Issue by marrs** [andmarti1424/sc-im#762]
I'm afraid this is a pretty lousy bug report as I'm no longer able to reproduce the error to provide any information, but it's serious enough that I feel I ought to at least report it.  I'm using the last stable release v0.8.2.

I was editing my accounts on a spreadsheet with a number of columns containing date, text, and numeric data.  At some point, I managed to engineer a situation in which, every time I tried to enter a new line by copying similar data from a row further up the spreadsheet, the app would segfault, referencing an invalid pointer as the cause of the issue.

This would happen every time I tried to copy data.  The key sequence would be something like `gg vlljy G p`, but other variations, like `10k vlljy 10j p` would also produce the error.

This would happen with 100% reliability.  I could load the file, immediately attempt the copy/paste, and cause the segfault.  I think it only happened when copying more than one row, but I can't be sure that it didn't also happen when copying a single row.

I *think* what was happening was that I somehow tricked `sc-im` into creating a pointer to a cell with no data in, perhaps by starting to enter some text into the next available cell and then changing my mind?  One thing for certain is that the `sc` file itself must have contianed a line that produced the dangling pointer when loaded into memory, because the issue would persist between saves.

I seemed to fix the error by deleting the empty cell with `x` or maybe `dr`, I presume thereby deleting the pointer.

Sadly I didn't back up the file before I fixed the issue (I was kind of in work mode) but I'll update this ticket if I'm able to reproduce the error again.

Sorry this isn't a more coherent bug report

**Comment by marrs** [comment]
I managed to reproduce the issue.  This is the smallest I can get the file.

```
# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

format A 13 2 0
leftstring A0 = "AAA"
let B0 = 10
let C0 = @sum(B0:B2,@eqs(B0,"AAA"))
leftstring A1 = "BBB"
let B1 = 20
goto A0

```

So I guess all that theorising above was wrong.  It appears to be the `@sum` function that's causing the problems.  If you change the range from `B0:B2` to `B0:B1`, then the issue goes away.

With the above file, you should be able to cause a segfault in 2 ways:

1. copy 2 lines (not including the cell with the formula) with `vljyjjp`.
2. copy 1 line and then undo with `vlyjjpu`. 

  This will cause a crash with the message *Segmentation fault (core dumped)*

**Comment by andmarti1424** [comment]
Im using the dev branch. I cannot get it to segfault with any of the 3.

**Comment by marrs** [comment]
I'll close the issue then.  Looks like you've probably fixed it.  I'll try and find the time to check myself on main and get back to you if I reproduce it again.

Thanks for your time

**Comment by andmarti1424** [comment]
Probably. But probably not. Please test it on main or dev branches and report back. Thanks!
