### ISSUE TITLE
new release of sc-im within two months?

### ISSUE THREAD

**Issue by alexmyczko** [andmarti1424/sc-im#763]
The last release is more than a year old, a lot has happened with the code commit wise,
is there a chance for a new release?

**Comment by andmarti1424** [comment]
Actually there is. I'm working on it for some time now

**Comment by alexmyczko** [comment]
@itzswirlz ^

**Comment by ItzSwirlz** [comment]
> @ItzSwirlz ^

I can push it to debian soon(TM)

**Comment by alexmyczko** [comment]
@ItzSwirlz how soon? can't see it on mentors.d.n... transition freeze started already...

**Comment by ItzSwirlz** [comment]
I uploaded it.. as I had to run out the door. When I come back (approx two hours) I can file a bug if needed

**Comment by alexmyczko** [comment]
upload enough, no bug needed thanks
