### ISSUE TITLE
Segfault when pasting large data

### ISSUE THREAD

**Issue by Chimrod** [andmarti1424/sc-im#77]
When you paste many rows, sc-im segfault 

goto A70
switch in visual mode and select all cells from A0 to A70, yank
go back in A70
paste

This cause a segfault.

**Comment by andmarti1424** [comment]
Could you please try it again updating to latest commit in depgraph branch?
Thanks!

**Comment by Chimrod** [comment]
Yes this is fixed !
Thanks for your reactivity !
