### ISSUE TITLE
What is the consistency between the differents copy methods ?

### ISSUE THREAD

**Issue by Chimrod** [andmarti1424/sc-im#78]
When we yank/paste a data which has been marked, the refs to other cells are updated (ie A0 + 1 will become D8 + 1). But this does not work when we directly yank/paste an element. Is this intended ?

The patch for updating the references is very simple (in [yank.c](https://github.com/andmarti1424/sc-im/blob/dev/src/yank.c#L223) ) : 

``` c
        if (type_paste == 'a' || type_paste == 's') {
            (void) copyent(destino, yl, diffr, diffc, 0, 0, maxrows, maxcols, 0);
            sync_refs();
            EvalAll();
            //(void) copyent(destino, yl, 0, 0, 0, 0, 0, 0, 0);
```

---

Performance question : with this patch sync_refs() and EvalAll() are called each for each element in the while loop. I've tried to put them outside the loop but this seems to break the undo/redo functionality. Is there a way to solve this ?

**Comment by andmarti1424** [comment]
See if I can understand what you are saying..
If you want to keep references of just an element.. you can use the copy command.
For instance:
put value 12 in A0
put value A0+1 in A1
copy A1 to D1 with yy and p commands.
That does not alter references.
Now mark A1 as 'a' with 'ma' command
Goto D2 and type 'ca'. That copies A1 formula but alter refereces..
It that what you want to achieve?

**Comment by Chimrod** [comment]
For my usage, I never need to copy an element without updating the references. If I really need a references to be fixed, I use the '$' notation ($A$10) which works in all spreadsheet.

But sc-im gives two differents ways for copying elements, and using the marks is the only one which allow to update the references. So my question is : is this intended or is that a legacy from sc ? Does it worth to keep a raw copy/paste which does not updates the refs ?

**Comment by andmarti1424** [comment]
I believe this works similiar in SC as well. Glad to see what other people think about it though.
In SC-IM you have different ways of pasting the data... 'Pf' command, 'Pv' command, 'Pc' command..
