### ISSUE TITLE
Lua - Get Calling Cell

### ISSUE THREAD

**Issue by Firimo** [andmarti1424/sc-im#784]
Hi,

is there a way to get the cell id (column,row), which is calling the Lua script?
The functions "curcol()" and "currow()" give me the id of the cell, where my *cursor* is at.
I want the id of where the @lua() string is at.

The current behavior is not what I would expect and it leads to a segmentation fault at startup in my specific use case (because I wanted to read from cells, to the left of the calling cell).

Otherwise sc-im is nice :+1:

Kind regards

**Comment by gzagatti** [comment]
It is indeed not possible to do what you wanted. PR#814 hopefully solves this issue, please take a look.

**Comment by andmarti1424** [comment]
Solved with PR#814.
