### ISSUE TITLE
Help with linking to ncursesw

### ISSUE THREAD

**Issue by JohnLunzer** [andmarti1424/sc-im#79]
I have built my own ncursesw and I am trying to link against it but it seems I can't get sc-im to pick up the library files:

```
gcc  block.o buffer.o cmds.o cmds_command.o cmds_edit.o cmds_insert.o cmds_normal.o cmds_visual.o color.o conf.o exec.o file.o filter.o format.o help.
o hide_show.o history.o input.o interp.o lex.o main.o maps.o marks.o pipe.o range.o screen.o shift.o sort.o undo.o vmtbl.o xls.o xlsx.o xmalloc.o yank
.o utils/dictionary.o utils/extra.o utils/string.o gram.o -o scim -lm -L/Users/jlunz/usr/lib 
cmds.o: In function `auto_justify':
/Users/jlunz/scratch/sc-im/src/cmds.c:1365: undefined reference to `COLS'
...
help.o: In function `show_lines':
Users/jlunz/scratch/sc-im/src/help.c:297: undefined reference to `wgetch'
```

There were hundreds of these undefined references. I only showed two. Any tips on what I'm doing wrong? My lib directory contains `libncursesw.so` , `libmenuw.so`, etc.

**Comment by andmarti1424** [comment]
Never did this, but check you have the header file in the same directory you are linking to..

**Comment by JohnLunzer** [comment]
So... after building ncursesw I would have my includes in Users/jlunz/include.

In order to get the build moving I had to add these lines to my makefile:

```
CFLAGS := $(CFLAGS) -I/Users/jlunz/usr/include -I/Users/jlunz/usr/include/ncursesw
LDLIBS := -lm -L/ssd/meaf/Users/jlunz/usr/lib 
```
Does anything seem wrong with this approach?

**Comment by andmarti1424** [comment]
I believe its OK. Could got it build then?

**Comment by JohnLunzer** [comment]
No sorry, what I meant was that without adding the CFLAGS and LDFLAGS I could not get it to move almost at all, because it was complaining about missing the header files. Then when I added these lines that is why I am getting these errors. Will try some stuff with my LD_LIBRARY_FLAGS path...

**Comment by JohnLunzer** [comment]
Got it, need the LDFLAGS from here:
```
ncursesw6-config --libs
```
