### ISSUE TITLE
Export a particular sheet alone to txt without interaction

### ISSUE THREAD

**Issue by simonante** [andmarti1424/sc-im#791]
Can I export only one particular sheet to txt without interaction?

**Comment by andmarti1424** [comment]
Have you tried selecting it in visual mode and then exporting?
Please do not open issues for questions. Try Discussions for that.

**Comment by simonante** [comment]
Sorry for opening an issue for this.
What I basically need is to obtain a certain macro cell from a sheet without interaction. This is because I have a script that edits a value of some cell in the raw sc file. I need a macro cell value without opening the sc-im interaction.
I can export the whole spreadsheet to csv or txt ```sc-im --quit_afterload --nocurses --export_mkd --output=out.txt file.sc | tee out.txt``` and find the macro there, but that is really painful with a larger document.
Do you have any idea for a better approach?

**Comment by andmarti1424** [comment]
you can use `echo getnum A3 | sc-im ...` or something like that
Please take a look at "External scripts" section in doc
