### ISSUE TITLE
A 9.9MB file takes forever to load

### ISSUE THREAD

**Issue by simonante** [andmarti1424/sc-im#792]
[This](https://drive.google.com/file/d/1Se5FTvOnzn2c84tFBuDmKgPHkSkBAL5J/view?usp=share_link) 9.9MB file that takes forever to load. The spreadsheet consists of 16 sheets, each with 421 columns, 240 rows, and some basic macros (mostly basic summation and cell references). A spreadsheet such as this with one sheet takes less than a minute to load, but with 16 sheets it takes more than 12 hours, possibly more.
What makes the loading time so long? Is it that the sheet contains many cells that reference to cells that are also a reference?

**Comment by simonante** [comment]
Any idea?

**Comment by andmarti1424** [comment]
@simonante will get back to you when I can take a look at it.

**Comment by simonante** [comment]
I can't believe the calculation of basic macros or a very large spreadsheet would take that long. Still can't figure it out.

**Comment by NicolasHatcher** [comment]
Hi @simonante does sci-im support macros? Also your 9.9MB file is not a public file, not sure if you intended that.

**Comment by andmarti1424** [comment]
@simonante Please share your file and reopen this. thanks
