### ISSUE TITLE
Connect cells

### ISSUE THREAD

**Issue by simonante** [andmarti1424/sc-im#793]
I often find myself missing the ability to connect cells visually, which can be done in Excel.
It would be nice to have a command that would connect any two cells in the interactive mode, also to adjust with hidden rows/cells.
![](https://i.imgur.com/ZjknDU9.jpeg)

**Comment by andmarti1424** [comment]
You mean connect with lines?
Im afraid ncurses does not allow this.
Please do not open issues for feature requests. Please use Discussions for this purpose.
