### ISSUE TITLE
Is it possible to map > and < keys?

### ISSUE THREAD

**Issue by SeerLite** [andmarti1424/sc-im#799]
Hi!

I'm trying to map `a>` to `z-` and `a< to `z+` but I can't get it to work.

    nnoremap "a<" "f+"
    nnoremap "a>" "f-"

I also tried writing `>` as `<gt>` and such but that didn't work either. Is there a way to map them?

**Comment by andmarti1424** [comment]
Hello. Answering to your question.. yes.
These for instance work for me..
`inoremap "<" "a"`
`nnoremap "a<" "j"`
`nnoremap "a<" "f+"`
