### ISSUE TITLE
How to build with xls and xlsx import on archlinux using yaourt?

### ISSUE THREAD

**Issue by blisk92** [andmarti1424/sc-im#80]
I've been trying to install this program with yaourt in archlinux, but I need the xls xlsx import function. I couldn't find any help online on how to do so. Can you point me in the right direction?

I also tried compiling it manually with the make command but I couldn't find the necessary libraries and dependencies for archlinux.

**Comment by andmarti1424** [comment]
Dont really know how yaourt works, but you should try building 
libzip
libxml2
libxlsreader
manually before building sc-im linking to those libraries..

**Comment by blisk92** [comment]
I tried that. But there is an error when I run `./install-sh` when building the packages. 

It shows `./install.sh: no input file specified`

I'm not sure what I'm doing wrong.

**Comment by andmarti1424** [comment]
install.sh is not a sc-im file. What is that file?

**Comment by blisk92** [comment]
`./install-sh` is for the dependencies libzip,libxml2,libxlsreader. Would it be possible for you to provide me a link to the packages?

**Comment by andmarti1424** [comment]
Try these:
libzip
https://nih.at/libzip/

libxml2
http://xmlsoft.org/downloads.html

libxlsreader
http://libxls.sourceforge.net/

**Comment by andmarti1424** [comment]
Hello. Could you build it?
