### ISSUE TITLE
Is it  possible to use the simple column format style in specific cells?

### ISSUE THREAD

**Issue by SeerLite** [andmarti1424/sc-im#801]
I'd like to have an easy keybind to increase and decrease decimal precision, but only in the current cell and not affect the entire column. Is that possible?

**Comment by andmarti1424** [comment]
Format that cell only

**Comment by SeerLite** [comment]
Hi, I don't see a way to format a single cell with the {COLUMN} {WIDTH} {PRECISION} {TYPE} options like columns. Am I missing something?

**Comment by andmarti1424** [comment]
You have to use `:format` command. Please see doc.

**Comment by SeerLite** [comment]
I have read the instructions for `:format` several times. I still don't see a way to achieve what I want, which is why I opened this issue.

Do you intend to say that the feature that I want is not planned?

**Comment by andmarti1424** [comment]
Please feel free to open discussions for  @questions. Issues are intended to report bugs.
To format only one cell you have to use print format.

**Comment by SeerLite** [comment]
Oh sorry! Are feature requests also done in discussions?

**Comment by andmarti1424** [comment]
Yes. Please use discussions for questions and feature requests. May be we should update Readme file
