### ISSUE TITLE
sc-im installation failure in Ubuntu 20.4L LTS

### ISSUE THREAD

**Issue by VictorCarreira** [andmarti1424/sc-im#803]
### Discussed in https://github.com/andmarti1424/sc-im/discussions/802

<div type='discussions-op-text'>

<sup>Originally posted by **VictorCarreira** April  6, 2023</sup>
To whom it may concern.
Dear colleagues after I installed all the dependencies I couldn't build the make file in the sc-im cloned repository.  I am attaching a PrintScreen of the error.
![Captura de tela de 2023-04-06 15-16-22](https://user-images.githubusercontent.com/5520827/230462138-295a5527-9b55-4896-bed6-dbff69427b54.png)
![Captura de tela de 2023-04-06 15-18-56](https://user-images.githubusercontent.com/5520827/230462535-4bb1cdd7-38cc-4007-986f-762d29907553.png)
</div>

**Comment by andmarti1424** [comment]
hello
1. you need to install bison. 
2. to run make command you need to be inside src folder.

**Comment by VictorCarreira** [comment]
It worked. Thanks.

**Comment by andmarti1424** [comment]
Great. What if you close the issue now? Don't hesitate to open a discussion for requesting help on things that are not bugs.. Thanks.
