### ISSUE TITLE
ODS import support not compiled in

### ISSUE THREAD

**Issue by letscho123** [andmarti1424/sc-im#806]
I installed `sc-im` v0.8.4 on Fedora 37 following this [guide](https://github.com/andmarti1424/sc-im/wiki/Installing-on-Fedora-27), it compiled without errors and works fine for most parts.
However, when I want to open an ODS file, it says "ODS import support not compiled in".

So my question is, how can I add ODS support when compiling?

First, I tried the [package](https://github.com/andmarti1424/sc-im/wiki/Installing-on-Fedora-36--(packaged)) where ODS files worked, but I always got ax syntax error message on startup, so I compiled it.

**Comment by andmarti1424** [comment]
I am sorry but I do not use Fedora. Check you have libzip libxml-2.0 installed on your system and retry building sc-i.m

**Comment by letscho123** [comment]
I had to install the devel version for the two packages. Now it is working.

Thanks a lot!

**Comment by ricemark20** [comment]
> I had to install the devel version for the two packages. Now it is working.
> 
> Thanks a lot!

Which two packages did you install?   I run Fedora and have the same issue.

**Comment by letscho123** [comment]
> Which two packages did you install? I run Fedora and have the same issue.

If my notes are correct I installed these packages: `sudo dnf install libxml2-devel libzip-devel ncurses-devel byacc`
