### ISSUE TITLE
syntax error :load

### ISSUE THREAD

**Issue by letscho123** [andmarti1424/sc-im#807]
I installed `sc-im` v0.8.4 on Fedora 37 following this [guide](https://github.com/andmarti1424/sc-im/wiki/Installing-on-Fedora-27), it compiled without errors and works fine for most parts.

When I want to load a theme on startup from the `scimrc` file, I get the error message "syntax error: :load /path/theme.sc".
The command `:load` works fine within `sc-im`.

Here is my `scimrc` file and all options except `:load` work:
```
set input_bar_bottom=1
set truncate
# set autocalc
set debug
set xlsx_readformulas
set ignorecase

# mappings
nnoremap "<RIGHT>" "fl"
nnoremap "<LEFT>" "fh"
nnoremap "<UP>" "fk"
nnoremap "<DOWN>" "fj"

nmap "Q" ":q!<cr>"
nmap "W" ":wq<cr>"

:load /home/user/Documents/sc-im/themes/old.sc
```
Also having only `:load` in the file gives the same error.

**Comment by andmarti1424** [comment]
:load is for use in runtime. Not inside scimrc file

**Comment by letscho123** [comment]
Is there another way to apply a theme automatically at startup?

**Comment by andmarti1424** [comment]
Yes, please read THEMES section in doc.

**Comment by letscho123** [comment]
Ahhh I got it.
Thanks a lot and I really like your program!
