### ISSUE TITLE
Mime type of SC-IM

### ISSUE THREAD

**Issue by Han8931** [andmarti1424/sc-im#808]
Hi, I am trying to set sc-im as a deafult app for sc files in LF file manager.
I wonder how to find mime type of sc-im.
It seems an output of `find --mime-type <filename>` is not working...

**Comment by andmarti1424** [comment]
Hello. sc-im use .sc files. But these files are not part of any standard. They are not transmitted over the internet either, as for instance a jpg or an html are..
