### ISSUE TITLE
Freeze rows & columns

### ISSUE THREAD

**Issue by martinheidegger** [andmarti1424/sc-im#81]
I am working with a file with a header line (not quite uncommon for csv) and the first column contains a key. When editing the file it would be nice to be able to lock, use it instead of A/1

**Comment by andmarti1424** [comment]
You mean like freeze rows and columns?

**Comment by martinheidegger** [comment]
Yes.

**Comment by andmarti1424** [comment]
Its in the roadmap, but did not started yet.. and have my home computer broken. :(
you will have to wait for this.

**Comment by andmarti1424** [comment]
would be useful to have more than section of screen freezed?

**Comment by andmarti1424** [comment]
This is now in the default and only branch. Please fell free to give it a test.

**Comment by andmarti1424** [comment]
Hello @martinheidegger, could you give it a test?
