### ISSUE TITLE
Zc and Zr don't work

### ISSUE THREAD

**Issue by Quaddroo** [andmarti1424/sc-im#815]
As described.
They are supposed to "zap" (hide) the current column or row, as per the help pages.

They do nothing on my system, running the latest version of this.

I also can't figure out how to them, since I could not find how to refer to the current cell in a map command
(something like nmap "Zc" ":hidecol {current column}", but the help does not explain how to refer to the current column)

**Comment by andmarti1424** [comment]
This works ok on my systems. What version are you using?
You might try using `@myrow` and `@mycol` to reference current row and column.
