### ISSUE TITLE
Unable to open a CSV file (syntax error)

### ISSUE THREAD

**Issue by ershov** [andmarti1424/sc-im#816]
Hi,

I'm trying to open a pretty normal CSV file here: https://gist.github.com/tadast/8827699 and I'm getting a bunch of errors starting from the second line like: `syntax error: label B1=" "AF""`. I can't even stop it with a `^C` or regular `kill` (only `kill -9` helps).

Needless to say that this file can be opened by any other editor.

The sequence of errors is: it complains at a bunch of fields, then `Illegal string expression`, then `error in slet - exprerr`.

**Comment by andmarti1424** [comment]
@ershov thank you for reporting this. please update to latest commit on dev branch and retry.
we will have to use a proper csv library oneday for csv import and export..

**Comment by andmarti1424** [comment]
@ershov could you test it? thanks

**Comment by ershov** [comment]
It works now. Thanks @andmarti1424
