### ISSUE TITLE
Command format changes cell colour

### ISSUE THREAD

**Issue by gzagatti** [andmarti1424/sc-im#819]
A command like `:format "###,###"` will change the cell color. I'd rather keep the cell of say type `NUMB` formatted as `NUMB`. I don't seem to find an option of turning off this feature. Is it possible?

**Comment by andmarti1424** [comment]
you can try changing line 875 to 876 on tui.c. will commit this in a few days.
![image](https://github.com/andmarti1424/sc-im/assets/9466161/400ee23d-f253-43f0-9a41-37da044dd44a)

**Comment by gzagatti** [comment]
Thanks for the quick fix. It helps a lot.
