### ISSUE TITLE
Opening an exported markdown file segfaults

### ISSUE THREAD

**Issue by BeastyBlacksmith** [andmarti1424/sc-im#820]
Maybe opening markdown is not supported, but getting an error message would be preferrable.

**Comment by mipmip** [comment]
@BeastyBlacksmith Can you send the markdown file that is making sc-im crash?
What is your OS and what sc-im version is causing this?

When I run `sc-im sc-im/Readme.md` I get all lines in a single column.

![Screenshot from 2024-08-16 15-03-11](https://github.com/user-attachments/assets/70487aac-9230-409f-a3c5-94c635cb53fe)

**Comment by BeastyBlacksmith** [comment]
Sorry, I don't have the file itself, but it was a markdown table.

I think I loaded a csv file, exported it as `.md` and then tried to read it back in.

My version is `0.8.2+ds-1` which is what is distributed via `apt`.

**Comment by mipmip** [comment]
This should work, so please confirm if this is still an issue.

**Comment by BeastyBlacksmith** [comment]
I tried today and I cannot reproduce
