### ISSUE TITLE
Conditional colour formatting

### ISSUE THREAD

**Issue by ConlangBabble** [andmarti1424/sc-im#823]
I'd like to be able to do conditional colour formatting for cells but I'm having trouble figuring out if something like this is possible in sc-im yet. For example, something simple like adding up some numbers and colouring the result cell based on the value in the cell (for example red for negative numbers, green for posiive numbers). I haven't had any luck finding anything in the help file that suggests something like this is doable but I figured I would ask anyways.

**Comment by cskeeters** [comment]
@ibsil did you find a way to achieve conditional formatting in sc-im?
