### ISSUE TITLE
sum doesn't sums

### ISSUE THREAD

**Issue by jjinkou2** [andmarti1424/sc-im#83]
i just download the last version 0.4.0  but when i try a function on a range, it doesn't work. 
@sum(B1:B2) gives always 0 whatever numbers are in B1 and B2. 
i compiled it on ubuntu and use the link here to compile without any problem: 
https://github.com/andmarti1424/sc-im/wiki/Debian-install-walk-through

**Comment by andmarti1424** [comment]
Please update to recent commit I did a couple of minutes ago

**Comment by jjinkou2** [comment]
thanks it works!

**Comment by andmarti1424** [comment]
It is related with how formulas are autoevaluated.  I am improving this. However i am curious in what you said.. The 0.4 published  release should not have this issue. How did you download it?

**Comment by jjinkou2** [comment]
well i think i  have cloned it through github. 

2 last  questions :
1) can a column be resized manually?  (not autoajust but giving it a number.)
2) can a text overlap several cells ? for example sc will format the tutorial (/usr/share/doc/sc/tutorial.sc) on adjacent cells but scim will display stars so i have to autoajust.

**Comment by andmarti1424** [comment]
1. You can resize columns with fl / fh commands, or with f+right_arrow / f+left_arrow keys.
You can also type 4fl, to increase width in 4 columns.

2. I believe this is no longer possible. It used to be possible in SC-IM as well, but when I cleaned the refresh() routine, I believe I removed that.

**Comment by jjinkou2** [comment]
thanks you!
 
for the overlap cells, i read your code and i commented these in the file "screen.c"
`
    // If content exceedes column width, outputs n number of '*' needed to fill column width
    /*if (str_len + num_len + padding > col_width ) {
        if (padding) wmemset(str_out + wcslen(str_out), L'#', padding);
        wmemset(str_out + wcslen(str_out), L'*', col_width - padding);
        return;
    }*/
`
now scim displays correctly your files a.sc or colors.sc

it 's not the best solution. i think this part of the code should be toggled either by a global variable (to let the user configure it) or may be the cell could have a special format.

**Comment by andmarti1424** [comment]
This almost work. You have a problem when in a cell you have both text and number, and apply a right alignment..

**Comment by andmarti1424** [comment]
Added a new configuration parameter called "overlap", to achieve what you wanted..
Hope it would be useful.

**Comment by jjinkou2** [comment]
thank you
