### ISSUE TITLE
Trying to copy one column from one file to another

### ISSUE THREAD

**Issue by Gavilaan** [andmarti1424/sc-im#839]
Hi,
i'm totally new to sc-im. Tried to find an irc or matrix channel to get some help, but wasn't lucky. Is there one?

My problem: i want to copy one column form one file to another. My steps:

1. open file
2. go to my column
3. press yc
4. load another file (with load command, didn't leave sc-im)
5. press p
6. nothing happens
I tried the same steps in one file, it works fine.
Is it not possible?
Thanks
Gav

**Comment by andmarti1424** [comment]
hello. all memory of previous opened file is free'd when you load the second file.

**Comment by Gavilaan** [comment]
Thanks
