### ISSUE TITLE
ctrl-o doesn't copy in insert mode

### ISSUE THREAD

**Issue by jjinkou2** [andmarti1424/sc-im#84]
when i enter into a visual mode from edit mode, the range isn't inserted. 
for example : i write in the cell B4 : =@sum( ctrl-v , then i select a range with ctrl-k ctrl-o => nothing is copied to the formula. 

Note: it works if i mark a range before writing my formula and then i do a ctrl-r

**Comment by andmarti1424** [comment]
Yep. You 're right. Broke this when adding WIDE CHAR support.
Will fix this.

**Comment by andmarti1424** [comment]
Please. Update to latest commit in this branch. It should be fixed. THanks.

**Comment by jjinkou2** [comment]
tested .it 's ok now . thanks
