### ISSUE TITLE
xls compile but with a minor change in source code

### ISSUE THREAD

**Issue by jjinkou2** [andmarti1424/sc-im#85]
i successfully compile scim with the last sourceforge libxlsreader with this minor correction in your file xls.c: 
i change this 
`xls_close(pWB);`
to this
`xls_close_WB(pWB);`

i add a page to your wiki for ubuntu too.

**Comment by andmarti1424** [comment]
Thanks for the wiki update.
I don't like that library.. It had a lot of issues. Will probably don't maintain it anymore.
XLSX just replaces the XLS format.
Please report back to see how did it worked for you.
THanks!

**Comment by jjinkou2** [comment]
some files are correctly imported. for instance your file t1.xls is ok. but the  file german.xls makes scim crash with a core dump. 

You are right, xlsx should be used when possible or csv.
