### ISSUE TITLE
`Pc` a range but keeping some references fixed

### ISSUE THREAD

**Issue by Nora-n** [andmarti1424/sc-im#851]
I want to create a column H that is, for instance, 10*G/(avg(G)). I can insert a column, then on the first row type `=11*G1/@avg(G1:G40)`, copy that formula, visual-select the rows `H2:H40` and `Pc` said formula. But pasting that formula with `Pc` changes the range in the average: I get `=11*G2/@avg(G2:G41)` etc, but I want to keep the average of the whole G column. The same thing happens if I have the average somewhere else and use that cell (for instance `=11*G1/G41` where `G41` has the value `=@avg(G1:G40)`: pasting that will update the range for `G1` and `G41`.

How to create a column based on another one?

Thanks!

_Originally posted by @Nora-n in https://github.com/andmarti1424/sc-im/discussions/847_

**Comment by andmarti1424** [comment]
May be I dont get the problem correctly. If you want to keep the avg fixed, you can type 11*G1/@avg($G$1:$G
$40), then you can copy and paste with Pc and G1 will get updated to reference G2, etc..

**Comment by Nora-n** [comment]
Wow that was an easy one, didn't find that in the help files. Wonderful! Tanks for the quick answer and for the tool, I'm loving it :-).
