### ISSUE TITLE
Rearranging sheets

### ISSUE THREAD

**Issue by diffract** [andmarti1424/sc-im#852]
Thanks for this great app.
I looked around in the help file and google and there doesn't seem to be a way to move sheets around.
I have a file with 6 sheets. I would like to move sheet 5 to position 3. Is there a way to do it without copying/pasting everything?
If not, i propose something like ":movesheet 3"

**Comment by andmarti1424** [comment]
Actually, there is no command to do that at runtime. Not the best, but perhaps better than copying and pasting.. you can try to edit the file and move the lines between `movetosheet`..
![image](https://github.com/andmarti1424/sc-im/assets/9466161/59dca4ae-c783-4aa7-9ea3-63c3b3ec1329)

**Comment by diffract** [comment]
Thank you.
Never crossed my mind that sc files were plain text.
I tried just rearranging the lines at the beginning of the file that start with "newsheet" and that did the trick. Works well enough for my needs.

**Comment by andmarti1424** [comment]
Sorry. Yes. You have to rearrange those `newsheet` lines.
