### ISSUE TITLE
Memory leaks froze my pc

### ISSUE THREAD

**Issue by TheYellowArchitect** [andmarti1424/sc-im#856]
I wanted to give a try at https://github.com/andmarti1424/sc-im/issues/486
I just wanted to search through this repo for that command option, hoping its an easy task (I am a newbie with linux)
I built according to the guide at README.md but couldn't find how to execute that local binary (where is that binary?)

Anyway, I ran the unit tests at `tests/run_all_tests.sh` (or was it `assert.sh`) anyway, first time it ran succesfully, then I ran it again, and it froze. Hard. Like, no input, no mouse no keyboard, had to reboot manually... Please remove these tests if they are reproducible, they can harm someone's computer.

P.S. I probably ran them with `sudo` rights since my user is sudo by default (yes, I recognize it's bad practice)

**Comment by andmarti1424** [comment]
Hello. Why you say there is a leak? Did you run sc-im with Valgrind or other tool and saw this?

**Comment by TheYellowArchitect** [comment]
Because I have run plenty of wild/random software, and my linux has never behaved this way before. Never before have I experienced input freeze (something which is normal in Windows with certain unoptimized programs)
Even if I run an infinite loop in bash, I can just kill the window (dwm), it wouldn't corrupt my entire pc (and on reboot it said something about RAM so yeah)

Here is the argument for memory leak, without the usage of any software: It completed the first time without issues, and since unit tests are supposed to be deterministic, it doesn't make sense for the 2nd time to cause issues. This means the state of the computer changed, and this can be true only if the memory was changed, hence my assumption for memory leak.

**Comment by andmarti1424** [comment]
I run all these tests with valgrind without any memory leaks in the log shown. please rerun those tests with valgrind and report back. if there is a memory leak you should see it in the log. thanks.

**Comment by TheYellowArchitect** [comment]
It sounds like a case of "it works on my machine"
I would love to help on this, but there is no way I will run that script again, as it was harmful to my hardware. If you wish, close this issue, I only wanted to report this bug.

**Comment by luna-in-space** [comment]
I don't understand how you can know this is a memory leak with no documentation. For all anyone knows there could be a million other things that caused this to happen unless you run it through valgrind.

**Comment by andmarti1424** [comment]
I agree with @luna-in-space. @TheYellowArchitect if you happen to run these with valgrind, please share the log. thanks again.
