### ISSUE TITLE
All colors get reset to defaults after 'gf'

### ISSUE THREAD

**Issue by 097115** [andmarti1424/sc-im#862]
I have custom colors set in my config. However, after pressing `gf` on any cell (may contain an URL, or be just an empty one), those colors reset to their default values.

Confirmed while running completely without the config, too[^1] ):

  - start `sc-im`
  - `:color "type=NORMAL fg=WHITE bg=BLUE"`
  - `NORMAL` color is changed
  - `gf`
  - `NORMAL` color is back to the default

Tested on 0ba93dc (dev) and fca17ce (main).

[^1]: Would be great to have something like Vim's `-u NONE`, btw. Instead of renaming the configuration folder manually :)

**Comment by andmarti1424** [comment]
@097115 confirmed. but how you have default_open_file_under_cursor_cmd configured? what is the content of the cell where you press gf?

**Comment by 097115** [comment]
> but how you have default_open_file_under_cursor_cmd configured?

Yep, it's set to `scopen`. And it works :)

> what is the content of the cell where you press gf?

It may be a filename, an URL or just an empty cell. After `gf`, the first two get correctly open by `scopen`, and with the last one nothing happens (as expected). The colors get reset every time.

**Comment by andmarti1424** [comment]
@097115 please update to latest commit on dev branch and retry. thanks.

**Comment by 097115** [comment]
@andmarti1424 

Looks like you've indeed fixed it :)

Thanks!
