### ISSUE TITLE
Copied (via Pc) formula not displaying right contents, even after recalc

### ISSUE THREAD

**Issue by truelson** [andmarti1424/sc-im#87]
I've included the repro file at end of this issue

Steps to reproduce:
If I yank the formula (yy) in C4 and then copy it to C5 (using Pc), the formula in C5 looks correct, but the value in C5 is the same as the value in C4.

Hitting "@" or :refresh does not change the value in C5. Quitting and reloading does make the value in C5 correct.

Thanks!

---
```
# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

format A 18 2 0
format B 15 2 0
format C 13 2 0
format D 27 1 0
leftstring A0 = "Now"
let B0 = @now-0
fmt B0 "# sec"
let C0 = B0
fmt C0 "d%H:%M"
leftstring A3 = "Start"
leftstring B3 = "End Time"
leftstring C3 = "Total Time"
let A4 = 1472036644
fmt A4 "d%Y-%m-%d %H:%M"
let B4 = 1472042320
fmt B4 "d%H:%M"
let C4 = (B4-A4)/60
fmt C4 "# min"
let A5 = 1472131723
fmt A5 "d%Y-%m-%d %H:%M"
let B5 = 1472134350
fmt B5 "d%H:%M"

```

**Comment by andmarti1424** [comment]
I will check this. Please try typing
:int rebuild_graph
to see if this have to do with the calculation process within the new graph implementation..

**Comment by andmarti1424** [comment]
Yes, I believe it is. Please take note that you shouldn't have this issue with v0.30 release

**Comment by truelson** [comment]
You are correct. Looking forward to 0.30

**Comment by andmarti1424** [comment]
v0.30 is a previous release.

**Comment by truelson** [comment]
whoops. thanks!

**Comment by andmarti1424** [comment]
Please try latest commit and see if it works now.

**Comment by andmarti1424** [comment]
Could you test this again, with latest version? Thanks!

**Comment by truelson** [comment]
Appears to work great now. Thanks!
