### ISSUE TITLE
Cannot make/build project

### ISSUE THREAD

**Issue by marrs** [andmarti1424/sc-im#870]
I tried compiling this project today and it worked fine until I did a `make -C src clean`.  Now it won't compile when I run `make -C src`.  I just get the following error:

```
yacc -d gram.y
make: yacc: No such file or directory
make: *** [Makefile:204: y.tab.c] Error 127
```

**Comment by andmarti1424** [comment]
Please check if you have yacc / bison installed on your distribution.

**Comment by marrs** [comment]
That did it. thanks
