### ISSUE TITLE
`nnoremap "C-k"`  requiring multiple presses to execute

### ISSUE THREAD

**Issue by tunalad** [andmarti1424/sc-im#873]
Hello,
So I was trying to create bindings to move rows and columns around the file by pressing `Ctrl+H/J/K/L`:

```conf
# move row up/down
nnoremap "<C-k>" "drkkp"
nnoremap "<C-j>" "drp"
# move column right/left
nnoremap "<C-l>" "dclpaa"
nnoremap "<C-h>" "dchpaa"
```

They all work, except Ctrl+K. Whenever I want to move the row up, I have to hit Ctrl+K three times for it to execute. 
I assume that's because of the Greek and math symbols Ctrl+K to start executing, even though it's insert mode only thing?

ps: I was initially trying to bind those to Alt key instead, but sadly it's not supported yet

**Comment by andmarti1424** [comment]
@tunalad I believe C-k is special keybinding and it might be captured by your terminal. so that it cannot be binded.

**Comment by tunalad** [comment]
> @tunalad I believe C-k is special keybinding and it might be captured by your terminal. so that it cannot be binded. EDIT: terminal or shell

you're right, it cuts text from the cursor's position and to the right XD

In that case, is Alt key planned for implementation?

**Comment by andmarti1424** [comment]
Regarding capturing ALT key is a limitation of ncurses I am afraid.

**Comment by tunalad** [comment]
> Regarding capturing ALT key is a limitation of ncurses I am afraid.

Can Ctrl+arrows be used instead?

**Comment by andmarti1424** [comment]
Not really sure. It might not. Feel free to try it.

**Comment by tunalad** [comment]
I did but they aren't working like this, so I assumed that there's a different way of defining arrows
```conf
nnoremap "<C-Down>" "drkkp"
nnoremap "<C-Up>" "drp"
```

**Comment by andmarti1424** [comment]
Almost sure ncurses cannot handle them

**Comment by tunalad** [comment]
Gotta deal with it then. Thanks for helping me figure the problem out tho
