### ISSUE TITLE
:help won't work if Working Directory (`pwd` output) Differs from sc-im Parent Folder

### ISSUE THREAD

**Issue by martinvahi** [andmarti1424/sc-im#882]
Assumption is that the "make install" step has not been done, id est the 

    sc-im

has the path of 

    <cloned source folder>/src/sc-im

The workaround in Bash-like pseudocode:

    FULL_PATH_TO_THE_INITIAL_WORKING_DIRECTORY="`pwd`" 
    cd <cloned source folder>/src
    sc-im   # runs the program
    wait  # this line might be skipped, but here for illustration. "man wait" has the details.
    cd $FULL_PATH_TO_THE_INITIAL_WORKING_DIRECTORY

The workaround script that can be placed to an arbitrary folder on PATH to 
start the sc-im has been attached to this flaw/bug report.
[sc-im.bash.txt](https://github.com/user-attachments/files/16321572/sc-im.bash.txt)

Thank You for reading this flaw/bug report.

**Comment by martinvahi** [comment]
Sorry for the double-post. Here's a flaw-fix/bug-fix to the dirty workaround script that I posted here earlier.

[sc-im.bash.v2.txt](https://github.com/user-attachments/files/16321596/sc-im.bash.v2.txt)

**Comment by andmarti1424** [comment]
This is not a bug. You must make install to fully use the app. Not just build it.
