### ISSUE TITLE
segmentation fault with lua function sc.sc

### ISSUE THREAD

**Issue by DHMike57** [andmarti1424/sc-im#897]
If a lua function passes an undo-able action through the interpreter (via `sc.sc` and `sc.lsetform`) then an invalid undo chain is created and there is a segfault on exit when there is an attempt to free the same memory twice.  (the bug does not occur with USE_UNDO unset)

File: `lua/s.lua`:
```lua

sc.sc("LET A4=100")

```
`$ echo -e 'LABEL A0= @lua("s.lua",0)' | sc-im --quit_afterload --nocurses`
`Segmentation fault (core dumped)`

See PR #898

**Comment by andmarti1424** [comment]
Merged PR 898.
