### ISSUE TITLE
dts invalid day error message in referenced calculations

### ISSUE THREAD

**Issue by DHMike57** [andmarti1424/sc-im#899]
`@dts` throws an error message if day=0.  This can happen as an intermediate stage calculating a valid cell and requires a user `<ret>` to continue.
In my particular use case I use `@dts` in combination with `@date `to show the day of the week in every row, requiring a `<ret>` for every row when loading the file.  

Minimal example:

file `dtsbug.sc`:
```
let A0 = @dts(2024,9,@nval("B",0))
let B0 = 12
goto A0

```
`$ sc-im /tmp/dtsbug.sc --nocurses  --quit_afterload`
`@dts: invalid argument or date out of range`

PR #900

**Comment by andmarti1424** [comment]
Merged PR 900.
