### ISSUE TITLE
Can't load saved file

### ISSUE THREAD

**Issue by kyrias** [andmarti1424/sc-im#90]
When I try to load a saved file, I just get `"^?" is not a SC-IM compatible file`

**Comment by andmarti1424** [comment]
Are you opening a .sc file?

**Comment by kyrias** [comment]
Getting the error when trying to open a .sc file that sc-im just wrote.  Get the same error no matter how I try to save or open it.

**Comment by kyrias** [comment]
Spoke too soon, it only works when passing a file on the commandline, if I try to use the same file with `:load` I get that error again.

**Comment by andmarti1424** [comment]
Please update to latest commit and try again! Thanks!

**Comment by kyrias** [comment]
Works, thanks.  (Also, any plans on supporting shell expansions for the path?  Nice being lazy. ;))

**Comment by kyrias** [comment]
Things like expanding tilde to the home directory.  To do it from C you can just use the `wordexp` POSIX C function.

**Comment by andmarti1424** [comment]
We sure can add that. Please open a new issue..
