### ISSUE TITLE
Seg fault, memory leaks and infinite loop in @replace

### ISSUE THREAD

**Issue by DHMike57** [andmarti1424/sc-im#912]
Invalid input causes a variety of the above problems:
```
echo -e 'label A0 = "aaa:bb"\nlabel A0 = @replace(a0,":","c")'|sc-im --quit_afterload --nocurses
Circular reference in seval
Segmentation fault (core dumped)
```
`echo -e 'label A0 = "aaa:bb"\nlabel A0 = @replace(a1,"","c")'|sc-im --quit_afterload --nocurses` causes infinite loop and needs to be killed.

Additionally, erronious input replaces the formula with `@replace(@err,"","c")`, which would cause a segfault if evaluated again - see fix in `seval`.

Memory leaks shown with valgrind - see test file in PR

See PR #911

**Comment by andmarti1424** [comment]
Merged PR 911. Thank you!
