### ISSUE TITLE
Ranges not updating + segfault

### ISSUE THREAD

**Issue by DHMike57** [andmarti1424/sc-im#918]
- `@sum(A0:@getent(@lastrow,0))` does not update if rows are added or deleted (applies generally to expressions in range definition)
- `@sum(A0:@getent(D0,0))` will cause a segfault if copied (including behind the scenes with undo)

```
echo -e 'let B0 = @sum(A0:@getent(D0,0))\nYANKAREA {"Sheet1"}!B0:B0 "a"\nGOTO B2\nPASTEYANKED {"Sheet1"} 0 "c"'|sc-im --quit_afterload --nocurses
Segmentation fault (core dumped)
```
See PR #917

**Comment by andmarti1424** [comment]
Merged PR 917. Thank you!
