### ISSUE TITLE
Recent "replace-update" broke something else

### ISSUE THREAD

**Issue by mark-0lchanski** [andmarti1424/sc-im#919]
Hey,

I have those 2 lines in one of my tables which worked nicely until the recent update (on the dev branch).

```
rightstring B55 = @coltoa(B54)#"1"
rightstring B56 = @replace("@sum(d1:0)","0",B55)
```

B55 returns a column number and adds a trailing `1` to it, while B56 will create a expression that is evaluated later.

When starting sc-im I now get a `scxfree: NULL`
However, running the command of cell B56 manually inside sc-im works fine (until saving, closing and reopening it again, which gives the same error).

Best regards,
Mark

**Comment by DHMike57** [comment]
Hi Mark, this was my PR that broke this - sorry!  See PR #920 for a fix
I added a test based on your usage and it seems to pass.

**Comment by andmarti1424** [comment]
Merged PR 920. Thanks

**Comment by mark-0lchanski** [comment]
Worked like a charm, thanks!
