### ISSUE TITLE
Github sponsor?

### ISSUE THREAD

**Issue by rusq** [andmarti1424/sc-im#925]
Hey Andrés, I was wondering if you'd be willing to setup Github Sponsorship button?  I think that would potentially extend the landscape of sponsorship, because one doesn't have to sign up at a third-party website, and you'll be open to one-time donations.

**Comment by andmarti1424** [comment]
HEllo! That might be a good idea. Any help or point to documentation on how that is done? Thanks

**Comment by rusq** [comment]
Yeah, it's quite easy - donations go through Stripe, and here's the doc: https://github.com/sponsors

**Comment by rusq** [comment]
For Paypal you could use https://ko-fi.com/

**Comment by andmarti1424** [comment]
I do not think the extra fee for using it worth it.

**Comment by rusq** [comment]
But Andrés, there is no fee, I use it for my project just fine.  Truly it’s hard to convince you to take my money 🤣

**Comment by andmarti1424** [comment]
THat's funny. hahah
Will see. I set it up at [Ko-fi.com/andmarti1424](https://ko-fi.com/andmarti1424)

**Comment by rusq** [comment]
Yay!

**Comment by rusq** [comment]
Last step left! https://github.com/andmarti1424/sc-im/blob/main/.github/FUNDING.yml#L6C8-L6C46

**Comment by andmarti1424** [comment]
I have added to dev branch but it didnt show up. Thanks for your donation!
