### ISSUE TITLE
:color not working

### ISSUE THREAD

**Issue by belanger** [andmarti1424/sc-im#94]
In the latest version, starting sc-im and then entering
<br />:color "type=HEADINGS bold=0 fg=BLACK bg=YELLOW"
<br />(taken from the documentation) gives me an error
<br />"Color definition incomplete"
<br />

**Comment by andmarti1424** [comment]
Thanks for reporting this. Please update to latest commit in depgraph branch and try again!

**Comment by belanger** [comment]
Fantastic!  Works great.
Thanks!
