### ISSUE TITLE
Handling filename with spaces

### ISSUE THREAD

**Issue by cyklee** [andmarti1424/sc-im#98]
When trying to open file:

`scim Test\ 1.xlsx`

Will result in:

`"Test" is not a SC-IM compatible file`

I understand that I can rename the file and avoid using spaces (as I should), however it might be nice for sc-im to handle filenames with space characters.

**Comment by andmarti1424** [comment]
Please update to latest depgraph branch commit and try again!

**Comment by cyklee** [comment]
Thanks @andmarti1424 , it appears the problem has been solved. I've updated to latest depgraph branch commit and scim can now open files with spaces in file names.
